#
msgid ""
msgstr ""
"Project-Id-Version: notmusicbot\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-11-11 16:38-0800\n"
"PO-Revision-Date: 2024-11-12 00:39\n"
"Last-Translator: \n"
"Language-Team: Chinese Simplified\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Crowdin-File: /fae/i18n/musicbot_logs.pot\n"
"X-Crowdin-File-ID: 26\n"
"X-Crowdin-Language: zh-CN\n"
"X-Crowdin-Project: notmusicbot\n"
"X-Crowdin-Project-ID: 734017\n"
"X-Generated-By: pygettext.py 1.5-mb01\n"

#. Used by: warning
#: musicbot/aliases.py:52
msgid "Aliases file not found, copying example_aliases.json"
msgstr "找不到别名文件，正在复制 example_aliases.json"

#. Used by: HelpfulError
#: musicbot/aliases.py:56
msgid ""
"Error while loading aliases.\n"
"\n"
"Problem:\n"
"  Your aliases files (aliases.json & example_aliases.json) are missing.\n"
"\n"
"Solution:\n"
"  Replace the alias config file(s) or copy them from:\n"
"    https://github.com/Just-Some-Bots/MusicBot/"
msgstr ""

#. Used by: error
#: musicbot/aliases.py:80
#, python-format
msgid "Failed to load aliases file:  %s"
msgstr "加载别名文件失败：  %s"

#. Used by: error
#: musicbot/aliases.py:88
#, python-format
msgid ""
"Failed to parse aliases file:  %s\n"
"Ensure the file contains valid JSON and restart the bot."
msgstr ""
"解析别名文件失败：  %s\n"
"确保文件包含有效的 JSON 并重启机器人。"

#. Used by: error
#: musicbot/aliases.py:118
#, python-format
msgid ""
"Aliases skipped for non-existent command:  %(command)s  ->  %(aliases)s"
msgstr ""

#. Used by: error
#: musicbot/aliases.py:126
#, python-format
msgid ""
"Alias(es) skipped for invalid alias data:  %(command)s  ->  %(aliases)s"
msgstr ""

#. Used by: error
#: musicbot/aliases.py:136
#, python-format
msgid "Alias `%(alias)s` skipped as already exists on command:  %(command)s"
msgstr ""

#. Used by: warning
#: musicbot/autoplaylist.py:77
#, python-format
msgid "Error loading auto playlist file:  %s"
msgstr "加载自动播放列表文件时出错：  %s"

#. Used by: info
#: musicbot/autoplaylist.py:181
#, python-format
msgid "Removing unplayable song from playlist, %(playlist)s: %(track)s"
msgstr ""

#. Used by: info
#: musicbot/autoplaylist.py:186
#, python-format
msgid "Removing song from playlist, %(playlist)s: %(track)s"
msgstr ""

#. Used by: exception
#: musicbot/autoplaylist.py:132 musicbot/autoplaylist.py:211
msgid "Could not log information about the playlist URL removal."
msgstr "无法记录播放列表URL移除信息。"

#. Used by: info
#: musicbot/autoplaylist.py:135 musicbot/autoplaylist.py:215
msgid "Updating playlist file..."
msgstr "正在更新播放列表文件..."

#. Used by: exception
#: musicbot/autoplaylist.py:158 musicbot/autoplaylist.py:231
#: musicbot/autoplaylist.py:268
#, python-format
msgid "Failed to save playlist file:  %s"
msgstr "保存播放列表文件失败：  %s"

#. Used by: debug
#: musicbot/autoplaylist.py:240
#, python-format
msgid "URL already in playlist %s, ignoring"
msgstr "已经在播放列表 %s中的 URL，忽略"

#. Used by: info
#: musicbot/autoplaylist.py:247
#, python-format
msgid "Adding new URL to playlist, %(playlist)s: %(track)s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:169
#, python-format
msgid "Initializing MusicBot %s"
msgstr "正在初始化 MusicBot %s"

#. Used by: error
#: musicbot/bot.py:252
#, python-format
msgid "Loop is closed, cannot create task for: %r"
msgstr ""

#. Used by: exception
#: musicbot/bot.py:268
#, python-format
msgid "Unhandled exception for task:  %r"
msgstr "任务未处理异常：  %r"

#. Used by: error
#: musicbot/bot.py:272
#, python-format
msgid "Unhandled exception for task:  %(task)r  --  %(raw_error)s"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:317 musicbot/bot.py:339
msgid "Spotify did not provide us with a token. Disabling."
msgstr "Spotify没有为我们提供令牌。禁用。"

#. Used by: info
#: musicbot/bot.py:321
msgid "Authenticated with Spotify successfully using client ID and secret."
msgstr "通过Spotify验证成功使用客户端 ID 和秘密。"

#. Used by: warning
#: musicbot/bot.py:325
#, python-format
msgid ""
"Could not start Spotify client. Is your client ID and secret correct? "
"Details: %s. Continuing anyway in 5 seconds..."
msgstr ""

#. Used by: warning
#: musicbot/bot.py:333
msgid ""
"The config did not have Spotify app credentials, attempting to use guest "
"mode."
msgstr "配置没有 Spotify 应用凭据，正在尝试使用访客模式。"

#. Used by: info
#: musicbot/bot.py:343
msgid "Authenticated with Spotify successfully using guest mode."
msgstr "使用 Spotify 验证成功使用访客模式。"

#. Used by: warning
#: musicbot/bot.py:348
#, python-format
msgid "Could not start Spotify client using guest mode. Details: %s."
msgstr ""

#. Used by: info
#: musicbot/bot.py:353
msgid "Initialized, now connecting to discord."
msgstr "已初始化，正在连接到 discord。"

#. Used by: debug
#: musicbot/bot.py:364
msgid "Network ping test is disabled via config."
msgstr "通过配置禁用网络ping测试。"

#. Used by: noise
#: musicbot/bot.py:368
msgid "Network ping test is closing down."
msgstr "网络Ping 测试正在关闭。"

#. Used by: warning
#: musicbot/bot.py:379
msgid "Could not resolve ping target."
msgstr "无法解析 ping 目标。"

#. Used by: noise
#: musicbot/bot.py:409
msgid "Network ping test cancelled."
msgstr "网络Ping 测试已取消。"

#. Used by: warning
#: musicbot/bot.py:423
msgid "Network testing via HTTP does not have a session to borrow."
msgstr "通过 HTTP 进行网络测试没有要借用的会话。"

#. Used by: warning
#: musicbot/bot.py:448
msgid "Could not locate `ping` executable in your environment."
msgstr "无法在您的环境中找到 ping` 可执行文件。"

#. Used by: error
#: musicbot/bot.py:474
#, python-format
msgid ""
"MusicBot could not locate a `ping` command path.  Will attempt to use HTTP ping instead.\n"
"MusicBot tried the following command:   %s\n"
"You should enable ping in your system or container environment for best results.\n"
"Alternatively disable network checking via config."
msgstr ""

#. Used by: error
#: musicbot/bot.py:484
#, python-format
msgid ""
"MusicBot was denied permission to execute the `ping` command.  Will attempt to use HTTP ping instead.\n"
"MusicBot tried the following command:   %s\n"
"You should enable ping in your system or container environment for best results.\n"
"Alternatively disable network checking via config."
msgstr ""

#. Used by: error
#: musicbot/bot.py:494
#, python-format
msgid ""
"Your environment may not allow the `ping` system command.  Will attempt to use HTTP ping instead.\n"
"MusicBot tried the following command:   %s\n"
"You should enable ping in your system or container environment for best results.\n"
"Alternatively disable network checking via config."
msgstr ""

#. Used by: info
#: musicbot/bot.py:509
msgid "MusicBot detected network is available again."
msgstr "侦测到的 MusicBot 网络再次可用."

#. Used by: warning
#: musicbot/bot.py:514
msgid "VoiceClient is not connected, waiting to resume MusicPlayer..."
msgstr "语音客户端未连接，正在等待恢复 MusicPlayer..."

#. Used by: info
#: musicbot/bot.py:518
#, python-format
msgid "Resuming playback of player:  (%(guild_id)s) %(player)r"
msgstr ""

#. Used by: info
#: musicbot/bot.py:529
msgid "MusicBot detected a network outage."
msgstr "MusicBot 检测到网络停用。"

#. Used by: info
#: musicbot/bot.py:533
#, python-format
msgid ""
"Pausing MusicPlayer due to network availability:  (%(guild_id)s) %(player)r"
msgstr ""

#. Used by: noise
#: musicbot/bot.py:554
#, python-format
msgid ""
"Looking for owner in guild: %(guild)s (required voice: %(required)s) and "
"got:  %(owner)s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:568
msgid "Checking for channels to auto-join or resume..."
msgstr "正在检查频道以自动加入或恢复..."

#. Used by: warning
#: musicbot/bot.py:580
#, python-format
msgid "Guild not available, cannot auto join:  %(id)s/%(name)s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:588
#, python-format
msgid "Found resumable voice channel:  %(channel)s  in guild:  %(guild)s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:601
#, python-format
msgid "Will try resuming voice session instead of Auto-Joining channel:  %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:618
#, python-format
msgid "Found owner in voice channel:  %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:623
#, python-format
msgid "Ignoring resumable channel, AutoSummon to owner in channel:  %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:628
#, python-format
msgid "Ignoring Auto-Join channel, AutoSummon to owner in channel:  %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:640
#, python-format
msgid "Already connected to channel:  %(channel)s  in guild:  %(guild)s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:649
#, python-format
msgid "Attempting to join channel:  %(channel)s  in guild:  %(guild)s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:656
msgid "Discarding MusicPlayer and making a new one..."
msgstr "丢弃音乐播放器并制作新音乐..."

#. Used by: debug
#: musicbot/bot.py:676
msgid "MusicBot will make a new MusicPlayer now..."
msgstr "MusicBot 现在将创建一个新的 MusicPlayer ..."

#. Used by: warning
#: musicbot/bot.py:697
#, python-format
msgid "Not joining %(guild)s/%(channel)s, it isn't a supported voice channel."
msgstr ""

#. Used by: info
#: musicbot/bot.py:700
msgid "Finished joining configured channels."
msgstr "已完成加入配置频道。"

#. Used by: CommandError
#: musicbot/bot.py:723
msgid "Member is not voice-enabled and cannot use this command."
msgstr "会员没有语音功能，无法使用此命令。"

#. Used by: PermissionsError
#: musicbot/bot.py:731
msgid "You cannot use this command when not in the voice channel."
msgstr "您不能在语音频道中使用此命令。"

#. Used by: debug
#: musicbot/bot.py:745
msgid "Getting bot Application Info."
msgstr "正在获取机器人应用程序信息。"

#. Used by: error
#: musicbot/bot.py:770
#, python-format
msgid "MusicBot does not have permission to Connect in channel:  %s"
msgstr ""

#. Used by: PermissionsError
#: musicbot/bot.py:774
#, python-format
msgid "MusicBot does not have permission to Connect in channel:  `%(name)s`"
msgstr ""

#. Used by: error
#: musicbot/bot.py:779
#, python-format
msgid "MusicBot does not have permission to Speak in channel:  %s"
msgstr ""

#. Used by: PermissionsError
#: musicbot/bot.py:783
#, python-format
msgid "MusicBot does not have permission to Speak in channel:  `%(name)s`"
msgstr ""

#. Used by: voicedebug
#: musicbot/bot.py:793
#, python-format
msgid "Reusing bots VoiceClient from guild:  %s"
msgstr ""

#. Used by: voicedebug
#: musicbot/bot.py:798
#, python-format
msgid "Forcing disconnect on stale VoiceClient in guild:  %s"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:804
msgid "Disconnect failed or was cancelled?"
msgstr "断开连接失败或已取消？"

#. Used by: critical
#: musicbot/bot.py:812
#, python-format
msgid "MusicBot is unable to connect to the channel right now:  %(channel)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:816
msgid ""
"MusicBot could not connect to the channel.\n"
"Try again later, or restart the bot if this continues."
msgstr ""

#. Used by: voicedebug
#: musicbot/bot.py:827
msgid "MusicBot has a VoiceClient now..."
msgstr "MusicBot 现在有一个语音客户端..."

#. Used by: warning
#: musicbot/bot.py:832
#, python-format
msgid ""
"Retrying connection after a timeout error (%(attempt)s) while trying to "
"connect to:  %(channel)s"
msgstr ""

#. Used by: exception
#: musicbot/bot.py:837
msgid "MusicBot VoiceClient connection attempt was cancelled. No retry."
msgstr "MusicBot 语音客户端连接尝试已取消。无需重试。"

#. Used by: CommandError
#: musicbot/bot.py:840
msgid ""
"MusicBot connection to voice was cancelled. This is odd. Maybe restart?"
msgstr "MusicBot 与语音的连接已取消。这是奇异的。可能要重新启动吗？"

#. Used by: info
#: musicbot/bot.py:846 musicbot/bot.py:8670
#, python-format
msgid "MusicBot is requesting to speak in channel: %s"
msgstr "MusicBot 请求在频道中说话: %s"

#. Used by: PermissionsError
#. Used by: exception
#: musicbot/bot.py:851 musicbot/bot.py:8676
msgid "MusicBot does not have permission to speak."
msgstr "MusicBot 没有发言权限。"

#. Used by: MusicbotException
#. Used by: exception
#: musicbot/bot.py:855 musicbot/bot.py:8678
msgid "MusicBot could not request to speak."
msgstr "MusicBot 无法请求发言。"

#. Used by: info
#: musicbot/bot.py:868
#, python-format
msgid "Disconnecting a MusicPlayer in guild:  %s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:880
msgid "Disconnecting VoiceClient before we kill the MusicPlayer."
msgstr "在杀死MusicPlayer前断开语音客户端。"

#. Used by: warning
#: musicbot/bot.py:888 musicbot/bot.py:907 musicbot/bot.py:919
#: musicbot/bot.py:942
msgid "The disconnect failed or was cancelled."
msgstr "断开连接失败或取消。"

#. Used by: debug
#: musicbot/bot.py:898
msgid ""
"MusicBot has a VoiceProtocol that is not a VoiceClient. Disconnecting "
"anyway..."
msgstr "MusicBot 有一个不是语音客户端的语音协议，仍然断开连接..."

#. Used by: debug
#: musicbot/bot.py:911
#, python-format
msgid "Disconnecting a rogue VoiceClient in guild:  %s"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:935
msgid "Disconnecting a non-guild VoiceClient..."
msgstr "断开非公会语音客户端的连接..."

#. Used by: warning
#: musicbot/bot.py:945
#, python-format
msgid ""
"MusicBot.voice_clients list contains a non-VoiceClient object?\n"
"The object is actually of type:  %s"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:955
#, python-format
msgid "We still have a MusicPlayer ref in guild (%(guild_id)s):  %(player)r"
msgstr ""

#. Used by: voicedebug
#: musicbot/bot.py:968
#, python-format
msgid "Guild (%(guild)s) wants a player, optional:  %(player)r"
msgstr ""

#. Used by: error
#: musicbot/bot.py:975
msgid ""
"[BUG] MusicPlayer is missing a VoiceClient somehow.  You should probably "
"restart the bot."
msgstr ""

#. Used by: warning
#: musicbot/bot.py:980
msgid "MusicPlayer has a VoiceClient that is not connected."
msgstr "MusicPlayer 有一个未连接的语音客户端。"

#. Used by: noise
#: musicbot/bot.py:981
#, python-format
msgid "MusicPlayer obj:  %r"
msgstr ""

#. Used by: noise
#: musicbot/bot.py:982
#, python-format
msgid "VoiceClient obj:  %r"
msgstr ""

#. Used by: voicedebug
#: musicbot/bot.py:1002
#, python-format
msgid ""
"Getting a MusicPlayer for guild:  %(guild)s  In Channel:  %(channel)s  "
"Create: %(create)s  Deserialize:  %(serial)s"
msgstr ""

#. Used by: voicedebug
#: musicbot/bot.py:1018
#, python-format
msgid ""
"Created player via deserialization for guild %(guild_id)s with %(number)s "
"entries"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:1027
msgid ""
"The bot is not in a voice channel.\n"
"Use the summon command to bring the bot to your voice channel."
msgstr ""

#. Used by: MusicbotException
#: musicbot/bot.py:1039
msgid "Something is wrong, we didn't get the VoiceClient."
msgstr "出错了，我们没有得到语音客户端。"

#. Used by: debug
#: musicbot/bot.py:1072
msgid "Running on_player_play"
msgstr "运行_player_player"

#. Used by: debug
#: musicbot/bot.py:1147
#, python-format
msgid "Setting URL history guild %(guild_id)s == %(url)s"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:1183 musicbot/bot.py:4940
#, python-format
msgid "No thumbnail set for entry with URL: %s"
msgstr "没有为 URL 条目设置缩略图： %s"

#. Used by: debug
#: musicbot/bot.py:1195
msgid "no channel to put now playing message into"
msgstr "没有频道放入正在播放消息"

#. Used by: debug
#: musicbot/bot.py:1207
msgid "ignored now-playing message as it was already posted."
msgstr "忽略正在播放的消息，因为它已经被发布。"

#. Used by: debug
#: musicbot/bot.py:1231
msgid "Running on_player_resume"
msgstr "运行 on_player_result"

#. Used by: debug
#: musicbot/bot.py:1244
msgid "Running on_player_pause"
msgstr "运行 on_player_pause"

#. Used by: debug
#: musicbot/bot.py:1260
msgid "Running on_player_stop"
msgstr "运行_player_stop"

#. Used by: debug
#: musicbot/bot.py:1270
msgid "Running on_player_finished_playing"
msgstr "运行_player_finished_play_playing"

#. Used by: debug
#: musicbot/bot.py:1272 musicbot/bot.py:1318 musicbot/bot.py:1389
msgid "Event loop is closed, nothing else to do here."
msgstr "事件循环已关闭，此处不需要做任何其它事情。"

#. Used by: debug
#: musicbot/bot.py:1276 musicbot/bot.py:1322 musicbot/bot.py:1393
msgid "Logout under way, ignoring this event."
msgstr "注销正在进行，忽略此事件。"

#. Used by: debug
#: musicbot/bot.py:1293
msgid "VoiceClient says it is not connected, nothing else we can do here."
msgstr "语音客户端说它没有连接，我们在这里无法做任何其他事情。"

#. Used by: info
#: musicbot/bot.py:1300
msgid "Player finished and queue is empty, leaving voice channel..."
msgstr "播放器已完成，队列为空，离开语音频道..."

#. Used by: everything
#: musicbot/bot.py:1314
msgid "Looping over queue to expunge songs with missing author..."
msgstr "正在循环播放队列以删除缺失作者的歌曲..."

#. Used by: noise
#: musicbot/bot.py:1353
#, python-format
msgid ""
"Author `%(user)s` absent, skipped (deleted) entry from queue:  %(song)s"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:1372
msgid "No playable songs in the Guild autoplaylist, disabling."
msgstr "公会自动播放列表中没有可播放的歌曲，禁用。"

#. Used by: debug
#: musicbot/bot.py:1377
msgid "No content in current autoplaylist. Filling with new music..."
msgstr "当前自动播放列表中没有内容。用新音乐填充..."

#. Used by: everything
#: musicbot/bot.py:1385
msgid "Looping over player autoplaylist..."
msgstr "正在循环播放器自动布局列表..."

#. Used by: error
#: musicbot/bot.py:1426
#, python-format
msgid "Error while processing song \"%(url)s\":  %(raw_error)s"
msgstr ""

#. Used by: error
#: musicbot/bot.py:1437
#, python-format
msgid "Error extracting song \"%(url)s\": %(raw_error)s"
msgstr ""

#. Used by: exception
#: musicbot/bot.py:1452
msgid "MusicBot needs to stop the auto playlist extraction and bail."
msgstr "MusicBot 需要停止自动播放列表提取和保释。"

#. Used by: exception
#: musicbot/bot.py:1457
msgid "MusicBot got an unhandled exception in player finished event."
msgstr "在玩家完成的活动中，MusicBot 有一个未处理的异常。"

#. Used by: info
#: musicbot/bot.py:1463
#, python-format
msgid "Expanding auto playlist with entries extracted from:  %s"
msgstr ""

#. Used by: error
#: musicbot/bot.py:1487
#, python-format
msgid "Error adding song from autoplaylist: %s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:1490
msgid "Exception data for above error:"
msgstr "上述异常数据错误："

#. Used by: warning
#: musicbot/bot.py:1496
msgid "No playable songs in the autoplaylist, disabling."
msgstr "自动播放列表中没有可播放的歌曲，禁用了。"

#. Used by: debug
#: musicbot/bot.py:1516
msgid "Running on_player_entry_added"
msgstr "已添加 on_player_entry_添加"

#. Used by: debug
#: musicbot/bot.py:1526
msgid "Automatically skipping auto-playlist entry for queued entry."
msgstr "自动跳过队列条目的自动播放列表条目。"

#. Used by: exception
#: musicbot/bot.py:1546
#, python-format
msgid "MusicPlayer exception for entry: %r"
msgstr ""

#. Used by: exception
#: musicbot/bot.py:1552
msgid "MusicPlayer exception."
msgstr "MusicPlayer 异常。"

#. Used by: info
#: musicbot/bot.py:1576
#, python-format
msgid "Auto playlist track could not be played:  %r"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:1615
msgid "Logout under way, ignoring status update event."
msgstr "注销正在进行，忽略状态更新事件。"

#. Used by: noise
#: musicbot/bot.py:1716
#, python-format
msgid "Update bot status:  %(status)s -- %(activity)r"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:1744
#, python-format
msgid "Serializing queue for %s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:1770
#, python-format
msgid "Deserializing queue for %s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:1788
#, python-format
msgid "Writing current song for %s"
msgstr ""

#. Used by: error
#: musicbot/bot.py:1813
#, python-format
msgid "Cannot send non-response object:  %r"
msgstr "无法发送无响应对象：  %r"

#. Used by: MusicbotException
#: musicbot/bot.py:1818
msgid "[Dev Bug] Tried sending an invalid response object."
msgstr "[Dev Bug ] 试图发送无效的响应对象。"

#. Used by: debug
#: musicbot/bot.py:1855
#, python-format
msgid "sending embed to: %s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:1858
#, python-format
msgid "sending text to: %s"
msgstr ""

#. Used by: error
#: musicbot/bot.py:1863
#, python-format
msgid "Cannot send message to \"%s\", no permission"
msgstr ""

#. Used by: error
#: musicbot/bot.py:1870
#, python-format
msgid "Cannot send message to \"%s\", invalid or deleted channel"
msgstr ""

#. Used by: error
#: musicbot/bot.py:1878
#, python-format
msgid "Message is over the message size limit (%s)"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:1886
msgid "Could not send private message, sending in fallback channel instead."
msgstr "无法发送私信，发送到后退频道中。"

#. Used by: warning
#: musicbot/bot.py:1904
#, python-format
msgid "Rate limited send message, retrying in %s seconds."
msgstr ""

#. Used by: warning
#: musicbot/bot.py:1910
#, python-format
msgid "Cancelled message retry for:  %s"
msgstr ""

#. Used by: error
#: musicbot/bot.py:1915
msgid "Rate limited send message, but cannot retry!"
msgstr "评分有限的发送消息，但不能重试！"

#. Used by: error
#: musicbot/bot.py:1921
msgid "Failed to send message in fallback channel."
msgstr "在后退频道中发送消息失败。"

#. Used by: error
#: musicbot/bot.py:1926 musicbot/bot.py:1990 musicbot/bot.py:2060
msgid "Failed to send due to an HTTP error."
msgstr "由于HTTP错误发送失败。"

#. Used by: warning
#: musicbot/bot.py:1952
#, python-format
msgid "Cannot delete message \"%s\", no permission"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:1957
#, python-format
msgid "Cannot delete message \"%s\", message not found"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:1975
#, python-format
msgid "Rate limited message delete, retrying in %s seconds."
msgstr ""

#. Used by: error
#: musicbot/bot.py:1980
msgid "Rate limited message delete, but cannot retry!"
msgstr "评分限制信息已删除，但无法重试！"

#. Used by: warning
#: musicbot/bot.py:1983
msgid "Failed to delete message"
msgstr "删除消息失败"

#. Used by: noise
#: musicbot/bot.py:1985
#, python-format
msgid "Got HTTPException trying to delete message: %s"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:2020
#, python-format
msgid "Cannot edit message \"%s\", message not found"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:2024
msgid "Sending message instead"
msgstr "发送消息"

#. Used by: warning
#: musicbot/bot.py:2041
#, python-format
msgid "Rate limited edit message, retrying in %s seconds."
msgstr ""

#. Used by: warning
#: musicbot/bot.py:2047
#, python-format
msgid "Cancelled message edit for:  %s"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:2053
msgid "Failed to edit message"
msgstr "编辑消息失败"

#. Used by: noise
#: musicbot/bot.py:2055
#, python-format
msgid "Got HTTPException trying to edit message %s to: %s"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:2077
#, python-format
msgid "Cancelled delete for message (ID: %(id)s):  %(content)s"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:2139
#, python-format
msgid "Caught a signal from the OS: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2143
msgid "Disconnecting and closing down MusicBot..."
msgstr "断开和关闭MusicBot"

#. Used by: exception
#: musicbot/bot.py:2146
msgid "Exception thrown while handling interrupt signal!"
msgstr "处理中断信号时抛出异常！"

#. Used by: info
#: musicbot/bot.py:2161
msgid "MusicBot is now doing shutdown steps..."
msgstr "MusicBot 正在执行关闭步骤..."

#. Used by: HelpfulError
#: musicbot/bot.py:2169
msgid ""
"Failed Discord API Login!\n"
"\n"
"Problem:\n"
"  MusicBot could not log into Discord API.\n"
"  Your Token may be incorrect or there may be an API outage.\n"
"\n"
"Solution:\n"
"  Make sure you have the correct Token set in your config.\n"
"  Check API status at the official site: discordstatus.com"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2183
msgid "Waiting for download threads to finish up..."
msgstr "正在等待下载线程完成..."

#. Used by: debug
#: musicbot/bot.py:2209
#, python-format
msgid "Will wait for task:  %(name)s  (%(func)s)"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:2216
#, python-format
msgid "Will try to cancel task:  %(name)s  (%(func)s)"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:2224
msgid "Awaiting pending tasks..."
msgstr "正在等待任务..."

#. Used by: debug
#: musicbot/bot.py:2230
msgid "Closing HTTP Connector."
msgstr "关闭HTTP连接器。"

#. Used by: debug
#: musicbot/bot.py:2236
msgid "Closing aiohttp session."
msgstr "闭幕会议."

#. Used by: noise
#: musicbot/bot.py:2248
msgid "Logout has been called."
msgstr "注销已被调用。"

#. Used by: error
#: musicbot/bot.py:2260
#, python-format
msgid ""
"Exception in %(event)s:\n"
"%(error)s"
msgstr ""

#. Used by: error
#: musicbot/bot.py:2276
#, python-format
msgid "Exception in %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2283
msgid "MusicBot resumed a session with discord."
msgstr "MusicBot恢复了不一致的会话。"

#. Used by: debug
#: musicbot/bot.py:2300
msgid "Finish on_ready"
msgstr "准备好完成"

#. Used by: debug
#: musicbot/bot.py:2307
msgid "Logged in, now getting MusicBot ready..."
msgstr "已登录，正在准备好MusicBot..."

#. Used by: critical
#: musicbot/bot.py:2310
msgid "ClientUser is somehow none, we gotta bail..."
msgstr "客户端在某种程度上是没有的，我们去做保释..."

#. Used by: info
#: musicbot/bot.py:2319
#, python-format
msgid "MusicBot:  %(id)s/%(name)s#%(desc)s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2330
#, python-format
msgid "Owner:     %(id)s/%(name)s#%(desc)s\n"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2338 musicbot/bot.py:2365
msgid "Guild List:"
msgstr "公会列表："

#. Used by: info
#. Used by: debug
#: musicbot/bot.py:2342 musicbot/bot.py:2368 musicbot/bot.py:8862
#, python-format
msgid " - %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2351
#, python-format
msgid "Left %s due to bot owner not found"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2356
#, python-format
msgid "Not proceeding with checks in %s servers due to unavailability"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:2362
#, python-format
msgid "Owner could not be found on any guild (id: %s)\n"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:2371
msgid "Owner unknown, bot is not on any guilds."
msgstr "所有者未知。机器人不在任何公会上。"

#. Used by: warning
#: musicbot/bot.py:2375
#, python-format
msgid ""
"To make the bot join a guild, paste this link in your browser. \n"
"Note: You should be logged into your main account and have \n"
"manage server permissions on the guild you want the bot to join.\n"
"  %s"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:2392
#, python-format
msgid "Got None for bound channel with ID:  %d"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:2398
#, python-format
msgid "Cannot bind to non Messageable channel with ID:  %d"
msgstr "无法绑定到 ID 为  %d 的不可信频道"

#. Used by: info
#: musicbot/bot.py:2412
msgid "Bound to text channels:"
msgstr "文本通道绑定："

#. Used by: info
#: musicbot/bot.py:2430 musicbot/bot.py:2480
#, python-format
msgid " - %(guild)s/%(channel)s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2434 musicbot/bot.py:2436
msgid "Not bound to any text channels"
msgstr "不绑定到任何文本频道"

#. Used by: warning
#: musicbot/bot.py:2447
#, python-format
msgid "Got None for auto join channel with ID:  %d"
msgstr "没有自动加入频道ID:  %d"

#. Used by: warning
#: musicbot/bot.py:2453
#, python-format
msgid "Cannot auto join a Private/Non-Guild channel with ID:  %d"
msgstr "无法自动加入私有/非公会频道与 ID:  %d"

#. Used by: warning
#: musicbot/bot.py:2461
#, python-format
msgid "Cannot auto join to non-connectable channel with ID:  %d"
msgstr "无法自动加入不可连接的频道 ID:  %d"

#. Used by: info
#: musicbot/bot.py:2477
msgid "Auto joining voice channels:"
msgstr "自动加入语音频道："

#. Used by: info
#: musicbot/bot.py:2485 musicbot/bot.py:2488
msgid "Not auto joining any voice channels"
msgstr "不自动加入任何语音频道"

#. Used by: warning
#: musicbot/bot.py:2501
#, python-format
msgid ""
"Detected missing config options!\n"
"\n"
"Problem:\n"
"  You config options file is missing some options.\n"
"  Default settings will be used for these options.\n"
"  Here is a list of options we didn't find:\n"
"  %(missing)s\n"
"\n"
"Solution:\n"
"  Copy new options from the example options file.\n"
"  Or use the config command to set and save them.\n"
"\n"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:2530
#, python-format
msgid "Event on_ready has fired %s times"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:2546
msgid "Getting application info."
msgstr "正在获取应用程序信息。"

#. Used by: debug
#: musicbot/bot.py:2564
msgid "Ensuring data folders exist"
msgstr "确保数据文件夹存在"

#. Used by: debug
#: musicbot/bot.py:2579
msgid "Validating config"
msgstr "正在验证配置"

#. Used by: debug
#: musicbot/bot.py:2582
msgid "Validating permissions config"
msgstr "正在验证权限配置"

#. Used by: _L
#: musicbot/bot.py:2592
msgid "Disabled"
msgstr "已禁用"

#. Used by: _L
#: musicbot/bot.py:2592
msgid "Enabled"
msgstr "已启用"

#. Used by: info
#: musicbot/bot.py:2595
msgid "Options:"
msgstr "选项："

#. Used by: info
#: musicbot/bot.py:2597
#, python-format
msgid "  Command prefix: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2602
#, python-format
msgid "  Default volume: %d%%"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2604
#, python-format
msgid "  Skip threshold: %(num)d votes or %(percent).0f%%"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2616
#, python-format
msgid "  Now Playing @mentions: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2623
#, python-format
msgid "  Auto-Playlist: %(status)s (order: %(order)s)"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2626
msgid "random"
msgstr "随机的"

#. Used by: _L
#: musicbot/bot.py:2626
msgid "sequential"
msgstr "序列"

#. Used by: info
#: musicbot/bot.py:2646
#, python-format
msgid "  Auto-Pause: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2648
#, python-format
msgid "  Delete Messages: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2653
#, python-format
msgid "    Delete Invoking: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2657
#, python-format
msgid "    Delete Now Playing: %s"
msgstr "    删除正在播放中: %s"

#. Used by: info
#: musicbot/bot.py:2660
#, python-format
msgid "  Debug Mode: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2664
#, python-format
msgid "  Downloaded songs will be %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2668
#, python-format
msgid "    Delete if unused for %d days"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2679
#, python-format
msgid "  Status message: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2691
#, python-format
msgid "  Spotify integration: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2704
#, python-format
msgid "    Timeout: %s seconds"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2716
#, python-format
msgid "    Timeout: %d seconds"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2717
#, python-format
msgid "  Self Deafen: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2719
#, python-format
msgid "  Per-server command prefix: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2725
#, python-format
msgid "  Round Robin Queue: %s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:2780
#, python-format
msgid "The requested song `%(subject)s` is blocked by the song block list."
msgstr ""

#. Used by: warning
#: musicbot/bot.py:2791
msgid ""
"Attempted to handle Voice Channel inactivity, but Bot is not in voice..."
msgstr "试图处理 Voice Channot 处于无活动状态，但Bot 没有语音..."

#. Used by: debug
#: musicbot/bot.py:2798
#, python-format
msgid "Channel activity already waiting in guild: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2808
#, python-format
msgid ""
"Channel activity waiting %(time)d seconds to leave channel: %(channel)s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2823
#, python-format
msgid "Channel activity timer for %s has expired. Disconnecting."
msgstr ""

#. Used by: info
#: musicbot/bot.py:2829
#, python-format
msgid "Channel activity timer canceled for: %(channel)s in %(guild)s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:2857
#, python-format
msgid "Ignoring player inactivity in auto-joined channel:  %s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:2864
#, python-format
msgid "Player activity timer already waiting in guild: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2872
#, python-format
msgid ""
"Player activity timer waiting %(time)d seconds to leave channel: %(channel)s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2884
#, python-format
msgid "Player activity timer for %s has expired. Disconnecting."
msgstr ""

#. Used by: info
#: musicbot/bot.py:2890 musicbot/bot.py:2895
#, python-format
msgid "Player activity timer canceled for: %(channel)s in %(guild)s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:2912
msgid "Player activity timer is being reset."
msgstr "正在重置玩家活动计时器。"

#. Used by: CommandError
#: musicbot/bot.py:3021
msgid "No such command"
msgstr "没有这种命令"

#. Used by: CommandError
#: musicbot/bot.py:3097
msgid "You must mention a user or provide their ID number."
msgstr "您必须提及用户或提供他们的身份号码。"

#. Used by: CommandError
#: musicbot/bot.py:3102
msgid "Invalid sub-command given. Use `help blockuser` for usage examples."
msgstr "给定的子命令无效。使用 \"help blockuser\" 作为使用示例。"

#. Used by: CommandError
#: musicbot/bot.py:3113
msgid "MusicBot could not find the user(s) you specified."
msgstr "MusicBot 无法找到您指定的用户。"

#. Used by: CommandError
#: musicbot/bot.py:3120
msgid "The owner cannot be added to the block list."
msgstr "所有者不能添加到方块列表。"

#. Used by: info
#: musicbot/bot.py:3124
#, python-format
msgid "Not adding user to block list, already blocked:  %(id)s/%(name)s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:3133
#, python-format
msgid "Not removing user from block list, not listed:  %(id)s/%(name)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:3150
msgid "Cannot add the users you listed, they are already added."
msgstr "无法添加您列出的用户，他们已经被添加。"

#. Used by: CommandError
#: musicbot/bot.py:3227
msgid "You must provide a song subject if no song is currently playing."
msgstr "如果没有歌曲正在播放，您必须提供一个歌曲主题。"

#. Used by: CommandError
#: musicbot/bot.py:3233
msgid "Invalid sub-command given. Use `help blocksong` for usage examples."
msgstr "给定的子命令无效。使用 \"help blocksong\" 作为使用示例。"

#. Used by: CommandError
#: musicbot/bot.py:3245
#, python-format
msgid "Subject `%(subject)s` is already in the song block list."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:3277
msgid "The subject is not in the song block list and cannot be removed."
msgstr "主题不在歌曲块列表中，无法删除。"

#. Used by: CommandError
#: musicbot/bot.py:3349
msgid "Invalid sub-command given. Use `help autoplaylist` for usage examples."
msgstr "给定的子命令无效。使用 \"help autoplaylist\" 作为使用示例。"

#. Used by: CommandError
#: musicbot/bot.py:3356
msgid "The supplied song link is invalid"
msgstr "提供的歌曲链接无效"

#. Used by: CommandError
#: musicbot/bot.py:3362
msgid "The queue is empty. Add some songs with a play command!"
msgstr "队列为空。用播放命令添加一些歌曲！"

#. Used by: CommandError
#: musicbot/bot.py:3390
msgid "This song is already in the autoplaylist."
msgstr "这首歌已经在自动播放列表中。"

#. Used by: CommandError
#: musicbot/bot.py:3407
msgid "This song is not yet in the autoplaylist."
msgstr "这首歌尚未在自动播放列表中。"

#. Used by: CommandError
#: musicbot/bot.py:3441
msgid "You must provide a playlist filename."
msgstr "您必须提供一个播放列表文件名。"

#. Used by: PermissionsError
#: musicbot/bot.py:3551
msgid "You are not allowed to request playlists"
msgstr "您无权请求播放列表"

#. Used by: PermissionsError
#: musicbot/bot.py:3559
#, python-format
msgid "Playlist has too many entries (%(songs)s but max is %(max)s)"
msgstr ""

#. Used by: PermissionsError
#: musicbot/bot.py:3570
#, python-format
msgid ""
"The playlist entries will exceed your queue limit.\n"
"There are %(songs)s in the list, and %(queued)s already in queue.\n"
"The limit is %(max)s for your group."
msgstr ""

#. Used by: debug
#: musicbot/bot.py:3594
msgid "Ignoring auto-pause due to network outage."
msgstr "由于网络停电，忽略自动暂停。"

#. Used by: voicedebug
#: musicbot/bot.py:3599
msgid ""
"MusicPlayer has no VoiceClient or has no channel data, cannot process auto-"
"pause."
msgstr "MusicPlayer 没有 VoiceClient 或没有频道数据，无法处理自动暂停。"

#. Used by: debug
#: musicbot/bot.py:3610
msgid "Already processing auto-pause, ignoring this event."
msgstr "已经在处理自动暂停，忽略此事件。"

#. Used by: warning
#: musicbot/bot.py:3618
#, python-format
msgid ""
"%sVoiceClient not connected, waiting %s seconds to handle auto-pause in "
"guild:  %s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:3626
msgid "Auto-pause waiting was cancelled."
msgstr "自动暂停等待已取消。"

#. Used by: info
#: musicbot/bot.py:3633
msgid "A new MusicPlayer is being connected, ignoring old auto-pause event."
msgstr "一个新的 MusicPlayer 正在连接，忽略旧的自动暂停事件。"

#. Used by: info
#: musicbot/bot.py:3649
#, python-format
msgid "Playing in an empty voice channel, running auto pause for guild: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:3656
#, python-format
msgid "Previously auto paused player is unpausing for guild: %s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:3887
msgid "Cannot use seek if there is nothing playing."
msgstr "如果没有播放，无法使用寻找。"

#. Used by: CommandError
#: musicbot/bot.py:3892
msgid "Cannot use seek on current track, it has an unknown duration."
msgstr "无法在当前轨道上使用寻找，它有未知的持续时间。"

#. Used by: CommandError
#: musicbot/bot.py:3898
msgid "Seeking is not supported for streams."
msgstr "不支持搜索。"

#. Used by: CommandError
#: musicbot/bot.py:3908
msgid "Cannot use seek without a time to position playback."
msgstr "没有时间定位播放，无法使用搜索引擎。"

#. Used by: CommandError
#: musicbot/bot.py:3926
#, python-format
msgid "Could not convert `%(input)s` to a valid time in seconds."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:3939
#, python-format
msgid ""
"Cannot seek to `%(input)s` (`%(seconds)s` seconds) in the current track with"
" a length of `%(progress)s / %(total)s`"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:4000
msgid "Invalid sub-command. Use the command `help repeat` for usage examples."
msgstr "无效的子命令。使用命令“help repat”作为使用示例。"

#. Used by: CommandError
#: musicbot/bot.py:4038
msgid "The player is not currently looping."
msgstr "玩家目前没有循环中。"

#. Used by: CommandError
#: musicbot/bot.py:4094
msgid "Song positions must be integers!"
msgstr "歌曲位置必须是整数！"

#. Used by: CommandError
#: musicbot/bot.py:4099
msgid "You gave a position outside the playlist size!"
msgstr "您提供了一个超出播放列表大小的位置！"

#. Used by: warning
#: musicbot/bot.py:4147
msgid ""
"Could not prompt for playlist playback, no message to add reactions to."
msgstr "无法提示播放列表播放，没有消息添加反应。"

#. Used by: CommandError
#: musicbot/bot.py:4236
msgid "Local media playback is not enabled."
msgstr "本地媒体播放未启用。"

#. Used by: CommandError
#: musicbot/bot.py:4279
msgid "Spotify URL is invalid or not currently supported."
msgstr "Spotify URL 无效或目前不支持。"

#. Used by: CommandError
#: musicbot/bot.py:4283
msgid "Detected a Spotify URL, but Spotify is not enabled."
msgstr "检测到 Spotify 网址，但Spotify 未启用。"

#. Used by: PermissionsError
#: musicbot/bot.py:4293 musicbot/bot.py:4498
#, python-format
msgid "You have reached your enqueued song limit (%(max)s)"
msgstr ""

#. Used by: PermissionsError
#: musicbot/bot.py:4299 musicbot/bot.py:4504 musicbot/bot.py:4601
msgid "Karaoke mode is enabled, please try again when its disabled!"
msgstr "Karaoke模式已启用，请禁用后再试一次！"

#. Used by: exception
#: musicbot/bot.py:4311
msgid "Issue with extract_info(): "
msgstr "与extract_info() 有关的问题： "

#. Used by: CommandError
#: musicbot/bot.py:4315 musicbot/bot.py:4520
#, python-format
msgid ""
"Failed to extract info due to error:\n"
"%(raw_error)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:4321
msgid "That video cannot be played. Try using the stream command."
msgstr "无法播放该视频。请尝试使用流命令。"

#. Used by: CommandError
#: musicbot/bot.py:4332
#, python-format
msgid "YouTube search returned no results for:  %(url)s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:4362
#, python-format
msgid ""
"Processed %(number)d of %(total)d songs in %(time).3f seconds at "
"%(time_per).2f s/song"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:4373
#, python-format
msgid ""
"No songs were added, all songs were over max duration (%(max)s seconds)"
msgstr ""

#. Used by: noise
#: musicbot/bot.py:4389
msgid "Extracted an entry with 'youtube:playlist' as extractor key"
msgstr "提取了“youtube:playlist”作为提取器键的条目"

#. Used by: PermissionsError
#: musicbot/bot.py:4401
#, python-format
msgid "Song duration exceeds limit (%(length)s > %(max)s)"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:4419
#, python-format
msgid "Added song(s) at position %s"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:4456
#, python-format
msgid "Cannot estimate time until playing for position: %d"
msgstr ""

#. Used by: exception
#: musicbot/bot.py:4517
#, python-format
msgid "Failed to get info from the stream request: %s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:4526
msgid "Streaming playlists is not yet supported."
msgstr "尚不支持流播放列表。"

#. Used by: PermissionsError
#: musicbot/bot.py:4595
#, python-format
msgid "You have reached your playlist item limit (%(max)s)"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:4607
msgid ""
"Please specify a search query.  Use `help search` for more information."
msgstr "请指定一个搜索查询。使用 \"help search \" 获取更多信息。"

#. Used by: CommandError
#: musicbot/bot.py:4643
#, python-format
msgid "You cannot search for more than %(max)s videos"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:4968
#, python-format
msgid "Waiting for summon lock: %s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:4971
#, python-format
msgid "Summon lock acquired for: %s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:4975
msgid "You are not connected to voice. Try joining a voice channel!"
msgstr "您没有连接到语音。请尝试加入一个语音频道！"

#. Used by: info
#: musicbot/bot.py:5000
#, python-format
msgid "Joining %(guild)s/%(channel)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5062
msgid "MusicBot cannot follow a user that is not a member of the server."
msgstr "MusicBot 不能关注不是服务器成员的用户。"

#. Used by: CommandError
#: musicbot/bot.py:5090
msgid "Player is not playing."
msgstr "播放器未播放。"

#. Used by: CommandError
#: musicbot/bot.py:5215
msgid "Nothing in the queue to remove!"
msgstr "队列中没有要移除的内容！"

#. Used by: CommandError
#: musicbot/bot.py:5236
#, python-format
msgid "Nothing found in the queue from user `%(user)s`"
msgstr ""

#. Used by: PermissionsError
#: musicbot/bot.py:5241 musicbot/bot.py:5277
msgid ""
"You do not have the permission to remove that entry from the queue.\n"
"You must be the one who queued it or have instant skip permissions."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5252 musicbot/bot.py:5257
msgid "Invalid entry number. Use the queue command to find queue positions."
msgstr "无效的条目编号。使用队列命令来查找队列位置。"

#. Used by: CommandError
#: musicbot/bot.py:5308
msgid "Can't skip! The player is not playing!"
msgstr "无法跳过！玩家没有在玩！"

#. Used by: PermissionsError
#: musicbot/bot.py:5360
msgid "You do not have permission to force skip a looped song."
msgstr "您没有权限强制跳过循环歌曲。"

#. Used by: PermissionsError
#: musicbot/bot.py:5380
msgid "You do not have permission to force skip."
msgstr "您没有强制跳过的权限。"

#. Used by: PermissionsError
#: musicbot/bot.py:5417 musicbot/bot.py:5450
msgid "You do not have permission to skip a looped song."
msgstr "您没有权限跳过循环歌曲。"

#. Used by: CommandError
#: musicbot/bot.py:5500
#, python-format
msgid "`%(new_volume)s` is not a valid number"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5541
#, python-format
msgid ""
"Unreasonable volume change provided: %(old_volume)s%(adjustment)s is %(new_volume)s.\n"
"Volume can only be set from 1 to 100."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5551
#, python-format
msgid ""
"Unreasonable volume provided: %(volume)s. Provide a value between 1 and 100."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5575
msgid ""
"No track is playing, cannot set speed.\n"
"Use the config command to set a default playback speed."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5583
msgid "Speed cannot be applied to streamed media."
msgstr "速度不能应用于流媒体。"

#. Used by: CommandError
#: musicbot/bot.py:5588
msgid "You must provide a speed to set."
msgstr "您必须提供一个速度来设置。"

#. Used by: CommandError
#: musicbot/bot.py:5597
msgid "The speed you provided is invalid. Use a number between 0.5 and 100."
msgstr "您提供的速度无效。请使用0.5 至 100之间的数字。"

#. Used by: CommandError
#: musicbot/bot.py:5656 musicbot/bot.py:5772 musicbot/bot.py:6704
#, python-format
msgid "Invalid option for command: `%(option)s`"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5670
#, python-format
msgid ""
"Failed to save aliases due to error:\n"
"`%(raw_error)s`"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5677
msgid "You must supply an alias and a command to alias"
msgstr "您必须为别名提供别名和命令"

#. Used by: CommandError
#: musicbot/bot.py:5692
msgid "You must supply an alias name to remove."
msgstr "您必须提供一个别名来移除。"

#. Used by: CommandError
#: musicbot/bot.py:5697
#, python-format
msgid "The alias `%(alias)s` does not exist."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5755
msgid "Config cannot use channel and user mentions at the same time."
msgstr "配置不能同时使用频道和用户提到。"

#. Used by: CommandError
#: musicbot/bot.py:5853
#, python-format
msgid ""
"Unable to reload Config due to the following error:\n"
"%(raw_error)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5871
msgid ""
"Could not resolve section name from option name. Please provide a valid "
"section and option name."
msgstr "无法解析选项名称中的部分名称。请提供一个有效的部分和选项名称。"

#. Used by: CommandError
#: musicbot/bot.py:5875
msgid "The option given is ambiguous, please provide a section name."
msgstr "给定的选项含混，请提供一个章节名称。"

#. Used by: CommandError
#: musicbot/bot.py:5881
msgid "You must provide a section name and option name for this command."
msgstr "您必须提供此命令的部分名称和选项名称。"

#. Used by: CommandError
#: musicbot/bot.py:5897
#, python-format
msgid ""
"The section `%(section)s` is not available.\n"
"The available sections are:  %(sections)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5905
#, python-format
msgid "The option `%(option)s` is not available."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5933
#, python-format
msgid "Option `%(option)s` is not editable. Cannot save to disk."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5942
#, python-format
msgid "Failed to save the option:  `%(option)s`"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5957
#, python-format
msgid "Option `%(option)s` is not editable, value cannot be displayed."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5987
#, python-format
msgid "Option `%(option)s` is not editable. Cannot update setting."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5993 musicbot/bot.py:6917
msgid "You must provide a section, option, and value for this sub command."
msgstr "您必须为此子命令提供一个章节、选项和值。"

#. Used by: debug
#: musicbot/bot.py:5997
#, python-format
msgid "Doing set with on %(config)s == %(value)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6004
#, python-format
msgid "Option `%(option)s` was not updated!"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6020
#, python-format
msgid "Option `%(option)s` is not editable. Cannot reset to default."
msgstr ""

#. Used by: debug
#: musicbot/bot.py:6032
#, python-format
msgid "Resetting %(config)s to default %(value)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6039
#, python-format
msgid "Option `%(option)s` was not reset to default!"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6072
msgid "The option command is deprecated, use the config command instead."
msgstr "选项命令已废弃，请使用配置命令。"

#. Used by: CommandError
#: musicbot/bot.py:6092
msgid "Invalid option specified, use: info, update, or clear"
msgstr "指定的选项无效，使用：信息、更新或清除"

#. Used by: CommandError
#: musicbot/bot.py:6149
msgid "**Failed** to delete cache, check logs for more info..."
msgstr "**删除缓存失败，请检查日志获取更多信息..."

#. Used by: CommandError
#: musicbot/bot.py:6184
msgid "Queue page argument must be a whole number."
msgstr "队列页面参数必须是一个整数。"

#. Used by: CommandError
#: musicbot/bot.py:6191
msgid "There are no songs queued! Queue something with a play command."
msgstr "没有播放队列的歌曲！队列中有播放命令的歌曲。"

#. Used by: CommandError
#: musicbot/bot.py:6198
#, python-format
msgid ""
"Requested page number is out of bounds.\n"
"There are **%(total)s** pages."
msgstr ""

#. Used by: debug
#: musicbot/bot.py:6241
msgid "Skipped the current playlist entry."
msgstr "跳过当前播放列表条目。"

#. Used by: debug
#: musicbot/bot.py:6284
msgid "Not enough entries to paginate the queue."
msgstr "没有足够的条目来分页队列。"

#. Used by: warning
#: musicbot/bot.py:6288
msgid "Could not post queue message, no message to add reactions to."
msgstr "无法发布队列消息，没有消息添加反应。"

#. Used by: CommandError
#: musicbot/bot.py:6290
msgid ""
"Try that again. MusicBot couldn't make or get a reference to the queue message.\n"
"If the issue persists, file a bug report."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6400
msgid "Cannot use purge on private DM channel."
msgstr "无法在私有DM频道上使用净化。"

#. Used by: CommandError
#: musicbot/bot.py:6432
msgid "The given URL was not a valid URL."
msgstr "给定的 URL 不是有效的 URL。"

#. Used by: CommandError
#: musicbot/bot.py:6442
#, python-format
msgid ""
"Could not extract info from input url\n"
"%(raw_error)s\n"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6447
msgid "This does not seem to be a playlist."
msgstr "这似乎不是一个播放列表。"

#. Used by: CommandError
#: musicbot/bot.py:6610
msgid ""
"Invalid user ID or server nickname, please double-check the ID and try "
"again."
msgstr "无效的用户ID或服务器昵称，请重新检查ID，然后重试。"

#. Used by: CommandError
#: musicbot/bot.py:6617
msgid "Could not determine the discord User.  Try again."
msgstr "无法确定 Discord 用户，请重试。"

#. Used by: CommandError
#: musicbot/bot.py:6688
msgid "Permissions cannot use channel and user mentions at the same time."
msgstr "权限不能同时使用频道和用户提到。"

#. Used by: CommandError
#: musicbot/bot.py:6723
#, python-format
msgid ""
"Unable to reload Permissions due to an error:\n"
"%(raw_error)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6760
msgid "You must provide a group or option name for this command."
msgstr "您必须为此命令提供一个组或选项名称。"

#. Used by: CommandError
#: musicbot/bot.py:6764
msgid "You must provide a group, option, and value to set for this command."
msgstr "您必须为此命令设置一个组、选项和值。"

#. Used by: CommandError
#: musicbot/bot.py:6778
#, python-format
msgid "The %(option)s sub-command requires a group and permission name."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6790
#, python-format
msgid ""
"The group `%(group)s` is not available.\n"
"The available groups are:  %(sections)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6801
#, python-format
msgid "The permission `%(option)s` is not available."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6837
#, python-format
msgid "Cannot add group `%(group)s` it already exists."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6855
msgid "Cannot remove built-in group."
msgstr "无法删除内置组。"

#. Used by: CommandError
#: musicbot/bot.py:6873 musicbot/bot.py:6912
msgid "The owner group is not editable."
msgstr "所有者群组不可编辑。"

#. Used by: CommandError
#: musicbot/bot.py:6881
#, python-format
msgid "Failed to save the group:  `%(group)s`"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:6921
#, python-format
msgid "Doing set on %(option)s with value: %(value)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6928
#, python-format
msgid "Permission `%(option)s` was not updated!"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6969
msgid ""
"Failed to change username. Did you change names too many times?\n"
"Remember name changes are limited to twice per hour.\n"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6975
#, python-format
msgid ""
"Failed to change username due to error:  \n"
"%(raw_error)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6997
msgid "Unable to change nickname: no permission."
msgstr "无法更改昵称：没有权限。"

#. Used by: CommandError
#: musicbot/bot.py:7005
#, python-format
msgid ""
"Failed to set nickname due to error:  \n"
"%(raw_error)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:7045
msgid "Custom emoji must be from this server to use as a prefix."
msgstr "自定义表情必须来自此服务器才能用作前缀。"

#. Used by: CommandError
#: musicbot/bot.py:7062
msgid ""
"Prefix per server is not enabled!\n"
"Use the config command to update the prefix instead."
msgstr ""
"每个服务器的前缀未启用！\n"
"使用配置命令来更新前缀。"

#. Used by: CommandError
#: musicbot/bot.py:7092
msgid "This command can only be used in guilds."
msgstr "此命令只能用于公会。"

#. Used by: CommandError
#: musicbot/bot.py:7097
msgid "Invalid sub-command given. Use the help command for more information."
msgstr "给定的子命令无效。请使用帮助命令获取更多信息。"

#. Used by: CommandError
#: musicbot/bot.py:7118
#, python-format
msgid "Cannot set language to `%(locale)s` it is not available."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:7163
msgid "You must provide a URL or attach a file."
msgstr "您必须提供一个 URL 或附加文件。"

#. Used by: CommandError
#: musicbot/bot.py:7173
#, python-format
msgid ""
"Unable to change avatar due to error:  \n"
"%(raw_error)s"
msgstr ""

#. Used by: warning
#: musicbot/bot.py:7198
#, python-format
msgid "MusicBot found a %s with no guild!  This could be a problem."
msgstr "MusicBot找到了一个 %s 没有公会！这可能是一个问题。"

#. Used by: CommandError
#: musicbot/bot.py:7210
#, python-format
msgid "Not currently connected to server `%(guild)s`"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:7251
msgid ""
"Invalid option given, use one of:  soft, full, upgrade, uppip, or upgit"
msgstr "给定的选项无效，请使用其中一项：软、完整、升级、上传或上传。"

#. Used by: CommandError
#: musicbot/bot.py:7360
msgid "You must provide an ID or name."
msgstr "您必须提供一个ID或名称。"

#. Used by: CommandError
#: musicbot/bot.py:7371
#, python-format
msgid "No guild was found with the ID or name `%(input)s`"
msgstr ""

#. Used by: critical
#: musicbot/bot.py:7428
#, python-format
msgid "Activating debug breakpoint ID: %(uuid)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:7468
msgid "Could not import `objgraph`, is it installed?"
msgstr "无法导入 `objgraph` ，是否安装？"

#. Used by: debug
#: musicbot/bot.py:7544
msgid "Debug code ran with eval()."
msgstr "调试代码使用 eval()."

#. Used by: debug
#: musicbot/bot.py:7554
msgid "Debug code ran with exec()."
msgstr "调试代码与 exec() 一起运行。"

#. Used by: exception
#: musicbot/bot.py:7557
msgid "Debug code failed to execute."
msgstr "调试代码执行失败。"

#. Used by: CommandError
#: musicbot/bot.py:7559
#, python-format
msgid ""
"Failed to execute debug code:\n"
"%(py_code)s\n"
"Exception: ```\n"
"%(ex_name)s:\n"
"%(ex_text)s```"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:7594 musicbot/bot.py:7655
#, python-format
msgid "Sub-command must be one of: %(options)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:7694
msgid "Could not locate git executable."
msgstr "无法找到 git 可执行文件。"

#. Used by: exception
#: musicbot/bot.py:7738
msgid "Failed while checking for updates via git command."
msgstr "通过 git 命令检查更新失败。"

#. Used by: debug
#: musicbot/bot.py:7767
msgid "Package missing meta in pip report."
msgstr "Pip报告中缺少元数据。"

#. Used by: exception
#: musicbot/bot.py:7781
msgid "Failed to get pip update status due to some error."
msgstr "由于某些错误，Pip更新状态失败。"

#. Used by: debug
#: musicbot/bot.py:7842
msgid "Got a strange voice client entry."
msgstr "获取一个奇怪的语音客户端条目。"

#. Used by: CommandError
#: musicbot/bot.py:7952
msgid "Cookies already enabled."
msgstr "Cookie 已启用。"

#. Used by: CommandError
#: musicbot/bot.py:7959
msgid "Cookies must be uploaded to be enabled. (Missing cookies file.)"
msgstr "Cookie 必须上传才能启用。(正在使用 cookies 文件)"

#. Used by: CommandError
#: musicbot/bot.py:7972
#, python-format
msgid "Could not enable cookies due to error:  %(raw_error)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:7986
#, python-format
msgid ""
"Could not rename cookies file due to error:  %(raw_error)s\n"
"Cookies temporarily disabled and will be re-enabled on next restart."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:7995
msgid ""
"No attached uploads were found, try again while uploading a cookie file."
msgstr "没有找到附加的上传文件，上传cookie文件时再试一次。"

#. Used by: warning
#: musicbot/bot.py:8004
#, python-format
msgid "Could not remove old, disabled cookies file:  %(raw_error)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:8013
#, python-format
msgid "Error downloading the cookies file from discord:  %(raw_error)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:8018
#, python-format
msgid "Could not save cookies to disk:  %(raw_error)s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8036
#, python-format
msgid "Got a message with no channel, somehow:  %s"
msgstr "获取一条没有频道的消息，或者说：  %s"

#. Used by: warning
#: musicbot/bot.py:8064
#, python-format
msgid "Ignoring command from myself (%s)"
msgstr "忽略自身的命令 (%s)"

#. Used by: warning
#: musicbot/bot.py:8072
#, python-format
msgid "Ignoring command from other bot (%s)"
msgstr "忽略其它机器人的命令(%s)"

#. Used by: warning
#: musicbot/bot.py:8080
#, python-format
msgid "Ignoring command from channel of type:  %s"
msgstr "忽略频道类型的命令：  %s"

#. Used by: warning
#: musicbot/bot.py:8175
#, python-format
msgid "User in block list: %(id)s/%(name)s  tried command: %(command)s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:8182
#, python-format
msgid "Message from %(id)s/%(name)s: %(message)s"
msgstr ""

#. Used by: PermissionsError
#: musicbot/bot.py:8217
#, python-format
msgid "This command is not allowed for your permissions group:  %(group)s"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:8252
msgid "This command requires you to be in a Voice channel."
msgstr "此命令要求您在语音频道中。"

#. Used by: debug
#: musicbot/bot.py:8341
#, python-format
msgid "Invalid command usage, missing values for params: %(params)r"
msgstr ""

#. Used by: error
#: musicbot/bot.py:8379
#, python-format
msgid "Error in %(command)s: %(err_name)s: %(err_text)s"
msgstr ""

#. Used by: error
#: musicbot/bot.py:8402
#, python-format
msgid "Exception while handling command: %(command)s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8433
#, python-format
msgid "Cannot generate help for missing command:  %s"
msgstr "无法为缺失的命令生成帮助：  %s"

#. Used by: critical
#: musicbot/bot.py:8437
#, python-format
msgid "Missing help data for command:  %s"
msgstr "缺少命令的帮助数据：  %s"

#. Used by: info
#: musicbot/bot.py:8554
#, python-format
msgid "Leaving voice channel %s in %s due to inactivity."
msgstr ""

#. Used by: info
#: musicbot/bot.py:8563
msgid "MusicBot has become connected."
msgstr "MusicBot 已连接。"

#. Used by: info
#: musicbot/bot.py:8567
msgid "MusicBot has become disconnected."
msgstr "MusicBot 已断开连接。"

#. Used by: everything
#: musicbot/bot.py:8572
#, python-format
msgid "Got a Socket Event:  %s"
msgstr "获取一个套接字事件:  %s"

#. Used by: warning
#: musicbot/bot.py:8588
msgid "VoiceState updated before on_ready finished"
msgstr "在 on_ready 完成之前更新语音状态"

#. Used by: info
#: musicbot/bot.py:8601
#, python-format
msgid "Ignoring %s in %s as it is a bound voice channel."
msgstr "忽略 %s 中的 %s ，因为它是一个绑定的语音频道。"

#. Used by: info
#: musicbot/bot.py:8610
#, python-format
msgid "%s has been detected as empty. Handling timeouts."
msgstr "%s 被检测为空。处理超时。"

#. Used by: info
#: musicbot/bot.py:8621
#, python-format
msgid "A user joined %s, cancelling timer."
msgstr "一个用户加入 %s，取消计时器。"

#. Used by: info
#: musicbot/bot.py:8634
#, python-format
msgid ""
"The bot got moved and the voice channel %s is empty. Handling timeouts."
msgstr "机器人移动了，音频道 %s 为空。处理超时。"

#. Used by: info
#: musicbot/bot.py:8643
#, python-format
msgid "The bot got moved and the voice channel %s is not empty."
msgstr "机器人移动了，声音频道 %s 不是空的。"

#. Used by: debug
#: musicbot/bot.py:8692
#, python-format
msgid "No longer following user %s"
msgstr "不再关注用户 %s"

#. Used by: debug
#: musicbot/bot.py:8714
#, python-format
msgid "Following user `%(user)s` to channel:  %(channel)s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8734
msgid "VoiceState disconnect before.channel is None."
msgstr "频道前没有语音状态断开连接。"

#. Used by: info
#: musicbot/bot.py:8761
#, python-format
msgid ""
"Disconnected from voice by Discord API in: %(guild)s/%(channel)s (Code: "
"%(code)s) [S:%(state)s]"
msgstr ""

#. Used by: error
#: musicbot/bot.py:8783
#, python-format
msgid "Cannot use auto-join channel with type: %(type)s  in guild:  %(guild)s"
msgstr ""

#. Used by: error
#: musicbot/bot.py:8790
#, python-format
msgid "Cannot find the auto-joined channel, was it deleted?  Guild:  %s"
msgstr "找不到自动加入的频道，是否删除？公会:  %s"

#. Used by: info
#: musicbot/bot.py:8796
#, python-format
msgid "Reconnecting to auto-joined guild on channel:  %s"
msgstr "重新连接到频道上的自动加入公会:  %s"

#. Used by: warning
#: musicbot/bot.py:8809
#, python-format
msgid "Cannot auto join channel:  %s"
msgstr "无法自动加入频道:  %s"

#. Used by: info
#: musicbot/bot.py:8825
#, python-format
msgid "Bot has been added to guild: %s"
msgstr "帐号已添加到公会: %s"

#. Used by: info
#: musicbot/bot.py:8837
#, python-format
msgid "Left guild '%s' due to bot owner not found."
msgstr "由于找不到机器人所有人，左公会为%s' 。"

#. Used by: debug
#: musicbot/bot.py:8851
#, python-format
msgid "Creating data folder for guild %s"
msgstr "为公会创建数据文件夹 %s"

#. Used by: info
#: musicbot/bot.py:8859
#, python-format
msgid "Bot has been removed from guild: %s"
msgstr "机器人已从公会中移除： %s"

#. Used by: debug
#: musicbot/bot.py:8860
msgid "Updated guild list:"
msgstr "更新公会列表："

#. Used by: info
#: musicbot/bot.py:8875
#, python-format
msgid "Guild \"%s\" has become available."
msgstr "公会\"%s\"已经可用。"

#. Used by: debug
#: musicbot/bot.py:8881
#, python-format
msgid "Resuming player in \"%s\" due to availability."
msgstr "由于可用，恢复玩家“%s”。"

#. Used by: info
#: musicbot/bot.py:8898
#, python-format
msgid "Guild \"%s\" has become unavailable."
msgstr "公会\"%s\" 已不可用。"

#. Used by: debug
#: musicbot/bot.py:8904
#, python-format
msgid "Pausing player in \"%s\" due to unavailability."
msgstr "由于不可用而暂停玩家 \"%s\"。"

#. Used by: info
#: musicbot/bot.py:8920
#, python-format
msgid "Guild update for:  %s"
msgstr "公会更新:  %s"

#. Used by: everything
#: musicbot/bot.py:8926
#, python-format
msgid "Guild attribute %(attr)s is now: %(new)s  -- Was: %(old)s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:8977
#, python-format
msgid "Channel update for:  %(channel)s  --  %(changes)s"
msgstr ""

#. Used by: warning
#: musicbot/config.py:86
#, python-format
msgid "Creating %s"
msgstr "正在创建 %s"

#. Used by: info
#: musicbot/config.py:107
#, python-format
msgid "Loading config from:  %s"
msgstr "正在加载配置：  %s"

#. Used by: HelpfulError
#: musicbot/config.py:1128
#, python-format
msgid ""
"Error while reading config.\n"
"\n"
"Problem:\n"
"  One or more required config option sections are missing.\n"
"  The missing sections are:\n"
"  %(sections)s\n"
"\n"
"Solution:\n"
"  Repair your config options file.\n"
"  Each [Section] must appear only once, with no other text on the same line.\n"
"  Each section must have at least one option.\n"
"  Use the example options as a template or copy it from the repository."
msgstr ""

#. Used by: warning
#: musicbot/config.py:1158
#, python-format
msgid ""
"Cannot store more than %s log files. Option LogsMaxKept will be limited "
"instead."
msgstr "不能存储超过 %s 的日志文件。选项LogsMaxKept 将被限制。"

#. Used by: warning
#: musicbot/config.py:1166
msgid ""
"Config option LogsDateFormat is empty and this will break log file rotation."
" Using default instead."
msgstr "配置选项 LogsDateFormat 是空的，这将破坏日志文件的旋转。使用默认值。"

#. Used by: HelpfulError
#: musicbot/config.py:1177
msgid ""
"Error while validating config options.\n"
"\n"
"Problem:\n"
"  Config option AudioCachePath is not a directory.\n"
"\n"
"Solution:\n"
"  Make sure the path you configured is a path to a folder / directory."
msgstr ""

#. Used by: exception
#: musicbot/config.py:1194
msgid "An exception was thrown while validating AudioCachePath."
msgstr "验证AudioCachePath时出现异常。"

#. Used by: HelpfulError
#: musicbot/config.py:1198
#, python-format
msgid ""
"Error while validating config options.\n"
"\n"
"Problem:\n"
"  AudioCachePath config option could not be set due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Double check the setting is a valid, accessible directory path."
msgstr ""

#. Used by: info
#: musicbot/config.py:1210
#, python-format
msgid "Audio Cache will be stored in:  %s"
msgstr "音频缓存将存储在:  %s"

#. Used by: HelpfulError
#: musicbot/config.py:1221
#, python-format
msgid ""
"Error while reading config options.\n"
"\n"
"Problem:\n"
"  No bot Token was specified in the config options or environment.\n"
"\n"
"Solution:\n"
"  Set the Token config option or set environment variable %(env_var)s with an App token."
msgstr ""

#. Used by: warning
#: musicbot/config.py:1242
msgid ""
"StatusMessage config option is too long, it will be limited to 128 "
"characters."
msgstr "状态消息配置选项太长，它将被限制为128个字符。"

#. Used by: warning
#: musicbot/config.py:1251
#, python-format
msgid ""
"The default playback speed must be between 0.5 and 100.0. The option value "
"of %.3f will be limited instead."
msgstr "默认播放速度必须在 0.5 和 100.0之间。 %.3f 的选项值将被限制。"

#. Used by: debug
#: musicbot/config.py:1268
msgid "Validating options with service data..."
msgstr "正在通过服务数据验证选项..."

#. Used by: debug
#: musicbot/config.py:1274
msgid "Acquired owner ID via API"
msgstr "通过 API 获得所有者ID"

#. Used by: HelpfulError
#: musicbot/config.py:1278
msgid ""
"Error while fetching 'OwnerID' automatically.\n"
"\n"
"Problem:\n"
"  Discord App info is not available.\n"
"  This could be a temporary API outage or a bug.\n"
"\n"
"Solution:\n"
"  Manually set the 'OwnerID' config option or try again later."
msgstr ""

#. Used by: critical
#: musicbot/config.py:1290
msgid "MusicBot does not have a user instance, cannot proceed."
msgstr "MusicBot 没有用户实例，不能继续。"

#. Used by: HelpfulError
#: musicbot/config.py:1296
msgid ""
"Error validating config options.\n"
"\n"
"Problem:\n"
"  The 'OwnerID' config is the same as your Bot / App ID.\n"
"\n"
"Solution:\n"
"  Do not use the Bot or App ID in the 'OwnerID' field."
msgstr ""
"验证配置选项时出错。\n"
"\n"
"问题：\n"
"  “所有者ID”配置与您的 Bot / App ID相同。\n"
"\n"
"解决方案：\n"
"  不要在“所有者ID”字段中使用机器人或App ID。"

#. Used by: warning
#: musicbot/config.py:1320
msgid "Config options file not found. Checking for alternatives..."
msgstr "找不到配置选项文件，正在检查替代..."

#. Used by: warning
#: musicbot/config.py:1333
#, python-format
msgid ""
"Renaming %(ini_file)s to %(option_file)s, you should probably turn file "
"extensions on."
msgstr ""

#. Used by: warning
#: musicbot/config.py:1341
#, python-format
msgid "Copying existing example options file:  %(example_file)s"
msgstr ""

#. Used by: exception
#: musicbot/config.py:1355
msgid "Something went wrong while trying to find a config option file."
msgstr "试图找到配置选项文件时出了错。"

#. Used by: HelpfulError
#: musicbot/config.py:1359
#, python-format
msgid ""
"Error locating config.\n"
"\n"
"Problem:\n"
"  Could not find or create a config file due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Verify the config folder and files exist and can be read by MusicBot."
msgstr ""
"定位配置时出错。\n"
"\n"
"问题：\n"
"  由于错误无法找到或创建配置文件：\n"
"  %(raw_error)s\n"
"\n"
"解决方案：\n"
"  验证配置文件夹和文件存在并且可以通过 MusicBot 读取。"

#. Used by: HelpfulError
#: musicbot/config.py:1377
#, python-format
msgid ""
"Error loading config.\n"
"\n"
"Problem:\n"
"  MusicBot could not read config file due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Make sure the file is accessible and error free.\n"
"  Copy the example file from the repo if all else fails."
msgstr ""

#. Used by: critical
#: musicbot/config.py:1401
msgid "Dev Bug! Config option has getter that is not available."
msgstr "开发错误！配置选项有不可用的getter。"

#. Used by: error
#: musicbot/config.py:1406
msgid ""
"Dev Bug! Config option has invalid type, getter and default must be the same"
" type."
msgstr "开发错误！配置选项的类型无效，获取类型和默认类型必须相同。"

#. Used by: debug
#: musicbot/config.py:1426
msgid "Option was missing previously."
msgstr "此前缺少备选办法。"

#. Used by: error
#: musicbot/config.py:1441
#, python-format
msgid "Config section not in parsed config! Missing: %s"
msgstr "配置部分不在解析后的配置中！缺少： %s"

#. Used by: info
#: musicbot/config.py:1446
#, python-format
msgid "Saved config option: %(config)s  =  %(value)s"
msgstr ""

#. Used by: exception
#: musicbot/config.py:1459
#, python-format
msgid "Failed to save config:  %s"
msgstr "保存配置失败：  %s"

#. Used by: warning
#: musicbot/config.py:1973
msgid ""
"Option names are not unique between INI sections!  Resolver is disabled."
msgstr "选项名称在INI部分之间并不唯一！解析器已被禁用。"

#. Used by: exception
#: musicbot/config.py:2151 musicbot/permissions.py:909
#, python-format
msgid "Failed to save default INI file at:  %s"
msgstr "保存默认 INI 文件失败:  %s"

#. Used by: HelpfulError
#: musicbot/config.py:2241
#, python-format
msgid ""
"Error loading config value.\n"
"\n"
"Problem:\n"
"  The owner ID in [%(section)s] > %(option)s is not valid.\n"
"\n"
"Solution:\n"
"  Set %(option)s to a numerical ID or set it to `auto` or `0` for automatic owner binding."
msgstr ""

#. Used by: HelpfulError
#: musicbot/config.py:2277
#, python-format
msgid ""
"Error loading config value.\n"
"\n"
"Problem:\n"
"  The config option [%(section)s] > %(option)s is not a valid file location.\n"
"\n"
"Solution:\n"
"  Check the path setting and make sure the file exists and is accessible to MusicBot."
msgstr ""

#. Used by: HelpfulError
#: musicbot/config.py:2307
#, python-format
msgid ""
"Error loading config value.\n"
"\n"
"Problem:\n"
"  One of the IDs in option [%(section)s] > %(option)s is invalid.\n"
"\n"
"Solution:\n"
"  Ensure all IDs are numerical, and separated only by spaces or commas."
msgstr ""

#. Used by: warning
#: musicbot/config.py:2343
#, python-format
msgid ""
"Invalid DebugLevel option \"%(value)s\" given, falling back to level: "
"%(fallback)s"
msgstr ""

#. Used by: warning
#: musicbot/config.py:2364
#, python-format
msgid ""
"Option [%(section)s] > %(option)s has invalid config value '%(value)s' using"
" default instead."
msgstr ""

#. Used by: warning
#: musicbot/config.py:2413
#, python-format
msgid ""
"Option [%(section)s] > %(option)s has a value greater than 100 %% "
"(%(value)s) and will be set to %(fallback)s instead."
msgstr ""

#. Used by: debug
#: musicbot/config.py:2538
#, python-format
msgid ""
"Renaming INI file entry [%(old_s)s] > %(old_o)s  to  [%(new_s)s] > %(new_o)s"
msgstr ""

#. Used by: debug
#: musicbot/config.py:2609
msgid "Upgrading config file with renamed options..."
msgstr "使用重命名选项升级配置文件..."

#. Used by: exception
#: musicbot/config.py:2643
msgid "Failed to upgrade config.  You'll need to upgrade it manually."
msgstr "升级配置失败。您需要手动升级。"

#. Used by: warning
#: musicbot/config.py:2684
#, python-format
msgid "Block list file not found:  %s"
msgstr "未找到方块列表文件：  %s"

#. Used by: error
#: musicbot/config.py:2705
#, python-format
msgid "Could not load block list from file:  %s"
msgstr "无法从文件加载块列表：  %s"

#. Used by: error
#: musicbot/config.py:2743 musicbot/config.py:2776
#, python-format
msgid "Could not update the block list file:  %s"
msgstr "无法更新块列表文件：  %s"

#. Used by: debug
#: musicbot/config.py:2803
#, python-format
msgid "Loaded User Block list with %s entries."
msgstr "使用 %s 条目加载用户块列表。"

#. Used by: warning
#: musicbot/config.py:2814
#, python-format
msgid "We found a legacy blacklist file, it will be renamed to:  %s"
msgstr "我们找到了一个旧的黑名单文件，它将被重命名为:  %s"

#. Used by: debug
#: musicbot/config.py:2860
#, python-format
msgid "Loaded a Song Block list with %s entries."
msgstr "使用 %s 条目加载歌曲方块列表。"

#. Used by: error
#: musicbot/constructs.py:220
msgid ""
"Cannot load data for guild with ID 0. This is likely a bug in the code!"
msgstr "无法用ID0加载公会数据。这可能是代码中的错误！"

#. Used by: debug
#: musicbot/constructs.py:229
#, python-format
msgid "No file for guild %(id)s/%(name)s"
msgstr ""

#. Used by: debug
#: musicbot/constructs.py:238
#, python-format
msgid "Loading guild data for guild with ID:  %(id)s/%(name)s"
msgstr ""

#. Used by: exception
#: musicbot/constructs.py:245
#, python-format
msgid "An OS error prevented reading guild data file:  %s"
msgstr "一个操作系统错误阻止读取公会数据文件：  %s"

#. Used by: info
#: musicbot/constructs.py:256
#, python-format
msgid "Guild %(id)s/%(name)s has custom command prefix: %(prefix)s"
msgstr ""

#. Used by: error
#: musicbot/constructs.py:276
msgid ""
"Cannot save data for guild with ID 0. This is likely a bug in the code!"
msgstr "无法保存与 ID 0的公会数据。这可能是代码中的一个错误！"

#. Used by: exception
#: musicbot/constructs.py:300
msgid "Could not save guild specific data due to OS Error."
msgstr "由于操作系统错误，无法保存公会特定数据。"

#. Used by: exception
#: musicbot/constructs.py:303
msgid "Failed to serialize guild specific data due to invalid data."
msgstr "由于无效数据，无法序列化公会特定数据。"

#. Used by: warning
#: musicbot/downloader.py:129
#, python-format
msgid "Forcing YTDLP to use User Agent:  %s"
msgstr "强制YTDLP使用用户代理:  %s"

#. Used by: info
#: musicbot/downloader.py:148
#, python-format
msgid "MusicBot will use cookies for yt-dlp from:  %s"
msgstr "MusicBot 将使用 cookie 的 yt-dlp:  %s"

#. Used by: info
#: musicbot/downloader.py:154
msgid "Yt-dlp will use your configured proxy server."
msgstr "Yt-dlp 将使用您配置的代理服务器。"

#. Used by: ExtractionError
#: musicbot/downloader.py:244
msgid "HEAD seems to have no headers..."
msgstr "HEAD 似乎没有信头..."

#. Used by: warning
#: musicbot/downloader.py:255
msgid "Checking media headers failed due to timeout."
msgstr "由于超时检查媒体头部失败。"

#. Used by: warning
#: musicbot/downloader.py:258
#, python-format
msgid "Failed HEAD request for:  %s"
msgstr "HEAD 请求失败：  %s"

#. Used by: exception
#: musicbot/downloader.py:259
msgid "HEAD Request exception: "
msgstr "HEAD 请求异常： "

#. Used by: noise
#: musicbot/downloader.py:327
#, python-format
msgid ""
"Sanitized YTDL Extraction Info (not JSON):\n"
"%s"
msgstr ""
"卫生化的 YTDL 提取信息(非JSON ):\n"
"%s"

#. Used by: noise
#: musicbot/downloader.py:329
#, python-format
msgid "Sanitized YTDL Extraction Info (not JSON):  %s"
msgstr "已卫生化的 YTDL 提取信息(而不是JSON ):  %s"

#. Used by: ExtractionError
#: musicbot/downloader.py:393
msgid "Song info extraction returned no data."
msgstr "歌曲信息提取没有返回数据。"

#. Used by: noise
#: musicbot/downloader.py:449
#, python-format
msgid "Called extract_info with:  '%(subject)s', %(args)s, %(kws)s"
msgstr ""

#. Used by: warning
#: musicbot/downloader.py:457
msgid "Cannot run extraction, loop is closed. (This is normal on shutdowns.)"
msgstr "无法运行提取，循环已关闭。(关机时这是正常的。)"

#. Used by: MusicbotException
#: musicbot/downloader.py:459
msgid "Cannot continue extraction, event loop is closed."
msgstr "无法继续提取，事件循环已关闭。"

#. Used by: ExtractionError
#: musicbot/downloader.py:468
msgid "Spotify URL is invalid or not supported."
msgstr "Spotify URL 无效或不支持。"

#. Used by: exception
#: musicbot/downloader.py:506
msgid "Download Error with stream URL"
msgstr "下载流URL错误"

#. Used by: debug
#: musicbot/downloader.py:511
msgid "Assuming content is a direct stream"
msgstr "假设内容是直接流"

#. Used by: ExtractionError
#: musicbot/downloader.py:519
msgid "Cannot stream an invalid URL."
msgstr "无法生成无效的 URL。"

#. Used by: noise
#: musicbot/downloader.py:530
msgid ""
"Caught NoSupportingHandlers, trying again after replacing colon with space."
msgstr "捕捉到NoSupportingHanders，在用空格替换冒号后再次尝试。"

#. Used by: noise
#: musicbot/downloader.py:574
#, python-format
msgid "Called safe_extract_info with:  %(args)s, %(kws)s"
msgstr ""

#. Used by: MusicbotException
#: musicbot/downloader.py:594
msgid "The local media file could not be found."
msgstr "找不到本地媒体文件。"

#. Used by: warning
#: musicbot/downloader.py:632
msgid "Missing __input_subject from YtdlpResponseDict"
msgstr "YtdlpResponseDict 缺少__input_subject"

#. Used by: warning
#: musicbot/downloader.py:637
msgid ""
"Entries is not a list in YtdlpResponseDict, set process=True to avoid this."
msgstr "条目不是 YtdlpResponseDict 中的列表, 设置进程=True 以避免这种情况。"

#. Used by: noise
#: musicbot/downloader.py:866
#, python-format
msgid "Warning, duration error for: %(url)s"
msgstr ""

#. Used by: debug
#: musicbot/entry.py:46
msgid "module 'pymediainfo' not found, will fall back to ffprobe."
msgstr "未找到模块“pymediainfo”，将会退回到ffprobe。"

#. Used by: debug
#: musicbot/entry.py:159
#, python-format
msgid "Created future for %r"
msgstr "%r 未来创建"

#. Used by: everything
#: musicbot/entry.py:171
#, python-format
msgid "Completed futures for %(entry)r with %(callback)r"
msgstr ""

#. Used by: exception
#: musicbot/entry.py:181
msgid "Unhandled exception in _for_each_future callback."
msgstr "在 _for_each_future 回拨中未处理异常。"

#. Used by: noise
#: musicbot/entry.py:223
#, python-format
msgid "Starting asyncio subprocess (%(process)s) with command: %(run)s"
msgstr ""

#. Used by: info
#: musicbot/entry.py:258
#, python-format
msgid ""
"Extraction did not provide a duration for this entry.\n"
"MusicBot cannot estimate queue times until it is downloaded.\n"
"Entry name:  %s"
msgstr ""

#. Used by: error
#: musicbot/entry.py:364 musicbot/entry.py:874 musicbot/entry.py:1084
msgid "Entry data is missing version number, cannot deserialize."
msgstr "条目数据缺失版本号，不能反序列化。"

#. Used by: error
#: musicbot/entry.py:367 musicbot/entry.py:877 musicbot/entry.py:1087
msgid "Entry data has the wrong version number, cannot deserialize."
msgstr "条目数据有错误的版本号，不能反序列化。"

#. Used by: warning
#: musicbot/entry.py:383
#, python-format
msgid "Deserialized URLPlaylistEntry cannot find channel with ID:  %s"
msgstr "反序列化的 URL 播放列表条目无法找到 ID 的频道:  %s"

#. Used by: warning
#: musicbot/entry.py:399
#, python-format
msgid "Deserialized URLPlaylistEntry has the wrong channel type:  %s"
msgstr "反序列化的 URL 播放列表条目有错误的频道类型：  %s"

#. Used by: warning
#: musicbot/entry.py:421
#, python-format
msgid "Deserialized URLPlaylistEntry cannot find author with ID:  %s"
msgstr "反序列化的 URL 播放列表条目找不到 ID 的作者：  %s"

#. Used by: warning
#: musicbot/entry.py:427
msgid ""
"Deserialized URLPlaylistEntry has an author ID but no channel for lookup!"
msgstr "反序列化的 URL 播放列表条目有作者ID，但没有查找频道！"

#. Used by: error
#: musicbot/entry.py:437 musicbot/entry.py:943 musicbot/entry.py:1157
#, python-format
msgid "Could not load %s"
msgstr "无法加载 %s"

#. Used by: InvalidDataError
#: musicbot/entry.py:474
#, python-format
msgid "Cannot download Spotify links, processing error with type: %(type)s"
msgstr ""

#. Used by: debug
#: musicbot/entry.py:486 musicbot/entry.py:948 musicbot/entry.py:1190
#, python-format
msgid "Getting ready for entry:  %r"
msgstr "准备进入：  %r"

#. Used by: warning
#: musicbot/entry.py:503
msgid "Download cached with different extension..."
msgstr "下载缓存的扩展..."

#. Used by: debug
#: musicbot/entry.py:512
msgid "Local size different from remote size. Re-downloading..."
msgstr "本地大小不同于远程大小。正在重新下载..."

#. Used by: debug
#: musicbot/entry.py:516
#, python-format
msgid "Download already cached at:  %s"
msgstr "下载已缓存于:  %s"

#. Used by: error
#: musicbot/entry.py:536 musicbot/entry.py:1206
#, python-format
msgid ""
"MusicBot could not get duration data for this entry.\n"
"Queue time estimation may be unavailable until this track is cleared.\n"
"Entry file: %s"
msgstr ""

#. Used by: debug
#: musicbot/entry.py:543
#, python-format
msgid "Got duration of %(time)s seconds for file:  %(file)s"
msgstr ""

#. Used by: error
#: musicbot/entry.py:554 musicbot/entry.py:1224
msgid ""
"There as a problem with working out EQ, likely caused by a strange "
"installation of FFmpeg. This has not impacted the ability for the bot to "
"work, but will mean your tracks will not be equalized."
msgstr "解决EQ问题可能是一个奇怪的安装程序造成的。 这不会影响机器人的工作能力，但意味着您的轨道将不会平等。"

#. Used by: error
#: musicbot/entry.py:566 musicbot/entry.py:1237
msgid "Exception while checking entry data."
msgstr "检查条目数据时出现异常。"

#. Used by: debug
#: musicbot/entry.py:577 musicbot/entry.py:1248
#, python-format
msgid "Trying to get duration via pymediainfo for:  %s"
msgstr "尝试通过pymediainfo 获取持续时间:  %s"

#. Used by: exception
#: musicbot/entry.py:583 musicbot/entry.py:1254
msgid "Failed to get duration via pymediainfo."
msgstr "无法通过 pymediainfo 获取持续时间。"

#. Used by: debug
#: musicbot/entry.py:590 musicbot/entry.py:1261
#, python-format
msgid "Trying to get duration via ffprobe for:  %s"
msgstr "尝试通过 ffprobe 获取持续时间:  %s"

#. Used by: error
#: musicbot/entry.py:593 musicbot/entry.py:1264
msgid "Could not locate ffprobe in your path!"
msgstr "无法在您的路径中找到 ffprobe!"

#. Used by: error
#: musicbot/entry.py:614 musicbot/entry.py:1285
msgid "ffprobe returned something that could not be used."
msgstr "ffprobe 返回了无法使用的东西。"

#. Used by: exception
#: musicbot/entry.py:617 musicbot/entry.py:1288
msgid "ffprobe could not be executed for some reason."
msgstr "由于某种原因无法执行 ffprobe。"

#. Used by: debug
#: musicbot/entry.py:627 musicbot/entry.py:1298
#, python-format
msgid "Calculating mean volume of:  %s"
msgstr "计算平均体积:  %s"

#. Used by: error
#: musicbot/entry.py:630 musicbot/entry.py:1301
msgid "Could not locate ffmpeg on your path!"
msgstr "无法在您的路径上找到 ffmpeg ！"

#. Used by: debug
#: musicbot/entry.py:656 musicbot/entry.py:1327
msgid "Could not parse 'I' in normalize json."
msgstr "无法解析 json。"

#. Used by: debug
#: musicbot/entry.py:664 musicbot/entry.py:1335
msgid "Could not parse 'LRA' in normalize json."
msgstr "无法解析 json 正常化 “LRA”。"

#. Used by: debug
#: musicbot/entry.py:672 musicbot/entry.py:1343
msgid "Could not parse 'TP' in normalize json."
msgstr "无法解析 json 正常化 “TP”。"

#. Used by: debug
#: musicbot/entry.py:680 musicbot/entry.py:1351
msgid "Could not parse 'thresh' in normalize json."
msgstr "无法解析 json 正常化 “阈值”。"

#. Used by: debug
#: musicbot/entry.py:688 musicbot/entry.py:1359
msgid "Could not parse 'offset' in normalize json."
msgstr "无法解析 json 正常化 'offset' 。"

#. Used by: info
#: musicbot/entry.py:705
#, python-format
msgid "Download started:  %r"
msgstr "开始下载：  %r"

#. Used by: everything
#: musicbot/entry.py:710
#, python-format
msgid "Download attempt %s of 3..."
msgstr "下载尝试 %s ，共 3 次..."

#. Used by: warning
#: musicbot/entry.py:722
#, python-format
msgid ""
"Download incomplete, retrying in %(time).1f seconds.  Reason: %(raw_error)s"
msgstr ""

#. Used by: error
#: musicbot/entry.py:730
#, python-format
msgid "Download failed, not retrying! Reason:  %(raw_error)s"
msgstr ""

#. Used by: ExtractionError
#: musicbot/entry.py:735
#, python-format
msgid "Download did not complete due to an error: %(raw_error)s"
msgstr ""

#. Used by: ExtractionError
#: musicbot/entry.py:741
#, python-format
msgid "Download failed due to a yt-dlp error: %(raw_error)s"
msgstr ""

#. Used by: error
#: musicbot/entry.py:747
msgid "Extraction encountered an unhandled exception."
msgstr "解压遇到一个未处理的异常。"

#. Used by: MusicbotException
#: musicbot/entry.py:751
#, python-format
msgid "Download failed due to an unhandled exception: %(raw_error)s"
msgstr ""

#. Used by: error
#: musicbot/entry.py:756
#, python-format
msgid "Download failed:  %r"
msgstr "下载失败：  %r"

#. Used by: ExtractionError
#: musicbot/entry.py:757
msgid "Failed to extract data for the requested media."
msgstr "为请求的媒体提取数据失败。"

#. Used by: info
#: musicbot/entry.py:759
#, python-format
msgid "Download complete:  %r"
msgstr "下载完成：  %r"

#. Used by: warning
#: musicbot/entry.py:890
#, python-format
msgid "Deserialized StreamPlaylistEntry cannot find channel with ID:  %s"
msgstr "反序列化的 StreamPlaylistEnter无法找到与 ID:  %s 的频道"

#. Used by: warning
#: musicbot/entry.py:906
#, python-format
msgid "Deserialized StreamPlaylistEntry has the wrong channel type:  %s"
msgstr "反序列化的 StreamPlaylistentre 有错误的频道类型:  %s"

#. Used by: warning
#: musicbot/entry.py:928
#, python-format
msgid "Deserialized StreamPlaylistEntry cannot find author with ID:  %s"
msgstr "反序列化的 StreamPlaylistEnter无法找到 ID 的作者：  %s"

#. Used by: warning
#: musicbot/entry.py:934
msgid ""
"Deserialized StreamPlaylistEntry has an author ID but no channel for lookup!"
msgstr "反序列化的 StreamPlaylistEnter有作者ID，但没有查找渠道！"

#. Used by: warning
#: musicbot/entry.py:1103
#, python-format
msgid "Deserialized LocalFilePlaylistEntry cannot find channel with ID:  %s"
msgstr "反序列化的 LocalFilePlaylistEnter无法找到与 ID:  %s 的频道"

#. Used by: warning
#: musicbot/entry.py:1119
#, python-format
msgid "Deserialized LocalFilePlaylistEntry has the wrong channel type:  %s"
msgstr "反序列化的本地文件播放列表条目有错误的通道类型：  %s"

#. Used by: warning
#: musicbot/entry.py:1141
#, python-format
msgid "Deserialized LocalFilePlaylistEntry cannot find author with ID:  %s"
msgstr "反序列化的 LocalFilePlaylistEnter无法找到ID:  %s 的作者"

#. Used by: warning
#: musicbot/entry.py:1147
msgid ""
"Deserialized LocalFilePlaylistEntry has an author ID but no channel for "
"lookup!"
msgstr "Desertialized LocalFilePlaylistEnt有作者ID，但没有查找渠道！"

#. Used by: debug
#: musicbot/entry.py:1213
#, python-format
msgid "Got duration of %(seconds)s seconds for file:  %(file)s"
msgstr ""

#. Used by: warning
#: musicbot/filecache.py:120
#, python-format
msgid "Failed to delete cache file:  %s"
msgstr "删除缓存文件失败：  %s"

#. Used by: debug
#: musicbot/filecache.py:131
msgid "Audio cache directory has been removed."
msgstr "音频缓存目录已删除。"

#. Used by: debug
#: musicbot/filecache.py:138
msgid "Audio cache directory could not be removed or renamed."
msgstr "无法删除或重命名音频缓存目录。"

#. Used by: debug
#: musicbot/filecache.py:145
msgid "Audio cache directory could not be removed."
msgstr "无法删除音频缓存目录。"

#. Used by: debug
#: musicbot/filecache.py:154
msgid "Audio cache has no limits set, nothing to delete."
msgstr "音频缓存没有设置限制，无需删除。"

#. Used by: debug
#: musicbot/filecache.py:217
#, python-format
msgid "Audio cache deleted %(number)s file(s), total of %(size)s removed."
msgstr ""

#. Used by: debug
#: musicbot/filecache.py:225
#, python-format
msgid ""
"Audio cached retained %(number)s file(s) from autoplaylist, total of "
"%(size)s retained."
msgstr ""

#. Used by: debug
#: musicbot/filecache.py:234
#, python-format
msgid "Audio cache is now %(size)s over %(number)s file(s)."
msgstr ""

#. Used by: debug
#: musicbot/filecache.py:250
msgid "Audio cache directory is missing, nothing to delete."
msgstr "缺少音频缓存目录，无需删除。"

#. Used by: noise
#: musicbot/filecache.py:269
msgid ""
"Audio cache file is from autoplaylist but marked as busted, ignoring it."
msgstr "音频缓存文件来自自动布局列表，但标记为忙，忽略它。"

#. Used by: debug
#: musicbot/filecache.py:280
#, python-format
msgid "Cache level requires cleanup. %s"
msgstr "缓存级别需要清理。 %s"

#. Used by: debug
#: musicbot/filecache.py:304
msgid "Auto playlist has no cache map, moving on."
msgstr "自动播放列表没有缓存地图，正在继续。"

#. Used by: info
#: musicbot/filecache.py:312
#, python-format
msgid "Loaded auto playlist cache map with %s entries."
msgstr "加载了带有 %s 条目的自动播放列表缓存图。"

#. Used by: exception
#: musicbot/filecache.py:316
msgid "Failed to load auto playlist cache map."
msgstr "自动载入播放列表缓存映射失败。"

#. Used by: debug
#: musicbot/filecache.py:341
#, python-format
msgid "Saved auto playlist cache map with %s entries."
msgstr "保存了带有 %s 条条目的自动播放列表缓存图。"

#. Used by: exception
#: musicbot/filecache.py:345
msgid "Failed to save auto playlist cache map."
msgstr "保存自动播放列表缓存映射失败。"

#. Used by: warning
#: musicbot/filecache.py:363
#, python-format
msgid ""
"Auto playlist cache map conflict on Key: %(file)s  Old: %(old)s  New: "
"%(new)s"
msgstr ""

#. Used by: debug
#: musicbot/i18n.py:229
#, python-format
msgid "Lang Argument Error:  %s"
msgstr "Lang 参数错误:  %s"

#. Used by: warning
#: musicbot/i18n.py:290
#, python-format
msgid "Failed to load log translations for any of:  [%s]  in:  %s"
msgstr ""

#. Used by: warning
#: musicbot/i18n.py:338
#, python-format
msgid ""
"Failed to load discord translations for any of:  [%s]  guild:  %s  in:  %s"
msgstr ""

#. Used by: debug
#: musicbot/json.py:14
#, python-format
msgid "Loading JSON file: %s"
msgstr "正在加载 JSON 文件： %s"

#. Used by: error
#: musicbot/json.py:27
#, python-format
msgid "Error parsing %s as JSON"
msgstr ""

#. Used by: warning
#: musicbot/json.py:36
#, python-format
msgid "Could not grab data from JSON key: %s"
msgstr "无法从 JSON 键抓取数据: %s"

#. Used by: debug
#: musicbot/logs.py:131
msgid "Skipping logger setup, already set up"
msgstr "跳过记录器设置，已经设置"

#. Used by: debug
#: musicbot/logs.py:283
#, python-format
msgid "Log level was previously set via override to: %s"
msgstr "日志级别先前通过覆盖设置到: %s"

#. Used by: info
#: musicbot/logs.py:292
#, python-format
msgid "Changing log level to:  %s"
msgstr ""

#. Used by: info
#: musicbot/logs.py:321
msgid "MusicBot loggers have been called to shut down."
msgstr "MusicBot 伐木者已被召唤关闭。"

#. Used by: warning
#: musicbot/permissions.py:120
#, python-format
msgid "Permissions file not found, copying from:  %s"
msgstr "找不到权限文件，复制自:  %s"

#. Used by: exception
#: musicbot/permissions.py:129
#, python-format
msgid "Error copying example permissions file:  %s"
msgstr "复制示例权限文件时出错：  %s"

#. Used by: debug
#: musicbot/permissions.py:195
msgid "Config 'OwnerID' is set auto, will set correctly later."
msgstr "配置“所有者ID”设置为自动设置，稍后会正确设置。"

#. Used by: debug
#: musicbot/permissions.py:212
msgid "Validating permissions..."
msgstr "正在验证权限..."

#. Used by: debug
#: musicbot/permissions.py:214
msgid "Setting auto 'OwnerID' for owner permissions group."
msgstr "为所有者权限组设置自动“所有者ID”。"

#. Used by: debug
#: musicbot/permissions.py:274
#, python-format
msgid "Updating group in permissions file:  %s"
msgstr "正在更新权限文件中的组:  %s"

#. Used by: debug
#: musicbot/permissions.py:280
#, python-format
msgid "Deleting group from permissions file:  %s"
msgstr "正在从权限文件中删除组：  %s"

#. Used by: debug
#: musicbot/permissions.py:285
#, python-format
msgid "Adding new group to permissions file:  %s"
msgstr "添加新组到权限文件：  %s"

#. Used by: debug
#: musicbot/permissions.py:300
msgid "Saving permissions file now."
msgstr "正在保存权限文件。"

#. Used by: exception
#: musicbot/permissions.py:306
msgid "ConfigUpdater could not parse the permissions file!"
msgstr "配置更新器无法解析权限文件！"

#. Used by: exception
#: musicbot/permissions.py:308
msgid "You have a duplicate section, fix your Permissions file!"
msgstr "您有一个重复的部分，修复您的权限文件！"

#. Used by: exception
#: musicbot/permissions.py:310
#, python-format
msgid "Failed to save permissions group:  %s"
msgstr "保存权限组失败：  %s"

#. Used by: critical
#: musicbot/permissions.py:325
msgid "Dev Bug! Permission has getter that is not available."
msgstr "开发错误！权限不可用。"

#. Used by: error
#: musicbot/permissions.py:330
msgid ""
"Dev Bug! Permission has invalid type, getter and default must be the same "
"type."
msgstr "开发错误！权限类型无效，获取类型和默认类型必须相同。"

#. Used by: warning
#: musicbot/permissions.py:574
msgid "Max search items can't be larger than 100. Setting to 100."
msgstr "最多搜索项不能大于 100。设置为 100。"

#. Used by: PermissionsError
#: musicbot/permissions.py:657
#, python-format
msgid ""
"You do not have permission to play the requested media.\n"
"The yt-dlp extractor `%(extractor)s` is not permitted in your group."
msgstr ""

#. Used by: noise
#: musicbot/player.py:86
#, python-format
msgid "Cleanup got called on the audio source:  %r"
msgstr "清理被调用到音频源：  %r"

#. Used by: noise
#: musicbot/player.py:191
#, python-format
msgid "MusicPlayer.skip() is called:  %s"
msgstr "MusicPlayer.skip() 被调用:  %s"

#. Used by: noise
#: musicbot/player.py:201
#, python-format
msgid "MusicPlayer.stop() is called:  %s"
msgstr "MusicPlayer.stop() 被调用:  %s"

#. Used by: warning
#: musicbot/player.py:216
msgid "Guild or network unavailable, cannot resume playback."
msgstr "公会或网络不可用，无法恢复播放。"

#. Used by: noise
#: musicbot/player.py:220
#, python-format
msgid "MusicPlayer.resume() is called:  %s"
msgstr "MusicPlayer.resume() 被调用:  %s"

#. Used by: noise
#: musicbot/player.py:240
#, python-format
msgid "MusicPlayer.pause() is called:  %s"
msgstr "MusicPlayer.pause() 被调用:  %s"

#. Used by: noise
#: musicbot/player.py:262
#, python-format
msgid "MusicPlayer.kill() is called:  %s"
msgstr "MusicPlayer.kill() 被调用:  %s"

#. Used by: debug
#: musicbot/player.py:288
msgid "Playback finished, but _current_entry is None."
msgstr "播放结束，但_current_entre 没有"

#. Used by: noise
#: musicbot/player.py:343
msgid "Possible Warning from kill_current_player()"
msgstr "可能来自击杀_current_player() 的警告"

#. Used by: noise
#: musicbot/player.py:362
#, python-format
msgid "MusicPlayer.play() is called:  %s"
msgstr "MusicPlayer.play() 被调用:  %s"

#. Used by: voicedebug
#: musicbot/player.py:372
msgid "MusicPlayer is dead, cannot play."
msgstr "MusicPlayer 已死亡，无法播放。"

#. Used by: warning
#: musicbot/player.py:377
msgid "Guild or network unavailable, cannot start playback."
msgstr "公会或网络不可用，无法启动回放。"

#. Used by: voicedebug
#: musicbot/player.py:382
msgid "MusicPlayer was previously paused, resuming current player."
msgstr "MusicPlayer 先前已暂停，恢复当前播放器。"

#. Used by: voicedebug
#: musicbot/player.py:388
msgid "MusicPlayer already locked for playback, this call is ignored."
msgstr "MusicPlayer 已经锁定播放，此通话将被忽略。"

#. Used by: warning
#: musicbot/player.py:399
msgid "Failed to get next entry."
msgstr "无法获取下一个条目。"

#. Used by: warning
#: musicbot/player.py:403
msgid "Failed to process entry for playback."
msgstr "处理播放条目失败。"

#. Used by: ffmpeg
#: musicbot/player.py:485
#, python-format
msgid "Creating player with options: ffmpeg %(before)s -i %(input)s %(after)s"
msgstr ""

#. Used by: voicedebug
#: musicbot/player.py:489
#, python-format
msgid "Playing %(source)r using %(client)r"
msgstr ""

#. Used by: debug
#: musicbot/player.py:520
#, python-format
msgid "Skipping deletion of '%s', found song in queue"
msgstr "正在跳过删除'%s'，在队列中找到歌曲"

#. Used by: debug
#: musicbot/player.py:524
#, python-format
msgid "Deleting file:  %s"
msgstr "正在删除文件：  %s"

#. Used by: debug
#: musicbot/player.py:529
#, python-format
msgid "File deleted:  %s"
msgstr "文件已删除：  %s"

#. Used by: warning
#: musicbot/player.py:533
msgid "Cannot delete file, it is currently in use."
msgstr "无法删除文件，它目前正在使用。"

#. Used by: warning
#: musicbot/player.py:536
msgid "Cannot delete file due to a permission error."
msgstr "由于权限错误，无法删除文件。"

#. Used by: warning
#: musicbot/player.py:541
msgid "Cannot delete file, it was not found."
msgstr "无法删除文件，找不到。"

#. Used by: warning
#: musicbot/player.py:547
msgid "Error while trying to delete file."
msgstr "删除文件时出错。"

#. Used by: debug
#: musicbot/player.py:552
msgid "Could not delete file, giving up and moving on"
msgstr "无法删除文件，放弃并移动"

#. Used by: error
#: musicbot/player.py:618
#, python-format
msgid "Deserialize returned an object that is not a MusicPlayer:  %s"
msgstr "反序列化返回的对象不是 MusicPlayer:  %s"

#. Used by: exception
#: musicbot/player.py:623
msgid "Failed to deserialize player"
msgstr "无法反序列化播放器"

#. Used by: ffmpeg
#: musicbot/player.py:685
#, python-format
msgid "Data from ffmpeg: %s"
msgstr "来自 ffmpeg的数据: %s"

#. Used by: ffmpeg
#: musicbot/player.py:695
#, python-format
msgid "Error from ffmpeg: %s"
msgstr "来自 ffmpeg的错误: %s"

#. Used by: ffmpeg
#: musicbot/player.py:703
#, python-format
msgid "Warning from ffmpeg:  %s"
msgstr "来自 ffmpeg的警告:  %s"

#. Used by: ffmpeg
#: musicbot/player.py:732
msgid "Unknown error decoding message from ffmpeg"
msgstr "未知错误解码来自 ffmpeg 的消息"

#. Used by: ffmpeg
#: musicbot/player.py:736
#, python-format
msgid "Decoded data from ffmpeg: %s"
msgstr "解码来自 ffmpeg的数据: %s"

#. Used by: noise
#: musicbot/playlist.py:121
#, python-format
msgid "Adding stream entry for URL:  %(url)s"
msgstr ""

#. Used by: ExtractionError
#: musicbot/playlist.py:159
msgid "Could not extract information"
msgstr "无法提取信息"

#. Used by: WrongEntryTypeError
#: musicbot/playlist.py:163
msgid "This is a playlist."
msgstr "这是一个播放列表。"

#. Used by: debug
#: musicbot/playlist.py:177
msgid "Entry info appears to be a stream, adding stream entry..."
msgstr "条目信息似乎是一个流，正在添加流条目..."

#. Used by: ExtractionError
#: musicbot/playlist.py:195
#, python-format
msgid "Invalid content type `%(type)s` for URL: %(url)s"
msgstr ""

#. Used by: warning
#: musicbot/playlist.py:203
msgid "Got text/html for content-type, this might be a stream."
msgstr "获取内容类型的文本/html ，这可能是一个串流。"

#. Used by: warning
#: musicbot/playlist.py:210
#, python-format
msgid "Questionable content-type \"%(type)s\" for url:  %(url)s"
msgstr ""

#. Used by: noise
#: musicbot/playlist.py:215
#, python-format
msgid "Adding URLPlaylistEntry for: %(subject)s"
msgstr ""

#. Used by: noise
#: musicbot/playlist.py:235
#, python-format
msgid "Adding LocalFilePlaylistEntry for: %(subject)s"
msgstr ""

#. Used by: debug
#: musicbot/playlist.py:280
#, python-format
msgid "Ignored video from compound playlist link with ID:  %s"
msgstr "从与ID的复合播放列表链接忽略视频:  %s"

#. Used by: info
#: musicbot/playlist.py:292
#, python-format
msgid ""
"Not allowing entry that is in song block list:  %(title)s  URL: %(url)s"
msgstr ""

#. Used by: debug
#: musicbot/playlist.py:305
#, python-format
msgid ""
"Ignoring song in entries by '%s', duration longer than permitted maximum."
msgstr "以 '%s' 忽略条目中的歌曲，持续时间超过允许的最大值。"

#. Used by: warning
#: musicbot/playlist.py:317
#, python-format
msgid "Not adding YouTube video because it is marked private or deleted:  %s"
msgstr "不添加 YouTube 视频，因为它已标记为私有或已删除：  %s"

#. Used by: warning
#: musicbot/playlist.py:342
msgid "Could not add item"
msgstr "无法添加项目"

#. Used by: debug
#: musicbot/playlist.py:343
#, python-format
msgid "Item: %s"
msgstr "项目： %s"

#. Used by: info
#: musicbot/playlist.py:346
#, python-format
msgid "Skipped %s bad entries"
msgstr "跳过 %s 错误条目"

#. Used by: everything
#: musicbot/playlist.py:387
msgid "Reorder looping over entries."
msgstr "在条目上重新排序循环."

#. Used by: everything
#: musicbot/playlist.py:469
#, python-format
msgid "Pre-downloading next track:  %r"
msgstr "预下载下一首曲目：  %r"

#. Used by: InvalidDataError
#: musicbot/playlist.py:495
msgid "no duration data"
msgstr "无持续时间数据"

#. Used by: InvalidDataError
#: musicbot/playlist.py:504
msgid "no duration data in current entry"
msgstr "当前条目中没有持续数据"

#. Used by: SpotifyError
#: musicbot/spotify.py:119
#, python-format
msgid "Invalid track_data, must be of type `track` got `%(type)s`"
msgstr ""

#. Used by: everything
#: musicbot/spotify.py:301
#, python-format
msgid "Ignored non-track entry in playlist with type:  %s"
msgstr "忽略播放列表中的非轨迹条目类型：  %s"

#. Used by: debug
#: musicbot/spotify.py:487
#, python-format
msgid "Spotify Album total tacks:  %(total)s  Next URL: %(url)s"
msgstr ""

#. Used by: debug
#: musicbot/spotify.py:492
#, python-format
msgid "Getting Spotify Album Next URL:  %s"
msgstr "获取 Spotify 相册下一个URL:  %s"

#. Used by: warning
#: musicbot/spotify.py:503
#, python-format
msgid ""
"Spotify Album Object may not be complete, expected %(total)s tracks but got "
"%(number)s"
msgstr ""

#. Used by: warning
#: musicbot/spotify.py:507
msgid "Spotify Album has more tracks than initial total."
msgstr "Spotify 相册比初始总数更多。"

#. Used by: debug
#: musicbot/spotify.py:530
#, python-format
msgid "Spotify Playlist total tacks: %(total)s  Next URL: %(url)s"
msgstr ""

#. Used by: debug
#: musicbot/spotify.py:535
#, python-format
msgid "Getting Spotify Playlist Next URL:  %s"
msgstr "获取 Spotify 播放列表下一个URL:  %s"

#. Used by: warning
#: musicbot/spotify.py:546
#, python-format
msgid ""
"Spotify Playlist Object may not be complete, expected %(total)s tracks but "
"got %(number)s"
msgstr ""

#. Used by: warning
#: musicbot/spotify.py:550
msgid "Spotify Playlist has more tracks than initial total."
msgstr "Spotify播放列表比初始播放列表更多的曲目。"

#. Used by: debug
#: musicbot/spotify.py:555
#, python-format
msgid "Spotify Playlist contained %s usable tracks."
msgstr "Spotify播放列表包含 %s 可用曲目。"

#. Used by: SpotifyError
#: musicbot/spotify.py:581 musicbot/spotify.py:617
#, python-format
msgid "Response status is not OK: [%(status)s] %(reason)s"
msgstr ""

#. Used by: SpotifyError
#: musicbot/spotify.py:587 musicbot/spotify.py:623 musicbot/spotify.py:733
msgid "Response JSON did not decode to a dict!"
msgstr "响应 JSON 没有解码到一个口令！"

#. Used by: exception
#: musicbot/spotify.py:596
#, python-format
msgid "Failed making GET request to url:  %s"
msgstr "向 url 发出GET 请求失败:  %s"

#. Used by: SpotifyError
#: musicbot/spotify.py:602
#, python-format
msgid "Could not make GET to URL:  %(url)s  Reason:  %(raw_error)s"
msgstr ""

#. Used by: exception
#: musicbot/spotify.py:632
#, python-format
msgid "Failed making POST request to url:  %s"
msgstr "向 url 发出POST 请求失败:  %s"

#. Used by: SpotifyError
#: musicbot/spotify.py:638
#, python-format
msgid "Could not make POST to URL:  %(url)s  Reason:  %(raw_error)s"
msgstr ""

#. Used by: SpotifyError
#: musicbot/spotify.py:672
msgid ""
"Failed to get a guest token from Spotify, please try specifying client ID "
"and client secret"
msgstr "无法从 Spotify 获取访客令牌，请尝试指定客户端 ID 和客户端密钥"

#. Used by: debug
#: musicbot/spotify.py:679
msgid "Created a new Guest Mode access token."
msgstr "创建了新访客模式访问令牌。"

#. Used by: SpotifyError
#: musicbot/spotify.py:683
#, python-format
msgid ""
"API response did not contain the expected data. Missing key: %(raw_error)s"
msgstr ""

#. Used by: SpotifyError
#: musicbot/spotify.py:689
#, python-format
msgid ""
"API response contained unexpected data.\n"
"%(raw_error)s"
msgstr ""

#. Used by: SpotifyError
#: musicbot/spotify.py:696
msgid "Requested a token from Spotify, did not end up getting one"
msgstr "从 Spotify 请求一个令牌，最终没有得到一个"

#. Used by: debug
#: musicbot/spotify.py:700
msgid "Created a new Client Mode access token."
msgstr "创建了新客户端模式访问令牌。"

#. Used by: SpotifyError
#: musicbot/spotify.py:727
#, python-format
msgid "API response status is not OK: [%(status)s]  %(reason)s"
msgstr ""

#. Used by: exception
#: musicbot/spotify.py:743
msgid "Failed to get Spotify Guest Token."
msgstr "获取 Spotify 访客令牌失败。"

#. Used by: error
#: musicbot/spotify.py:750
#, python-format
msgid "Failed to get Guest Token due to: %(raw_error)s"
msgstr ""

#. Used by: PermissionsError
#: musicbot/utils.py:174
msgid "Only the owner can use this command."
msgstr "只有所有者可以使用此命令。"

#. Used by: PermissionsError
#: musicbot/utils.py:194
msgid "Only dev users can use this command."
msgstr "只有dev 用户可以使用此命令。"

#. Used by: debug
#: musicbot/utils.py:280 musicbot/utils.py:322
msgid "Cannot count members when voice_channel is None."
msgstr "语音频道无时无法计数成员。"

#. Used by: warning
#: run.py:107
msgid "Could not find git executable."
msgstr "找不到 git 可执行文件。"

#. Used by: info
#: run.py:156
msgid "Attempting to upgrade with `git pull` on current path."
msgstr "尝试使用当前路径上的 git 脉冲进行升级。"

#. Used by: info
#: run.py:163
#, python-format
msgid "Result of git pull:  %s"
msgstr "git 脉冲的结果:  %s"

#. Used by: exception
#: run.py:171
msgid "Upgrade failed, you need to run `git pull` manually."
msgstr "升级失败，您需要手动运行 `git pull` 。"

#. Used by: _L
#: run.py:181
msgid "Cannot execute pip."
msgstr "无法执行管道。"

#. Used by: exception
#: run.py:188
msgid "Error using -m method"
msgstr "使用 -m 方法出错"

#. Used by: exception
#: run.py:234
msgid "PIP failed while calling sub-process."
msgstr "调用子进程时PIP失败。"

#. Used by: exception
#: run.py:237
msgid "PIP failed due to Permission Error."
msgstr "由于权限错误，PIP失败。"

#. Used by: exception
#: run.py:241
#, python-format
msgid "PIP failed due to missing Python executable?  (%s)"
msgstr "PIP因缺少Python 可执行文件而失败？(%s)"

#. Used by: exception
#: run.py:246
msgid "PIP failed due to OSError."
msgstr "由于OS错误，PIP失败。"

#. Used by: warning
#: run.py:267
msgid "Could not decode pip update report JSON."
msgstr "无法解码 pipp 更新报告 JSON"

#. Used by: _L
#: run.py:289
msgid "Cannot locate or execute python -m pip"
msgstr "无法定位或执行 python -m pip"

#. Used by: info
#: run.py:292
#, python-format
msgid "Attempting to upgrade with `%s` on current path..."
msgstr "尝试在当前路径上使用%s升级..."

#. Used by: info
#: run.py:310
#, python-format
msgid ""
"Result of pip upgrade:\n"
"%s"
msgstr ""
"螺丝刀升级结果:\n"
"%s"

#. Used by: info
#: run.py:315
#, python-format
msgid "Result exit code from pip upgrade: %s"
msgstr "从 pip 升级中退出代码: %s"

#. Used by: exception
#: run.py:330
msgid "Upgrade failed to execute or we could not understand the output"
msgstr "升级失败，或者我们无法理解输出"

#. Used by: warning
#: run.py:333
#, python-format
msgid "You may need to run `%s` manually."
msgstr "您可能需要手动运行 `%s'。"

#. Used by: _L
#: run.py:342
msgid "Press enter to continue . . ."
msgstr "按回车键继续"

#. Used by: info
#: run.py:355
msgid "Starting sanity checks"
msgstr "开始智能检查"

#. Used by: info
#: run.py:366
msgid "Required checks passed."
msgstr "所需检查通过。"

#. Used by: info
#: run.py:379
msgid "Skipped checking for updates."
msgstr "跳过检查更新。"

#. Used by: info
#: run.py:381
msgid "Optional checks passed."
msgstr "可选检查通过。"

#. Used by: warning
#: run.py:403
msgid "Could not locate py.exe"
msgstr "无法定位py.exe"

#. Used by: info
#: run.py:418
msgid "Python 3 found.  Launching bot..."
msgstr "Python 3找到。正在启动机器人..."

#. Used by: info
#: run.py:478
msgid "Ensuring we're in the right environment"
msgstr "确保我们处于正确的环境"

#. Used by: critical
#: run.py:501
#, python-format
msgid "Failed environment check, %s"
msgstr "环境检查失败， %s"

#. Used by: info
#: run.py:542
#, python-format
msgid "Detected FFmpeg is installed at:  %s"
msgstr "检测到的 FFmpeg 安装于:  %s"

#. Used by: info
#: run.py:544
msgid "Adding local bins/ folder environment PATH for bundled ffmpeg..."
msgstr "正在为捆绑的 ffpeg添加本地bins/文件夹环境PATH ..."

#. Used by: critical
#: run.py:553
msgid ""
"MusicBot could not locate FFmpeg binary in your environment.\n"
"Please install FFmpeg so it is available in your environment PATH variable."
msgstr ""

#. Used by: info
#: run.py:558
msgid ""
"On Windows, you can add a pre-compiled EXE to the MusicBot `bin` folder,\n"
"or you can install FFmpeg system-wide using WinGet or by running the install.bat file."
msgstr ""
"在 Windows上，您可以将事先编译的 EXE 添加到 MusicBot `bin` 文件夹。\n"
"或者您可以通过 WinGet 或通过运行安装来安装 FFmpeg 。 在文件中。"

#. Used by: info
#: run.py:563
msgid ""
"On MacOS, you may be able to install FFmpeg via homebrew.\n"
"Otherwise, check the official FFmpeg site for build or install steps."
msgstr ""

#. Used by: info
#: run.py:568
msgid ""
"On Linux, many distros make FFmpeg available via system package managers.\n"
"Check for ffmpeg with your system package manager or build from sources."
msgstr ""

#. Used by: warning
#: run.py:581
#, python-format
msgid "Less than %sMB of free space remains on this device"
msgstr "此设备上剩余的剩余空间小于 %sMB"

#. Used by: info
#: run.py:590
msgid ""
"\n"
"Checking for updates to MusicBot or dependencies..."
msgstr ""
"\n"
"正在检查对 MusicBot 或依赖关系的更新..."

#. Used by: info
#: run.py:607
msgid "No MusicBot updates available via `git` command."
msgstr "没有通过 `git` 命令提供的 MusicBot 更新。"

#. Used by: warning
#: run.py:610
msgid ""
"Could not check for updates using `git` commands.  You should check "
"manually."
msgstr "无法使用 'git' 命令检查更新。您应该手动检查。"

#. Used by: _L
#: run.py:617
msgid "The following packages can be updated:\n"
msgstr "以下软件包可以更新：\n"

#. Used by: _L
#: run.py:623
#, python-format
msgid "  %s  to version:  %s\n"
msgstr "  %s  到版本:  %s\n"

#. Used by: info
#: run.py:634
msgid "No dependency updates available via `pip` command."
msgstr "无法通过 `pip` 命令更新依赖信息。"

#. Used by: warning
#: run.py:637
msgid ""
"Could not check for updates using `pip` commands.  You should check "
"manually."
msgstr "无法使用 \"pip\" 命令检查更新。您应该手动检查。"

#. Used by: info
#: run.py:641
#, python-format
msgid ""
"You can run a guided update by using the command:\n"
"    %s ./update.py"
msgstr ""
"您可以使用命令运行一个指导更新：\n"
"    %s ./update.py"

#. Used by: _L
#: run.py:659
msgid "Value is above the maximum limit."
msgstr "值高于最大限制。"

#. Used by: _L
#: run.py:661
msgid "Value must not be negative."
msgstr "值不能为负值。"

#. Used by: _L
#: run.py:665
#, python-format
msgid "Value for Max Logs Kept must be a number from 0 to %s"
msgstr "最大日志的值必须是 0 到 %s 的数字"

#. Used by: _L
#: run.py:675
#, python-format
msgid "Log level '%s' is not available."
msgstr "日志关卡 '%s不可用。"

#. Used by: _L
#: run.py:679
#, python-format
msgid "Log Level must be one of:  %s"
msgstr "日志级别必须是:  %s"

#. Used by: _L
#: run.py:689
msgid ""
"Launch a music playing discord bot built using discord.py, youtubeDL, and "
"ffmpeg."
msgstr "启动使用 discord.py, youtubeDL 和 ffmpeg 构建的音乐播放机器人。"

#. Used by: _L
#: run.py:692
msgid "Available via Github:"
msgstr "通过 Github："

#. Used by: _L
#: run.py:696
msgid "For more help and support with this bot, join our discord:"
msgstr "为了获得更多的帮助和支持，加入我们的不和："

#. Used by: _L
#: run.py:698
msgid "This software is provided under the MIT License."
msgstr "这种软件是根据MIT许可证提供的。"

#. Used by: _L
#: run.py:700
msgid "See the `LICENSE` text file for complete details."
msgstr "详情请参阅`LICENSE`文本文件。"

#. Used by: _L
#: run.py:713
msgid ""
"Override the default / system detected language for all text in MusicBot."
msgstr "覆盖 MusicBot 中所有文本的默认值/系统。"

#. Used by: _L
#: run.py:723
msgid "Use this language for all server-side log messages from MusicBot."
msgstr "对于来自 MusicBot 的所有服务器端日志消息使用此语言。"

#. Used by: _L
#: run.py:733
msgid ""
"Use this language for all messages sent to discord from MusicBot.\n"
"This does not prevent per-guild language selection."
msgstr ""
"对于来自 MusicBot 发送到不和的所有消息使用此语言。\n"
"这并不阻止每个公会语言的选择。"

#. Used by: _L
#: run.py:744
msgid "Print the MusicBot version information and exit."
msgstr "打印MusicBot 版本信息并退出。"

#. Used by: _L
#: run.py:752
msgid "Skip all optional startup checks, including the update check."
msgstr "跳过所有可选的启动检查，包括更新检查。"

#. Used by: _L
#: run.py:760
msgid "Skip only the disk space check at startup."
msgstr "启动时仅跳过磁盘空间检查。"

#. Used by: _L
#: run.py:768
msgid "Skip only the update check at startup."
msgstr "在启动时仅跳过更新检查。"

#. Used by: _L
#: run.py:777
msgid ""
"Disable MusicBot from trying to install dependencies when it cannot import "
"them."
msgstr "禁用 MusicBot 在无法导入时无法安装依赖项。"

#. Used by: _L
#: run.py:789
#, python-format
msgid ""
"Specify how many log files to keep, between 0 and %s inclusive. (Default: "
"%s)"
msgstr "指定要保存多少日志文件，介于 0 到 %s 之间。(默认： %s)"

#. Used by: _L
#: run.py:800
#, python-format
msgid "Override the log level settings set in config. Must be one of: %s"
msgstr "覆盖配置中设置的日志级别设置。必须是: %s"

#. Used by: _L
#: run.py:812
#, python-format
msgid ""
"Override the default date format used when rotating log files. This should "
"contain values compatible with strftime().  (Default:  '%s')"
msgstr "重写旋转日志文件时使用的默认日期格式。这应该包含与 strftime()兼容的值。(默认：'%s')"

#. Used by: _L
#: run.py:843
#, python-format
msgid "Version:  %s"
msgstr "版本:  %s"

#. Used by: _L
#: run.py:918
msgid "Opened a new MusicBot instance. This terminal can be safely closed!"
msgstr "打开了一个新的 MusicBot 实例。此终端可以安全地关闭！"

#. Used by: info
#: run.py:989
#, python-format
msgid "Loading MusicBot version:  %s"
msgstr "正在加载 MusicBot 版本：  %s"

#. Used by: info
#: run.py:990
#, python-format
msgid "Log opened:  %s"
msgstr "日志已打开:  %s"

#. Used by: info
#: run.py:991
#, python-format
msgid "Python version:  %s"
msgstr "Python version:  %s"

#. Used by: warning
#: run.py:1000
#, python-format
msgid "Changing working directory to:  %s"
msgstr "更改工作目录到:  %s"

#. Used by: critical
#: run.py:1004
msgid ""
"Cannot start the bot!  You started `run.py` in the wrong directory and we "
"could not locate `musicbot` and `.git` folders to verify a new directory "
"location."
msgstr "无法启动机器人！您在错误的目录中启动了`run.py`，我们无法定位`musicbot`和`。 它的文件夹以验证新的目录位置。"

#. Used by: error
#: run.py:1009
msgid ""
"For best results, start `run.py` from the same folder you cloned MusicBot into.\n"
"If you did not use git to clone the repository, you are strongly urged to."
msgstr ""
"为了取得最好的结果，从同一个文件夹中开始`run.py`，你克隆了MusicBot。\n"
"如果你没有使用 git 来克隆仓库，你会被强烈敦促."

#. Used by: critical
#: run.py:1074
msgid ""
"Certificate error is not a verification error, not trying certifi and "
"exiting."
msgstr "证书错误不是验证错误，而不是尝试验证和退出。"

#. Used by: exception
#: run.py:1076
msgid "Here is the exact error, it could be a bug."
msgstr "这是一个确切的错误，它可能是一个错误。"

#. Used by: warning
#: run.py:1092
msgid ""
"To easily add a certificate to Windows trust store, \n"
"you can open the failing site in Microsoft Edge or IE...\n"
msgstr ""
"若要轻松将证书添加到Windows信任商店， \n"
"您可以在 Microsoft Edge 或 IE中打开失败站点...\n"

#. Used by: warning
#: run.py:1098
msgid ""
"Could not get Issuer Certificate from default trust store, trying certifi "
"instead."
msgstr "无法从默认的信任商店获取发行者证书，请改用 certifi。"

#. Used by: exception
#: run.py:1107
msgid "Syntax error (modification detected, did you edit the code?)"
msgstr "语法错误(检测到更改，您是否编辑代码？)"

#. Used by: exception
#: run.py:1110
msgid "Syntax error (this is a bug, not your fault)"
msgstr "语法错误 (这是一个bug, 而不是你的错误)"

#. Used by: error
#: run.py:1122
msgid ""
"Cannot start MusicBot due to an error!\n"
"\n"
"Problem:\n"
"  There was an error importing MusicBot or a dependency package.\n"
"\n"
"Solution:\n"
"  You need to manually install pip packages for MusicBot\n"
"  or launch without `--no-install-deps` and MusicBot will try to install them for you."
msgstr ""

#. Used by: info
#: run.py:1155
msgid "Attempting to install MusicBot dependency packages automatically...\n"
msgstr "尝试自动安装 MusicBot 依赖软件包...\n"

#. Used by: critical
#: run.py:1164
#, python-format
msgid ""
"MusicBot dependencies may not be installed!\n"
"\n"
"Problem:\n"
"  The pip install process ended with a possible error.\n"
"  Some or all of the the dependencies may be missing.\n"
"\n"
"Solution:\n"
"  You must manually install dependency packages.\n"
"  Open a CMD prompt / terminal to the MusicBot directory.\n"
"  You can try using the update scripts install packages.\n"
"  Or try this manual command:\n"
"    %(py_bin)s -m pip install -U -r ./requirements.txt\n"
"\n"
"You can also ask for help in MusicBot's support discord:\n"
"  https://discord.gg/bots"
msgstr ""

#. Used by: info
#: run.py:1185
msgid "OK, lets hope installing dependencies worked!"
msgstr "好的，让我们希望安装依赖关系成功！"

#. Used by: error
#: run.py:1197
msgid ""
"MusicBot got an ImportError after trying to install packages. MusicBot must "
"exit..."
msgstr "MusicBot 在尝试安装软件包后发生导入错误。MusicBot必须退出..."

#. Used by: exception
#: run.py:1199
msgid "The exception which caused the above error: "
msgstr "造成上述错误的异常： "

#. Used by: info
#: run.py:1218
msgid "MusicBot is doing a soft restart..."
msgstr "MusicBot 正在进行软重启..."

#. Used by: info
#: run.py:1222
msgid "MusicBot is doing a full process restart..."
msgstr "MusicBot 正在重启整个进程..."

#. Used by: exception
#: run.py:1228
msgid "Error starting bot"
msgstr "启动机器人出错"

#. Used by: debug
#: run.py:1233
msgid "Closing event loop."
msgstr "关闭活动循环。"

#. Used by: info
#: run.py:1238
#, python-format
msgid "Restarting in %s seconds..."
msgstr "在 %s 秒后重启..."

#. Used by: info
#: run.py:1242
msgid "All done."
msgstr "全部完成。"

#. Used by: _L
#: run.py:1271
msgid "OK, we're closing!"
msgstr "好的，我们正在关闭！"

#. Used by: info
#: musicbot/bot.py:2159
msgid "MusicBot is now doing start up steps..."
msgstr ""

#. Used by: warning
#: musicbot/bot.py:2166
msgid "Start up failed at login."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:3481
#, python-format
msgid "No playlist file exists with the name: `%(playlist)s`"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5165
msgid ""
"There is nothing currently playing. Play something with a play command."
msgstr ""

#. Used by: error
#: musicbot/bot.py:5179
#, python-format
msgid ""
"Missing permissions to delete queue file for %(guild)s(%(id)s) at: %(path)s"
msgstr ""

#. Used by: exception
#: musicbot/bot.py:5184
#, python-format
msgid "OS level error while trying to delete queue file: %(path)s"
msgstr ""

#. Used by: info
#: musicbot/config.py:1084
msgid "Generating new config options files..."
msgstr ""

#. Used by: HelpfulError
#: musicbot/config.py:1094
#, python-format
msgid ""
"Error creating default config options file.\n"
"\n"
"Problem:\n"
"  MusicBot attempted to generate the config files but failed due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Make sure MusicBot can read and write to your config files.\n"
msgstr ""

#. Used by: error
#: musicbot/config.py:1348
#, python-format
msgid ""
"Could not locate config options or example options files.\n"
"MusicBot will generate the config files at the location:\n"
"  %(cfg_file)s"
msgstr ""

#. Used by: everything
#: musicbot/filecache.py:332
msgid "Cachemap defer flag is set, not yet saving to disk..."
msgstr ""

#. Used by: error
#: musicbot/permissions.py:136
#, python-format
msgid ""
"Could not locate config permissions or example permissions files.\n"
"MusicBot will generate the config files at the location:\n"
"  %(perms_file)s"
msgstr ""

#. Used by: info
#: musicbot/permissions.py:163
msgid "Generating new config permissions files..."
msgstr ""

#. Used by: HelpfulError
#: musicbot/permissions.py:172
#, python-format
msgid ""
"Error creating default config permissions file.\n"
"\n"
"Problem:\n"
"  MusicBot attempted to generate the config files but failed due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Make sure MusicBot can read and write to your config files.\n"
msgstr ""

#. Used by: critical
#: run.py:525
#, python-format
msgid ""
"MusicBot could not write files in the following directory:\n"
"%(dir)s"
msgstr ""

#. Used by: critical
#: run.py:529
msgid "Please make sure MusicBot can read and write in the above directory."
msgstr ""

#. Used by: exception
#: run.py:536
msgid "Failed to clean up write-test path."
msgstr ""

#. Used by: _L
#: run.py:826
msgid ""
"Supply a directory where MusicBot can store all mutable files.\n"
"Essentially treats the install directory as read-only.\n"
"MusicBot must have permission to create this directory.\n"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2414
msgid "Private Channel"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2416
msgid "Unknown User DM"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2418
#, python-format
msgid "User DM: %(name)s"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2422
msgid "Unknown Channel (Partial)"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2424
#, python-format
msgid "Unnamed Channel: %(id)s"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2803
msgid "Unknown Channel"
msgstr ""

#. TRANSLATORS: Placeholder for empty track title.
#. Used by: _X
#: musicbot/entry.py:299 musicbot/entry.py:821 musicbot/entry.py:1020
msgid "Unknown"
msgstr ""

#. Used by: info
#: musicbot/bot.py:709
#, python-format
msgid "MusicBot may use up to %(rate).2f %(suffix)s of bandwidth."
msgstr ""

#. Used by: everything
#: musicbot/player.py:446
#, python-format
msgid "Probed codec and bitrate: %(name)s at %(rate)s kbps"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2599
#, python-format
msgid "  Command by @mention: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2601
#, python-format
msgid "  Command aliases: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2610
#, python-format
msgid "    Legacy skip: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2612
#, python-format
msgid "    Author insta-skip: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2620
#, python-format
msgid "  Auto-join Owner's voice channel: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2632
#, python-format
msgid "    Save per-server queue history: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2636
#, python-format
msgid "    Save global queue history: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2640
#, python-format
msgid "    Remove URLs on extraction error: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2643
#, python-format
msgid "    Skip playlist for user requests: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2661
#, python-format
msgid "  Songs blocklist: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2662
#, python-format
msgid "  Users blocklist: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2671
#, python-format
msgid "    Delete if cache exceeds %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2674
#, python-format
msgid "  Pre-download next track: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2681
#, python-format
msgid "  Write current song title to file: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2684
#, python-format
msgid "  Respond with Embeds: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2687
msgid "    Footer Text Disabled"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2689
#, python-format
msgid "    Footer Text:  %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2695
#, python-format
msgid "  Leave servers where Owner is not a member: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2699
#, python-format
msgid "  Disconnect from inactive channel: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2708
#, python-format
msgid "  Disconnect at end of queue: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2712
#, python-format
msgid "  Disconnect when player idles: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2722
#, python-format
msgid "  Search using reactions: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2723
#, python-format
msgid "    Results per search: %d"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2728
#, python-format
msgid "  Local media files: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2731
#, python-format
msgid "  Network checking ping tests: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2741
#, python-format
msgid "  Audio processed with: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2744
#, python-format
msgid "  Equalize audio level per-track: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2749
#, python-format
msgid "  HTTP Proxy set to:  %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2751
#, python-format
msgid "  User Agent set to:  %s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8149
msgid ""
"MusicBot has bound channel config and caller channel is not in bound "
"channels."
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8156
msgid "Caller server has a bound channel, caller channel ignored."
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8159
msgid "Caller server has no bound channel, caller allowed."
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8162
#, python-format
msgid "Unbound channel (%s) in server:  %s"
msgstr ""

#. Used by: info
#: musicbot/testrig.py:462
msgid "Starting Command Tests..."
msgstr ""

#. Used by: info
#: musicbot/testrig.py:510
#, python-format
msgid "Buffered command: %(cmd)s"
msgstr ""

#. Used by: info
#: musicbot/testrig.py:527
#, python-format
msgid "- Processing CMD %(n)s of %(t)s: %(cmd)s"
msgstr ""

#. Used by: info
#: run.py:389
msgid "Checking for Python 3.9+"
msgstr ""

#. Used by: warning
#: run.py:393
#, python-format
msgid "Python 3.9+ is required. This version is %s"
msgstr ""

#. Used by: warning
#: run.py:395
msgid "Attempting to locate Python 3.9..."
msgstr ""

#. Used by: warning
#: run.py:414
msgid "Could not execute `py.exe -3.9` "
msgstr ""

#. Used by: info
#: run.py:423
msgid "Trying \"python3.9\""
msgstr ""

#. Used by: warning
#: run.py:426
msgid "Could not locate python3.9 on path."
msgstr ""

#. Used by: info
#: run.py:440
#, python-format
msgid ""
"\n"
"Python 3.9 found.  Re-launching bot using: %s run.py\n"
msgstr ""

#. Used by: critical
#: run.py:445
msgid ""
"Could not find Python 3.9 or higher.  Please run the bot using Python "
"version 3.9 to 3.13"
msgstr ""

#. Used by: ExtractionError
#: musicbot/downloader.py:502
#, python-format
msgid "Error in yt-dlp while downloading media data: %(raw_error)s"
msgstr ""

#. Used by: ExtractionError
#: musicbot/downloader.py:523
#, python-format
msgid "Error in yt-dlp while downloading stream data: %(raw_error)s"
msgstr ""

#. Used by: noise
#: musicbot/downloader.py:557
#, python-format
msgid ""
"Extractor %(extractor)s returned single-entry result, replacing base info "
"with entry info."
msgstr ""

#. Used by: info
#: run.py:1053
msgid "Updating example config files..."
msgstr ""

#~ msgid ""
#~ "Experimental Yt-dlp OAuth2 plugin is enabled. This might break at any point!"
#~ msgstr "实验性的 Yt-dlp OAuth2 插件已启用。这可能会在任何时候中断！"

#~ msgid ""
#~ "Cookies TXT file detected. MusicBot will pass them to yt-dlp.\n"
#~ "Cookies are not recommended, may not be supported, and may totally break.\n"
#~ "Copying cookies from your web-browser risks exposing personal data and \n"
#~ "in the best case can result in your accounts being banned!\n"
#~ "\n"
#~ "You have been warned!  Good Luck!  \\U0001F596\n"
#~ msgstr ""
#~ "检测到 Cookies TXT 文件。MusicBot 会将它们传递到 yt-dlp.\n"
#~ "Cookies 不被推荐，可能不被支持，可能完全断开。\n"
#~ "从您的网页浏览器复制cookie有暴露个人数据的风险， \n"
#~ "在最好的情况下可能导致您的账户被禁止！\n"
#~ "\n"
#~ "您已被警告！祝您好运！  \\U0001F596\n"

#~ msgid ""
#~ "Original OAuth2 plugin is installed and will be used instead.\n"
#~ "This may cause MusicBot to not close completely, or hang pending authorization!\n"
#~ "To close MusicBot, you must manually Kill the MusicBot process!\n"
#~ "Yt-dlp is being set to show warnings and other log messages, to show the Auth code.\n"
#~ "Uninstall the yt-dlp-youtube-oauth2 package to use integrated OAuth2 features instead."
#~ msgstr ""

#, python-format
#~ msgid "Error in yt-dlp while downloading data: %(raw_error)s"
#~ msgstr ""

#~ msgid ""
#~ "Extractor youtube:search returned single-entry result, replacing base info "
#~ "with entry info."
#~ msgstr "Extractor youtube:search 返回了单条目结果，以条目信息取代基础信息。"

#, python-format
#~ msgid "Failed to save ytdlp oauth2 token data due to:  %s"
#~ msgstr "保存 ytdlp ooth2 令牌数据失败，原因是：  %s"

#~ msgid "Loading YouTube TV OAuth2 token data."
#~ msgstr "正在加载 YouTube TV OAuth2 令牌数据。"

#, python-format
#~ msgid "Failed to load ytdlp oauth2 token data due to:  %s"
#~ msgstr "无法加载 ytdlp ooth2 令牌数据，原因是：  %s"

#~ msgid "Storing YouTube TV OAuth2 token data"
#~ msgstr "存储 YouTube TV OAuth2 令牌数据"

#~ msgid "Invalid cached OAuth2 token data."
#~ msgstr "无效缓存 OAuth2 令牌数据。"

#~ msgid "Access token expired, refreshing"
#~ msgstr "访问令牌已过期，正在刷新"

#~ msgid ""
#~ "YouTube cookies have been provided, but OAuth2 is being used. If you "
#~ "encounter problems, stop providing YouTube cookies to yt-dlp."
#~ msgstr ""
#~ "YouTube cookie 已经提供，但是OAuth2 正在使用。如果您遇到问题，停止提供 YouTube cookie 到 yt-dlp。"

#~ msgid "Refreshing YouTube TV oauth2 token..."
#~ msgstr "正在刷新 YouTube TV oauth2 令牌..."

#, python-format
#~ msgid ""
#~ "Failed to refresh OAuth2 access token due to:  %s\n"
#~ "Restarting authorization flow..."
#~ msgstr ""
#~ "无法刷新 OAuth2 访问令牌，原因是：  %s\n"
#~ "重新启动授权流程..."

#~ msgid "Starting oauth2 flow..."
#~ msgstr "正在启动 oauth2 流程..."

#, python-format
#~ msgid ""
#~ "\n"
#~ "NOTICE:\n"
#~ "To give yt-dlp access to your account, visit:\n"
#~ "  %s\n"
#~ "Then enter this authorization code:  %s\n"
#~ "You have %s seconds to complete authorization.\n"
#~ msgstr ""

#~ msgid ""
#~ "The application may hang until authorization time out if closed at this "
#~ "point. This is normal."
#~ msgstr "如果此时关闭，应用程序可以挂断直到授权超时。这是正常的。"

#~ msgid "Timed out while waiting for OAuth2 token."
#~ msgstr "等待 OAuth2 令牌时超时。"

#~ msgid "The device code has expired, restarting authorization flow for yt-dlp."
#~ msgstr "设备代码已过期，正在为yt-dlp重启授权流程。"

#~ msgid "Yt-dlp OAuth2 authorization successful."
#~ msgstr "Yt-dlp OAuth2 授权成功。"

#, python-format
#~ msgid "Adding OAuth2 Plugin to Yt-dlp IE:  %s"
#~ msgstr "将 OAuth2 插件添加到 Yt-dlp IE:  %s"

#, python-format
#~ msgid "Default Yt-dlp Clients:  %s"
#~ msgstr "默认 Yt-dlp 客户端:  %s"

#, python-format
#~ msgid "  Auto-Summon: %s"
#~ msgstr ""

#, python-format
#~ msgid "    Delete if size exceeds %s"
#~ msgstr ""

#, python-format
#~ msgid "  Write current songs to file: %s"
#~ msgstr ""

#, python-format
#~ msgid "  Author insta-skip: %s"
#~ msgstr ""

#, python-format
#~ msgid "  Embeds: %s"
#~ msgstr ""

#, python-format
#~ msgid "  Legacy skip: %s"
#~ msgstr ""

#, python-format
#~ msgid "  Leave non owners: %s"
#~ msgstr ""

#, python-format
#~ msgid "  Leave inactive VC: %s"
#~ msgstr ""

#, python-format
#~ msgid "  Leave at song end/empty queue: %s"
#~ msgstr ""

#, python-format
#~ msgid "  Leave when player idles: %s"
#~ msgstr ""

#, python-format
#~ msgid "  Search List: %s"
#~ msgstr ""

#~ msgid "Checking for Python 3.8+"
#~ msgstr "正在检查 Python 3.8+"

#, python-format
#~ msgid "Python 3.8+ is required. This version is %s"
#~ msgstr "Python 3.8+ 是必需的。此版本是 %s"

#~ msgid "Attempting to locate Python 3.8..."
#~ msgstr "正在尝试找到 Python 3.8..."

#~ msgid "Could not execute `py.exe -3.8` "
#~ msgstr "无法执行 py.exe -3.8` "

#~ msgid "Trying \"python3.8\""
#~ msgstr "尝试\"python3.8\""

#~ msgid "Could not locate python3.8 on path."
#~ msgstr "无法在路径上找到 python3.8"

#, python-format
#~ msgid ""
#~ "\n"
#~ "Python 3.8 found.  Re-launching bot using: %s run.py\n"
#~ msgstr ""
#~ "\n"
#~ "Python 3.8已经找到。正在重启机器人使用： %s run.py\n"

#~ msgid ""
#~ "Could not find Python 3.8 or higher.  Please run the bot using Python 3.8"
#~ msgstr "找不到 Python 3.8 或更高版本。请使用 Python 3.8 运行机器人。"

#, python-format
#~ msgid "  Audio Codec: %s"
#~ msgstr ""

#, python-format
#~ msgid "Generated a new %(example_file)s and copied it to %(option_file)s"
#~ msgstr ""

#~ msgid "Current working directory does not seem to be writable"
#~ msgstr "当前工作目录似乎不可写"

#~ msgid "Please move the bot to a folder that is writable"
#~ msgstr "请移动机器人到可写入的文件夹"
