#
msgid ""
msgstr ""
"Project-Id-Version: notmusicbot\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-11-11 16:38-0800\n"
"PO-Revision-Date: 2024-11-12 00:39\n"
"Last-Translator: \n"
"Language-Team: Russian\n"
"Language: ru_RU\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=4; plural=((n%10==1 && n%100!=11) ? 0 : ((n%10 >= 2 && n%10 <=4 && (n%100 < 12 || n%100 > 14)) ? 1 : ((n%10 == 0 || (n%10 >= 5 && n%10 <=9)) || (n%100 >= 11 && n%100 <= 14)) ? 2 : 3));\n"
"X-Crowdin-File: /fae/i18n/musicbot_logs.pot\n"
"X-Crowdin-File-ID: 26\n"
"X-Crowdin-Language: ru\n"
"X-Crowdin-Project: notmusicbot\n"
"X-Crowdin-Project-ID: 734017\n"
"X-Generated-By: pygettext.py 1.5-mb01\n"

#. Used by: warning
#: musicbot/aliases.py:52
msgid "Aliases file not found, copying example_aliases.json"
msgstr "Файл псевдонимов не найден, копирование example_aliases.json"

#. Used by: HelpfulError
#: musicbot/aliases.py:56
msgid ""
"Error while loading aliases.\n"
"\n"
"Problem:\n"
"  Your aliases files (aliases.json & example_aliases.json) are missing.\n"
"\n"
"Solution:\n"
"  Replace the alias config file(s) or copy them from:\n"
"    https://github.com/Just-Some-Bots/MusicBot/"
msgstr ""

#. Used by: error
#: musicbot/aliases.py:80
#, python-format
msgid "Failed to load aliases file:  %s"
msgstr "Не удалось загрузить файл псевдонимов:  %s"

#. Used by: error
#: musicbot/aliases.py:88
#, python-format
msgid ""
"Failed to parse aliases file:  %s\n"
"Ensure the file contains valid JSON and restart the bot."
msgstr ""
"Не удалось разобрать файл псевдонимов:  %s\n"
"Убедитесь, что файл содержит корректный JSON и перезапустите бот."

#. Used by: error
#: musicbot/aliases.py:118
#, python-format
msgid ""
"Aliases skipped for non-existent command:  %(command)s  ->  %(aliases)s"
msgstr ""
"Псевдонимы пропущены для несуществующей команды:  %(command)s  ->  "
"%(aliases)s"

#. Used by: error
#: musicbot/aliases.py:126
#, python-format
msgid ""
"Alias(es) skipped for invalid alias data:  %(command)s  ->  %(aliases)s"
msgstr ""
"Алиас(ы) пропущены для недопустимых данных алиаса:  %(command)s  ->  "
"%(aliases)s"

#. Used by: error
#: musicbot/aliases.py:136
#, python-format
msgid "Alias `%(alias)s` skipped as already exists on command:  %(command)s"
msgstr ""
"Псевдоним `%(alias)s` пропущен как уже существует в команде:  %(command)s"

#. Used by: warning
#: musicbot/autoplaylist.py:77
#, python-format
msgid "Error loading auto playlist file:  %s"
msgstr "Ошибка загрузки файла автоплейлиста:  %s"

#. Used by: info
#: musicbot/autoplaylist.py:181
#, python-format
msgid "Removing unplayable song from playlist, %(playlist)s: %(track)s"
msgstr ""
"Удаление невоспроизводимой песни из плейлиста, %(playlist)s: %(track)s"

#. Used by: info
#: musicbot/autoplaylist.py:186
#, python-format
msgid "Removing song from playlist, %(playlist)s: %(track)s"
msgstr "Удаление песни из плейлиста, %(playlist)s: %(track)s"

#. Used by: exception
#: musicbot/autoplaylist.py:132 musicbot/autoplaylist.py:211
msgid "Could not log information about the playlist URL removal."
msgstr "Не удалось зарегистрировать информацию о удалении URL плейлиста."

#. Used by: info
#: musicbot/autoplaylist.py:135 musicbot/autoplaylist.py:215
msgid "Updating playlist file..."
msgstr "Обновление файла плейлиста..."

#. Used by: exception
#: musicbot/autoplaylist.py:158 musicbot/autoplaylist.py:231
#: musicbot/autoplaylist.py:268
#, python-format
msgid "Failed to save playlist file:  %s"
msgstr "Не удалось сохранить файл плейлиста:  %s"

#. Used by: debug
#: musicbot/autoplaylist.py:240
#, python-format
msgid "URL already in playlist %s, ignoring"
msgstr "URL-адрес уже в плейлисте %s, игнорируется"

#. Used by: info
#: musicbot/autoplaylist.py:247
#, python-format
msgid "Adding new URL to playlist, %(playlist)s: %(track)s"
msgstr "Добавление нового URL в плейлист, %(playlist)s: %(track)s"

#. Used by: info
#: musicbot/bot.py:169
#, python-format
msgid "Initializing MusicBot %s"
msgstr "Инициализация MusicBot %s"

#. Used by: error
#: musicbot/bot.py:252
#, python-format
msgid "Loop is closed, cannot create task for: %r"
msgstr "Цикл закрыт, невозможно создать задачу для: %r"

#. Used by: exception
#: musicbot/bot.py:268
#, python-format
msgid "Unhandled exception for task:  %r"
msgstr "Необработанное исключение для задачи:  %r"

#. Used by: error
#: musicbot/bot.py:272
#, python-format
msgid "Unhandled exception for task:  %(task)r  --  %(raw_error)s"
msgstr "Необработанное исключение для задачи:  %(task)r --  %(raw_error)s"

#. Used by: warning
#: musicbot/bot.py:317 musicbot/bot.py:339
msgid "Spotify did not provide us with a token. Disabling."
msgstr "Spotify не предоставил нам токен. Отключен."

#. Used by: info
#: musicbot/bot.py:321
msgid "Authenticated with Spotify successfully using client ID and secret."
msgstr ""
"Аутентификация в Spotify прошла успешно с использованием ID клиента и "
"секрета."

#. Used by: warning
#: musicbot/bot.py:325
#, python-format
msgid ""
"Could not start Spotify client. Is your client ID and secret correct? "
"Details: %s. Continuing anyway in 5 seconds..."
msgstr ""
"Не удалось запустить клиент Spotify. ID вашего клиента и секретные данные? "
"Подробности: %s. Продолжиться все равно через 5 секунд..."

#. Used by: warning
#: musicbot/bot.py:333
msgid ""
"The config did not have Spotify app credentials, attempting to use guest "
"mode."
msgstr ""
"В конфигурации нет учетных данных приложения Spotify, пытаясь использовать "
"гостевой режим."

#. Used by: info
#: musicbot/bot.py:343
msgid "Authenticated with Spotify successfully using guest mode."
msgstr "Аутентификация в Spotify прошла успешно в гостевом режиме."

#. Used by: warning
#: musicbot/bot.py:348
#, python-format
msgid "Could not start Spotify client using guest mode. Details: %s."
msgstr ""
"Невозможно запустить клиент Spotify в гостевом режиме. Подробности: %s."

#. Used by: info
#: musicbot/bot.py:353
msgid "Initialized, now connecting to discord."
msgstr "Инициализирован, теперь подключаемся к discord."

#. Used by: debug
#: musicbot/bot.py:364
msgid "Network ping test is disabled via config."
msgstr "Тест сетевого пинга отключён через config."

#. Used by: noise
#: musicbot/bot.py:368
msgid "Network ping test is closing down."
msgstr "Тест сетевого пинга закрывается вниз."

#. Used by: warning
#: musicbot/bot.py:379
msgid "Could not resolve ping target."
msgstr "Не удалось определить цель"

#. Used by: noise
#: musicbot/bot.py:409
msgid "Network ping test cancelled."
msgstr "Тест сетевого пинга отменен."

#. Used by: warning
#: musicbot/bot.py:423
msgid "Network testing via HTTP does not have a session to borrow."
msgstr "Сетевое тестирование через HTTP не имеет сеанса для заимствования."

#. Used by: warning
#: musicbot/bot.py:448
msgid "Could not locate `ping` executable in your environment."
msgstr "Не удалось найти исполняемый файл `ping` в вашей среде."

#. Used by: error
#: musicbot/bot.py:474
#, python-format
msgid ""
"MusicBot could not locate a `ping` command path.  Will attempt to use HTTP ping instead.\n"
"MusicBot tried the following command:   %s\n"
"You should enable ping in your system or container environment for best results.\n"
"Alternatively disable network checking via config."
msgstr ""
"MusicBot не может найти путь к команде `ping`. Вместо этого попытается использовать HTTP ping.\n"
"MusicBot выполнил следующую команду:   %s\n"
"Вы должны включить ping в системе или контейнерном окружении для получения наилучшего результата.\n"
"Или отключите проверку сети через конфигурацию."

#. Used by: error
#: musicbot/bot.py:484
#, python-format
msgid ""
"MusicBot was denied permission to execute the `ping` command.  Will attempt to use HTTP ping instead.\n"
"MusicBot tried the following command:   %s\n"
"You should enable ping in your system or container environment for best results.\n"
"Alternatively disable network checking via config."
msgstr ""
"MusicBot отказано в разрешении на выполнение команды `ping`. Вместо этого попытается использовать HTTP ping .\n"
"MusicBot выполнил следующую команду:   %s\n"
"Вы должны включить ping в системе или контейнерном окружении для получения наилучшего результата.\n"
"Или отключите проверку сети через конфигурацию."

#. Used by: error
#: musicbot/bot.py:494
#, python-format
msgid ""
"Your environment may not allow the `ping` system command.  Will attempt to use HTTP ping instead.\n"
"MusicBot tried the following command:   %s\n"
"You should enable ping in your system or container environment for best results.\n"
"Alternatively disable network checking via config."
msgstr ""
"Ваша среда может не разрешать системную команду `ping`. Вместо этого попытается использовать HTTP ping.\n"
"MusicBot выполнил следующую команду:   %s\n"
"Вы должны включить ping в системе или контейнерном окружении для получения наилучшего результата.\n"
"Или отключите проверку сети через конфигурацию."

#. Used by: info
#: musicbot/bot.py:509
msgid "MusicBot detected network is available again."
msgstr "Обнаруженная сеть MusicBot снова доступна."

#. Used by: warning
#: musicbot/bot.py:514
msgid "VoiceClient is not connected, waiting to resume MusicPlayer..."
msgstr "VoiceClient не подключен, ожидается возобновление MusicPlayer..."

#. Used by: info
#: musicbot/bot.py:518
#, python-format
msgid "Resuming playback of player:  (%(guild_id)s) %(player)r"
msgstr "Возобновление воспроизведения игрока: (%(guild_id)s) %(player)r"

#. Used by: info
#: musicbot/bot.py:529
msgid "MusicBot detected a network outage."
msgstr "MusicBot обнаружил ошибки в сети."

#. Used by: info
#: musicbot/bot.py:533
#, python-format
msgid ""
"Pausing MusicPlayer due to network availability:  (%(guild_id)s) %(player)r"
msgstr "Пауза MusicPlayer из-за доступности сети: (%(guild_id)s) %(player)r"

#. Used by: noise
#: musicbot/bot.py:554
#, python-format
msgid ""
"Looking for owner in guild: %(guild)s (required voice: %(required)s) and "
"got:  %(owner)s"
msgstr ""
"Ищете владельца в гильдии: %(guild)s (требуется голос: %(required)s) и "
"получили:  %(owner)s"

#. Used by: info
#: musicbot/bot.py:568
msgid "Checking for channels to auto-join or resume..."
msgstr ""
"Проверка каналов для автоматического подключения или возобновления "
"доступа..."

#. Used by: warning
#: musicbot/bot.py:580
#, python-format
msgid "Guild not available, cannot auto join:  %(id)s/%(name)s"
msgstr ""
"Гильдия недоступна, невозможно автоматически присоединиться:  "
"%(id)s/%(name)s"

#. Used by: info
#: musicbot/bot.py:588
#, python-format
msgid "Found resumable voice channel:  %(channel)s  in guild:  %(guild)s"
msgstr ""
"Найден восходящий голосовой канал:  %(channel)s  в гильдии:  %(guild)s"

#. Used by: info
#: musicbot/bot.py:601
#, python-format
msgid "Will try resuming voice session instead of Auto-Joining channel:  %s"
msgstr ""
"Попробует возобновить голосовую сессию вместо автоподключения к каналу:  %s"

#. Used by: info
#: musicbot/bot.py:618
#, python-format
msgid "Found owner in voice channel:  %s"
msgstr "Найден владелец в голосовом канале:  %s"

#. Used by: info
#: musicbot/bot.py:623
#, python-format
msgid "Ignoring resumable channel, AutoSummon to owner in channel:  %s"
msgstr "Игнорирование восходящего канала, автодайвинг владельцу в канале:  %s"

#. Used by: info
#: musicbot/bot.py:628
#, python-format
msgid "Ignoring Auto-Join channel, AutoSummon to owner in channel:  %s"
msgstr ""
"Игнорирование автоподключения канала AutoSummon для владельца канала:  %s"

#. Used by: info
#: musicbot/bot.py:640
#, python-format
msgid "Already connected to channel:  %(channel)s  in guild:  %(guild)s"
msgstr "Уже подключен к каналу:  %(channel)s  в гильдии:  %(guild)s"

#. Used by: info
#: musicbot/bot.py:649
#, python-format
msgid "Attempting to join channel:  %(channel)s  in guild:  %(guild)s"
msgstr "Попытка присоединиться к каналу:  %(channel)s  в гильдии:  %(guild)s"

#. Used by: info
#: musicbot/bot.py:656
msgid "Discarding MusicPlayer and making a new one..."
msgstr "Отмена Музыкального Игрока и создание нового..."

#. Used by: debug
#: musicbot/bot.py:676
msgid "MusicBot will make a new MusicPlayer now..."
msgstr "MusicBot теперь создаст новый музыкальный плеер..."

#. Used by: warning
#: musicbot/bot.py:697
#, python-format
msgid "Not joining %(guild)s/%(channel)s, it isn't a supported voice channel."
msgstr ""
"Не присоединяйтесь к %(guild)s/%(channel)s, это не поддерживаемый голосовой "
"канал."

#. Used by: info
#: musicbot/bot.py:700
msgid "Finished joining configured channels."
msgstr "Подключение к настроенным каналам завершено."

#. Used by: CommandError
#: musicbot/bot.py:723
msgid "Member is not voice-enabled and cannot use this command."
msgstr ""
"Участник не включен голосовым путем и не может использовать эту команду."

#. Used by: PermissionsError
#: musicbot/bot.py:731
msgid "You cannot use this command when not in the voice channel."
msgstr "Вы не можете использовать эту команду, если не в голосовом канале."

#. Used by: debug
#: musicbot/bot.py:745
msgid "Getting bot Application Info."
msgstr "Получение информации о приложении бота."

#. Used by: error
#: musicbot/bot.py:770
#, python-format
msgid "MusicBot does not have permission to Connect in channel:  %s"
msgstr "Музыкабот не имеет разрешения на подключение в канале:  %s"

#. Used by: PermissionsError
#: musicbot/bot.py:774
#, python-format
msgid "MusicBot does not have permission to Connect in channel:  `%(name)s`"
msgstr "У Музыкабота нет прав подключаться в канале: `%(name)s`"

#. Used by: error
#: musicbot/bot.py:779
#, python-format
msgid "MusicBot does not have permission to Speak in channel:  %s"
msgstr "У Музыкабота нет прав говорить в канале:  %s"

#. Used by: PermissionsError
#: musicbot/bot.py:783
#, python-format
msgid "MusicBot does not have permission to Speak in channel:  `%(name)s`"
msgstr "У Музыкабота нет прав говорить в канале: `%(name)s`"

#. Used by: voicedebug
#: musicbot/bot.py:793
#, python-format
msgid "Reusing bots VoiceClient from guild:  %s"
msgstr "Повторное использование ботов VoiceClient от гильдии:  %s"

#. Used by: voicedebug
#: musicbot/bot.py:798
#, python-format
msgid "Forcing disconnect on stale VoiceClient in guild:  %s"
msgstr "Принудительное отключение от устаревшего VoiceClient в гильдии:  %s"

#. Used by: warning
#: musicbot/bot.py:804
msgid "Disconnect failed or was cancelled?"
msgstr "Отключение не удалось или было отменено?"

#. Used by: critical
#: musicbot/bot.py:812
#, python-format
msgid "MusicBot is unable to connect to the channel right now:  %(channel)s"
msgstr "Музыкабот не может подключиться к каналу прямо сейчас:  %(channel)s"

#. Used by: CommandError
#: musicbot/bot.py:816
msgid ""
"MusicBot could not connect to the channel.\n"
"Try again later, or restart the bot if this continues."
msgstr ""

#. Used by: voicedebug
#: musicbot/bot.py:827
msgid "MusicBot has a VoiceClient now..."
msgstr "У MusicBot есть VoiceClient сейчас..."

#. Used by: warning
#: musicbot/bot.py:832
#, python-format
msgid ""
"Retrying connection after a timeout error (%(attempt)s) while trying to "
"connect to:  %(channel)s"
msgstr ""
"Повторная попытка подключения после ошибки таймаута (%(attempt)s) при "
"попытке подключиться к  %(channel)s"

#. Used by: exception
#: musicbot/bot.py:837
msgid "MusicBot VoiceClient connection attempt was cancelled. No retry."
msgstr ""
"Попытка соединения с MusicBot VoiceClient отменена. Повторите попытку."

#. Used by: CommandError
#: musicbot/bot.py:840
msgid ""
"MusicBot connection to voice was cancelled. This is odd. Maybe restart?"
msgstr ""
"Подключение MusicBot к голосу было отменено. Это странно. Может быть "
"перезапустить?"

#. Used by: info
#: musicbot/bot.py:846 musicbot/bot.py:8670
#, python-format
msgid "MusicBot is requesting to speak in channel: %s"
msgstr "Музыкальный робот просит говорить в канале: %s"

#. Used by: PermissionsError
#. Used by: exception
#: musicbot/bot.py:851 musicbot/bot.py:8676
msgid "MusicBot does not have permission to speak."
msgstr "У MusicBot нет разрешения на чтение."

#. Used by: MusicbotException
#. Used by: exception
#: musicbot/bot.py:855 musicbot/bot.py:8678
msgid "MusicBot could not request to speak."
msgstr "MusicBot не может просить говорить."

#. Used by: info
#: musicbot/bot.py:868
#, python-format
msgid "Disconnecting a MusicPlayer in guild:  %s"
msgstr "Отключение MusicPlayer в гильдии:  %s"

#. Used by: debug
#: musicbot/bot.py:880
msgid "Disconnecting VoiceClient before we kill the MusicPlayer."
msgstr "Отключение VoiceClient до того, как мы убьем MusicPlayer."

#. Used by: warning
#: musicbot/bot.py:888 musicbot/bot.py:907 musicbot/bot.py:919
#: musicbot/bot.py:942
msgid "The disconnect failed or was cancelled."
msgstr "Отключение не удалось или было отменено."

#. Used by: debug
#: musicbot/bot.py:898
msgid ""
"MusicBot has a VoiceProtocol that is not a VoiceClient. Disconnecting "
"anyway..."
msgstr "У MusicBot есть VoiceProtocol который не является VoiceClient."

#. Used by: debug
#: musicbot/bot.py:911
#, python-format
msgid "Disconnecting a rogue VoiceClient in guild:  %s"
msgstr "Отключение неточного VoiceClient в гильдии:  %s"

#. Used by: warning
#: musicbot/bot.py:935
msgid "Disconnecting a non-guild VoiceClient..."
msgstr "Отключение VoiceClient, не являющийся гильдией..."

#. Used by: warning
#: musicbot/bot.py:945
#, python-format
msgid ""
"MusicBot.voice_clients list contains a non-VoiceClient object?\n"
"The object is actually of type:  %s"
msgstr ""
"Список MusicBot.voice_clients содержит объект, отличный от VoiceClient?\n"
"На самом деле тип объекта:  %s"

#. Used by: warning
#: musicbot/bot.py:955
#, python-format
msgid "We still have a MusicPlayer ref in guild (%(guild_id)s):  %(player)r"
msgstr ""
"У нас все еще есть отзыв MusicPlayer в гильдии (%(guild_id)s):  %(player)r"

#. Used by: voicedebug
#: musicbot/bot.py:968
#, python-format
msgid "Guild (%(guild)s) wants a player, optional:  %(player)r"
msgstr "Гильдия (%(guild)s) хочет игрока, опционально:  %(player)r"

#. Used by: error
#: musicbot/bot.py:975
msgid ""
"[BUG] MusicPlayer is missing a VoiceClient somehow.  You should probably "
"restart the bot."
msgstr ""
"[BUG] В MusicPlayer отсутствует VoiceClient, скорее всего вам следует "
"перезапустить бота."

#. Used by: warning
#: musicbot/bot.py:980
msgid "MusicPlayer has a VoiceClient that is not connected."
msgstr "У MusicPlayer есть VoiceClient который не подключен."

#. Used by: noise
#: musicbot/bot.py:981
#, python-format
msgid "MusicPlayer obj:  %r"
msgstr "Музыкальный проигрыватель:  %r"

#. Used by: noise
#: musicbot/bot.py:982
#, python-format
msgid "VoiceClient obj:  %r"
msgstr "VoiceClient obj:  %r"

#. Used by: voicedebug
#: musicbot/bot.py:1002
#, python-format
msgid ""
"Getting a MusicPlayer for guild:  %(guild)s  In Channel:  %(channel)s  "
"Create: %(create)s  Deserialize:  %(serial)s"
msgstr ""
"Получение Музыкального Игрока для гильдии:  %(guild)s  В Канале:  "
"%(channel)s  Создать: %(create)s  Дестрализация:  %(serial)s"

#. Used by: voicedebug
#: musicbot/bot.py:1018
#, python-format
msgid ""
"Created player via deserialization for guild %(guild_id)s with %(number)s "
"entries"
msgstr ""
"Создан игрок посредством десериализации для гильдии %(guild_id)s с записями "
"%(number)s"

#. Used by: CommandError
#: musicbot/bot.py:1027
msgid ""
"The bot is not in a voice channel.\n"
"Use the summon command to bring the bot to your voice channel."
msgstr ""

#. Used by: MusicbotException
#: musicbot/bot.py:1039
msgid "Something is wrong, we didn't get the VoiceClient."
msgstr "Что-то не так, мы не получили VoiceClient."

#. Used by: debug
#: musicbot/bot.py:1072
msgid "Running on_player_play"
msgstr "Выполняется на _плеере"

#. Used by: debug
#: musicbot/bot.py:1147
#, python-format
msgid "Setting URL history guild %(guild_id)s == %(url)s"
msgstr "Установка истории URL гильдии %(guild_id)s == %(url)s"

#. Used by: warning
#: musicbot/bot.py:1183 musicbot/bot.py:4940
#, python-format
msgid "No thumbnail set for entry with URL: %s"
msgstr "Нет миниатюры для записи с URL: %s"

#. Used by: debug
#: musicbot/bot.py:1195
msgid "no channel to put now playing message into"
msgstr "нет канала для воспроизведения сообщения"

#. Used by: debug
#: musicbot/bot.py:1207
msgid "ignored now-playing message as it was already posted."
msgstr ""
"проигнорировал сейчас воспроизводимое сообщение, поскольку оно уже было "
"опубликовано."

#. Used by: debug
#: musicbot/bot.py:1231
msgid "Running on_player_resume"
msgstr "Выполняется на плеер_возобновление"

#. Used by: debug
#: musicbot/bot.py:1244
msgid "Running on_player_pause"
msgstr "Пауза"

#. Used by: debug
#: musicbot/bot.py:1260
msgid "Running on_player_stop"
msgstr "Выполняется по игроку_стопу"

#. Used by: debug
#: musicbot/bot.py:1270
msgid "Running on_player_finished_playing"
msgstr "Выполняется на игровом автомате"

#. Used by: debug
#: musicbot/bot.py:1272 musicbot/bot.py:1318 musicbot/bot.py:1389
msgid "Event loop is closed, nothing else to do here."
msgstr "Цикл события закрыт, здесь нет ничего другого."

#. Used by: debug
#: musicbot/bot.py:1276 musicbot/bot.py:1322 musicbot/bot.py:1393
msgid "Logout under way, ignoring this event."
msgstr "Выход из системы, игнорирует это событие."

#. Used by: debug
#: musicbot/bot.py:1293
msgid "VoiceClient says it is not connected, nothing else we can do here."
msgstr ""
"VoiceClient говорит, что он не подключен, ничего другого мы можем сделать "
"здесь."

#. Used by: info
#: musicbot/bot.py:1300
msgid "Player finished and queue is empty, leaving voice channel..."
msgstr "Плеер завершён и очередь пуста, покидая голосовой канал..."

#. Used by: everything
#: musicbot/bot.py:1314
msgid "Looping over queue to expunge songs with missing author..."
msgstr ""
"Зацикливание над очередью для исключения песен с недостающим автором..."

#. Used by: noise
#: musicbot/bot.py:1353
#, python-format
msgid ""
"Author `%(user)s` absent, skipped (deleted) entry from queue:  %(song)s"
msgstr ""
"Автор `%(user)s` отсутствует, пропущен (удален) запись из очереди:  %(song)s"

#. Used by: warning
#: musicbot/bot.py:1372
msgid "No playable songs in the Guild autoplaylist, disabling."
msgstr "Нет воспроизводимых песен в автомате гильдии, отключается."

#. Used by: debug
#: musicbot/bot.py:1377
msgid "No content in current autoplaylist. Filling with new music..."
msgstr "Нет содержимого в текущем автомате. Заполнение новой музыкой..."

#. Used by: everything
#: musicbot/bot.py:1385
msgid "Looping over player autoplaylist..."
msgstr "Зацикливание автоматов игрока..."

#. Used by: error
#: musicbot/bot.py:1426
#, python-format
msgid "Error while processing song \"%(url)s\":  %(raw_error)s"
msgstr "Ошибка при обработке песни \"%(url)s\":  %(raw_error)s"

#. Used by: error
#: musicbot/bot.py:1437
#, python-format
msgid "Error extracting song \"%(url)s\": %(raw_error)s"
msgstr "Ошибка распаковки песни \"%(url)s\": %(raw_error)s"

#. Used by: exception
#: musicbot/bot.py:1452
msgid "MusicBot needs to stop the auto playlist extraction and bail."
msgstr "MusicBot должен остановить извлечение автоплейлиста и залог."

#. Used by: exception
#: musicbot/bot.py:1457
msgid "MusicBot got an unhandled exception in player finished event."
msgstr ""
"MusicBot получил необработанное исключение в игроке законченное событие."

#. Used by: info
#: musicbot/bot.py:1463
#, python-format
msgid "Expanding auto playlist with entries extracted from:  %s"
msgstr "Развертывание автоплейлиста с записями, извлеченными из:  %s"

#. Used by: error
#: musicbot/bot.py:1487
#, python-format
msgid "Error adding song from autoplaylist: %s"
msgstr "Ошибка добавления трека из автомата: %s"

#. Used by: debug
#: musicbot/bot.py:1490
msgid "Exception data for above error:"
msgstr "Данные об исключении для вышеописанной ошибки:"

#. Used by: warning
#: musicbot/bot.py:1496
msgid "No playable songs in the autoplaylist, disabling."
msgstr "Нет воспроизводимых песен в автомате, отключается."

#. Used by: debug
#: musicbot/bot.py:1516
msgid "Running on_player_entry_added"
msgstr "Выполняется по игроку_entry_added"

#. Used by: debug
#: musicbot/bot.py:1526
msgid "Automatically skipping auto-playlist entry for queued entry."
msgstr ""
"Автоматически пропускать запись в список автовоспроизведения для записи в "
"очереди."

#. Used by: exception
#: musicbot/bot.py:1546
#, python-format
msgid "MusicPlayer exception for entry: %r"
msgstr "Исключение из музыкального плеера для записи: %r"

#. Used by: exception
#: musicbot/bot.py:1552
msgid "MusicPlayer exception."
msgstr "Исключение из музыкального плеера."

#. Used by: info
#: musicbot/bot.py:1576
#, python-format
msgid "Auto playlist track could not be played:  %r"
msgstr "Не удалось воспроизвести трек автоплейлиста:  %r"

#. Used by: debug
#: musicbot/bot.py:1615
msgid "Logout under way, ignoring status update event."
msgstr "Идет выход из системы, проигнорировано событие обновления статуса."

#. Used by: noise
#: musicbot/bot.py:1716
#, python-format
msgid "Update bot status:  %(status)s -- %(activity)r"
msgstr "Статус бота:  %(status)s -- %(activity)r"

#. Used by: debug
#: musicbot/bot.py:1744
#, python-format
msgid "Serializing queue for %s"
msgstr "Сериализация очереди для %s"

#. Used by: debug
#: musicbot/bot.py:1770
#, python-format
msgid "Deserializing queue for %s"
msgstr "Десериализация очереди для %s"

#. Used by: debug
#: musicbot/bot.py:1788
#, python-format
msgid "Writing current song for %s"
msgstr "Запись текущей песни для %s"

#. Used by: error
#: musicbot/bot.py:1813
#, python-format
msgid "Cannot send non-response object:  %r"
msgstr "Не удается отправить объект без ответа:  %r"

#. Used by: MusicbotException
#: musicbot/bot.py:1818
msgid "[Dev Bug] Tried sending an invalid response object."
msgstr "[Dev Bug] Попытка отправить некорректный объект ответа."

#. Used by: debug
#: musicbot/bot.py:1855
#, python-format
msgid "sending embed to: %s"
msgstr "отправка вставки на: %s"

#. Used by: debug
#: musicbot/bot.py:1858
#, python-format
msgid "sending text to: %s"
msgstr "отправка текста в: %s"

#. Used by: error
#: musicbot/bot.py:1863
#, python-format
msgid "Cannot send message to \"%s\", no permission"
msgstr "Не удается отправить сообщение \"%s\", нет разрешения"

#. Used by: error
#: musicbot/bot.py:1870
#, python-format
msgid "Cannot send message to \"%s\", invalid or deleted channel"
msgstr "Не удается отправить сообщение \"%s\", недопустимый или удаленный канал"

#. Used by: error
#: musicbot/bot.py:1878
#, python-format
msgid "Message is over the message size limit (%s)"
msgstr "Сообщение превышает предел размера сообщения (%s)"

#. Used by: debug
#: musicbot/bot.py:1886
msgid "Could not send private message, sending in fallback channel instead."
msgstr ""
"Не удалось отправить личное сообщение, вместо этого отправка в резервный "
"канал."

#. Used by: warning
#: musicbot/bot.py:1904
#, python-format
msgid "Rate limited send message, retrying in %s seconds."
msgstr ""
"Оценить ограниченное количество отправленных сообщений, повторить попытку "
"через %s секунд."

#. Used by: warning
#: musicbot/bot.py:1910
#, python-format
msgid "Cancelled message retry for:  %s"
msgstr "Отменено сообщение повторно:  %s"

#. Used by: error
#: musicbot/bot.py:1915
msgid "Rate limited send message, but cannot retry!"
msgstr ""
"Оцените ограниченное количество отправленных сообщений, но не удается "
"повторить попытку!"

#. Used by: error
#: musicbot/bot.py:1921
msgid "Failed to send message in fallback channel."
msgstr "Не удалось отправить сообщение в запасном канале."

#. Used by: error
#: musicbot/bot.py:1926 musicbot/bot.py:1990 musicbot/bot.py:2060
msgid "Failed to send due to an HTTP error."
msgstr "Не удалось отправить из-за ошибки HTTP."

#. Used by: warning
#: musicbot/bot.py:1952
#, python-format
msgid "Cannot delete message \"%s\", no permission"
msgstr "Невозможно удалить сообщение \"%s\", нет разрешения"

#. Used by: warning
#: musicbot/bot.py:1957
#, python-format
msgid "Cannot delete message \"%s\", message not found"
msgstr "Невозможно удалить сообщение \"%s\", сообщение не найдено"

#. Used by: warning
#: musicbot/bot.py:1975
#, python-format
msgid "Rate limited message delete, retrying in %s seconds."
msgstr ""
"Оцените ограниченное удаление сообщения, повторная попытка через %s секунд."

#. Used by: error
#: musicbot/bot.py:1980
msgid "Rate limited message delete, but cannot retry!"
msgstr ""
"Оцените ограниченное сообщение удаления, но не могу повторить попытку!"

#. Used by: warning
#: musicbot/bot.py:1983
msgid "Failed to delete message"
msgstr "Не удалось удалить сообщение"

#. Used by: noise
#: musicbot/bot.py:1985
#, python-format
msgid "Got HTTPException trying to delete message: %s"
msgstr "Получено HTTPException пытается удалить сообщение: %s"

#. Used by: warning
#: musicbot/bot.py:2020
#, python-format
msgid "Cannot edit message \"%s\", message not found"
msgstr "Невозможно изменить сообщение \"%s\", сообщение не найдено"

#. Used by: warning
#: musicbot/bot.py:2024
msgid "Sending message instead"
msgstr "Отправка сообщения"

#. Used by: warning
#: musicbot/bot.py:2041
#, python-format
msgid "Rate limited edit message, retrying in %s seconds."
msgstr ""
"Оценить ограниченное сообщение редактирования, повторная попытка через %s "
"секунд."

#. Used by: warning
#: musicbot/bot.py:2047
#, python-format
msgid "Cancelled message edit for:  %s"
msgstr "Отменено изменение сообщения для:  %s"

#. Used by: warning
#: musicbot/bot.py:2053
msgid "Failed to edit message"
msgstr "Не удалось изменить сообщение"

#. Used by: noise
#: musicbot/bot.py:2055
#, python-format
msgid "Got HTTPException trying to edit message %s to: %s"
msgstr "Принято HTTPException, пытающееся редактировать сообщение %s в: %s"

#. Used by: warning
#: musicbot/bot.py:2077
#, python-format
msgid "Cancelled delete for message (ID: %(id)s):  %(content)s"
msgstr "Отменено удаление сообщения (ID: %(id)s):  %(content)s"

#. Used by: warning
#: musicbot/bot.py:2139
#, python-format
msgid "Caught a signal from the OS: %s"
msgstr "Получен сигнал от ОС: %s"

#. Used by: info
#: musicbot/bot.py:2143
msgid "Disconnecting and closing down MusicBot..."
msgstr "Отключение и включение MusicBot..."

#. Used by: exception
#: musicbot/bot.py:2146
msgid "Exception thrown while handling interrupt signal!"
msgstr "Исключение выбрасывается при обработке сигнала прерывания!"

#. Used by: info
#: musicbot/bot.py:2161
msgid "MusicBot is now doing shutdown steps..."
msgstr "MusicBot теперь делает шаги выключения..."

#. Used by: HelpfulError
#: musicbot/bot.py:2169
msgid ""
"Failed Discord API Login!\n"
"\n"
"Problem:\n"
"  MusicBot could not log into Discord API.\n"
"  Your Token may be incorrect or there may be an API outage.\n"
"\n"
"Solution:\n"
"  Make sure you have the correct Token set in your config.\n"
"  Check API status at the official site: discordstatus.com"
msgstr ""
"Ошибка входа в Discord API!\n"
"\n"
"Проблема:\n"
"  MusicBot не смог войти в Discord API.\n"
"  Ваш токен может быть неправильным или может возникнуть ошибка API.\n"
"\n"
"Решение:\n"
"  Убедитесь, что в конфигурации установлен правильный токен.\n"
"  Проверка статуса API на официальном сайте: discordstatus.com"

#. Used by: info
#: musicbot/bot.py:2183
msgid "Waiting for download threads to finish up..."
msgstr "Ожидание окончания потоков загрузки..."

#. Used by: debug
#: musicbot/bot.py:2209
#, python-format
msgid "Will wait for task:  %(name)s  (%(func)s)"
msgstr "Подождите задачи:  %(name)s  (%(func)s)"

#. Used by: debug
#: musicbot/bot.py:2216
#, python-format
msgid "Will try to cancel task:  %(name)s  (%(func)s)"
msgstr "Попробует отменить задачу:  %(name)s  (%(func)s)"

#. Used by: debug
#: musicbot/bot.py:2224
msgid "Awaiting pending tasks..."
msgstr "Ожидается ожидание задач..."

#. Used by: debug
#: musicbot/bot.py:2230
msgid "Closing HTTP Connector."
msgstr "Закрытие HTTP-коннектора."

#. Used by: debug
#: musicbot/bot.py:2236
msgid "Closing aiohttp session."
msgstr "Завершение сеанса aiohttp."

#. Used by: noise
#: musicbot/bot.py:2248
msgid "Logout has been called."
msgstr "Выход был вызван."

#. Used by: error
#: musicbot/bot.py:2260
#, python-format
msgid ""
"Exception in %(event)s:\n"
"%(error)s"
msgstr ""
"Исключение в %(event)s:\n"
"%(error)s"

#. Used by: error
#: musicbot/bot.py:2276
#, python-format
msgid "Exception in %s"
msgstr "Исключение в %s"

#. Used by: info
#: musicbot/bot.py:2283
msgid "MusicBot resumed a session with discord."
msgstr "Музыкальный робот возобновил сессию с дискордом."

#. Used by: debug
#: musicbot/bot.py:2300
msgid "Finish on_ready"
msgstr "Завершить _готовое"

#. Used by: debug
#: musicbot/bot.py:2307
msgid "Logged in, now getting MusicBot ready..."
msgstr "Вход выполнен, теперь MusicBot готов..."

#. Used by: critical
#: musicbot/bot.py:2310
msgid "ClientUser is somehow none, we gotta bail..."
msgstr "Клиент как-то нет, мы должны забрать гвозд..."

#. Used by: info
#: musicbot/bot.py:2319
#, python-format
msgid "MusicBot:  %(id)s/%(name)s#%(desc)s"
msgstr "Музыкабот:  %(id)s/%(name)s#%(desc)s"

#. Used by: info
#: musicbot/bot.py:2330
#, python-format
msgid "Owner:     %(id)s/%(name)s#%(desc)s\n"
msgstr "Владелец:     %(id)s/%(name)s#%(desc)s\n"

#. Used by: info
#: musicbot/bot.py:2338 musicbot/bot.py:2365
msgid "Guild List:"
msgstr "Список гильдий:"

#. Used by: info
#. Used by: debug
#: musicbot/bot.py:2342 musicbot/bot.py:2368 musicbot/bot.py:8862
#, python-format
msgid " - %s"
msgstr " - %s"

#. Used by: info
#: musicbot/bot.py:2351
#, python-format
msgid "Left %s due to bot owner not found"
msgstr "Лев. %s из-за того, что владелец бота не найден"

#. Used by: info
#: musicbot/bot.py:2356
#, python-format
msgid "Not proceeding with checks in %s servers due to unavailability"
msgstr "Не выполняется проверка на серверах %s из-за недоступности"

#. Used by: warning
#: musicbot/bot.py:2362
#, python-format
msgid "Owner could not be found on any guild (id: %s)\n"
msgstr "Владелец не найден ни в одной гильдии (id: %s)\n"

#. Used by: warning
#: musicbot/bot.py:2371
msgid "Owner unknown, bot is not on any guilds."
msgstr "Владелец неизвестен, бот не на гильдиях."

#. Used by: warning
#: musicbot/bot.py:2375
#, python-format
msgid ""
"To make the bot join a guild, paste this link in your browser. \n"
"Note: You should be logged into your main account and have \n"
"manage server permissions on the guild you want the bot to join.\n"
"  %s"
msgstr ""
"Чтобы сделать бота присоединится к гильдии, вставьте эту ссылку в браузер. \n"
"Примечание: Вы должны войти в свою главную учетную запись и иметь \n"
"управлять разрешениями сервера в гильдии, которую вы хотите, чтобы бот присоединился.\n"
"  %s"

#. Used by: warning
#: musicbot/bot.py:2392
#, python-format
msgid "Got None for bound channel with ID:  %d"
msgstr "Нет привязки канала с ID:  %d"

#. Used by: warning
#: musicbot/bot.py:2398
#, python-format
msgid "Cannot bind to non Messageable channel with ID:  %d"
msgstr "Не удается привязать к каналу без сообщения с ID:  %d"

#. Used by: info
#: musicbot/bot.py:2412
msgid "Bound to text channels:"
msgstr "Привязано к текстовым каналам:"

#. Used by: info
#: musicbot/bot.py:2430 musicbot/bot.py:2480
#, python-format
msgid " - %(guild)s/%(channel)s"
msgstr " - %(guild)s/%(channel)s"

#. Used by: info
#: musicbot/bot.py:2434 musicbot/bot.py:2436
msgid "Not bound to any text channels"
msgstr "Нет привязки к текстовым каналам"

#. Used by: warning
#: musicbot/bot.py:2447
#, python-format
msgid "Got None for auto join channel with ID:  %d"
msgstr "Нет для автоподключения к каналу с ID:  %d"

#. Used by: warning
#: musicbot/bot.py:2453
#, python-format
msgid "Cannot auto join a Private/Non-Guild channel with ID:  %d"
msgstr ""
"Невозможно автоматически присоединиться к частному каналу негильдии с ID:  "
"%d"

#. Used by: warning
#: musicbot/bot.py:2461
#, python-format
msgid "Cannot auto join to non-connectable channel with ID:  %d"
msgstr ""
"Невозможно автоматически подключиться к каналу без подключения с ID:  %d"

#. Used by: info
#: musicbot/bot.py:2477
msgid "Auto joining voice channels:"
msgstr "Автоподсоединение к голосовым каналам:"

#. Used by: info
#: musicbot/bot.py:2485 musicbot/bot.py:2488
msgid "Not auto joining any voice channels"
msgstr "Не подключаться к голосовым каналам"

#. Used by: warning
#: musicbot/bot.py:2501
#, python-format
msgid ""
"Detected missing config options!\n"
"\n"
"Problem:\n"
"  You config options file is missing some options.\n"
"  Default settings will be used for these options.\n"
"  Here is a list of options we didn't find:\n"
"  %(missing)s\n"
"\n"
"Solution:\n"
"  Copy new options from the example options file.\n"
"  Or use the config command to set and save them.\n"
"\n"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:2530
#, python-format
msgid "Event on_ready has fired %s times"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:2546
msgid "Getting application info."
msgstr "Получение информации о приложении."

#. Used by: debug
#: musicbot/bot.py:2564
msgid "Ensuring data folders exist"
msgstr "Обеспечение наличия папок данных существует"

#. Used by: debug
#: musicbot/bot.py:2579
msgid "Validating config"
msgstr "Проверка конфигурации"

#. Used by: debug
#: musicbot/bot.py:2582
msgid "Validating permissions config"
msgstr "Проверка конфигурации прав доступа"

#. Used by: _L
#: musicbot/bot.py:2592
msgid "Disabled"
msgstr "Отключено"

#. Used by: _L
#: musicbot/bot.py:2592
msgid "Enabled"
msgstr "Включено"

#. Used by: info
#: musicbot/bot.py:2595
msgid "Options:"
msgstr "Параметры:"

#. Used by: info
#: musicbot/bot.py:2597
#, python-format
msgid "  Command prefix: %s"
msgstr "  Префикс команды: %s"

#. Used by: info
#: musicbot/bot.py:2602
#, python-format
msgid "  Default volume: %d%%"
msgstr "  По умолчанию: %d%%"

#. Used by: info
#: musicbot/bot.py:2604
#, python-format
msgid "  Skip threshold: %(num)d votes or %(percent).0f%%"
msgstr "  Пропустить порог: %(num)d голосов или %(percent).0f%%"

#. Used by: info
#: musicbot/bot.py:2616
#, python-format
msgid "  Now Playing @mentions: %s"
msgstr "  Играет в @mentions: %s"

#. Used by: info
#: musicbot/bot.py:2623
#, python-format
msgid "  Auto-Playlist: %(status)s (order: %(order)s)"
msgstr "  Автоплейлист: %(status)s (заказ: %(order)s)"

#. Used by: _L
#: musicbot/bot.py:2626
msgid "random"
msgstr "случайный"

#. Used by: _L
#: musicbot/bot.py:2626
msgid "sequential"
msgstr "последовательный"

#. Used by: info
#: musicbot/bot.py:2646
#, python-format
msgid "  Auto-Pause: %s"
msgstr "  Автопауза: %s"

#. Used by: info
#: musicbot/bot.py:2648
#, python-format
msgid "  Delete Messages: %s"
msgstr "  Удалить сообщения: %s"

#. Used by: info
#: musicbot/bot.py:2653
#, python-format
msgid "    Delete Invoking: %s"
msgstr "    Удалить вызов: %s"

#. Used by: info
#: musicbot/bot.py:2657
#, python-format
msgid "    Delete Now Playing: %s"
msgstr "    Удалить сейчас Играет: %s"

#. Used by: info
#: musicbot/bot.py:2660
#, python-format
msgid "  Debug Mode: %s"
msgstr "  Режим отладки: %s"

#. Used by: info
#: musicbot/bot.py:2664
#, python-format
msgid "  Downloaded songs will be %s"
msgstr "  Загруженные песни будут %s"

#. Used by: info
#: musicbot/bot.py:2668
#, python-format
msgid "    Delete if unused for %d days"
msgstr "    Удалить если не использовано для %d дней"

#. Used by: info
#: musicbot/bot.py:2679
#, python-format
msgid "  Status message: %s"
msgstr "  Сообщение статуса: %s"

#. Used by: info
#: musicbot/bot.py:2691
#, python-format
msgid "  Spotify integration: %s"
msgstr "  Интеграция Spotify: %s"

#. Used by: info
#: musicbot/bot.py:2704
#, python-format
msgid "    Timeout: %s seconds"
msgstr "    Таймаут: %s секунд"

#. Used by: info
#: musicbot/bot.py:2716
#, python-format
msgid "    Timeout: %d seconds"
msgstr "    Таймаут: %d секунд"

#. Used by: info
#: musicbot/bot.py:2717
#, python-format
msgid "  Self Deafen: %s"
msgstr "  Самоглушено: %s"

#. Used by: info
#: musicbot/bot.py:2719
#, python-format
msgid "  Per-server command prefix: %s"
msgstr "  Префикс команды на сервер: %s"

#. Used by: info
#: musicbot/bot.py:2725
#, python-format
msgid "  Round Robin Queue: %s"
msgstr "  Очередь грабинов: %s"

#. Used by: CommandError
#: musicbot/bot.py:2780
#, python-format
msgid "The requested song `%(subject)s` is blocked by the song block list."
msgstr "Запрошенная песня `%(subject)s` заблокирована списком блоков песен."

#. Used by: warning
#: musicbot/bot.py:2791
msgid ""
"Attempted to handle Voice Channel inactivity, but Bot is not in voice..."
msgstr "Пытался работать с 'Голосовым каналом', но бот не в голосе..."

#. Used by: debug
#: musicbot/bot.py:2798
#, python-format
msgid "Channel activity already waiting in guild: %s"
msgstr "Активность канала уже ожидается в гильдии: %s"

#. Used by: info
#: musicbot/bot.py:2808
#, python-format
msgid ""
"Channel activity waiting %(time)d seconds to leave channel: %(channel)s"
msgstr ""
"Действия канала ожидают %(time)d секунд, чтобы покинуть канал: %(channel)s"

#. Used by: info
#: musicbot/bot.py:2823
#, python-format
msgid "Channel activity timer for %s has expired. Disconnecting."
msgstr "Таймер активности канала для %s истек. Отсоединение."

#. Used by: info
#: musicbot/bot.py:2829
#, python-format
msgid "Channel activity timer canceled for: %(channel)s in %(guild)s"
msgstr "Таймер активности канала отменен для: %(channel)s в %(guild)s"

#. Used by: debug
#: musicbot/bot.py:2857
#, python-format
msgid "Ignoring player inactivity in auto-joined channel:  %s"
msgstr "Игнорирование бездействия игрока в автоподключенном канале:  %s"

#. Used by: debug
#: musicbot/bot.py:2864
#, python-format
msgid "Player activity timer already waiting in guild: %s"
msgstr "Таймер активности игрока уже ждет гильдии: %s"

#. Used by: info
#: musicbot/bot.py:2872
#, python-format
msgid ""
"Player activity timer waiting %(time)d seconds to leave channel: %(channel)s"
msgstr ""
"Таймер активности игрока, ожидающий %(time)d секунд, чтобы покинуть канал: "
"%(channel)s"

#. Used by: info
#: musicbot/bot.py:2884
#, python-format
msgid "Player activity timer for %s has expired. Disconnecting."
msgstr "Таймер активности игрока %s истек. Отсоединение."

#. Used by: info
#: musicbot/bot.py:2890 musicbot/bot.py:2895
#, python-format
msgid "Player activity timer canceled for: %(channel)s in %(guild)s"
msgstr "Таймер активности игрока отменен для: %(channel)s в %(guild)s"

#. Used by: debug
#: musicbot/bot.py:2912
msgid "Player activity timer is being reset."
msgstr "Таймер активности игрока восстанавливается."

#. Used by: CommandError
#: musicbot/bot.py:3021
msgid "No such command"
msgstr "Нет такой команды"

#. Used by: CommandError
#: musicbot/bot.py:3097
msgid "You must mention a user or provide their ID number."
msgstr ""
"Вы должны указать пользователя или указать его идентификационный номер."

#. Used by: CommandError
#: musicbot/bot.py:3102
msgid "Invalid sub-command given. Use `help blockuser` for usage examples."
msgstr ""
"Неверная субкоманда. Для примеров использования используйте `help "
"blockuser`."

#. Used by: CommandError
#: musicbot/bot.py:3113
msgid "MusicBot could not find the user(s) you specified."
msgstr "MusicBot не может найти указанного пользователя."

#. Used by: CommandError
#: musicbot/bot.py:3120
msgid "The owner cannot be added to the block list."
msgstr "Владелец не может быть добавлен в заблокированный список."

#. Used by: info
#: musicbot/bot.py:3124
#, python-format
msgid "Not adding user to block list, already blocked:  %(id)s/%(name)s"
msgstr ""
"Не добавляет пользователя в чёрный список, уже заблокирован:  "
"%(id)s/%(name)s"

#. Used by: info
#: musicbot/bot.py:3133
#, python-format
msgid "Not removing user from block list, not listed:  %(id)s/%(name)s"
msgstr ""
"Не удаляется пользователь из черного списка, не в списке:  %(id)s/%(name)s"

#. Used by: CommandError
#: musicbot/bot.py:3150
msgid "Cannot add the users you listed, they are already added."
msgstr ""
"Не удается добавить пользователей, которые вы указали, они уже добавлены."

#. Used by: CommandError
#: musicbot/bot.py:3227
msgid "You must provide a song subject if no song is currently playing."
msgstr ""
"Вы должны предоставить тему песни, если песня в настоящее время не "
"воспроизводится."

#. Used by: CommandError
#: musicbot/bot.py:3233
msgid "Invalid sub-command given. Use `help blocksong` for usage examples."
msgstr ""
"Неверная субкоманда. Используйте `help blocksong` для примеров "
"использования."

#. Used by: CommandError
#: musicbot/bot.py:3245
#, python-format
msgid "Subject `%(subject)s` is already in the song block list."
msgstr "Тема `%(subject)s` уже находится в списке блоков песен."

#. Used by: CommandError
#: musicbot/bot.py:3277
msgid "The subject is not in the song block list and cannot be removed."
msgstr "Тема отсутствует в списке блоков песни и не может быть удалена."

#. Used by: CommandError
#: musicbot/bot.py:3349
msgid "Invalid sub-command given. Use `help autoplaylist` for usage examples."
msgstr ""
"Неверная субкоманда. Используйте `help autoplaylist` для примеров "
"использования."

#. Used by: CommandError
#: musicbot/bot.py:3356
msgid "The supplied song link is invalid"
msgstr "Недействительная ссылка на песню"

#. Used by: CommandError
#: musicbot/bot.py:3362
msgid "The queue is empty. Add some songs with a play command!"
msgstr ""
"Очередь пуста. Добавьте несколько песен с помощью команды воспроизведения!"

#. Used by: CommandError
#: musicbot/bot.py:3390
msgid "This song is already in the autoplaylist."
msgstr "Эта песня уже есть в автомате."

#. Used by: CommandError
#: musicbot/bot.py:3407
msgid "This song is not yet in the autoplaylist."
msgstr "Эта песня еще не находится в автомате."

#. Used by: CommandError
#: musicbot/bot.py:3441
msgid "You must provide a playlist filename."
msgstr "Вы должны указать имя файла плейлиста."

#. Used by: PermissionsError
#: musicbot/bot.py:3551
msgid "You are not allowed to request playlists"
msgstr "Вам не разрешено запрашивать плейлисты"

#. Used by: PermissionsError
#: musicbot/bot.py:3559
#, python-format
msgid "Playlist has too many entries (%(songs)s but max is %(max)s)"
msgstr ""
"Плейлист имеет слишком много записей (%(songs)s , но максимум %(max)s)"

#. Used by: PermissionsError
#: musicbot/bot.py:3570
#, python-format
msgid ""
"The playlist entries will exceed your queue limit.\n"
"There are %(songs)s in the list, and %(queued)s already in queue.\n"
"The limit is %(max)s for your group."
msgstr ""

#. Used by: debug
#: musicbot/bot.py:3594
msgid "Ignoring auto-pause due to network outage."
msgstr "Игнорирование автопаузы из-за отключения сети."

#. Used by: voicedebug
#: musicbot/bot.py:3599
msgid ""
"MusicPlayer has no VoiceClient or has no channel data, cannot process auto-"
"pause."
msgstr ""
"У MusicPlayer нет VoiceClient или нет данных о каналах, не может работать с "
"автопаузами."

#. Used by: debug
#: musicbot/bot.py:3610
msgid "Already processing auto-pause, ignoring this event."
msgstr "Уже обрабатывается автопауза, игнорируется это событие."

#. Used by: warning
#: musicbot/bot.py:3618
#, python-format
msgid ""
"%sVoiceClient not connected, waiting %s seconds to handle auto-pause in "
"guild:  %s"
msgstr ""
"%sVoiceClient не подключен, ожидание %s секунд для обработки автопаузы в "
"гильдии:  %s"

#. Used by: debug
#: musicbot/bot.py:3626
msgid "Auto-pause waiting was cancelled."
msgstr "Ожидание автопаузы было отменено."

#. Used by: info
#: musicbot/bot.py:3633
msgid "A new MusicPlayer is being connected, ignoring old auto-pause event."
msgstr ""
"Подключается новый музыкальный плеер, игнорируя старое событие автопаузы."

#. Used by: info
#: musicbot/bot.py:3649
#, python-format
msgid "Playing in an empty voice channel, running auto pause for guild: %s"
msgstr ""
"Проигрывание в пустом голосовом канале, запуск автопаузы для гильдии: %s"

#. Used by: info
#: musicbot/bot.py:3656
#, python-format
msgid "Previously auto paused player is unpausing for guild: %s"
msgstr "Ранее автопауза игрока не приостанавливается для гильдии: %s"

#. Used by: CommandError
#: musicbot/bot.py:3887
msgid "Cannot use seek if there is nothing playing."
msgstr "Невозможно использовать поиск, если нет проигрывания."

#. Used by: CommandError
#: musicbot/bot.py:3892
msgid "Cannot use seek on current track, it has an unknown duration."
msgstr ""
"Невозможно использовать поиск по текущему треку, он имеет неизвестную "
"длительность."

#. Used by: CommandError
#: musicbot/bot.py:3898
msgid "Seeking is not supported for streams."
msgstr "Поиск не поддерживается для потоков."

#. Used by: CommandError
#: musicbot/bot.py:3908
msgid "Cannot use seek without a time to position playback."
msgstr ""
"Невозможно использовать переключение без времени для размещения "
"воспроизведения."

#. Used by: CommandError
#: musicbot/bot.py:3926
#, python-format
msgid "Could not convert `%(input)s` to a valid time in seconds."
msgstr "Не удалось преобразовать `%(input)s` в допустимое время в секундах."

#. Used by: CommandError
#: musicbot/bot.py:3939
#, python-format
msgid ""
"Cannot seek to `%(input)s` (`%(seconds)s` seconds) in the current track with"
" a length of `%(progress)s / %(total)s`"
msgstr ""
"Не удается переключиться в `%(input)s` (`%(seconds)s` секунд) в текущем "
"треке длиной `%(progress)s / %(total)s`"

#. Used by: CommandError
#: musicbot/bot.py:4000
msgid "Invalid sub-command. Use the command `help repeat` for usage examples."
msgstr ""
"Неверная субкоманда. Используйте команду `help repeat` для примеров "
"использования."

#. Used by: CommandError
#: musicbot/bot.py:4038
msgid "The player is not currently looping."
msgstr "Игрок в данный момент не зацикливается."

#. Used by: CommandError
#: musicbot/bot.py:4094
msgid "Song positions must be integers!"
msgstr "Позиции песни должны быть целыми!"

#. Used by: CommandError
#: musicbot/bot.py:4099
msgid "You gave a position outside the playlist size!"
msgstr "Вы поставили позицию за пределами плейлиста!"

#. Used by: warning
#: musicbot/bot.py:4147
msgid ""
"Could not prompt for playlist playback, no message to add reactions to."
msgstr ""
"Не удалось запросить воспроизведение плейлиста, нет сообщений для добавления"
" реакций."

#. Used by: CommandError
#: musicbot/bot.py:4236
msgid "Local media playback is not enabled."
msgstr "Воспроизведение локального медиа не включено."

#. Used by: CommandError
#: musicbot/bot.py:4279
msgid "Spotify URL is invalid or not currently supported."
msgstr ""
"URL-адрес Spotify недействителен или в настоящее время не поддерживается."

#. Used by: CommandError
#: musicbot/bot.py:4283
msgid "Detected a Spotify URL, but Spotify is not enabled."
msgstr "Обнаружен URL-адрес Spotify, но Spotify не включен."

#. Used by: PermissionsError
#: musicbot/bot.py:4293 musicbot/bot.py:4498
#, python-format
msgid "You have reached your enqueued song limit (%(max)s)"
msgstr "Вы достигли лимита на добавленные песни (%(max)s)"

#. Used by: PermissionsError
#: musicbot/bot.py:4299 musicbot/bot.py:4504 musicbot/bot.py:4601
msgid "Karaoke mode is enabled, please try again when its disabled!"
msgstr "Караоке-режим включен, попробуйте еще раз, когда он отключен!"

#. Used by: exception
#: musicbot/bot.py:4311
msgid "Issue with extract_info(): "
msgstr "Проблема с extract_info(): "

#. Used by: CommandError
#: musicbot/bot.py:4315 musicbot/bot.py:4520
#, python-format
msgid ""
"Failed to extract info due to error:\n"
"%(raw_error)s"
msgstr ""
"Не удалось извлечь информацию из-за ошибки:\n"
"%(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:4321
msgid "That video cannot be played. Try using the stream command."
msgstr ""
"Это видео не может быть воспроизведено. Попробуйте использовать команду "
"трансляции."

#. Used by: CommandError
#: musicbot/bot.py:4332
#, python-format
msgid "YouTube search returned no results for:  %(url)s"
msgstr "Поиск YouTube не дал результатов по запросу:  %(url)s"

#. Used by: info
#: musicbot/bot.py:4362
#, python-format
msgid ""
"Processed %(number)d of %(total)d songs in %(time).3f seconds at "
"%(time_per).2f s/song"
msgstr ""
"Обработано %(number)d из %(total)d песен в %(time).3f секунд на "
"%(time_per).2f / песню"

#. Used by: CommandError
#: musicbot/bot.py:4373
#, python-format
msgid ""
"No songs were added, all songs were over max duration (%(max)s seconds)"
msgstr ""
"Не было добавлено треков, все песни были больше длительности (%(max)s "
"секунд)"

#. Used by: noise
#: musicbot/bot.py:4389
msgid "Extracted an entry with 'youtube:playlist' as extractor key"
msgstr "Извлечь запись с помощью клавиши 'youtube:playlist'"

#. Used by: PermissionsError
#: musicbot/bot.py:4401
#, python-format
msgid "Song duration exceeds limit (%(length)s > %(max)s)"
msgstr "Длительность песни превышает предел (%(length)s > %(max)s)"

#. Used by: debug
#: musicbot/bot.py:4419
#, python-format
msgid "Added song(s) at position %s"
msgstr "Добавлена песня(и) на позиции %s"

#. Used by: warning
#: musicbot/bot.py:4456
#, python-format
msgid "Cannot estimate time until playing for position: %d"
msgstr "Не удается оценить время до игры за позицию: %d"

#. Used by: exception
#: musicbot/bot.py:4517
#, python-format
msgid "Failed to get info from the stream request: %s"
msgstr "Не удалось получить информацию из запроса потока: %s"

#. Used by: CommandError
#: musicbot/bot.py:4526
msgid "Streaming playlists is not yet supported."
msgstr "Потоковые плейлисты еще не поддерживаются."

#. Used by: PermissionsError
#: musicbot/bot.py:4595
#, python-format
msgid "You have reached your playlist item limit (%(max)s)"
msgstr "Вы достигли предела в плейлисте (%(max)s)"

#. Used by: CommandError
#: musicbot/bot.py:4607
msgid ""
"Please specify a search query.  Use `help search` for more information."
msgstr ""
"Пожалуйста, укажите поисковый запрос. Используйте `help search` для "
"получения дополнительной информации."

#. Used by: CommandError
#: musicbot/bot.py:4643
#, python-format
msgid "You cannot search for more than %(max)s videos"
msgstr "Вы не можете искать более чем %(max)s видео"

#. Used by: debug
#: musicbot/bot.py:4968
#, python-format
msgid "Waiting for summon lock: %s"
msgstr "Ожидание вызова: %s"

#. Used by: debug
#: musicbot/bot.py:4971
#, python-format
msgid "Summon lock acquired for: %s"
msgstr "Призвать замок для: %s"

#. Used by: CommandError
#: musicbot/bot.py:4975
msgid "You are not connected to voice. Try joining a voice channel!"
msgstr ""
"Вы не подключены к голосу. Попробуйте подключиться к голосовому каналу!"

#. Used by: info
#: musicbot/bot.py:5000
#, python-format
msgid "Joining %(guild)s/%(channel)s"
msgstr "Присоединение к %(guild)s/%(channel)s"

#. Used by: CommandError
#: musicbot/bot.py:5062
msgid "MusicBot cannot follow a user that is not a member of the server."
msgstr ""
"MusicBot не может следить за пользователем, не являющимся членом сервера."

#. Used by: CommandError
#: musicbot/bot.py:5090
msgid "Player is not playing."
msgstr "Плеер не играет."

#. Used by: CommandError
#: musicbot/bot.py:5215
msgid "Nothing in the queue to remove!"
msgstr "Нечего удалять в очереди!"

#. Used by: CommandError
#: musicbot/bot.py:5236
#, python-format
msgid "Nothing found in the queue from user `%(user)s`"
msgstr "В очереди у пользователя `%(user)s ничего не найдено"

#. Used by: PermissionsError
#: musicbot/bot.py:5241 musicbot/bot.py:5277
msgid ""
"You do not have the permission to remove that entry from the queue.\n"
"You must be the one who queued it or have instant skip permissions."
msgstr ""
"У вас недостаточно прав для удаления этой записи из очереди.\n"
"Вы должны быть тот, кто поставил его в очередь или имеет мгновенные пропуска."

#. Used by: CommandError
#: musicbot/bot.py:5252 musicbot/bot.py:5257
msgid "Invalid entry number. Use the queue command to find queue positions."
msgstr ""
"Неверный номер записи. Используйте команду очереди для поиска позиций."

#. Used by: CommandError
#: musicbot/bot.py:5308
msgid "Can't skip! The player is not playing!"
msgstr "Нельзя пропустить! Игрок не играет!"

#. Used by: PermissionsError
#: musicbot/bot.py:5360
msgid "You do not have permission to force skip a looped song."
msgstr ""
"У вас недостаточно прав для принудительного пропуска циклической песни."

#. Used by: PermissionsError
#: musicbot/bot.py:5380
msgid "You do not have permission to force skip."
msgstr "У вас нет разрешения на принудительный пропуск."

#. Used by: PermissionsError
#: musicbot/bot.py:5417 musicbot/bot.py:5450
msgid "You do not have permission to skip a looped song."
msgstr "У вас нет разрешения на пропуск зацикливаемой песни."

#. Used by: CommandError
#: musicbot/bot.py:5500
#, python-format
msgid "`%(new_volume)s` is not a valid number"
msgstr "`%(new_volume)s` не является допустимым числом"

#. Used by: CommandError
#: musicbot/bot.py:5541
#, python-format
msgid ""
"Unreasonable volume change provided: %(old_volume)s%(adjustment)s is %(new_volume)s.\n"
"Volume can only be set from 1 to 100."
msgstr ""
"Неприемлемое изменение объема предусматривается: %(old_volume)s%(adjustment)s является %(new_volume)s.\n"
"Том может быть установлен только от 1 до 100."

#. Used by: CommandError
#: musicbot/bot.py:5551
#, python-format
msgid ""
"Unreasonable volume provided: %(volume)s. Provide a value between 1 and 100."
msgstr "Неприемлемый объём: %(volume)s. Предоставьте значение от 1 до 100."

#. Used by: CommandError
#: musicbot/bot.py:5575
msgid ""
"No track is playing, cannot set speed.\n"
"Use the config command to set a default playback speed."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5583
msgid "Speed cannot be applied to streamed media."
msgstr "Скорость не может быть применена к потоковым носителям."

#. Used by: CommandError
#: musicbot/bot.py:5588
msgid "You must provide a speed to set."
msgstr "Вы должны предоставить скорость для установки."

#. Used by: CommandError
#: musicbot/bot.py:5597
msgid "The speed you provided is invalid. Use a number between 0.5 and 100."
msgstr ""
"Предоставленная вами скорость является недопустимой. Используйте число в "
"диапазоне от 0.5 до 100."

#. Used by: CommandError
#: musicbot/bot.py:5656 musicbot/bot.py:5772 musicbot/bot.py:6704
#, python-format
msgid "Invalid option for command: `%(option)s`"
msgstr "Недопустимый параметр для команды: `%(option)s`"

#. Used by: CommandError
#: musicbot/bot.py:5670
#, python-format
msgid ""
"Failed to save aliases due to error:\n"
"`%(raw_error)s`"
msgstr ""
"Не удалось сохранить псевдонимы из-за ошибки:\n"
"`%(raw_error)s`"

#. Used by: CommandError
#: musicbot/bot.py:5677
msgid "You must supply an alias and a command to alias"
msgstr "Вы должны указать псевдоним и команду для псевдонима"

#. Used by: CommandError
#: musicbot/bot.py:5692
msgid "You must supply an alias name to remove."
msgstr "Вы должны указать имя псевдонима для удаления."

#. Used by: CommandError
#: musicbot/bot.py:5697
#, python-format
msgid "The alias `%(alias)s` does not exist."
msgstr "Псевдоним `%(alias)s` не существует."

#. Used by: CommandError
#: musicbot/bot.py:5755
msgid "Config cannot use channel and user mentions at the same time."
msgstr ""
"Конфигурация не может использовать канал и упоминания пользователя "
"одновременно."

#. Used by: CommandError
#: musicbot/bot.py:5853
#, python-format
msgid ""
"Unable to reload Config due to the following error:\n"
"%(raw_error)s"
msgstr ""
"Не удалось перезагрузить конфигурацию из-за следующей ошибки:\n"
"%(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:5871
msgid ""
"Could not resolve section name from option name. Please provide a valid "
"section and option name."
msgstr ""
"Не удалось определить название секции с названием опции. Пожалуйста, укажите"
" корректный раздел и название опции."

#. Used by: CommandError
#: musicbot/bot.py:5875
msgid "The option given is ambiguous, please provide a section name."
msgstr "Указанная опция является неоднозначной, укажите название раздела."

#. Used by: CommandError
#: musicbot/bot.py:5881
msgid "You must provide a section name and option name for this command."
msgstr ""
"Вы должны указать название раздела и название параметра для этой команды."

#. Used by: CommandError
#: musicbot/bot.py:5897
#, python-format
msgid ""
"The section `%(section)s` is not available.\n"
"The available sections are:  %(sections)s"
msgstr ""
"Раздел `%(section)s` недоступен.\n"
"Доступные разделы:  %(sections)s"

#. Used by: CommandError
#: musicbot/bot.py:5905
#, python-format
msgid "The option `%(option)s` is not available."
msgstr "Опция `%(option)s` недоступна."

#. Used by: CommandError
#: musicbot/bot.py:5933
#, python-format
msgid "Option `%(option)s` is not editable. Cannot save to disk."
msgstr "Параметр `%(option)s` не редактируется. Невозможно сохранить на диск."

#. Used by: CommandError
#: musicbot/bot.py:5942
#, python-format
msgid "Failed to save the option:  `%(option)s`"
msgstr "Не удалось сохранить опцию: `%(option)s`"

#. Used by: CommandError
#: musicbot/bot.py:5957
#, python-format
msgid "Option `%(option)s` is not editable, value cannot be displayed."
msgstr ""
"Параметр `%(option)s` не может быть отредактирован, значение не "
"отображается."

#. Used by: CommandError
#: musicbot/bot.py:5987
#, python-format
msgid "Option `%(option)s` is not editable. Cannot update setting."
msgstr "Параметр `%(option)s` не редактируется. Не удается обновить параметр."

#. Used by: CommandError
#: musicbot/bot.py:5993 musicbot/bot.py:6917
msgid "You must provide a section, option, and value for this sub command."
msgstr "Вы должны указать раздел, параметр и значение для этой подкоманды."

#. Used by: debug
#: musicbot/bot.py:5997
#, python-format
msgid "Doing set with on %(config)s == %(value)s"
msgstr "Выполнение установлено с помощью %(config)s == %(value)s"

#. Used by: CommandError
#: musicbot/bot.py:6004
#, python-format
msgid "Option `%(option)s` was not updated!"
msgstr "Опция `%(option)s` не была обновлена!"

#. Used by: CommandError
#: musicbot/bot.py:6020
#, python-format
msgid "Option `%(option)s` is not editable. Cannot reset to default."
msgstr ""
"Параметр `%(option)s` не является редактируемым. Невозможно сбросить к "
"значению по умолчанию."

#. Used by: debug
#: musicbot/bot.py:6032
#, python-format
msgid "Resetting %(config)s to default %(value)s"
msgstr "Сброс %(config)s на стандартный %(value)s"

#. Used by: CommandError
#: musicbot/bot.py:6039
#, python-format
msgid "Option `%(option)s` was not reset to default!"
msgstr "Параметр `%(option)s` не был сброшен до значения по умолчанию!"

#. Used by: CommandError
#: musicbot/bot.py:6072
msgid "The option command is deprecated, use the config command instead."
msgstr "Команда опции является устаревшим, используйте команду config."

#. Used by: CommandError
#: musicbot/bot.py:6092
msgid "Invalid option specified, use: info, update, or clear"
msgstr ""
"Указан неверный параметр, используйте информацию: info, update, or clear"

#. Used by: CommandError
#: musicbot/bot.py:6149
msgid "**Failed** to delete cache, check logs for more info..."
msgstr ""
"**Не удалось** удалить кэш, проверьте журналы для получения дополнительной "
"информации..."

#. Used by: CommandError
#: musicbot/bot.py:6184
msgid "Queue page argument must be a whole number."
msgstr "Аргумент очереди страницы должен быть целым числом."

#. Used by: CommandError
#: musicbot/bot.py:6191
msgid "There are no songs queued! Queue something with a play command."
msgstr ""
"Нет песен в очереди! Очередь что-то с помощью команды воспроизведения."

#. Used by: CommandError
#: musicbot/bot.py:6198
#, python-format
msgid ""
"Requested page number is out of bounds.\n"
"There are **%(total)s** pages."
msgstr ""

#. Used by: debug
#: musicbot/bot.py:6241
msgid "Skipped the current playlist entry."
msgstr "Текущий элемент плейлиста пропущен."

#. Used by: debug
#: musicbot/bot.py:6284
msgid "Not enough entries to paginate the queue."
msgstr "Недостаточно записей для создания нужной очереди."

#. Used by: warning
#: musicbot/bot.py:6288
msgid "Could not post queue message, no message to add reactions to."
msgstr ""
"Не удалось отправить сообщение в очередь. Нет сообщений для добавления "
"реакций."

#. Used by: CommandError
#: musicbot/bot.py:6290
msgid ""
"Try that again. MusicBot couldn't make or get a reference to the queue message.\n"
"If the issue persists, file a bug report."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:6400
msgid "Cannot use purge on private DM channel."
msgstr "Нельзя использовать очистку в приватном ЛС канале."

#. Used by: CommandError
#: musicbot/bot.py:6432
msgid "The given URL was not a valid URL."
msgstr "Указанный URL не является допустимым URL."

#. Used by: CommandError
#: musicbot/bot.py:6442
#, python-format
msgid ""
"Could not extract info from input url\n"
"%(raw_error)s\n"
msgstr ""
"Не удалось извлечь информацию из входного url\n"
"%(raw_error)s\n"

#. Used by: CommandError
#: musicbot/bot.py:6447
msgid "This does not seem to be a playlist."
msgstr "Похоже, что это не плейлист."

#. Used by: CommandError
#: musicbot/bot.py:6610
msgid ""
"Invalid user ID or server nickname, please double-check the ID and try "
"again."
msgstr ""
"Неверный ID пользователя или имя сервера, проверьте ID и повторите попытку."

#. Used by: CommandError
#: musicbot/bot.py:6617
msgid "Could not determine the discord User.  Try again."
msgstr "Не удалось определить пользователя discord. Попробуйте еще раз."

#. Used by: CommandError
#: musicbot/bot.py:6688
msgid "Permissions cannot use channel and user mentions at the same time."
msgstr ""
"Права доступа не могут использовать каналы и упоминания пользователей "
"одновременно."

#. Used by: CommandError
#: musicbot/bot.py:6723
#, python-format
msgid ""
"Unable to reload Permissions due to an error:\n"
"%(raw_error)s"
msgstr ""
"Не удается перезагрузить разрешения из-за ошибки:\n"
"%(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:6760
msgid "You must provide a group or option name for this command."
msgstr "Вы должны указать название группы или опции для этой команды."

#. Used by: CommandError
#: musicbot/bot.py:6764
msgid "You must provide a group, option, and value to set for this command."
msgstr "Вы должны указать группу, опцию и значение для этой команды."

#. Used by: CommandError
#: musicbot/bot.py:6778
#, python-format
msgid "The %(option)s sub-command requires a group and permission name."
msgstr "Субкоманда %(option)s требует имя группы и прав доступа."

#. Used by: CommandError
#: musicbot/bot.py:6790
#, python-format
msgid ""
"The group `%(group)s` is not available.\n"
"The available groups are:  %(sections)s"
msgstr ""
"Группа `%(group)s` недоступна.\n"
"Доступные группы:  %(sections)s"

#. Used by: CommandError
#: musicbot/bot.py:6801
#, python-format
msgid "The permission `%(option)s` is not available."
msgstr "Разрешение `%(option)s` недоступно."

#. Used by: CommandError
#: musicbot/bot.py:6837
#, python-format
msgid "Cannot add group `%(group)s` it already exists."
msgstr "Невозможно добавить группу `%(group)s`, она уже существует."

#. Used by: CommandError
#: musicbot/bot.py:6855
msgid "Cannot remove built-in group."
msgstr "Невозможно удалить встроенную группу."

#. Used by: CommandError
#: musicbot/bot.py:6873 musicbot/bot.py:6912
msgid "The owner group is not editable."
msgstr "Группа владельцев не редактируется."

#. Used by: CommandError
#: musicbot/bot.py:6881
#, python-format
msgid "Failed to save the group:  `%(group)s`"
msgstr "Не удалось сохранить группу: `%(group)s`"

#. Used by: debug
#: musicbot/bot.py:6921
#, python-format
msgid "Doing set on %(option)s with value: %(value)s"
msgstr "Выполнение установлено на %(option)s со значением: %(value)s"

#. Used by: CommandError
#: musicbot/bot.py:6928
#, python-format
msgid "Permission `%(option)s` was not updated!"
msgstr "Разрешение `%(option)s` не было обновлено!"

#. Used by: CommandError
#: musicbot/bot.py:6969
msgid ""
"Failed to change username. Did you change names too many times?\n"
"Remember name changes are limited to twice per hour.\n"
msgstr ""
"Не удалось изменить имя пользователя. Вы изменили имена слишком много раз?\n"
"Запомнить, что изменения имени ограничены дважды в час.\n"

#. Used by: CommandError
#: musicbot/bot.py:6975
#, python-format
msgid ""
"Failed to change username due to error:  \n"
"%(raw_error)s"
msgstr ""
"Не удалось изменить имя пользователя из-за ошибки:  \n"
"%(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:6997
msgid "Unable to change nickname: no permission."
msgstr "Невозможно изменить никнейм: нет разрешения."

#. Used by: CommandError
#: musicbot/bot.py:7005
#, python-format
msgid ""
"Failed to set nickname due to error:  \n"
"%(raw_error)s"
msgstr ""
"Не удалось задать псевдоним из-за ошибки:  \n"
"%(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:7045
msgid "Custom emoji must be from this server to use as a prefix."
msgstr ""
"Пользовательские эмодзи должны быть с этого сервера, чтобы использовать в "
"качестве префикса."

#. Used by: CommandError
#: musicbot/bot.py:7062
msgid ""
"Prefix per server is not enabled!\n"
"Use the config command to update the prefix instead."
msgstr ""
"Префикс на сервер не включен!\n"
"Используйте команду конфигурации для обновления префикса."

#. Used by: CommandError
#: musicbot/bot.py:7092
msgid "This command can only be used in guilds."
msgstr "Эта команда может быть использована только в гильдиях."

#. Used by: CommandError
#: musicbot/bot.py:7097
msgid "Invalid sub-command given. Use the help command for more information."
msgstr ""
"Неверная субкоманда. Используйте команду справки для получения "
"дополнительной информации."

#. Used by: CommandError
#: musicbot/bot.py:7118
#, python-format
msgid "Cannot set language to `%(locale)s` it is not available."
msgstr "Не удается установить язык в `%(locale)s`, он недоступен."

#. Used by: CommandError
#: musicbot/bot.py:7163
msgid "You must provide a URL or attach a file."
msgstr "Вы должны указать URL или прикрепить файл."

#. Used by: CommandError
#: musicbot/bot.py:7173
#, python-format
msgid ""
"Unable to change avatar due to error:  \n"
"%(raw_error)s"
msgstr ""
"Невозможно изменить аватар из-за ошибки:  \n"
"%(raw_error)s"

#. Used by: warning
#: musicbot/bot.py:7198
#, python-format
msgid "MusicBot found a %s with no guild!  This could be a problem."
msgstr "MusicBot обнаружил %s без гильдии! Это может быть проблемой."

#. Used by: CommandError
#: musicbot/bot.py:7210
#, python-format
msgid "Not currently connected to server `%(guild)s`"
msgstr "Сейчас не подключен к серверу`%(guild)s`"

#. Used by: CommandError
#: musicbot/bot.py:7251
msgid ""
"Invalid option given, use one of:  soft, full, upgrade, uppip, or upgit"
msgstr ""
"Недопустимый параметр, используйте один из: мягкий, полный, обновление, "
"uppip, или upgit"

#. Used by: CommandError
#: musicbot/bot.py:7360
msgid "You must provide an ID or name."
msgstr "Вы должны указать ID или имя."

#. Used by: CommandError
#: musicbot/bot.py:7371
#, python-format
msgid "No guild was found with the ID or name `%(input)s`"
msgstr "Не найдено ни одной гильдии с ID или именем `%(input)s`"

#. Used by: critical
#: musicbot/bot.py:7428
#, python-format
msgid "Activating debug breakpoint ID: %(uuid)s"
msgstr "Активация точки останова ID: %(uuid)s"

#. Used by: CommandError
#: musicbot/bot.py:7468
msgid "Could not import `objgraph`, is it installed?"
msgstr "Не удалось импортировать `objgraph`, он установлен?"

#. Used by: debug
#: musicbot/bot.py:7544
msgid "Debug code ran with eval()."
msgstr "Код отладки запускался с помощью eval()."

#. Used by: debug
#: musicbot/bot.py:7554
msgid "Debug code ran with exec()."
msgstr "Код отладки запускался с exec()."

#. Used by: exception
#: musicbot/bot.py:7557
msgid "Debug code failed to execute."
msgstr "Не удалось выполнить код отладки."

#. Used by: CommandError
#: musicbot/bot.py:7559
#, python-format
msgid ""
"Failed to execute debug code:\n"
"%(py_code)s\n"
"Exception: ```\n"
"%(ex_name)s:\n"
"%(ex_text)s```"
msgstr ""
"Не удалось выполнить отладочный код:\n"
"%(py_code)s\n"
"Exception: ```\n"
"%(ex_name)s:\n"
"%(ex_text)s```"

#. Used by: CommandError
#: musicbot/bot.py:7594 musicbot/bot.py:7655
#, python-format
msgid "Sub-command must be one of: %(options)s"
msgstr "Подкоманда должна быть одной из %(options)s"

#. Used by: CommandError
#: musicbot/bot.py:7694
msgid "Could not locate git executable."
msgstr "Не удалось найти исполняемый файл git."

#. Used by: exception
#: musicbot/bot.py:7738
msgid "Failed while checking for updates via git command."
msgstr "Не удалось проверить наличие обновлений по команде git."

#. Used by: debug
#: musicbot/bot.py:7767
msgid "Package missing meta in pip report."
msgstr "Пакет отсутствует в отчете pip."

#. Used by: exception
#: musicbot/bot.py:7781
msgid "Failed to get pip update status due to some error."
msgstr "Не удалось получить статус обновления pip из-за некоторой ошибки."

#. Used by: debug
#: musicbot/bot.py:7842
msgid "Got a strange voice client entry."
msgstr "Получена запись о странном голосовом клиенте."

#. Used by: CommandError
#: musicbot/bot.py:7952
msgid "Cookies already enabled."
msgstr "Cookies уже включены."

#. Used by: CommandError
#: musicbot/bot.py:7959
msgid "Cookies must be uploaded to be enabled. (Missing cookies file.)"
msgstr "Cookies должны быть загружены для включения. (issing cookies файл.)"

#. Used by: CommandError
#: musicbot/bot.py:7972
#, python-format
msgid "Could not enable cookies due to error:  %(raw_error)s"
msgstr "Не удалось включить куки из-за ошибки:  %(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:7986
#, python-format
msgid ""
"Could not rename cookies file due to error:  %(raw_error)s\n"
"Cookies temporarily disabled and will be re-enabled on next restart."
msgstr ""
"Не удалось переименовать файл cookies из-за ошибки:  %(raw_error)s\n"
"Cookies временно отключены и будут повторно включены при следующем перезапуске."

#. Used by: CommandError
#: musicbot/bot.py:7995
msgid ""
"No attached uploads were found, try again while uploading a cookie file."
msgstr ""
"Не найдено приложенных загрузок, попробуйте еще раз при загрузке файла "
"cookie."

#. Used by: warning
#: musicbot/bot.py:8004
#, python-format
msgid "Could not remove old, disabled cookies file:  %(raw_error)s"
msgstr "Не удалось удалить старый, отключен файл cookie:  %(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:8013
#, python-format
msgid "Error downloading the cookies file from discord:  %(raw_error)s"
msgstr "Ошибка при загрузке файла cookie с дискода:  %(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:8018
#, python-format
msgid "Could not save cookies to disk:  %(raw_error)s"
msgstr "Не удалось сохранить куки на диске:  %(raw_error)s"

#. Used by: debug
#: musicbot/bot.py:8036
#, python-format
msgid "Got a message with no channel, somehow:  %s"
msgstr "Получено сообщение без канала, как-то  %s"

#. Used by: warning
#: musicbot/bot.py:8064
#, python-format
msgid "Ignoring command from myself (%s)"
msgstr "Игнорирование команды от себя (%s)"

#. Used by: warning
#: musicbot/bot.py:8072
#, python-format
msgid "Ignoring command from other bot (%s)"
msgstr "Игнорирование команды от другого бота (%s)"

#. Used by: warning
#: musicbot/bot.py:8080
#, python-format
msgid "Ignoring command from channel of type:  %s"
msgstr "Игнорирование команды из канала типа:  %s"

#. Used by: warning
#: musicbot/bot.py:8175
#, python-format
msgid "User in block list: %(id)s/%(name)s  tried command: %(command)s"
msgstr ""
"Пользователь в блочном списке: %(id)s/%(name)s  попробовала команду: "
"%(command)s"

#. Used by: info
#: musicbot/bot.py:8182
#, python-format
msgid "Message from %(id)s/%(name)s: %(message)s"
msgstr "Сообщение от %(id)s/%(name)s: %(message)s"

#. Used by: PermissionsError
#: musicbot/bot.py:8217
#, python-format
msgid "This command is not allowed for your permissions group:  %(group)s"
msgstr "Эта команда не разрешена для вашей группы прав:  %(group)s"

#. Used by: CommandError
#: musicbot/bot.py:8252
msgid "This command requires you to be in a Voice channel."
msgstr "Эта команда требует, чтобы вы были в голосовом канале."

#. Used by: debug
#: musicbot/bot.py:8341
#, python-format
msgid "Invalid command usage, missing values for params: %(params)r"
msgstr ""
"Неверное использование команды, отсутствуют значения для параметров: "
"%(params)r"

#. Used by: error
#: musicbot/bot.py:8379
#, python-format
msgid "Error in %(command)s: %(err_name)s: %(err_text)s"
msgstr "Ошибка в %(command)s: %(err_name)s: %(err_text)s"

#. Used by: error
#: musicbot/bot.py:8402
#, python-format
msgid "Exception while handling command: %(command)s"
msgstr "Исключение при обработке команды: %(command)s"

#. Used by: debug
#: musicbot/bot.py:8433
#, python-format
msgid "Cannot generate help for missing command:  %s"
msgstr "Невозможно сгенерировать справку для отсутствующей команды:  %s"

#. Used by: critical
#: musicbot/bot.py:8437
#, python-format
msgid "Missing help data for command:  %s"
msgstr "Отсутствуют вспомогательные данные для команды:  %s"

#. Used by: info
#: musicbot/bot.py:8554
#, python-format
msgid "Leaving voice channel %s in %s due to inactivity."
msgstr "Выход голосового канала %s в %s из-за отсутствия активности."

#. Used by: info
#: musicbot/bot.py:8563
msgid "MusicBot has become connected."
msgstr "Музыкабот подключен."

#. Used by: info
#: musicbot/bot.py:8567
msgid "MusicBot has become disconnected."
msgstr "Музыкабот был разорван."

#. Used by: everything
#: musicbot/bot.py:8572
#, python-format
msgid "Got a Socket Event:  %s"
msgstr "Получено событие сокета:  %s"

#. Used by: warning
#: musicbot/bot.py:8588
msgid "VoiceState updated before on_ready finished"
msgstr "VoiceState обновляется до окончания on_ready"

#. Used by: info
#: musicbot/bot.py:8601
#, python-format
msgid "Ignoring %s in %s as it is a bound voice channel."
msgstr "Игнорирование %s в %s , как это связанный голосовой канал."

#. Used by: info
#: musicbot/bot.py:8610
#, python-format
msgid "%s has been detected as empty. Handling timeouts."
msgstr "%s был обнаружен как пустой. Тайм-аут обработки."

#. Used by: info
#: musicbot/bot.py:8621
#, python-format
msgid "A user joined %s, cancelling timer."
msgstr "Пользователь присоединился к %s, время отмены таймера."

#. Used by: info
#: musicbot/bot.py:8634
#, python-format
msgid ""
"The bot got moved and the voice channel %s is empty. Handling timeouts."
msgstr "Бот перемещен, голосовой канал %s пуст. Тайм-аут обработки."

#. Used by: info
#: musicbot/bot.py:8643
#, python-format
msgid "The bot got moved and the voice channel %s is not empty."
msgstr "Бот был перемещен и голосовой канал %s не пуст."

#. Used by: debug
#: musicbot/bot.py:8692
#, python-format
msgid "No longer following user %s"
msgstr "Больше не следует за пользователем %s"

#. Used by: debug
#: musicbot/bot.py:8714
#, python-format
msgid "Following user `%(user)s` to channel:  %(channel)s"
msgstr "Следовать за пользователем `%(user)s` на канал:  %(channel)s"

#. Used by: debug
#: musicbot/bot.py:8734
msgid "VoiceState disconnect before.channel is None."
msgstr "VoiceState отключает before.channel не подключен."

#. Used by: info
#: musicbot/bot.py:8761
#, python-format
msgid ""
"Disconnected from voice by Discord API in: %(guild)s/%(channel)s (Code: "
"%(code)s) [S:%(state)s]"
msgstr ""
"Отключено от голоса Discord API в: %(guild)s/%(channel)s (Код: %(code)s) "
"[S:%(state)s]"

#. Used by: error
#: musicbot/bot.py:8783
#, python-format
msgid "Cannot use auto-join channel with type: %(type)s  in guild:  %(guild)s"
msgstr ""
"Невозможно использовать автовход с типом канала: %(type)s  в гильдии:  "
"%(guild)s"

#. Used by: error
#: musicbot/bot.py:8790
#, python-format
msgid "Cannot find the auto-joined channel, was it deleted?  Guild:  %s"
msgstr "Не удается найти канал автоподключения, он был удален? Гильдия:  %s"

#. Used by: info
#: musicbot/bot.py:8796
#, python-format
msgid "Reconnecting to auto-joined guild on channel:  %s"
msgstr ""
"Повторное подключение к автоматически подключенной гильдии на канале:  %s"

#. Used by: warning
#: musicbot/bot.py:8809
#, python-format
msgid "Cannot auto join channel:  %s"
msgstr "Невозможно автоматически присоединиться к каналу:  %s"

#. Used by: info
#: musicbot/bot.py:8825
#, python-format
msgid "Bot has been added to guild: %s"
msgstr "Бот был добавлен в гильдию: %s"

#. Used by: info
#: musicbot/bot.py:8837
#, python-format
msgid "Left guild '%s' due to bot owner not found."
msgstr "Левая гильдия '%s' из-за не найден владелец бота."

#. Used by: debug
#: musicbot/bot.py:8851
#, python-format
msgid "Creating data folder for guild %s"
msgstr "Создание папки данных для гильдии %s"

#. Used by: info
#: musicbot/bot.py:8859
#, python-format
msgid "Bot has been removed from guild: %s"
msgstr "Бот был удален из гильдии: %s"

#. Used by: debug
#: musicbot/bot.py:8860
msgid "Updated guild list:"
msgstr "Обновленный список гильдий:"

#. Used by: info
#: musicbot/bot.py:8875
#, python-format
msgid "Guild \"%s\" has become available."
msgstr "Гильдия \"%s\" стала доступна."

#. Used by: debug
#: musicbot/bot.py:8881
#, python-format
msgid "Resuming player in \"%s\" due to availability."
msgstr "Возобновление доступа игрока в \"%s\" из-за доступности."

#. Used by: info
#: musicbot/bot.py:8898
#, python-format
msgid "Guild \"%s\" has become unavailable."
msgstr "Гильдия \"%s\" недоступна."

#. Used by: debug
#: musicbot/bot.py:8904
#, python-format
msgid "Pausing player in \"%s\" due to unavailability."
msgstr "Пауза игрока в \"%s\" из-за недоступности."

#. Used by: info
#: musicbot/bot.py:8920
#, python-format
msgid "Guild update for:  %s"
msgstr "Обновление гильдии для:  %s"

#. Used by: everything
#: musicbot/bot.py:8926
#, python-format
msgid "Guild attribute %(attr)s is now: %(new)s  -- Was: %(old)s"
msgstr "Атрибут гильдии %(attr)s сейчас: %(new)s  -- Was: %(old)s"

#. Used by: info
#: musicbot/bot.py:8977
#, python-format
msgid "Channel update for:  %(channel)s  --  %(changes)s"
msgstr "Обновление канала для:  %(channel)s  --  %(changes)s"

#. Used by: warning
#: musicbot/config.py:86
#, python-format
msgid "Creating %s"
msgstr "Создание %s"

#. Used by: info
#: musicbot/config.py:107
#, python-format
msgid "Loading config from:  %s"
msgstr "Загрузка конфигурации из:  %s"

#. Used by: HelpfulError
#: musicbot/config.py:1128
#, python-format
msgid ""
"Error while reading config.\n"
"\n"
"Problem:\n"
"  One or more required config option sections are missing.\n"
"  The missing sections are:\n"
"  %(sections)s\n"
"\n"
"Solution:\n"
"  Repair your config options file.\n"
"  Each [Section] must appear only once, with no other text on the same line.\n"
"  Each section must have at least one option.\n"
"  Use the example options as a template or copy it from the repository."
msgstr ""

#. Used by: warning
#: musicbot/config.py:1158
#, python-format
msgid ""
"Cannot store more than %s log files. Option LogsMaxKept will be limited "
"instead."
msgstr ""
"Невозможно хранить больше файлов журнала %s . Опция LogsMaxKept будет "
"ограничена."

#. Used by: warning
#: musicbot/config.py:1166
msgid ""
"Config option LogsDateFormat is empty and this will break log file rotation."
" Using default instead."
msgstr ""
"Параметр LogsDateFormat пуст и это нарушит поворот файла журнала. Вместо "
"него будет использоваться значение по умолчанию."

#. Used by: HelpfulError
#: musicbot/config.py:1177
msgid ""
"Error while validating config options.\n"
"\n"
"Problem:\n"
"  Config option AudioCachePath is not a directory.\n"
"\n"
"Solution:\n"
"  Make sure the path you configured is a path to a folder / directory."
msgstr ""

#. Used by: exception
#: musicbot/config.py:1194
msgid "An exception was thrown while validating AudioCachePath."
msgstr "Исключение было вызвано при проверке AudioCachePath."

#. Used by: HelpfulError
#: musicbot/config.py:1198
#, python-format
msgid ""
"Error while validating config options.\n"
"\n"
"Problem:\n"
"  AudioCachePath config option could not be set due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Double check the setting is a valid, accessible directory path."
msgstr ""
"Ошибка при проверке параметров конфигурации.\n"
"\n"
"Проблема:\n"
"  Опция конфигурации AudioCachePath не может быть установлена из-за ошибки:\n"
"  %(raw_error)s\n"
"\n"
"Решение:\n"
"  Двойная проверка правильности, доступный путь к каталогу."

#. Used by: info
#: musicbot/config.py:1210
#, python-format
msgid "Audio Cache will be stored in:  %s"
msgstr "Кэш аудио будет храниться в:  %s"

#. Used by: HelpfulError
#: musicbot/config.py:1221
#, python-format
msgid ""
"Error while reading config options.\n"
"\n"
"Problem:\n"
"  No bot Token was specified in the config options or environment.\n"
"\n"
"Solution:\n"
"  Set the Token config option or set environment variable %(env_var)s with an App token."
msgstr ""

#. Used by: warning
#: musicbot/config.py:1242
msgid ""
"StatusMessage config option is too long, it will be limited to 128 "
"characters."
msgstr ""
"Опция StatusMessage слишком длинная, она будет ограничена 128 символов."

#. Used by: warning
#: musicbot/config.py:1251
#, python-format
msgid ""
"The default playback speed must be between 0.5 and 100.0. The option value "
"of %.3f will be limited instead."
msgstr ""
"Скорость воспроизведения по умолчанию должна быть между 0.5 и 100.0. Вместо "
"этого значение параметра %.3f будет ограничено."

#. Used by: debug
#: musicbot/config.py:1268
msgid "Validating options with service data..."
msgstr "Проверка параметров с данными сервиса..."

#. Used by: debug
#: musicbot/config.py:1274
msgid "Acquired owner ID via API"
msgstr "Приобретенный ID владельца через API"

#. Used by: HelpfulError
#: musicbot/config.py:1278
msgid ""
"Error while fetching 'OwnerID' automatically.\n"
"\n"
"Problem:\n"
"  Discord App info is not available.\n"
"  This could be a temporary API outage or a bug.\n"
"\n"
"Solution:\n"
"  Manually set the 'OwnerID' config option or try again later."
msgstr ""

#. Used by: critical
#: musicbot/config.py:1290
msgid "MusicBot does not have a user instance, cannot proceed."
msgstr "У MusicBot нет экземпляра пользователя, невозможно продолжить."

#. Used by: HelpfulError
#: musicbot/config.py:1296
msgid ""
"Error validating config options.\n"
"\n"
"Problem:\n"
"  The 'OwnerID' config is the same as your Bot / App ID.\n"
"\n"
"Solution:\n"
"  Do not use the Bot or App ID in the 'OwnerID' field."
msgstr ""

#. Used by: warning
#: musicbot/config.py:1320
msgid "Config options file not found. Checking for alternatives..."
msgstr "Файл параметров конфигурации не найден. Проверка альтернативы..."

#. Used by: warning
#: musicbot/config.py:1333
#, python-format
msgid ""
"Renaming %(ini_file)s to %(option_file)s, you should probably turn file "
"extensions on."
msgstr ""
"Переименование %(ini_file)s на %(option_file)s, скорее всего, вам следует "
"включить расширения."

#. Used by: warning
#: musicbot/config.py:1341
#, python-format
msgid "Copying existing example options file:  %(example_file)s"
msgstr "Копирование существующего файла параметров примера:  %(example_file)s"

#. Used by: exception
#: musicbot/config.py:1355
msgid "Something went wrong while trying to find a config option file."
msgstr "Что-то пошло не так при попытке найти файл конфигурации."

#. Used by: HelpfulError
#: musicbot/config.py:1359
#, python-format
msgid ""
"Error locating config.\n"
"\n"
"Problem:\n"
"  Could not find or create a config file due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Verify the config folder and files exist and can be read by MusicBot."
msgstr ""
"Ошибка поиска конфигурации.\n"
"\n"
"Проблема:\n"
"  Не удалось найти или создать файл конфигурации из-за ошибки:\n"
"  %(raw_error)s\n"
"\n"
"Решение:\n"
"  Проверьте папку конфигурации и файлы существуют и могут быть прочитаны MusicBot."

#. Used by: HelpfulError
#: musicbot/config.py:1377
#, python-format
msgid ""
"Error loading config.\n"
"\n"
"Problem:\n"
"  MusicBot could not read config file due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Make sure the file is accessible and error free.\n"
"  Copy the example file from the repo if all else fails."
msgstr ""
"Ошибка загрузки конфигурации.\n"
"\n"
"Проблема:\n"
"  MusicBot не смог прочитать конфигурационный файл из-за ошибки:\n"
"  %(raw_error)s\n"
"\n"
"Решение:\n"
"  Убедитесь, что файл доступен и ошибки бесплатны.\n"
"  Скопируйте файл примера из репозитория, если все остальное не удалось."

#. Used by: critical
#: musicbot/config.py:1401
msgid "Dev Bug! Config option has getter that is not available."
msgstr "Dev Bug! Параметр конфигурации имеет getter, который не доступен."

#. Used by: error
#: musicbot/config.py:1406
msgid ""
"Dev Bug! Config option has invalid type, getter and default must be the same"
" type."
msgstr ""
"Dev Bug! Параметр конфигурации имеет недопустимый тип, getter и по умолчанию"
" должен быть одинаковым."

#. Used by: debug
#: musicbot/config.py:1426
msgid "Option was missing previously."
msgstr "Ранее отсутствовал вариант."

#. Used by: error
#: musicbot/config.py:1441
#, python-format
msgid "Config section not in parsed config! Missing: %s"
msgstr "Раздел конфигурации не в анализируемой конфигурации! Отсутствует: %s"

#. Used by: info
#: musicbot/config.py:1446
#, python-format
msgid "Saved config option: %(config)s  =  %(value)s"
msgstr "Сохраненная конфигурация: %(config)s  =  %(value)s"

#. Used by: exception
#: musicbot/config.py:1459
#, python-format
msgid "Failed to save config:  %s"
msgstr "Не удалось сохранить конфигурацию:  %s"

#. Used by: warning
#: musicbot/config.py:1973
msgid ""
"Option names are not unique between INI sections!  Resolver is disabled."
msgstr "Имена опций не уникальны между INI-разделами! Резольвер отключен."

#. Used by: exception
#: musicbot/config.py:2151 musicbot/permissions.py:909
#, python-format
msgid "Failed to save default INI file at:  %s"
msgstr "Не удалось сохранить INI-файл по умолчанию в:  %s"

#. Used by: HelpfulError
#: musicbot/config.py:2241
#, python-format
msgid ""
"Error loading config value.\n"
"\n"
"Problem:\n"
"  The owner ID in [%(section)s] > %(option)s is not valid.\n"
"\n"
"Solution:\n"
"  Set %(option)s to a numerical ID or set it to `auto` or `0` for automatic owner binding."
msgstr ""
"Ошибка загрузки значения конфигурации.\n"
"\n"
"Проблема:\n"
"  ID владельца в [%(section)s] > %(option)s недопустим.\n"
"\n"
"Решение:\n"
"  Установите %(option)s на числовой ID или установите его в `auto` или `0` для автоматической привязки владельца."

#. Used by: HelpfulError
#: musicbot/config.py:2277
#, python-format
msgid ""
"Error loading config value.\n"
"\n"
"Problem:\n"
"  The config option [%(section)s] > %(option)s is not a valid file location.\n"
"\n"
"Solution:\n"
"  Check the path setting and make sure the file exists and is accessible to MusicBot."
msgstr ""
"Ошибка загрузки значения конфигурации.\n"
"\n"
"Проблема:\n"
"  Параметр конфигурации [%(section)s] > %(option)s не является допустимым местоположением файла.\n"
"\n"
"Решение:\n"
"  Проверьте настройки пути и убедитесь, что файл существует и доступен для MusicBot."

#. Used by: HelpfulError
#: musicbot/config.py:2307
#, python-format
msgid ""
"Error loading config value.\n"
"\n"
"Problem:\n"
"  One of the IDs in option [%(section)s] > %(option)s is invalid.\n"
"\n"
"Solution:\n"
"  Ensure all IDs are numerical, and separated only by spaces or commas."
msgstr ""
"Ошибка загрузки значения конфигурации.\n"
"\n"
"Проблема:\n"
"  Один из идентификаторов в опции [%(section)s] > %(option)s является недопустимым.\n"
"\n"
"Решение:\n"
"  Убедитесь, что все ID числовые и разделены только пробелами или запятыми."

#. Used by: warning
#: musicbot/config.py:2343
#, python-format
msgid ""
"Invalid DebugLevel option \"%(value)s\" given, falling back to level: "
"%(fallback)s"
msgstr ""
"Недопустимый параметр уровня отладки \"%(value)s\" указан, падающий обратно "
"на уровень: %(fallback)s"

#. Used by: warning
#: musicbot/config.py:2364
#, python-format
msgid ""
"Option [%(section)s] > %(option)s has invalid config value '%(value)s' using"
" default instead."
msgstr ""
"Опция [%(section)s] > %(option)s имеет неверное значение конфигурации "
"'%(value)s' вместо значения по умолчанию."

#. Used by: warning
#: musicbot/config.py:2413
#, python-format
msgid ""
"Option [%(section)s] > %(option)s has a value greater than 100 %% "
"(%(value)s) and will be set to %(fallback)s instead."
msgstr ""
"Вариант [%(section)s] > %(option)s имеет значение больше 100 %% (%(value)s) "
"и вместо него будет установлен %(fallback)s."

#. Used by: debug
#: musicbot/config.py:2538
#, python-format
msgid ""
"Renaming INI file entry [%(old_s)s] > %(old_o)s  to  [%(new_s)s] > %(new_o)s"
msgstr ""
"Переименование INI-файла [%(old_s)s] > %(old_o)s  на [%(new_s)s] > %(new_o)s"

#. Used by: debug
#: musicbot/config.py:2609
msgid "Upgrading config file with renamed options..."
msgstr "Обновление конфигурационного файла с переименованными опциями..."

#. Used by: exception
#: musicbot/config.py:2643
msgid "Failed to upgrade config.  You'll need to upgrade it manually."
msgstr "Не удалось обновить конфигурацию. Вам нужно обновить ее вручную."

#. Used by: warning
#: musicbot/config.py:2684
#, python-format
msgid "Block list file not found:  %s"
msgstr "Файл блока списка не найден:  %s"

#. Used by: error
#: musicbot/config.py:2705
#, python-format
msgid "Could not load block list from file:  %s"
msgstr "Не удалось загрузить список блокировок из файла:  %s"

#. Used by: error
#: musicbot/config.py:2743 musicbot/config.py:2776
#, python-format
msgid "Could not update the block list file:  %s"
msgstr "Не удалось обновить файл списка блоков:  %s"

#. Used by: debug
#: musicbot/config.py:2803
#, python-format
msgid "Loaded User Block list with %s entries."
msgstr "Загружен блокированный список пользователей с записями %s."

#. Used by: warning
#: musicbot/config.py:2814
#, python-format
msgid "We found a legacy blacklist file, it will be renamed to:  %s"
msgstr ""
"Мы нашли устаревший файл в черном списке, он будет переименован на:  %s"

#. Used by: debug
#: musicbot/config.py:2860
#, python-format
msgid "Loaded a Song Block list with %s entries."
msgstr "Загружен Блок песни с записями %s."

#. Used by: error
#: musicbot/constructs.py:220
msgid ""
"Cannot load data for guild with ID 0. This is likely a bug in the code!"
msgstr ""
"Не удается загрузить данные для гильдии с ID 0. Вероятно, это ошибка в коде!"

#. Used by: debug
#: musicbot/constructs.py:229
#, python-format
msgid "No file for guild %(id)s/%(name)s"
msgstr "Нет файла для гильдии %(id)s/%(name)s"

#. Used by: debug
#: musicbot/constructs.py:238
#, python-format
msgid "Loading guild data for guild with ID:  %(id)s/%(name)s"
msgstr "Загрузка данных гильдии с ID:  %(id)s/%(name)s"

#. Used by: exception
#: musicbot/constructs.py:245
#, python-format
msgid "An OS error prevented reading guild data file:  %s"
msgstr "Ошибка ОС не удалось прочитать файл данных гильдии:  %s"

#. Used by: info
#: musicbot/constructs.py:256
#, python-format
msgid "Guild %(id)s/%(name)s has custom command prefix: %(prefix)s"
msgstr ""
"У гильдии %(id)s/%(name)s есть пользовательский префикс команд: %(prefix)s"

#. Used by: error
#: musicbot/constructs.py:276
msgid ""
"Cannot save data for guild with ID 0. This is likely a bug in the code!"
msgstr ""
"Невозможно сохранить данные для гильдии с ID 0. Возможно, это ошибка в коде!"

#. Used by: exception
#: musicbot/constructs.py:300
msgid "Could not save guild specific data due to OS Error."
msgstr "Не удалось сохранить данные конкретной гильдии из-за ошибки ОС."

#. Used by: exception
#: musicbot/constructs.py:303
msgid "Failed to serialize guild specific data due to invalid data."
msgstr ""
"Не удалось сериализовать данные для конкретной гильдии из-за некорректных "
"данных."

#. Used by: warning
#: musicbot/downloader.py:129
#, python-format
msgid "Forcing YTDLP to use User Agent:  %s"
msgstr "Принудительное YTDLP использовать User Agent:  %s"

#. Used by: info
#: musicbot/downloader.py:148
#, python-format
msgid "MusicBot will use cookies for yt-dlp from:  %s"
msgstr "Музыкабот будет использовать cookies для yt-dlp от:  %s"

#. Used by: info
#: musicbot/downloader.py:154
msgid "Yt-dlp will use your configured proxy server."
msgstr "Yt-dlp будет использовать настроенный прокси сервер."

#. Used by: ExtractionError
#: musicbot/downloader.py:244
msgid "HEAD seems to have no headers..."
msgstr "HEAD не имеет заголовков..."

#. Used by: warning
#: musicbot/downloader.py:255
msgid "Checking media headers failed due to timeout."
msgstr "Проверка заголовков медиа не выполнена из-за таймаута."

#. Used by: warning
#: musicbot/downloader.py:258
#, python-format
msgid "Failed HEAD request for:  %s"
msgstr "Ошибка запроса HEAD для:  %s"

#. Used by: exception
#: musicbot/downloader.py:259
msgid "HEAD Request exception: "
msgstr "HEAD запрос исключения: "

#. Used by: noise
#: musicbot/downloader.py:327
#, python-format
msgid ""
"Sanitized YTDL Extraction Info (not JSON):\n"
"%s"
msgstr ""
"Санитированная информация о извлечении YTDL (не JSON):\n"
"%s"

#. Used by: noise
#: musicbot/downloader.py:329
#, python-format
msgid "Sanitized YTDL Extraction Info (not JSON):  %s"
msgstr "Ранизированная информация о извлечении YTDL (не JSON):  %s"

#. Used by: ExtractionError
#: musicbot/downloader.py:393
msgid "Song info extraction returned no data."
msgstr "Извлечение информации о треке не дало никаких данных."

#. Used by: noise
#: musicbot/downloader.py:449
#, python-format
msgid "Called extract_info with:  '%(subject)s', %(args)s, %(kws)s"
msgstr "Вызвал extract_info с: '%(subject)s', %(args)s, %(kws)s"

#. Used by: warning
#: musicbot/downloader.py:457
msgid "Cannot run extraction, loop is closed. (This is normal on shutdowns.)"
msgstr ""
"Невозможно запустить распаковку, цикл закрыт. (нормальный при выключении)"

#. Used by: MusicbotException
#: musicbot/downloader.py:459
msgid "Cannot continue extraction, event loop is closed."
msgstr "Невозможно продолжить извлечение. Цикл события закрыт."

#. Used by: ExtractionError
#: musicbot/downloader.py:468
msgid "Spotify URL is invalid or not supported."
msgstr "URL-адрес Spotify недействителен или не поддерживается."

#. Used by: exception
#: musicbot/downloader.py:506
msgid "Download Error with stream URL"
msgstr "Ошибка загрузки с URL потока"

#. Used by: debug
#: musicbot/downloader.py:511
msgid "Assuming content is a direct stream"
msgstr "Предположим, что содержимое является прямым потоком"

#. Used by: ExtractionError
#: musicbot/downloader.py:519
msgid "Cannot stream an invalid URL."
msgstr "Невозможно провести некорректный URL-адрес."

#. Used by: noise
#: musicbot/downloader.py:530
msgid ""
"Caught NoSupportingHandlers, trying again after replacing colon with space."
msgstr ""
"Найдено NoSupportingHandlers, попробуйте снова после замены двоеточия на "
"пространство."

#. Used by: noise
#: musicbot/downloader.py:574
#, python-format
msgid "Called safe_extract_info with:  %(args)s, %(kws)s"
msgstr "Вызвал safe_extract_info с:  %(args)s, %(kws)s"

#. Used by: MusicbotException
#: musicbot/downloader.py:594
msgid "The local media file could not be found."
msgstr "Локальный медиа-файл не найден."

#. Used by: warning
#: musicbot/downloader.py:632
msgid "Missing __input_subject from YtdlpResponseDict"
msgstr "Отсутствует __input_subject из YtdlpResponseDict"

#. Used by: warning
#: musicbot/downloader.py:637
msgid ""
"Entries is not a list in YtdlpResponseDict, set process=True to avoid this."
msgstr ""
"Записи не являются списком в YtdlpResponseDict, задайте process=True, чтобы "
"избежать этого."

#. Used by: noise
#: musicbot/downloader.py:866
#, python-format
msgid "Warning, duration error for: %(url)s"
msgstr "Внимание, ошибка продолжительности для: %(url)s"

#. Used by: debug
#: musicbot/entry.py:46
msgid "module 'pymediainfo' not found, will fall back to ffprobe."
msgstr "модуль 'pymediainfo' не найден, вернется в ffprobe."

#. Used by: debug
#: musicbot/entry.py:159
#, python-format
msgid "Created future for %r"
msgstr "Создано будущее для %r"

#. Used by: everything
#: musicbot/entry.py:171
#, python-format
msgid "Completed futures for %(entry)r with %(callback)r"
msgstr "Завершенные фьючерсы для %(entry)r с %(callback)r"

#. Used by: exception
#: musicbot/entry.py:181
msgid "Unhandled exception in _for_each_future callback."
msgstr "Необработанное исключение в _for_each_future callback."

#. Used by: noise
#: musicbot/entry.py:223
#, python-format
msgid "Starting asyncio subprocess (%(process)s) with command: %(run)s"
msgstr "Запуск подпроцесса асиньо (%(process)s) с командой: %(run)s"

#. Used by: info
#: musicbot/entry.py:258
#, python-format
msgid ""
"Extraction did not provide a duration for this entry.\n"
"MusicBot cannot estimate queue times until it is downloaded.\n"
"Entry name:  %s"
msgstr ""

#. Used by: error
#: musicbot/entry.py:364 musicbot/entry.py:874 musicbot/entry.py:1084
msgid "Entry data is missing version number, cannot deserialize."
msgstr "Отсутствует номер версии входных данных, невозможно десериализовать."

#. Used by: error
#: musicbot/entry.py:367 musicbot/entry.py:877 musicbot/entry.py:1087
msgid "Entry data has the wrong version number, cannot deserialize."
msgstr ""
"Данные записи имеют неверный номер версии, невозможно десериализовать."

#. Used by: warning
#: musicbot/entry.py:383
#, python-format
msgid "Deserialized URLPlaylistEntry cannot find channel with ID:  %s"
msgstr "Десериализованный URLPlaylistEntry не может найти канал с ID:  %s"

#. Used by: warning
#: musicbot/entry.py:399
#, python-format
msgid "Deserialized URLPlaylistEntry has the wrong channel type:  %s"
msgstr "Десериализованный URLPlaylistEntry имеет неверный тип канала:  %s"

#. Used by: warning
#: musicbot/entry.py:421
#, python-format
msgid "Deserialized URLPlaylistEntry cannot find author with ID:  %s"
msgstr "Десериализованный URLPlaylistEntry не может найти автора с ID:  %s"

#. Used by: warning
#: musicbot/entry.py:427
msgid ""
"Deserialized URLPlaylistEntry has an author ID but no channel for lookup!"
msgstr ""
"Десериализованный URLPlaylistEntry имеет ID автора, но нет канала для "
"поиска!"

#. Used by: error
#: musicbot/entry.py:437 musicbot/entry.py:943 musicbot/entry.py:1157
#, python-format
msgid "Could not load %s"
msgstr "Не удалось загрузить %s"

#. Used by: InvalidDataError
#: musicbot/entry.py:474
#, python-format
msgid "Cannot download Spotify links, processing error with type: %(type)s"
msgstr "Не удается загрузить ссылки Spotify, ошибка обработки типа %(type)s"

#. Used by: debug
#: musicbot/entry.py:486 musicbot/entry.py:948 musicbot/entry.py:1190
#, python-format
msgid "Getting ready for entry:  %r"
msgstr "Готово к записи:  %r"

#. Used by: warning
#: musicbot/entry.py:503
msgid "Download cached with different extension..."
msgstr "Скачать кэш с различным расширением..."

#. Used by: debug
#: musicbot/entry.py:512
msgid "Local size different from remote size. Re-downloading..."
msgstr ""
"Локальный размер отличается от удаленного размера. Повторите загрузку..."

#. Used by: debug
#: musicbot/entry.py:516
#, python-format
msgid "Download already cached at:  %s"
msgstr "Скачивание уже кэшировано:  %s"

#. Used by: error
#: musicbot/entry.py:536 musicbot/entry.py:1206
#, python-format
msgid ""
"MusicBot could not get duration data for this entry.\n"
"Queue time estimation may be unavailable until this track is cleared.\n"
"Entry file: %s"
msgstr ""
"MusicBot не может получить данные о продолжительности для этой записи.\n"
"Оценка времени может быть недоступна до тех пор, пока трек не будет очищен.\n"
"Файл записи: %s"

#. Used by: debug
#: musicbot/entry.py:543
#, python-format
msgid "Got duration of %(time)s seconds for file:  %(file)s"
msgstr "Получена длительность %(time)s секунд для файла:  %(file)s"

#. Used by: error
#: musicbot/entry.py:554 musicbot/entry.py:1224
msgid ""
"There as a problem with working out EQ, likely caused by a strange "
"installation of FFmpeg. This has not impacted the ability for the bot to "
"work, but will mean your tracks will not be equalized."
msgstr ""
"Возникла проблема с разработкой EQ, вероятно, вызвана странной установкой "
"FFmpeg. Это не повлияло на способность бота работать, но означает, что ваши "
"треки не будут выравниваться."

#. Used by: error
#: musicbot/entry.py:566 musicbot/entry.py:1237
msgid "Exception while checking entry data."
msgstr "Исключение при проверке входных данных."

#. Used by: debug
#: musicbot/entry.py:577 musicbot/entry.py:1248
#, python-format
msgid "Trying to get duration via pymediainfo for:  %s"
msgstr "Попытка получить длительность через pymediainfo для:  %s"

#. Used by: exception
#: musicbot/entry.py:583 musicbot/entry.py:1254
msgid "Failed to get duration via pymediainfo."
msgstr "Не удалось получить длительность через pymediainfo."

#. Used by: debug
#: musicbot/entry.py:590 musicbot/entry.py:1261
#, python-format
msgid "Trying to get duration via ffprobe for:  %s"
msgstr "Пытаемся получить длительность через ffprobe для:  %s"

#. Used by: error
#: musicbot/entry.py:593 musicbot/entry.py:1264
msgid "Could not locate ffprobe in your path!"
msgstr "Не удалось найти ffprobe в вашем пути!"

#. Used by: error
#: musicbot/entry.py:614 musicbot/entry.py:1285
msgid "ffprobe returned something that could not be used."
msgstr "ffprobe возвращает то, что не может быть использован."

#. Used by: exception
#: musicbot/entry.py:617 musicbot/entry.py:1288
msgid "ffprobe could not be executed for some reason."
msgstr "ffprobe не может быть выполнен по той или иной причине."

#. Used by: debug
#: musicbot/entry.py:627 musicbot/entry.py:1298
#, python-format
msgid "Calculating mean volume of:  %s"
msgstr "Расчет среднего объёма:  %s"

#. Used by: error
#: musicbot/entry.py:630 musicbot/entry.py:1301
msgid "Could not locate ffmpeg on your path!"
msgstr "Не удалось найти ffmpeg на вашем пути!"

#. Used by: debug
#: musicbot/entry.py:656 musicbot/entry.py:1327
msgid "Could not parse 'I' in normalize json."
msgstr "Не удалось разобрать «I» в нормализации json."

#. Used by: debug
#: musicbot/entry.py:664 musicbot/entry.py:1335
msgid "Could not parse 'LRA' in normalize json."
msgstr "Не удалось разобрать 'LRA' в нормализации json."

#. Used by: debug
#: musicbot/entry.py:672 musicbot/entry.py:1343
msgid "Could not parse 'TP' in normalize json."
msgstr "Не удалось разобрать 'TP' в нормализации json."

#. Used by: debug
#: musicbot/entry.py:680 musicbot/entry.py:1351
msgid "Could not parse 'thresh' in normalize json."
msgstr "Не удалось разобрать 'thresh' в нормализации json."

#. Used by: debug
#: musicbot/entry.py:688 musicbot/entry.py:1359
msgid "Could not parse 'offset' in normalize json."
msgstr "Не удалось разобрать 'offset' в нормализации json."

#. Used by: info
#: musicbot/entry.py:705
#, python-format
msgid "Download started:  %r"
msgstr "Загрузка начата:  %r"

#. Used by: everything
#: musicbot/entry.py:710
#, python-format
msgid "Download attempt %s of 3..."
msgstr "Попытка загрузить %s из 3..."

#. Used by: warning
#: musicbot/entry.py:722
#, python-format
msgid ""
"Download incomplete, retrying in %(time).1f seconds.  Reason: %(raw_error)s"
msgstr ""
"Загрузка не завершена, повторная попытка через %(time).1f секунд. Причина: "
"%(raw_error)s"

#. Used by: error
#: musicbot/entry.py:730
#, python-format
msgid "Download failed, not retrying! Reason:  %(raw_error)s"
msgstr "Ошибка загрузки, не повтора! Причина:  %(raw_error)s"

#. Used by: ExtractionError
#: musicbot/entry.py:735
#, python-format
msgid "Download did not complete due to an error: %(raw_error)s"
msgstr "Загрузка не завершена из-за ошибки: %(raw_error)s"

#. Used by: ExtractionError
#: musicbot/entry.py:741
#, python-format
msgid "Download failed due to a yt-dlp error: %(raw_error)s"
msgstr "Загрузка не удалась из-за ошибки yt-dlp: %(raw_error)s"

#. Used by: error
#: musicbot/entry.py:747
msgid "Extraction encountered an unhandled exception."
msgstr "В извлечении обнаружено необработанное исключение."

#. Used by: MusicbotException
#: musicbot/entry.py:751
#, python-format
msgid "Download failed due to an unhandled exception: %(raw_error)s"
msgstr "Загрузка не удалась из-за необработанного исключения: %(raw_error)s"

#. Used by: error
#: musicbot/entry.py:756
#, python-format
msgid "Download failed:  %r"
msgstr "Ошибка загрузки:  %r"

#. Used by: ExtractionError
#: musicbot/entry.py:757
msgid "Failed to extract data for the requested media."
msgstr "Не удалось извлечь данные для запрошенного носителя."

#. Used by: info
#: musicbot/entry.py:759
#, python-format
msgid "Download complete:  %r"
msgstr "Загрузка завершена:  %r"

#. Used by: warning
#: musicbot/entry.py:890
#, python-format
msgid "Deserialized StreamPlaylistEntry cannot find channel with ID:  %s"
msgstr "Десериализованный StreamPlaylistEntry не может найти канал с ID:  %s"

#. Used by: warning
#: musicbot/entry.py:906
#, python-format
msgid "Deserialized StreamPlaylistEntry has the wrong channel type:  %s"
msgstr "Десериализованный StreamPlaylistEntry имеет неверный тип канала:  %s"

#. Used by: warning
#: musicbot/entry.py:928
#, python-format
msgid "Deserialized StreamPlaylistEntry cannot find author with ID:  %s"
msgstr "Десериализованный StreamPlaylistEntry не может найти автора с ID:  %s"

#. Used by: warning
#: musicbot/entry.py:934
msgid ""
"Deserialized StreamPlaylistEntry has an author ID but no channel for lookup!"
msgstr ""
"Десериализованный StreamPlaylistEntry имеет ID автора, но нет канала для "
"поиска!"

#. Used by: warning
#: musicbot/entry.py:1103
#, python-format
msgid "Deserialized LocalFilePlaylistEntry cannot find channel with ID:  %s"
msgstr ""
"Десериализованный LocalFilePlaylistEntry не может найти канал с ID:  %s"

#. Used by: warning
#: musicbot/entry.py:1119
#, python-format
msgid "Deserialized LocalFilePlaylistEntry has the wrong channel type:  %s"
msgstr ""
"Десериализованный LocalFilePlaylistEntry имеет неверный тип канала:  %s"

#. Used by: warning
#: musicbot/entry.py:1141
#, python-format
msgid "Deserialized LocalFilePlaylistEntry cannot find author with ID:  %s"
msgstr ""
"Десериализованный LocalFilePlaylistEntry не может найти автора с ID:  %s"

#. Used by: warning
#: musicbot/entry.py:1147
msgid ""
"Deserialized LocalFilePlaylistEntry has an author ID but no channel for "
"lookup!"
msgstr ""
"Десериализованный LocalFilePlaylistEntry имеет идентификатор автора, но нет "
"канала для поиска!"

#. Used by: debug
#: musicbot/entry.py:1213
#, python-format
msgid "Got duration of %(seconds)s seconds for file:  %(file)s"
msgstr "Получена длительность %(seconds)s секунд для файла:  %(file)s"

#. Used by: warning
#: musicbot/filecache.py:120
#, python-format
msgid "Failed to delete cache file:  %s"
msgstr "Не удалось удалить файл кэша:  %s"

#. Used by: debug
#: musicbot/filecache.py:131
msgid "Audio cache directory has been removed."
msgstr "Директория кэша аудио удалена."

#. Used by: debug
#: musicbot/filecache.py:138
msgid "Audio cache directory could not be removed or renamed."
msgstr "Каталог кэша аудио не может быть удален или переименован."

#. Used by: debug
#: musicbot/filecache.py:145
msgid "Audio cache directory could not be removed."
msgstr "Не удалось удалить директорию кэша звука."

#. Used by: debug
#: musicbot/filecache.py:154
msgid "Audio cache has no limits set, nothing to delete."
msgstr "Кэш аудио не имеет ограничений для удаления."

#. Used by: debug
#: musicbot/filecache.py:217
#, python-format
msgid "Audio cache deleted %(number)s file(s), total of %(size)s removed."
msgstr "Кэш аудио удалён %(number)s файл(ы), всего %(size)s удален."

#. Used by: debug
#: musicbot/filecache.py:225
#, python-format
msgid ""
"Audio cached retained %(number)s file(s) from autoplaylist, total of "
"%(size)s retained."
msgstr ""
"Аудио кэш сохранён %(number)s файл(ы) из автомата, в общей сложности "
"%(size)s сохранен."

#. Used by: debug
#: musicbot/filecache.py:234
#, python-format
msgid "Audio cache is now %(size)s over %(number)s file(s)."
msgstr "Кэш аудио теперь %(size)s над файлом(ями) %(number)s."

#. Used by: debug
#: musicbot/filecache.py:250
msgid "Audio cache directory is missing, nothing to delete."
msgstr "Директория кэша аудио отсутствует, нечего удалять."

#. Used by: noise
#: musicbot/filecache.py:269
msgid ""
"Audio cache file is from autoplaylist but marked as busted, ignoring it."
msgstr "Файл кэша звука из автомата, но помечен как занятый, игнорируя его."

#. Used by: debug
#: musicbot/filecache.py:280
#, python-format
msgid "Cache level requires cleanup. %s"
msgstr "Уровень кэша требует очистки. %s"

#. Used by: debug
#: musicbot/filecache.py:304
msgid "Auto playlist has no cache map, moving on."
msgstr "Автоматический плейлист не имеет карты кэша, перемещаясь вперёд."

#. Used by: info
#: musicbot/filecache.py:312
#, python-format
msgid "Loaded auto playlist cache map with %s entries."
msgstr "Карта кэша автоматически загружена с записями %s."

#. Used by: exception
#: musicbot/filecache.py:316
msgid "Failed to load auto playlist cache map."
msgstr "Не удалось загрузить карту кэша плейлиста."

#. Used by: debug
#: musicbot/filecache.py:341
#, python-format
msgid "Saved auto playlist cache map with %s entries."
msgstr "Кэш автоматического списка воспроизведения сохранен с записями %s."

#. Used by: exception
#: musicbot/filecache.py:345
msgid "Failed to save auto playlist cache map."
msgstr "Не удалось сохранить карту кэша плейлиста."

#. Used by: warning
#: musicbot/filecache.py:363
#, python-format
msgid ""
"Auto playlist cache map conflict on Key: %(file)s  Old: %(old)s  New: "
"%(new)s"
msgstr ""
"Автоматический конфликт кэша карты плейлиста с ключом: %(file)s  Старые: "
"%(old)s  Новый: %(new)s"

#. Used by: debug
#: musicbot/i18n.py:229
#, python-format
msgid "Lang Argument Error:  %s"
msgstr "Ошибка аргумента языка:  %s"

#. Used by: warning
#: musicbot/i18n.py:290
#, python-format
msgid "Failed to load log translations for any of:  [%s]  in:  %s"
msgstr ""

#. Used by: warning
#: musicbot/i18n.py:338
#, python-format
msgid ""
"Failed to load discord translations for any of:  [%s]  guild:  %s  in:  %s"
msgstr ""
"Не удалось загрузить discord перевод для любой из:  [%s]  гильдии:  %s  in:"
"  %s"

#. Used by: debug
#: musicbot/json.py:14
#, python-format
msgid "Loading JSON file: %s"
msgstr "Загрузка JSON-файла: %s"

#. Used by: error
#: musicbot/json.py:27
#, python-format
msgid "Error parsing %s as JSON"
msgstr "Ошибка разбора %s как JSON"

#. Used by: warning
#: musicbot/json.py:36
#, python-format
msgid "Could not grab data from JSON key: %s"
msgstr "Не удалось получить данные из ключа JSON: %s"

#. Used by: debug
#: musicbot/logs.py:131
msgid "Skipping logger setup, already set up"
msgstr "Пропуск настроек логгера, уже настроен"

#. Used by: debug
#: musicbot/logs.py:283
#, python-format
msgid "Log level was previously set via override to: %s"
msgstr "Уровень журнала ранее был установлен переопределение: %s"

#. Used by: info
#: musicbot/logs.py:292
#, python-format
msgid "Changing log level to:  %s"
msgstr "Изменение уровня журнала на:  %s"

#. Used by: info
#: musicbot/logs.py:321
msgid "MusicBot loggers have been called to shut down."
msgstr "Логгеры MusicBot были вызваны для отключения."

#. Used by: warning
#: musicbot/permissions.py:120
#, python-format
msgid "Permissions file not found, copying from:  %s"
msgstr "Файл разрешений не найден, копирование из:  %s"

#. Used by: exception
#: musicbot/permissions.py:129
#, python-format
msgid "Error copying example permissions file:  %s"
msgstr "Ошибка копирования образца файла разрешений:  %s"

#. Used by: debug
#: musicbot/permissions.py:195
msgid "Config 'OwnerID' is set auto, will set correctly later."
msgstr ""
"Конфигурация 'OwnerID' установлена автоматически, правильно настроена позже."

#. Used by: debug
#: musicbot/permissions.py:212
msgid "Validating permissions..."
msgstr "Проверка прав доступа..."

#. Used by: debug
#: musicbot/permissions.py:214
msgid "Setting auto 'OwnerID' for owner permissions group."
msgstr "Установка автоматического 'ID владельца' для группы прав владельца."

#. Used by: debug
#: musicbot/permissions.py:274
#, python-format
msgid "Updating group in permissions file:  %s"
msgstr "Обновление группы в файле разрешений:  %s"

#. Used by: debug
#: musicbot/permissions.py:280
#, python-format
msgid "Deleting group from permissions file:  %s"
msgstr "Удаление группы из файла разрешений:  %s"

#. Used by: debug
#: musicbot/permissions.py:285
#, python-format
msgid "Adding new group to permissions file:  %s"
msgstr "Добавление новой группы в файл разрешений:  %s"

#. Used by: debug
#: musicbot/permissions.py:300
msgid "Saving permissions file now."
msgstr "Сохранение файла разрешений сейчас."

#. Used by: exception
#: musicbot/permissions.py:306
msgid "ConfigUpdater could not parse the permissions file!"
msgstr "ConfigUpdater не смог разобрать файл разрешений!"

#. Used by: exception
#: musicbot/permissions.py:308
msgid "You have a duplicate section, fix your Permissions file!"
msgstr "У вас есть дублирующий раздел, исправьте ваш файл прав!"

#. Used by: exception
#: musicbot/permissions.py:310
#, python-format
msgid "Failed to save permissions group:  %s"
msgstr "Не удалось сохранить группу прав:  %s"

#. Used by: critical
#: musicbot/permissions.py:325
msgid "Dev Bug! Permission has getter that is not available."
msgstr "Dev Bug! Разрешение получилось, что недоступно."

#. Used by: error
#: musicbot/permissions.py:330
msgid ""
"Dev Bug! Permission has invalid type, getter and default must be the same "
"type."
msgstr ""
"Dev Bug! Разрешение имеет недопустимый тип, getter и по умолчанию должны "
"быть одинаковыми."

#. Used by: warning
#: musicbot/permissions.py:574
msgid "Max search items can't be larger than 100. Setting to 100."
msgstr ""
"Максимальное количество элементов для поиска не может быть больше 100. "
"Параметр 100."

#. Used by: PermissionsError
#: musicbot/permissions.py:657
#, python-format
msgid ""
"You do not have permission to play the requested media.\n"
"The yt-dlp extractor `%(extractor)s` is not permitted in your group."
msgstr ""

#. Used by: noise
#: musicbot/player.py:86
#, python-format
msgid "Cleanup got called on the audio source:  %r"
msgstr "Очистка вызвана на источнике звука:  %r"

#. Used by: noise
#: musicbot/player.py:191
#, python-format
msgid "MusicPlayer.skip() is called:  %s"
msgstr "MusicPlayer.skip() вызывается:  %s"

#. Used by: noise
#: musicbot/player.py:201
#, python-format
msgid "MusicPlayer.stop() is called:  %s"
msgstr "MusicPlayer.stop() вызывается:  %s"

#. Used by: warning
#: musicbot/player.py:216
msgid "Guild or network unavailable, cannot resume playback."
msgstr "Гильдия или сеть недоступны, невозможно возобновить воспроизведение."

#. Used by: noise
#: musicbot/player.py:220
#, python-format
msgid "MusicPlayer.resume() is called:  %s"
msgstr "MusicPlayer.resume() вызывается:  %s"

#. Used by: noise
#: musicbot/player.py:240
#, python-format
msgid "MusicPlayer.pause() is called:  %s"
msgstr "MusicPlayer.pause() вызывается:  %s"

#. Used by: noise
#: musicbot/player.py:262
#, python-format
msgid "MusicPlayer.kill() is called:  %s"
msgstr "MusicPlayer.kill() вызывается:  %s"

#. Used by: debug
#: musicbot/player.py:288
msgid "Playback finished, but _current_entry is None."
msgstr "Воспроизведение завершено, но _current_entry пуст."

#. Used by: noise
#: musicbot/player.py:343
msgid "Possible Warning from kill_current_player()"
msgstr "Возможно предупреждение об убийстве_current_player()"

#. Used by: noise
#: musicbot/player.py:362
#, python-format
msgid "MusicPlayer.play() is called:  %s"
msgstr "MusicPlayer.play() вызывается:  %s"

#. Used by: voicedebug
#: musicbot/player.py:372
msgid "MusicPlayer is dead, cannot play."
msgstr "Музыкальный плеер мертв, воспроизведение невозможно."

#. Used by: warning
#: musicbot/player.py:377
msgid "Guild or network unavailable, cannot start playback."
msgstr "Гильдия или сеть недоступна, невозможно начать воспроизведение."

#. Used by: voicedebug
#: musicbot/player.py:382
msgid "MusicPlayer was previously paused, resuming current player."
msgstr "Музыкальный плеер был ранее приостановлен, возобновить текущий плеер."

#. Used by: voicedebug
#: musicbot/player.py:388
msgid "MusicPlayer already locked for playback, this call is ignored."
msgstr ""
"Музыкальный плеер уже заблокирован для воспроизведения, этот вызов "
"игнорируется."

#. Used by: warning
#: musicbot/player.py:399
msgid "Failed to get next entry."
msgstr "Не удалось получить следующую запись."

#. Used by: warning
#: musicbot/player.py:403
msgid "Failed to process entry for playback."
msgstr "Не удалось обработать запись для проигрывания."

#. Used by: ffmpeg
#: musicbot/player.py:485
#, python-format
msgid "Creating player with options: ffmpeg %(before)s -i %(input)s %(after)s"
msgstr "Создание игрока с опциями: ffmpeg %(before)s -i %(input)s %(after)s"

#. Used by: voicedebug
#: musicbot/player.py:489
#, python-format
msgid "Playing %(source)r using %(client)r"
msgstr "Играет в %(source)используя %(client)r"

#. Used by: debug
#: musicbot/player.py:520
#, python-format
msgid "Skipping deletion of '%s', found song in queue"
msgstr "Пропуск удаления '%s', найдено песню в очереди"

#. Used by: debug
#: musicbot/player.py:524
#, python-format
msgid "Deleting file:  %s"
msgstr "Удаление файла:  %s"

#. Used by: debug
#: musicbot/player.py:529
#, python-format
msgid "File deleted:  %s"
msgstr "Файл удален:  %s"

#. Used by: warning
#: musicbot/player.py:533
msgid "Cannot delete file, it is currently in use."
msgstr "Не удается удалить файл, он в настоящее время используется."

#. Used by: warning
#: musicbot/player.py:536
msgid "Cannot delete file due to a permission error."
msgstr "Невозможно удалить файл из-за ошибки прав доступа."

#. Used by: warning
#: musicbot/player.py:541
msgid "Cannot delete file, it was not found."
msgstr "Невозможно удалить файл, он не найден."

#. Used by: warning
#: musicbot/player.py:547
msgid "Error while trying to delete file."
msgstr "Ошибка при попытке удалить файл."

#. Used by: debug
#: musicbot/player.py:552
msgid "Could not delete file, giving up and moving on"
msgstr "Не удалось удалить файл, отправка и перемещение"

#. Used by: error
#: musicbot/player.py:618
#, python-format
msgid "Deserialize returned an object that is not a MusicPlayer:  %s"
msgstr "Десериализация вернула объект, который не является MusicPlayer:  %s"

#. Used by: exception
#: musicbot/player.py:623
msgid "Failed to deserialize player"
msgstr "Не удалось десериализовать игрока"

#. Used by: ffmpeg
#: musicbot/player.py:685
#, python-format
msgid "Data from ffmpeg: %s"
msgstr "Данные из ffmpeg: %s"

#. Used by: ffmpeg
#: musicbot/player.py:695
#, python-format
msgid "Error from ffmpeg: %s"
msgstr "Ошибка из ffmpeg: %s"

#. Used by: ffmpeg
#: musicbot/player.py:703
#, python-format
msgid "Warning from ffmpeg:  %s"
msgstr "Предупреждение от ffmpeg:  %s"

#. Used by: ffmpeg
#: musicbot/player.py:732
msgid "Unknown error decoding message from ffmpeg"
msgstr "Неизвестная ошибка декодирования сообщения от ffmpeg"

#. Used by: ffmpeg
#: musicbot/player.py:736
#, python-format
msgid "Decoded data from ffmpeg: %s"
msgstr "Декодированные данные из ffmpeg: %s"

#. Used by: noise
#: musicbot/playlist.py:121
#, python-format
msgid "Adding stream entry for URL:  %(url)s"
msgstr "Добавление записи потока для URL:  %(url)s"

#. Used by: ExtractionError
#: musicbot/playlist.py:159
msgid "Could not extract information"
msgstr "Не удалось извлечь информацию"

#. Used by: WrongEntryTypeError
#: musicbot/playlist.py:163
msgid "This is a playlist."
msgstr "Это плейлист."

#. Used by: debug
#: musicbot/playlist.py:177
msgid "Entry info appears to be a stream, adding stream entry..."
msgstr "Информация о записи похожа на поток, добавление записи на поток..."

#. Used by: ExtractionError
#: musicbot/playlist.py:195
#, python-format
msgid "Invalid content type `%(type)s` for URL: %(url)s"
msgstr "Недопустимый тип содержимого `%(type)s` для URL: %(url)s"

#. Used by: warning
#: musicbot/playlist.py:203
msgid "Got text/html for content-type, this might be a stream."
msgstr "Получен текстовый/html для типа содержимого, это может быть поток."

#. Used by: warning
#: musicbot/playlist.py:210
#, python-format
msgid "Questionable content-type \"%(type)s\" for url:  %(url)s"
msgstr "Сомнительный тип содержимого \"%(type)s\" для url:  %(url)s"

#. Used by: noise
#: musicbot/playlist.py:215
#, python-format
msgid "Adding URLPlaylistEntry for: %(subject)s"
msgstr "Добавление URLPlaylistList для: %(subject)s"

#. Used by: noise
#: musicbot/playlist.py:235
#, python-format
msgid "Adding LocalFilePlaylistEntry for: %(subject)s"
msgstr "Добавление LocalFilePlaylistEntry для: %(subject)s"

#. Used by: debug
#: musicbot/playlist.py:280
#, python-format
msgid "Ignored video from compound playlist link with ID:  %s"
msgstr "Игнорировать видео из составного плейлиста с ID:  %s"

#. Used by: info
#: musicbot/playlist.py:292
#, python-format
msgid ""
"Not allowing entry that is in song block list:  %(title)s  URL: %(url)s"
msgstr "Не разрешается запись в списке блоков песни:  %(title)s  URL: %(url)s"

#. Used by: debug
#: musicbot/playlist.py:305
#, python-format
msgid ""
"Ignoring song in entries by '%s', duration longer than permitted maximum."
msgstr "Игнорирование песни в записях '%s', длиннее допустимого максимума."

#. Used by: warning
#: musicbot/playlist.py:317
#, python-format
msgid "Not adding YouTube video because it is marked private or deleted:  %s"
msgstr ""
"Видео YouTube не добавлено, потому что оно помечено как приватное или "
"удалено:  %s"

#. Used by: warning
#: musicbot/playlist.py:342
msgid "Could not add item"
msgstr "Не удалось добавить элемент"

#. Used by: debug
#: musicbot/playlist.py:343
#, python-format
msgid "Item: %s"
msgstr "Предмет: %s"

#. Used by: info
#: musicbot/playlist.py:346
#, python-format
msgid "Skipped %s bad entries"
msgstr "Пропущенные %s плохие записи"

#. Used by: everything
#: musicbot/playlist.py:387
msgid "Reorder looping over entries."
msgstr "Переупорядочить циклы поверх записей."

#. Used by: everything
#: musicbot/playlist.py:469
#, python-format
msgid "Pre-downloading next track:  %r"
msgstr "Предзагрузка следующего трека:  %r"

#. Used by: InvalidDataError
#: musicbot/playlist.py:495
msgid "no duration data"
msgstr "нет длительности данных"

#. Used by: InvalidDataError
#: musicbot/playlist.py:504
msgid "no duration data in current entry"
msgstr "нет данных о продолжительности в текущей записи"

#. Used by: SpotifyError
#: musicbot/spotify.py:119
#, python-format
msgid "Invalid track_data, must be of type `track` got `%(type)s`"
msgstr "Недопустимые track_data, должны быть типа `track` получен `%(type)s`"

#. Used by: everything
#: musicbot/spotify.py:301
#, python-format
msgid "Ignored non-track entry in playlist with type:  %s"
msgstr "Игнорируется запись нетрека в плейлисте с типом  %s"

#. Used by: debug
#: musicbot/spotify.py:487
#, python-format
msgid "Spotify Album total tacks:  %(total)s  Next URL: %(url)s"
msgstr ""

#. Used by: debug
#: musicbot/spotify.py:492
#, python-format
msgid "Getting Spotify Album Next URL:  %s"
msgstr "Получение URL-адреса альбома Spotify:  %s"

#. Used by: warning
#: musicbot/spotify.py:503
#, python-format
msgid ""
"Spotify Album Object may not be complete, expected %(total)s tracks but got "
"%(number)s"
msgstr ""
"Альбом Spotify может не быть завершён, ожидается %(total)s треков, но "
"получено %(number)s"

#. Used by: warning
#: musicbot/spotify.py:507
msgid "Spotify Album has more tracks than initial total."
msgstr "Альбом Spotify содержит больше треков, чем начальная сумма."

#. Used by: debug
#: musicbot/spotify.py:530
#, python-format
msgid "Spotify Playlist total tacks: %(total)s  Next URL: %(url)s"
msgstr ""

#. Used by: debug
#: musicbot/spotify.py:535
#, python-format
msgid "Getting Spotify Playlist Next URL:  %s"
msgstr "Получение плейлиста Spotify:  %s"

#. Used by: warning
#: musicbot/spotify.py:546
#, python-format
msgid ""
"Spotify Playlist Object may not be complete, expected %(total)s tracks but "
"got %(number)s"
msgstr ""
"Spotify Playlist Object не может быть завершен, ожидается %(total)s треков, "
"но получено %(number)s"

#. Used by: warning
#: musicbot/spotify.py:550
msgid "Spotify Playlist has more tracks than initial total."
msgstr "Плейлист Spotify больше треков, чем начальный итог."

#. Used by: debug
#: musicbot/spotify.py:555
#, python-format
msgid "Spotify Playlist contained %s usable tracks."
msgstr "Spotify Playlist содержит %s дорожки, пригодные для использования."

#. Used by: SpotifyError
#: musicbot/spotify.py:581 musicbot/spotify.py:617
#, python-format
msgid "Response status is not OK: [%(status)s] %(reason)s"
msgstr "Нет статуса ответа: [%(status)s] %(reason)s"

#. Used by: SpotifyError
#: musicbot/spotify.py:587 musicbot/spotify.py:623 musicbot/spotify.py:733
msgid "Response JSON did not decode to a dict!"
msgstr "Ответ JSON не декодировал немного!"

#. Used by: exception
#: musicbot/spotify.py:596
#, python-format
msgid "Failed making GET request to url:  %s"
msgstr "Не удалось сделать запрос GET url:  %s"

#. Used by: SpotifyError
#: musicbot/spotify.py:602
#, python-format
msgid "Could not make GET to URL:  %(url)s  Reason:  %(raw_error)s"
msgstr "Не удалось сделать GET по URL:  %(url)s  Причина:  %(raw_error)s"

#. Used by: exception
#: musicbot/spotify.py:632
#, python-format
msgid "Failed making POST request to url:  %s"
msgstr "Не удалось сделать запрос POST на url:  %s"

#. Used by: SpotifyError
#: musicbot/spotify.py:638
#, python-format
msgid "Could not make POST to URL:  %(url)s  Reason:  %(raw_error)s"
msgstr "Не удалось сделать POST по URL:  %(url)s  Причина:  %(raw_error)s"

#. Used by: SpotifyError
#: musicbot/spotify.py:672
msgid ""
"Failed to get a guest token from Spotify, please try specifying client ID "
"and client secret"
msgstr ""
"Не удалось получить токен гостя из Spotify, попробуйте указать ID клиента и "
"секретный ключ клиента"

#. Used by: debug
#: musicbot/spotify.py:679
msgid "Created a new Guest Mode access token."
msgstr "Создан новый маркер доступа к гостевому режиму."

#. Used by: SpotifyError
#: musicbot/spotify.py:683
#, python-format
msgid ""
"API response did not contain the expected data. Missing key: %(raw_error)s"
msgstr ""
"Ответ API не содержит ожидаемых данных. Отсутствует ключ: %(raw_error)s"

#. Used by: SpotifyError
#: musicbot/spotify.py:689
#, python-format
msgid ""
"API response contained unexpected data.\n"
"%(raw_error)s"
msgstr ""
"Ответ API содержит неожиданные данные.\n"
"%(raw_error)s"

#. Used by: SpotifyError
#: musicbot/spotify.py:696
msgid "Requested a token from Spotify, did not end up getting one"
msgstr "Запрашиваемый токен из Spotify, не получается"

#. Used by: debug
#: musicbot/spotify.py:700
msgid "Created a new Client Mode access token."
msgstr "Создан новый маркер доступа к режиму клиента."

#. Used by: SpotifyError
#: musicbot/spotify.py:727
#, python-format
msgid "API response status is not OK: [%(status)s]  %(reason)s"
msgstr "Неправильный статус ответа от API: [%(status)s]  %(reason)s"

#. Used by: exception
#: musicbot/spotify.py:743
msgid "Failed to get Spotify Guest Token."
msgstr "Не удалось получить гостевой токен Spotify."

#. Used by: error
#: musicbot/spotify.py:750
#, python-format
msgid "Failed to get Guest Token due to: %(raw_error)s"
msgstr "Не удалось получить Жетон гостя из-за этого: %(raw_error)s"

#. Used by: PermissionsError
#: musicbot/utils.py:174
msgid "Only the owner can use this command."
msgstr "Только владелец может использовать эту команду."

#. Used by: PermissionsError
#: musicbot/utils.py:194
msgid "Only dev users can use this command."
msgstr "Только пользователи dev могут использовать эту команду."

#. Used by: debug
#: musicbot/utils.py:280 musicbot/utils.py:322
msgid "Cannot count members when voice_channel is None."
msgstr "Нельзя посчитать участников, если голосовой канал пуст."

#. Used by: warning
#: run.py:107
msgid "Could not find git executable."
msgstr "Не удалось найти исполняемый файл git."

#. Used by: info
#: run.py:156
msgid "Attempting to upgrade with `git pull` on current path."
msgstr "Попытка обновить с помощью `git pull` на текущем пути."

#. Used by: info
#: run.py:163
#, python-format
msgid "Result of git pull:  %s"
msgstr "Результат git pull:  %s"

#. Used by: exception
#: run.py:171
msgid "Upgrade failed, you need to run `git pull` manually."
msgstr "Обновление не удалось, вам нужно запустить `git pull` вручную."

#. Used by: _L
#: run.py:181
msgid "Cannot execute pip."
msgstr "Невозможно выполнить путь."

#. Used by: exception
#: run.py:188
msgid "Error using -m method"
msgstr "Ошибка при использовании метода -m"

#. Used by: exception
#: run.py:234
msgid "PIP failed while calling sub-process."
msgstr "Ошибка PIP при вызове подпроцесса."

#. Used by: exception
#: run.py:237
msgid "PIP failed due to Permission Error."
msgstr "PIP не удался из-за ошибки разрешения."

#. Used by: exception
#: run.py:241
#, python-format
msgid "PIP failed due to missing Python executable?  (%s)"
msgstr "PIP не удалось из-за отсутствия исполняемого файла Python? (%s)"

#. Used by: exception
#: run.py:246
msgid "PIP failed due to OSError."
msgstr "PIP не удалось из-за ошибки OS."

#. Used by: warning
#: run.py:267
msgid "Could not decode pip update report JSON."
msgstr "Не удалось декодировать pip доклад обновления JSON."

#. Used by: _L
#: run.py:289
msgid "Cannot locate or execute python -m pip"
msgstr "Не удается найти или выполнить python -m pip"

#. Used by: info
#: run.py:292
#, python-format
msgid "Attempting to upgrade with `%s` on current path..."
msgstr "Попытка обновить с помощью `%s` на текущем пути..."

#. Used by: info
#: run.py:310
#, python-format
msgid ""
"Result of pip upgrade:\n"
"%s"
msgstr ""
"Результат улучшения Pip:\n"
"%s"

#. Used by: info
#: run.py:315
#, python-format
msgid "Result exit code from pip upgrade: %s"
msgstr "Результат выхода из обновления Pip: %s"

#. Used by: exception
#: run.py:330
msgid "Upgrade failed to execute or we could not understand the output"
msgstr "Обновление не удалось выполнить или мы не смогли понять вывод"

#. Used by: warning
#: run.py:333
#, python-format
msgid "You may need to run `%s` manually."
msgstr "Возможно вам нужно запустить `%s` вручную."

#. Used by: _L
#: run.py:342
msgid "Press enter to continue . . ."
msgstr "Нажмите Enter, чтобы продолжить. . ."

#. Used by: info
#: run.py:355
msgid "Starting sanity checks"
msgstr "Начало проверки санитарии"

#. Used by: info
#: run.py:366
msgid "Required checks passed."
msgstr "Проведены необходимые проверки."

#. Used by: info
#: run.py:379
msgid "Skipped checking for updates."
msgstr "Пропущена проверка обновлений."

#. Used by: info
#: run.py:381
msgid "Optional checks passed."
msgstr "Необязательные проверки пройдены."

#. Used by: warning
#: run.py:403
msgid "Could not locate py.exe"
msgstr "Не удалось найти py.exe"

#. Used by: info
#: run.py:418
msgid "Python 3 found.  Launching bot..."
msgstr "Найден Python 3. Запуск бота..."

#. Used by: info
#: run.py:478
msgid "Ensuring we're in the right environment"
msgstr "Обеспечение того, что мы находимся в правильной среде"

#. Used by: critical
#: run.py:501
#, python-format
msgid "Failed environment check, %s"
msgstr "Ошибка проверки окружения, %s"

#. Used by: info
#: run.py:542
#, python-format
msgid "Detected FFmpeg is installed at:  %s"
msgstr "Обнаружен FFmpeg установлен в:  %s"

#. Used by: info
#: run.py:544
msgid "Adding local bins/ folder environment PATH for bundled ffmpeg..."
msgstr "Добавление локальной среды bins/ папок PATH для комплекта ffmpeg..."

#. Used by: critical
#: run.py:553
msgid ""
"MusicBot could not locate FFmpeg binary in your environment.\n"
"Please install FFmpeg so it is available in your environment PATH variable."
msgstr ""

#. Used by: info
#: run.py:558
msgid ""
"On Windows, you can add a pre-compiled EXE to the MusicBot `bin` folder,\n"
"or you can install FFmpeg system-wide using WinGet or by running the install.bat file."
msgstr ""
"В Windows вы можете добавить предварительно скомпилированный EXE в папку MusicBot `bin`,\n"
"или вы можете установить FFmpeg в системе с помощью WinGet или с помощью установки. в файл."

#. Used by: info
#: run.py:563
msgid ""
"On MacOS, you may be able to install FFmpeg via homebrew.\n"
"Otherwise, check the official FFmpeg site for build or install steps."
msgstr ""

#. Used by: info
#: run.py:568
msgid ""
"On Linux, many distros make FFmpeg available via system package managers.\n"
"Check for ffmpeg with your system package manager or build from sources."
msgstr ""

#. Used by: warning
#: run.py:581
#, python-format
msgid "Less than %sMB of free space remains on this device"
msgstr "На этом устройстве осталось меньше %sМБ свободного места"

#. Used by: info
#: run.py:590
msgid ""
"\n"
"Checking for updates to MusicBot or dependencies..."
msgstr ""
"\n"
"Проверка обновлений для MusicBot или зависимостей..."

#. Used by: info
#: run.py:607
msgid "No MusicBot updates available via `git` command."
msgstr "Нет доступных обновлений MusicBot с помощью команды `git`."

#. Used by: warning
#: run.py:610
msgid ""
"Could not check for updates using `git` commands.  You should check "
"manually."
msgstr ""
"Не удалось проверить наличие обновлений с помощью команд `git`. Проверьте "
"вручную."

#. Used by: _L
#: run.py:617
msgid "The following packages can be updated:\n"
msgstr "Следующие пакеты могут быть обновлены:\n"

#. Used by: _L
#: run.py:623
#, python-format
msgid "  %s  to version:  %s\n"
msgstr "  %s  к версии:  %s\n"

#. Used by: info
#: run.py:634
msgid "No dependency updates available via `pip` command."
msgstr "Нет доступных обновлений зависимостей с помощью команды `pip`."

#. Used by: warning
#: run.py:637
msgid ""
"Could not check for updates using `pip` commands.  You should check "
"manually."
msgstr ""
"Не удалось проверить наличие обновлений с помощью команд `pip`. Проверьте "
"вручную."

#. Used by: info
#: run.py:641
#, python-format
msgid ""
"You can run a guided update by using the command:\n"
"    %s ./update.py"
msgstr ""
"Вы можете запустить обновление руководства, используя команду:\n"
"    %s ./update.py"

#. Used by: _L
#: run.py:659
msgid "Value is above the maximum limit."
msgstr "Значение превышает максимальный лимит."

#. Used by: _L
#: run.py:661
msgid "Value must not be negative."
msgstr "Значение не должно быть отрицательным."

#. Used by: _L
#: run.py:665
#, python-format
msgid "Value for Max Logs Kept must be a number from 0 to %s"
msgstr "Значение максимального числа журналов должно быть числом от 0 до %s"

#. Used by: _L
#: run.py:675
#, python-format
msgid "Log level '%s' is not available."
msgstr "Уровень журнала '%s' недоступен."

#. Used by: _L
#: run.py:679
#, python-format
msgid "Log Level must be one of:  %s"
msgstr "Уровень журнала должен быть одним из:  %s"

#. Used by: _L
#: run.py:689
msgid ""
"Launch a music playing discord bot built using discord.py, youtubeDL, and "
"ffmpeg."
msgstr ""
"Запустите музыкальный дискорд с помощью discord.py, youtubeDL и ffmpeg."

#. Used by: _L
#: run.py:692
msgid "Available via Github:"
msgstr "Доступно через Github:"

#. Used by: _L
#: run.py:696
msgid "For more help and support with this bot, join our discord:"
msgstr ""
"Для получения дополнительной помощи и поддержки с этим ботом, "
"присоединяйтесь к нашему разногласию:"

#. Used by: _L
#: run.py:698
msgid "This software is provided under the MIT License."
msgstr "Это программное обеспечение предоставляется по лицензии MIT."

#. Used by: _L
#: run.py:700
msgid "See the `LICENSE` text file for complete details."
msgstr "Полную информацию см. в текстовом файле `LICENSE`."

#. Used by: _L
#: run.py:713
msgid ""
"Override the default / system detected language for all text in MusicBot."
msgstr ""
"Переопределить язык по умолчанию / система для всего текста в MusicBot."

#. Used by: _L
#: run.py:723
msgid "Use this language for all server-side log messages from MusicBot."
msgstr "Используйте этот язык для всех серверных журналов от MusicBot."

#. Used by: _L
#: run.py:733
msgid ""
"Use this language for all messages sent to discord from MusicBot.\n"
"This does not prevent per-guild language selection."
msgstr ""
"Используйте этот язык для всех сообщений, отправленных на дискорд от MusicBot.\n"
"Это не предотвращает выбор языка для каждой гильдии."

#. Used by: _L
#: run.py:744
msgid "Print the MusicBot version information and exit."
msgstr "Печатайте информацию о версии MusicBot и выходите."

#. Used by: _L
#: run.py:752
msgid "Skip all optional startup checks, including the update check."
msgstr ""
"Пропустить все опциональные проверки запуска, включая проверку обновления."

#. Used by: _L
#: run.py:760
msgid "Skip only the disk space check at startup."
msgstr "Пропустить проверку только дискового пространства при запуске."

#. Used by: _L
#: run.py:768
msgid "Skip only the update check at startup."
msgstr "Пропустить проверку обновлений только при запуске."

#. Used by: _L
#: run.py:777
msgid ""
"Disable MusicBot from trying to install dependencies when it cannot import "
"them."
msgstr ""
"Отключите MusicBot от попытки установки зависимостей, когда он не может "
"импортировать их."

#. Used by: _L
#: run.py:789
#, python-format
msgid ""
"Specify how many log files to keep, between 0 and %s inclusive. (Default: "
"%s)"
msgstr ""
"Укажите, сколько файлов журнала нужно хранить между 0 и %s включительно. (По"
" умолчанию: %s)"

#. Used by: _L
#: run.py:800
#, python-format
msgid "Override the log level settings set in config. Must be one of: %s"
msgstr ""
"Переопределить уровень журнала, установленный в настройках. Должно быть одно"
" из: %s"

#. Used by: _L
#: run.py:812
#, python-format
msgid ""
"Override the default date format used when rotating log files. This should "
"contain values compatible with strftime().  (Default:  '%s')"
msgstr ""
"Переопределить формат даты по умолчанию, используемый при повороте лог "
"файлов. Это должно содержать значения, совместимые с strftime(). (По "
"умолчанию: '%s')"

#. Used by: _L
#: run.py:843
#, python-format
msgid "Version:  %s"
msgstr "Версия:  %s"

#. Used by: _L
#: run.py:918
msgid "Opened a new MusicBot instance. This terminal can be safely closed!"
msgstr ""
"Открыт новый экземпляр MusicBot. Этот терминал может быть безопасно закрыт!"

#. Used by: info
#: run.py:989
#, python-format
msgid "Loading MusicBot version:  %s"
msgstr "Загрузка версии MusicBot:  %s"

#. Used by: info
#: run.py:990
#, python-format
msgid "Log opened:  %s"
msgstr "Открыт журнал:  %s"

#. Used by: info
#: run.py:991
#, python-format
msgid "Python version:  %s"
msgstr "Python version:  %s"

#. Used by: warning
#: run.py:1000
#, python-format
msgid "Changing working directory to:  %s"
msgstr "Изменение рабочего каталога на:  %s"

#. Used by: critical
#: run.py:1004
msgid ""
"Cannot start the bot!  You started `run.py` in the wrong directory and we "
"could not locate `musicbot` and `.git` folders to verify a new directory "
"location."
msgstr ""
"Не удается запустить бота! Вы начали `run.py` в неправильном каталоге, и мы "
"не смогли найти `musicbot` и `. это папки, чтобы проверить новое "
"расположение каталога."

#. Used by: error
#: run.py:1009
msgid ""
"For best results, start `run.py` from the same folder you cloned MusicBot into.\n"
"If you did not use git to clone the repository, you are strongly urged to."
msgstr ""
"Для получения наилучших результатов запустите `run.py` из той же папки, в которую вы клонировали MusicBot.\n"
"Если вы не использовали git для клонирования репозитория, вам настоятельно рекомендуется это сделать."

#. Used by: critical
#: run.py:1074
msgid ""
"Certificate error is not a verification error, not trying certifi and "
"exiting."
msgstr ""
"Ошибка сертификата не является ошибкой проверки, не пытайтесь certifi и "
"выйти."

#. Used by: exception
#: run.py:1076
msgid "Here is the exact error, it could be a bug."
msgstr "Вот точная ошибка, это может быть ошибка."

#. Used by: warning
#: run.py:1092
msgid ""
"To easily add a certificate to Windows trust store, \n"
"you can open the failing site in Microsoft Edge or IE...\n"
msgstr ""
"Чтобы легко добавить сертификат в хранилище доверия Windows, \n"
"вы можете открыть сайт с ошибками в Microsoft Edge или IE...\n"

#. Used by: warning
#: run.py:1098
msgid ""
"Could not get Issuer Certificate from default trust store, trying certifi "
"instead."
msgstr ""
"Не удалось получить сертификат эмитента из магазина доверия по умолчанию, "
"вместо этого попробуйте certifi."

#. Used by: exception
#: run.py:1107
msgid "Syntax error (modification detected, did you edit the code?)"
msgstr "Ошибка синтаксиса (обнаружена модификация, вы отредактировали код?)"

#. Used by: exception
#: run.py:1110
msgid "Syntax error (this is a bug, not your fault)"
msgstr "Ошибка синтаксиса (это ошибка, не ваша вина)"

#. Used by: error
#: run.py:1122
msgid ""
"Cannot start MusicBot due to an error!\n"
"\n"
"Problem:\n"
"  There was an error importing MusicBot or a dependency package.\n"
"\n"
"Solution:\n"
"  You need to manually install pip packages for MusicBot\n"
"  or launch without `--no-install-deps` and MusicBot will try to install them for you."
msgstr ""
"Невозможно запустить MusicBot из-за ошибки!\n"
"\n"
"Проблема:\n"
"  Возникла ошибка при импорте MusicBot или пакета зависимостей.\n"
"\n"
"Решение:\n"
"  Вам нужно вручную установить pip пакеты для MusicBot\n"
"  или запустить без `--no-install-deps` и MusicBot попытается установить их для вас."

#. Used by: info
#: run.py:1155
msgid "Attempting to install MusicBot dependency packages automatically...\n"
msgstr ""
"Попытка автоматической установки пакетов с зависимостью от MusicBot...\n"

#. Used by: critical
#: run.py:1164
#, python-format
msgid ""
"MusicBot dependencies may not be installed!\n"
"\n"
"Problem:\n"
"  The pip install process ended with a possible error.\n"
"  Some or all of the the dependencies may be missing.\n"
"\n"
"Solution:\n"
"  You must manually install dependency packages.\n"
"  Open a CMD prompt / terminal to the MusicBot directory.\n"
"  You can try using the update scripts install packages.\n"
"  Or try this manual command:\n"
"    %(py_bin)s -m pip install -U -r ./requirements.txt\n"
"\n"
"You can also ask for help in MusicBot's support discord:\n"
"  https://discord.gg/bots"
msgstr ""

#. Used by: info
#: run.py:1185
msgid "OK, lets hope installing dependencies worked!"
msgstr "OK, позволяет надеяться, что зависимости работают!"

#. Used by: error
#: run.py:1197
msgid ""
"MusicBot got an ImportError after trying to install packages. MusicBot must "
"exit..."
msgstr ""
"У MusicBot возникла ошибка при попытке установить пакеты. MusicBot должен "
"выйти..."

#. Used by: exception
#: run.py:1199
msgid "The exception which caused the above error: "
msgstr "Исключение, вызвавшее указанную ошибку: "

#. Used by: info
#: run.py:1218
msgid "MusicBot is doing a soft restart..."
msgstr "MusicBot делает мягкий перезапуск..."

#. Used by: info
#: run.py:1222
msgid "MusicBot is doing a full process restart..."
msgstr "MusicBot выполняет полный перезапуск процесса..."

#. Used by: exception
#: run.py:1228
msgid "Error starting bot"
msgstr "Ошибка при запуске бота"

#. Used by: debug
#: run.py:1233
msgid "Closing event loop."
msgstr "Цикл закрытия событий."

#. Used by: info
#: run.py:1238
#, python-format
msgid "Restarting in %s seconds..."
msgstr "Перезапуск через %s секунд..."

#. Used by: info
#: run.py:1242
msgid "All done."
msgstr "Всё готово."

#. Used by: _L
#: run.py:1271
msgid "OK, we're closing!"
msgstr "ОК, мы закрываем!"

#. Used by: info
#: musicbot/bot.py:2159
msgid "MusicBot is now doing start up steps..."
msgstr ""

#. Used by: warning
#: musicbot/bot.py:2166
msgid "Start up failed at login."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:3481
#, python-format
msgid "No playlist file exists with the name: `%(playlist)s`"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5165
msgid ""
"There is nothing currently playing. Play something with a play command."
msgstr ""

#. Used by: error
#: musicbot/bot.py:5179
#, python-format
msgid ""
"Missing permissions to delete queue file for %(guild)s(%(id)s) at: %(path)s"
msgstr ""

#. Used by: exception
#: musicbot/bot.py:5184
#, python-format
msgid "OS level error while trying to delete queue file: %(path)s"
msgstr ""

#. Used by: info
#: musicbot/config.py:1084
msgid "Generating new config options files..."
msgstr ""

#. Used by: HelpfulError
#: musicbot/config.py:1094
#, python-format
msgid ""
"Error creating default config options file.\n"
"\n"
"Problem:\n"
"  MusicBot attempted to generate the config files but failed due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Make sure MusicBot can read and write to your config files.\n"
msgstr ""

#. Used by: error
#: musicbot/config.py:1348
#, python-format
msgid ""
"Could not locate config options or example options files.\n"
"MusicBot will generate the config files at the location:\n"
"  %(cfg_file)s"
msgstr ""

#. Used by: everything
#: musicbot/filecache.py:332
msgid "Cachemap defer flag is set, not yet saving to disk..."
msgstr ""

#. Used by: error
#: musicbot/permissions.py:136
#, python-format
msgid ""
"Could not locate config permissions or example permissions files.\n"
"MusicBot will generate the config files at the location:\n"
"  %(perms_file)s"
msgstr ""

#. Used by: info
#: musicbot/permissions.py:163
msgid "Generating new config permissions files..."
msgstr ""

#. Used by: HelpfulError
#: musicbot/permissions.py:172
#, python-format
msgid ""
"Error creating default config permissions file.\n"
"\n"
"Problem:\n"
"  MusicBot attempted to generate the config files but failed due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Make sure MusicBot can read and write to your config files.\n"
msgstr ""

#. Used by: critical
#: run.py:525
#, python-format
msgid ""
"MusicBot could not write files in the following directory:\n"
"%(dir)s"
msgstr ""

#. Used by: critical
#: run.py:529
msgid "Please make sure MusicBot can read and write in the above directory."
msgstr ""

#. Used by: exception
#: run.py:536
msgid "Failed to clean up write-test path."
msgstr ""

#. Used by: _L
#: run.py:826
msgid ""
"Supply a directory where MusicBot can store all mutable files.\n"
"Essentially treats the install directory as read-only.\n"
"MusicBot must have permission to create this directory.\n"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2414
msgid "Private Channel"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2416
msgid "Unknown User DM"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2418
#, python-format
msgid "User DM: %(name)s"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2422
msgid "Unknown Channel (Partial)"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2424
#, python-format
msgid "Unnamed Channel: %(id)s"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2803
msgid "Unknown Channel"
msgstr ""

#. TRANSLATORS: Placeholder for empty track title.
#. Used by: _X
#: musicbot/entry.py:299 musicbot/entry.py:821 musicbot/entry.py:1020
msgid "Unknown"
msgstr ""

#. Used by: info
#: musicbot/bot.py:709
#, python-format
msgid "MusicBot may use up to %(rate).2f %(suffix)s of bandwidth."
msgstr ""

#. Used by: everything
#: musicbot/player.py:446
#, python-format
msgid "Probed codec and bitrate: %(name)s at %(rate)s kbps"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2599
#, python-format
msgid "  Command by @mention: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2601
#, python-format
msgid "  Command aliases: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2610
#, python-format
msgid "    Legacy skip: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2612
#, python-format
msgid "    Author insta-skip: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2620
#, python-format
msgid "  Auto-join Owner's voice channel: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2632
#, python-format
msgid "    Save per-server queue history: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2636
#, python-format
msgid "    Save global queue history: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2640
#, python-format
msgid "    Remove URLs on extraction error: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2643
#, python-format
msgid "    Skip playlist for user requests: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2661
#, python-format
msgid "  Songs blocklist: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2662
#, python-format
msgid "  Users blocklist: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2671
#, python-format
msgid "    Delete if cache exceeds %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2674
#, python-format
msgid "  Pre-download next track: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2681
#, python-format
msgid "  Write current song title to file: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2684
#, python-format
msgid "  Respond with Embeds: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2687
msgid "    Footer Text Disabled"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2689
#, python-format
msgid "    Footer Text:  %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2695
#, python-format
msgid "  Leave servers where Owner is not a member: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2699
#, python-format
msgid "  Disconnect from inactive channel: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2708
#, python-format
msgid "  Disconnect at end of queue: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2712
#, python-format
msgid "  Disconnect when player idles: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2722
#, python-format
msgid "  Search using reactions: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2723
#, python-format
msgid "    Results per search: %d"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2728
#, python-format
msgid "  Local media files: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2731
#, python-format
msgid "  Network checking ping tests: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2741
#, python-format
msgid "  Audio processed with: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2744
#, python-format
msgid "  Equalize audio level per-track: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2749
#, python-format
msgid "  HTTP Proxy set to:  %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2751
#, python-format
msgid "  User Agent set to:  %s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8149
msgid ""
"MusicBot has bound channel config and caller channel is not in bound "
"channels."
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8156
msgid "Caller server has a bound channel, caller channel ignored."
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8159
msgid "Caller server has no bound channel, caller allowed."
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8162
#, python-format
msgid "Unbound channel (%s) in server:  %s"
msgstr ""

#. Used by: info
#: musicbot/testrig.py:462
msgid "Starting Command Tests..."
msgstr ""

#. Used by: info
#: musicbot/testrig.py:510
#, python-format
msgid "Buffered command: %(cmd)s"
msgstr ""

#. Used by: info
#: musicbot/testrig.py:527
#, python-format
msgid "- Processing CMD %(n)s of %(t)s: %(cmd)s"
msgstr ""

#. Used by: info
#: run.py:389
msgid "Checking for Python 3.9+"
msgstr ""

#. Used by: warning
#: run.py:393
#, python-format
msgid "Python 3.9+ is required. This version is %s"
msgstr ""

#. Used by: warning
#: run.py:395
msgid "Attempting to locate Python 3.9..."
msgstr ""

#. Used by: warning
#: run.py:414
msgid "Could not execute `py.exe -3.9` "
msgstr ""

#. Used by: info
#: run.py:423
msgid "Trying \"python3.9\""
msgstr ""

#. Used by: warning
#: run.py:426
msgid "Could not locate python3.9 on path."
msgstr ""

#. Used by: info
#: run.py:440
#, python-format
msgid ""
"\n"
"Python 3.9 found.  Re-launching bot using: %s run.py\n"
msgstr ""

#. Used by: critical
#: run.py:445
msgid ""
"Could not find Python 3.9 or higher.  Please run the bot using Python "
"version 3.9 to 3.13"
msgstr ""

#. Used by: ExtractionError
#: musicbot/downloader.py:502
#, python-format
msgid "Error in yt-dlp while downloading media data: %(raw_error)s"
msgstr ""

#. Used by: ExtractionError
#: musicbot/downloader.py:523
#, python-format
msgid "Error in yt-dlp while downloading stream data: %(raw_error)s"
msgstr ""

#. Used by: noise
#: musicbot/downloader.py:557
#, python-format
msgid ""
"Extractor %(extractor)s returned single-entry result, replacing base info "
"with entry info."
msgstr ""

#. Used by: info
#: run.py:1053
msgid "Updating example config files..."
msgstr ""

#~ msgid ""
#~ "Experimental Yt-dlp OAuth2 plugin is enabled. This might break at any point!"
#~ msgstr ""
#~ "Экспериментальный Yt-dlp OAuth2 плагин включен. Это может сломать в любой "
#~ "точке!"

#~ msgid ""
#~ "Cookies TXT file detected. MusicBot will pass them to yt-dlp.\n"
#~ "Cookies are not recommended, may not be supported, and may totally break.\n"
#~ "Copying cookies from your web-browser risks exposing personal data and \n"
#~ "in the best case can result in your accounts being banned!\n"
#~ "\n"
#~ "You have been warned!  Good Luck!  \\U0001F596\n"
#~ msgstr ""

#~ msgid ""
#~ "Original OAuth2 plugin is installed and will be used instead.\n"
#~ "This may cause MusicBot to not close completely, or hang pending authorization!\n"
#~ "To close MusicBot, you must manually Kill the MusicBot process!\n"
#~ "Yt-dlp is being set to show warnings and other log messages, to show the Auth code.\n"
#~ "Uninstall the yt-dlp-youtube-oauth2 package to use integrated OAuth2 features instead."
#~ msgstr ""
#~ "Оригинальный плагин OAuth2 установлен и будет использован вместо него.\n"
#~ "Это может привести к тому, что MusicBot не будет закрыт полностью!\n"
#~ "Чтобы закрыть MusicBot, вы должны вручную убить процесс MusicBot!\n"
#~ "Yt-dlp имеет значение для отображения предупреждений и других сообщений журнала, чтобы показать код аутентификации.\n"
#~ "Удалите пакет yt-dlp-youtube-oauth2 для использования интегрированных функций OAuth2."

#, python-format
#~ msgid "Error in yt-dlp while downloading data: %(raw_error)s"
#~ msgstr "Ошибка yt-dlp при загрузке данных: %(raw_error)s"

#~ msgid ""
#~ "Extractor youtube:search returned single-entry result, replacing base info "
#~ "with entry info."
#~ msgstr ""
#~ "Extractor youtube:search returned single-entry result replacing base info "
#~ "with entry info."

#, python-format
#~ msgid "Failed to save ytdlp oauth2 token data due to:  %s"
#~ msgstr "Не удалось сохранить данные токена ytdlp oauth2 из-за этого:  %s"

#~ msgid "Loading YouTube TV OAuth2 token data."
#~ msgstr "Загрузка данных токена YouTube TV OAuth2."

#, python-format
#~ msgid "Failed to load ytdlp oauth2 token data due to:  %s"
#~ msgstr "Не удалось загрузить данные токена ytdlp oauth2 из-за этого:  %s"

#~ msgid "Storing YouTube TV OAuth2 token data"
#~ msgstr "Хранение данных токена OAuth2 YouTube TV"

#~ msgid "Invalid cached OAuth2 token data."
#~ msgstr "Недопустимые кэшированные данные токена OAuth2."

#~ msgid "Access token expired, refreshing"
#~ msgstr "Маркер доступа истек, обновление"

#~ msgid ""
#~ "YouTube cookies have been provided, but OAuth2 is being used. If you "
#~ "encounter problems, stop providing YouTube cookies to yt-dlp."
#~ msgstr ""
#~ "Предоставлены cookies YouTube, но используется OAuth2. Если вы сталкиваетесь"
#~ " с проблемами, перестаньте предоставлять YouTube cookies yt-dlp."

#~ msgid "Refreshing YouTube TV oauth2 token..."
#~ msgstr "Обновление ТВ YouTube oauth2 токена..."

#, python-format
#~ msgid ""
#~ "Failed to refresh OAuth2 access token due to:  %s\n"
#~ "Restarting authorization flow..."
#~ msgstr ""
#~ "Не удалось обновить токен доступа OAuth2 из-за использования:  %s\n"
#~ "Перезапуск потока авторизации..."

#~ msgid "Starting oauth2 flow..."
#~ msgstr "Запуск oauth2 потока..."

#, python-format
#~ msgid ""
#~ "\n"
#~ "NOTICE:\n"
#~ "To give yt-dlp access to your account, visit:\n"
#~ "  %s\n"
#~ "Then enter this authorization code:  %s\n"
#~ "You have %s seconds to complete authorization.\n"
#~ msgstr ""

#~ msgid ""
#~ "The application may hang until authorization time out if closed at this "
#~ "point. This is normal."
#~ msgstr ""
#~ "Приложение может зависнуть до истечения времени авторизации, если оно "
#~ "закрыто. Это нормально."

#~ msgid "Timed out while waiting for OAuth2 token."
#~ msgstr "Истекло время ожидания токена OAuth2."

#~ msgid "The device code has expired, restarting authorization flow for yt-dlp."
#~ msgstr ""
#~ "Срок действия кода устройства истек, перезапустив поток авторизации для yt-"
#~ "dlp."

#~ msgid "Yt-dlp OAuth2 authorization successful."
#~ msgstr "Yt-dlp OAuth2 авторизация успешна."

#, python-format
#~ msgid "Adding OAuth2 Plugin to Yt-dlp IE:  %s"
#~ msgstr "Добавление OAuth2 плагина к Yt-dlp IE:  %s"

#, python-format
#~ msgid "Default Yt-dlp Clients:  %s"
#~ msgstr "Клиенты Yt-dlp по умолчанию:  %s"

#, python-format
#~ msgid "  Auto-Summon: %s"
#~ msgstr "  Автовызов: %s"

#, python-format
#~ msgid "    Delete if size exceeds %s"
#~ msgstr "    Удалять, если размер превышает %s"

#, python-format
#~ msgid "  Write current songs to file: %s"
#~ msgstr "  Записать текущие песни в файл: %s"

#, python-format
#~ msgid "  Author insta-skip: %s"
#~ msgstr "  Автор Insta-skip: %s"

#, python-format
#~ msgid "  Embeds: %s"
#~ msgstr "  Embeds: %s"

#, python-format
#~ msgid "  Legacy skip: %s"
#~ msgstr "  Пропуск старого: %s"

#, python-format
#~ msgid "  Leave non owners: %s"
#~ msgstr "  Оставить невладельцев: %s"

#, python-format
#~ msgid "  Leave inactive VC: %s"
#~ msgstr "  Оставить неактивный VC: %s"

#, python-format
#~ msgid "  Leave at song end/empty queue: %s"
#~ msgstr "  Оставить на конец и пустую очередь: %s"

#, python-format
#~ msgid "  Leave when player idles: %s"
#~ msgstr "  Оставь, когда игрок фармит: %s"

#, python-format
#~ msgid "  Search List: %s"
#~ msgstr "  Список поиска: %s"

#~ msgid "Checking for Python 3.8+"
#~ msgstr "Проверка Python 3.8+"

#, python-format
#~ msgid "Python 3.8+ is required. This version is %s"
#~ msgstr "Требуется Python 3.8+ версия %s"

#~ msgid "Attempting to locate Python 3.8..."
#~ msgstr "Попытка найти Python 3.8..."

#~ msgid "Could not execute `py.exe -3.8` "
#~ msgstr "Не удалось выполнить `py.exe -3.8` "

#~ msgid "Trying \"python3.8\""
#~ msgstr "Попытка \"python3.8\""

#~ msgid "Could not locate python3.8 on path."
#~ msgstr "Не удалось найти python3.8 на пути."

#, python-format
#~ msgid ""
#~ "\n"
#~ "Python 3.8 found.  Re-launching bot using: %s run.py\n"
#~ msgstr ""

#~ msgid ""
#~ "Could not find Python 3.8 or higher.  Please run the bot using Python 3.8"
#~ msgstr ""
#~ "Не удалось найти Python 3.8 или выше. Пожалуйста, запустите бота с помощью "
#~ "Python 3.8"

#, python-format
#~ msgid "  Audio Codec: %s"
#~ msgstr ""

#, python-format
#~ msgid "Generated a new %(example_file)s and copied it to %(option_file)s"
#~ msgstr ""
#~ "Сгенерировал новый %(example_file)s и скопировал его в %(option_file)s"

#~ msgid "Current working directory does not seem to be writable"
#~ msgstr "Текущий рабочий каталог не доступен для записи"

#~ msgid "Please move the bot to a folder that is writable"
#~ msgstr "Пожалуйста, переместите бота в папку, которая доступна для записи"
