#
msgid ""
msgstr ""
"Project-Id-Version: notmusicbot\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-11-11 16:38-0800\n"
"PO-Revision-Date: 2024-11-12 00:41\n"
"Last-Translator: \n"
"Language-Team: French\n"
"Language: fr_FR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Crowdin-File: /fae/i18n/musicbot_logs.pot\n"
"X-Crowdin-File-ID: 26\n"
"X-Crowdin-Language: fr\n"
"X-Crowdin-Project: notmusicbot\n"
"X-Crowdin-Project-ID: 734017\n"
"X-Generated-By: pygettext.py 1.5-mb01\n"

#. Used by: warning
#: musicbot/aliases.py:52
msgid "Aliases file not found, copying example_aliases.json"
msgstr "Fichier d'alias introuvable, copiant exemple_aliases.json"

#. Used by: HelpfulError
#: musicbot/aliases.py:56
msgid ""
"Error while loading aliases.\n"
"\n"
"Problem:\n"
"  Your aliases files (aliases.json & example_aliases.json) are missing.\n"
"\n"
"Solution:\n"
"  Replace the alias config file(s) or copy them from:\n"
"    https://github.com/Just-Some-Bots/MusicBot/"
msgstr ""
"Erreur lors du chargement.\n"
"\n"
"Problème :\n"
"  Vos fichiers d'alias (aliases.json & example_aliases.json) sont manquants.\n"
"\n"
"Solution :\n"
"  Remplacez le(s) fichier(s) de configuration d'alias ou copiez-les:\n"
"    https://github.com/Just-Some-Bots/MusicBot/"

#. Used by: error
#: musicbot/aliases.py:80
#, python-format
msgid "Failed to load aliases file:  %s"
msgstr "Impossible de charger le fichier d'alias :  %s"

#. Used by: error
#: musicbot/aliases.py:88
#, python-format
msgid ""
"Failed to parse aliases file:  %s\n"
"Ensure the file contains valid JSON and restart the bot."
msgstr ""
"Échec de l'analyse du fichier d'alias :  %s\n"
"Assurez-vous que le fichier contient du JSON valide et redémarrez le bot."

#. Used by: error
#: musicbot/aliases.py:118
#, python-format
msgid ""
"Aliases skipped for non-existent command:  %(command)s  ->  %(aliases)s"
msgstr ""
"Alias ignorés pour une commande inexistante :  %(command)s  ->  %(aliases)s"

#. Used by: error
#: musicbot/aliases.py:126
#, python-format
msgid ""
"Alias(es) skipped for invalid alias data:  %(command)s  ->  %(aliases)s"
msgstr ""
"Alias(s) ignoré(s) pour les données d'alias invalides :  %(command)s  ->  "
"%(aliases)s"

#. Used by: error
#: musicbot/aliases.py:136
#, python-format
msgid "Alias `%(alias)s` skipped as already exists on command:  %(command)s"
msgstr ""
"Alias `%(alias)s` ignoré comme il existe déjà sur commande :  %(command)s"

#. Used by: warning
#: musicbot/autoplaylist.py:77
#, python-format
msgid "Error loading auto playlist file:  %s"
msgstr ""
"Erreur lors du chargement du fichier de la liste de lecture automatique :  "
"%s"

#. Used by: info
#: musicbot/autoplaylist.py:181
#, python-format
msgid "Removing unplayable song from playlist, %(playlist)s: %(track)s"
msgstr ""
"Suppression de la chanson injouable de la playlist, %(playlist)s: %(track)s"

#. Used by: info
#: musicbot/autoplaylist.py:186
#, python-format
msgid "Removing song from playlist, %(playlist)s: %(track)s"
msgstr "Suppression de la chanson de la playlist, %(playlist)s: %(track)s"

#. Used by: exception
#: musicbot/autoplaylist.py:132 musicbot/autoplaylist.py:211
msgid "Could not log information about the playlist URL removal."
msgstr ""
"Impossible d'enregistrer les informations à propos de la suppression de "
"l'URL de la playlist."

#. Used by: info
#: musicbot/autoplaylist.py:135 musicbot/autoplaylist.py:215
msgid "Updating playlist file..."
msgstr "Mise à jour du fichier de liste de lecture..."

#. Used by: exception
#: musicbot/autoplaylist.py:158 musicbot/autoplaylist.py:231
#: musicbot/autoplaylist.py:268
#, python-format
msgid "Failed to save playlist file:  %s"
msgstr "Impossible d'enregistrer le fichier de la playlist :  %s"

#. Used by: debug
#: musicbot/autoplaylist.py:240
#, python-format
msgid "URL already in playlist %s, ignoring"
msgstr "URL déjà dans la playlist %s, ignorée"

#. Used by: info
#: musicbot/autoplaylist.py:247
#, python-format
msgid "Adding new URL to playlist, %(playlist)s: %(track)s"
msgstr "Ajout d'une nouvelle URL à la playlist, %(playlist)s: %(track)s"

#. Used by: info
#: musicbot/bot.py:169
#, python-format
msgid "Initializing MusicBot %s"
msgstr "Initialisation de MusicBot %s"

#. Used by: error
#: musicbot/bot.py:252
#, python-format
msgid "Loop is closed, cannot create task for: %r"
msgstr "La boucle est fermée, impossible de créer une tâche pour : %r"

#. Used by: exception
#: musicbot/bot.py:268
#, python-format
msgid "Unhandled exception for task:  %r"
msgstr "Exception non gérée pour la tâche :  %r"

#. Used by: error
#: musicbot/bot.py:272
#, python-format
msgid "Unhandled exception for task:  %(task)r  --  %(raw_error)s"
msgstr "Exception non gérée pour la tâche :  %(task)r --  %(raw_error)s"

#. Used by: warning
#: musicbot/bot.py:317 musicbot/bot.py:339
msgid "Spotify did not provide us with a token. Disabling."
msgstr "Spotify ne nous a pas fourni de jeton. Désactivation."

#. Used by: info
#: musicbot/bot.py:321
msgid "Authenticated with Spotify successfully using client ID and secret."
msgstr ""
"Authentifié avec Spotify avec succès en utilisant l'ID du client et le "
"secret."

#. Used by: warning
#: musicbot/bot.py:325
#, python-format
msgid ""
"Could not start Spotify client. Is your client ID and secret correct? "
"Details: %s. Continuing anyway in 5 seconds..."
msgstr ""
"Impossible de démarrer le client Spotify. Votre identifiant client et votre "
"secret sont-ils corrects ? Détails: %s. Continuer quand même dans 5 "
"secondes..."

#. Used by: warning
#: musicbot/bot.py:333
msgid ""
"The config did not have Spotify app credentials, attempting to use guest "
"mode."
msgstr ""
"La configuration n'a pas les identifiants de l'application Spotify, en "
"essayant d'utiliser le mode invité."

#. Used by: info
#: musicbot/bot.py:343
msgid "Authenticated with Spotify successfully using guest mode."
msgstr "Authentifié avec Spotify avec succès en mode invité."

#. Used by: warning
#: musicbot/bot.py:348
#, python-format
msgid "Could not start Spotify client using guest mode. Details: %s."
msgstr ""
"Impossible de démarrer le client Spotify en utilisant le mode invité. "
"Détails : %s."

#. Used by: info
#: musicbot/bot.py:353
msgid "Initialized, now connecting to discord."
msgstr "Initialisé, se connecte maintenant à discord."

#. Used by: debug
#: musicbot/bot.py:364
msgid "Network ping test is disabled via config."
msgstr "Le test de ping réseau est désactivé via la configuration."

#. Used by: noise
#: musicbot/bot.py:368
msgid "Network ping test is closing down."
msgstr "Le test de ping réseau est en train de se fermer."

#. Used by: warning
#: musicbot/bot.py:379
msgid "Could not resolve ping target."
msgstr "Impossible de résoudre la cible du ping"

#. Used by: noise
#: musicbot/bot.py:409
msgid "Network ping test cancelled."
msgstr "Test de ping réseau annulé."

#. Used by: warning
#: musicbot/bot.py:423
msgid "Network testing via HTTP does not have a session to borrow."
msgstr "Le test de réseau via HTTP n'a pas de session à emprunter."

#. Used by: warning
#: musicbot/bot.py:448
msgid "Could not locate `ping` executable in your environment."
msgstr "Impossible de localiser l'exécutable `ping` dans votre environnement."

#. Used by: error
#: musicbot/bot.py:474
#, python-format
msgid ""
"MusicBot could not locate a `ping` command path.  Will attempt to use HTTP ping instead.\n"
"MusicBot tried the following command:   %s\n"
"You should enable ping in your system or container environment for best results.\n"
"Alternatively disable network checking via config."
msgstr ""
"MusicBot n'a pas pu localiser un chemin de commande `ping`. Il tentera d'utiliser le ping HTTP à la place.\n"
"MusicBot a essayé la commande suivante :   %s\n"
"Vous devriez activer le ping dans votre environnement système ou conteneur pour de meilleurs résultats.\n"
"Sinon, désactiver la vérification du réseau par le biais de la configuration."

#. Used by: error
#: musicbot/bot.py:484
#, python-format
msgid ""
"MusicBot was denied permission to execute the `ping` command.  Will attempt to use HTTP ping instead.\n"
"MusicBot tried the following command:   %s\n"
"You should enable ping in your system or container environment for best results.\n"
"Alternatively disable network checking via config."
msgstr ""
"MusicBot s'est vu refuser la permission d'exécuter la commande `ping`. Il tentera d'utiliser le ping HTTP à la place.\n"
"MusicBot a essayé la commande suivante :   %s\n"
"Vous devriez activer le ping dans votre environnement système ou conteneur pour de meilleurs résultats.\n"
"Sinon, désactiver la vérification du réseau par le biais de la configuration."

#. Used by: error
#: musicbot/bot.py:494
#, python-format
msgid ""
"Your environment may not allow the `ping` system command.  Will attempt to use HTTP ping instead.\n"
"MusicBot tried the following command:   %s\n"
"You should enable ping in your system or container environment for best results.\n"
"Alternatively disable network checking via config."
msgstr ""
"Votre environnement peut ne pas autoriser la commande `ping` du système. Il va essayer d'utiliser le ping HTTP à la place.\n"
"MusicBot a essayé la commande suivante :   %s\n"
"Vous devriez activer le ping dans votre environnement système ou conteneur pour de meilleurs résultats.\n"
"Sinon, désactiver la vérification du réseau par le biais de la configuration."

#. Used by: info
#: musicbot/bot.py:509
msgid "MusicBot detected network is available again."
msgstr "Le réseau détecté par MusicBot est à nouveau disponible."

#. Used by: warning
#: musicbot/bot.py:514
msgid "VoiceClient is not connected, waiting to resume MusicPlayer..."
msgstr ""
"VoiceClient n'est pas connecté, en attente de reprise de MusicPlayer..."

#. Used by: info
#: musicbot/bot.py:518
#, python-format
msgid "Resuming playback of player:  (%(guild_id)s) %(player)r"
msgstr "Reprise de la lecture du joueur : (%(guild_id)s) %(player)r"

#. Used by: info
#: musicbot/bot.py:529
msgid "MusicBot detected a network outage."
msgstr "MusicBot a détecté une panne de réseau."

#. Used by: info
#: musicbot/bot.py:533
#, python-format
msgid ""
"Pausing MusicPlayer due to network availability:  (%(guild_id)s) %(player)r"
msgstr ""
"Suspendre MusicPlayer en raison de la disponibilité du réseau : "
"(%(guild_id)s) %(player)r"

#. Used by: noise
#: musicbot/bot.py:554
#, python-format
msgid ""
"Looking for owner in guild: %(guild)s (required voice: %(required)s) and "
"got:  %(owner)s"
msgstr ""
"Recherche du propriétaire dans la guilde : %(guild)s (voix requise : "
"%(required)s) et obtenu :  %(owner)s"

#. Used by: info
#: musicbot/bot.py:568
msgid "Checking for channels to auto-join or resume..."
msgstr "Vérification des salons à rejoindre ou à reprendre automatiquement..."

#. Used by: warning
#: musicbot/bot.py:580
#, python-format
msgid "Guild not available, cannot auto join:  %(id)s/%(name)s"
msgstr ""
"Guilde non disponible, impossible de rejoindre automatiquement :  "
"%(id)s/%(name)s"

#. Used by: info
#: musicbot/bot.py:588
#, python-format
msgid "Found resumable voice channel:  %(channel)s  in guild:  %(guild)s"
msgstr "Canal vocal disponible :  %(channel)s  dans la guilde :  %(guild)s"

#. Used by: info
#: musicbot/bot.py:601
#, python-format
msgid "Will try resuming voice session instead of Auto-Joining channel:  %s"
msgstr ""
"Essaiera de reprendre la session vocale au lieu de rejoindre automatiquement"
" le canal :  %s"

#. Used by: info
#: musicbot/bot.py:618
#, python-format
msgid "Found owner in voice channel:  %s"
msgstr "Propriétaire trouvé dans le salon vocal :  %s"

#. Used by: info
#: musicbot/bot.py:623
#, python-format
msgid "Ignoring resumable channel, AutoSummon to owner in channel:  %s"
msgstr ""
"Ignorant le canal de révocation, Invocation automatique au propriétaire dans"
" le canal :  %s"

#. Used by: info
#: musicbot/bot.py:628
#, python-format
msgid "Ignoring Auto-Join channel, AutoSummon to owner in channel:  %s"
msgstr ""
"Ignorer le canal de connexion automatique, Invoquer automatiquement au "
"propriétaire du canal :  %s"

#. Used by: info
#: musicbot/bot.py:640
#, python-format
msgid "Already connected to channel:  %(channel)s  in guild:  %(guild)s"
msgstr "Déjà connecté au salon :  %(channel)s  dans la guilde :  %(guild)s"

#. Used by: info
#: musicbot/bot.py:649
#, python-format
msgid "Attempting to join channel:  %(channel)s  in guild:  %(guild)s"
msgstr ""
"Tentative de rejoindre le salon :  %(channel)s  dans la guilde :  %(guild)s"

#. Used by: info
#: musicbot/bot.py:656
msgid "Discarding MusicPlayer and making a new one..."
msgstr "Discarding MusicPlayer and making a new on..."

#. Used by: debug
#: musicbot/bot.py:676
msgid "MusicBot will make a new MusicPlayer now..."
msgstr "MusicBot va créer un nouveau MusicPlayer..."

#. Used by: warning
#: musicbot/bot.py:697
#, python-format
msgid "Not joining %(guild)s/%(channel)s, it isn't a supported voice channel."
msgstr ""
"Ne pas rejoindre %(guild)s/%(channel)s, ce n'est pas un salon vocal pris en "
"charge."

#. Used by: info
#: musicbot/bot.py:700
msgid "Finished joining configured channels."
msgstr "Terminé de rejoindre les canaux configurés."

#. Used by: CommandError
#: musicbot/bot.py:723
msgid "Member is not voice-enabled and cannot use this command."
msgstr ""
"Le membre n'est pas activé par la voix et ne peut pas utiliser cette "
"commande."

#. Used by: PermissionsError
#: musicbot/bot.py:731
msgid "You cannot use this command when not in the voice channel."
msgstr ""
"Vous ne pouvez pas utiliser cette commande quand vous n'êtes pas dans le "
"salon vocal."

#. Used by: debug
#: musicbot/bot.py:745
msgid "Getting bot Application Info."
msgstr "Récupération des infos d'application du bot."

#. Used by: error
#: musicbot/bot.py:770
#, python-format
msgid "MusicBot does not have permission to Connect in channel:  %s"
msgstr "MusicBot n'a pas la permission de se connecter au salon :  %s"

#. Used by: PermissionsError
#: musicbot/bot.py:774
#, python-format
msgid "MusicBot does not have permission to Connect in channel:  `%(name)s`"
msgstr ""
"MusicBot n'a pas la permission de se connecter dans le salon : `%(name)s`"

#. Used by: error
#: musicbot/bot.py:779
#, python-format
msgid "MusicBot does not have permission to Speak in channel:  %s"
msgstr "MusicBot n'a pas la permission de parler dans le canal :  %s"

#. Used by: PermissionsError
#: musicbot/bot.py:783
#, python-format
msgid "MusicBot does not have permission to Speak in channel:  `%(name)s`"
msgstr "MusicBot n'a pas la permission de parler dans le salon : `%(name)s`"

#. Used by: voicedebug
#: musicbot/bot.py:793
#, python-format
msgid "Reusing bots VoiceClient from guild:  %s"
msgstr "Réutilisation des bots VoiceClient de la guilde :  %s"

#. Used by: voicedebug
#: musicbot/bot.py:798
#, python-format
msgid "Forcing disconnect on stale VoiceClient in guild:  %s"
msgstr ""
"Forcer la déconnexion sur un VoiceClient obsolète dans la guilde :  %s"

#. Used by: warning
#: musicbot/bot.py:804
msgid "Disconnect failed or was cancelled?"
msgstr "La déconnexion a échoué ou a été annulée ?"

#. Used by: critical
#: musicbot/bot.py:812
#, python-format
msgid "MusicBot is unable to connect to the channel right now:  %(channel)s"
msgstr ""
"MusicBot ne peut pas se connecter au salon pour le moment :  %(channel)s"

#. Used by: CommandError
#: musicbot/bot.py:816
msgid ""
"MusicBot could not connect to the channel.\n"
"Try again later, or restart the bot if this continues."
msgstr ""
"MusicBot n'a pas pu se connecter au canal.\n"
"Réessayez plus tard ou redémarrez le bot si cela continue."

#. Used by: voicedebug
#: musicbot/bot.py:827
msgid "MusicBot has a VoiceClient now..."
msgstr "MusicBot a maintenant un client vocal..."

#. Used by: warning
#: musicbot/bot.py:832
#, python-format
msgid ""
"Retrying connection after a timeout error (%(attempt)s) while trying to "
"connect to:  %(channel)s"
msgstr ""
"Retentative de connexion après une erreur de délai (%(attempt)s) lors de la "
"tentative de connexion à :  %(channel)s"

#. Used by: exception
#: musicbot/bot.py:837
msgid "MusicBot VoiceClient connection attempt was cancelled. No retry."
msgstr ""
"La tentative de connexion de MusicBot VoiceClient a été annulée. Aucune "
"nouvelle tentative."

#. Used by: CommandError
#: musicbot/bot.py:840
msgid ""
"MusicBot connection to voice was cancelled. This is odd. Maybe restart?"
msgstr ""
"La connexion MusicBot à la voix a été annulée. C'est bizarre. Peut-être "
"redémarrez-vous?"

#. Used by: info
#: musicbot/bot.py:846 musicbot/bot.py:8670
#, python-format
msgid "MusicBot is requesting to speak in channel: %s"
msgstr "MusicBot demande à parler dans le canal : %s"

#. Used by: PermissionsError
#. Used by: exception
#: musicbot/bot.py:851 musicbot/bot.py:8676
msgid "MusicBot does not have permission to speak."
msgstr "MusicBot n'a pas la permission de parler."

#. Used by: MusicbotException
#. Used by: exception
#: musicbot/bot.py:855 musicbot/bot.py:8678
msgid "MusicBot could not request to speak."
msgstr "MusicBot n'a pas pu demander à parler."

#. Used by: info
#: musicbot/bot.py:868
#, python-format
msgid "Disconnecting a MusicPlayer in guild:  %s"
msgstr "Déconnexion d'un MusicPlayer dans la guilde :  %s"

#. Used by: debug
#: musicbot/bot.py:880
msgid "Disconnecting VoiceClient before we kill the MusicPlayer."
msgstr "Déconnexion de VoiceClient avant de tuer le MusicPlayer."

#. Used by: warning
#: musicbot/bot.py:888 musicbot/bot.py:907 musicbot/bot.py:919
#: musicbot/bot.py:942
msgid "The disconnect failed or was cancelled."
msgstr "La déconnexion a échoué ou a été annulée."

#. Used by: debug
#: musicbot/bot.py:898
msgid ""
"MusicBot has a VoiceProtocol that is not a VoiceClient. Disconnecting "
"anyway..."
msgstr ""
"MusicBot a un protocole vocal qui n'est pas un client vocal. Déconnexion "
"quand même..."

#. Used by: debug
#: musicbot/bot.py:911
#, python-format
msgid "Disconnecting a rogue VoiceClient in guild:  %s"
msgstr "Déconnexion d'un client vocal immature dans la guilde :  %s"

#. Used by: warning
#: musicbot/bot.py:935
msgid "Disconnecting a non-guild VoiceClient..."
msgstr "Déconnexion d'un client vocal non-guilde..."

#. Used by: warning
#: musicbot/bot.py:945
#, python-format
msgid ""
"MusicBot.voice_clients list contains a non-VoiceClient object?\n"
"The object is actually of type:  %s"
msgstr ""
"La liste MusicBot.voice_clients contient un objet non-VoiceClient ?\n"
"L'objet est en fait de type :  %s"

#. Used by: warning
#: musicbot/bot.py:955
#, python-format
msgid "We still have a MusicPlayer ref in guild (%(guild_id)s):  %(player)r"
msgstr ""
"Nous avons encore un ref MusicPlayer dans la guilde (%(guild_id)s) :  "
"%(player)r"

#. Used by: voicedebug
#: musicbot/bot.py:968
#, python-format
msgid "Guild (%(guild)s) wants a player, optional:  %(player)r"
msgstr "Guilde (%(guild)s) veut un joueur, optionnel:  %(player)r"

#. Used by: error
#: musicbot/bot.py:975
msgid ""
"[BUG] MusicPlayer is missing a VoiceClient somehow.  You should probably "
"restart the bot."
msgstr ""
"[BUG] MusicPlayer ne dispose pas d'un VoiceClient. Vous devriez probablement"
" redémarrer le bot."

#. Used by: warning
#: musicbot/bot.py:980
msgid "MusicPlayer has a VoiceClient that is not connected."
msgstr "MusicPlayer a un Client Voix qui n'est pas connecté."

#. Used by: noise
#: musicbot/bot.py:981
#, python-format
msgid "MusicPlayer obj:  %r"
msgstr "Lecteur musical obj:  %r"

#. Used by: noise
#: musicbot/bot.py:982
#, python-format
msgid "VoiceClient obj:  %r"
msgstr "VoiceClient obj:  %r"

#. Used by: voicedebug
#: musicbot/bot.py:1002
#, python-format
msgid ""
"Getting a MusicPlayer for guild:  %(guild)s  In Channel:  %(channel)s  "
"Create: %(create)s  Deserialize:  %(serial)s"
msgstr ""
"Obtenir un MusicPlayer pour la guilde :  %(guild)s  Dans la chaîne :  "
"%(channel)s  Création : %(create)s  Désérialisation :  %(serial)s"

#. Used by: voicedebug
#: musicbot/bot.py:1018
#, python-format
msgid ""
"Created player via deserialization for guild %(guild_id)s with %(number)s "
"entries"
msgstr ""
"Joueur créé par désérialisation pour la guilde %(guild_id)s avec des entrées"
" %(number)s"

#. Used by: CommandError
#: musicbot/bot.py:1027
msgid ""
"The bot is not in a voice channel.\n"
"Use the summon command to bring the bot to your voice channel."
msgstr ""
"Le bot n'est pas dans un salon vocal.\n"
"Utilisez la commande d'invocation pour amener le bot dans votre canal vocal."

#. Used by: MusicbotException
#: musicbot/bot.py:1039
msgid "Something is wrong, we didn't get the VoiceClient."
msgstr "Quelque chose ne va pas, nous n'avons pas obtenu le VoiceClient."

#. Used by: debug
#: musicbot/bot.py:1072
msgid "Running on_player_play"
msgstr "En cours d'exécution sur_player_play"

#. Used by: debug
#: musicbot/bot.py:1147
#, python-format
msgid "Setting URL history guild %(guild_id)s == %(url)s"
msgstr "Définition de l'historique des URL %(guild_id)s == %(url)s"

#. Used by: warning
#: musicbot/bot.py:1183 musicbot/bot.py:4940
#, python-format
msgid "No thumbnail set for entry with URL: %s"
msgstr "Aucune vignette définie pour l'entrée avec l'URL : %s"

#. Used by: debug
#: musicbot/bot.py:1195
msgid "no channel to put now playing message into"
msgstr "aucun canal dans lequel mettre le message en cours de lecture"

#. Used by: debug
#: musicbot/bot.py:1207
msgid "ignored now-playing message as it was already posted."
msgstr "a ignoré le message qui était déjà publié."

#. Used by: debug
#: musicbot/bot.py:1231
msgid "Running on_player_resume"
msgstr "En cours d'exécution sur_player_resume"

#. Used by: debug
#: musicbot/bot.py:1244
msgid "Running on_player_pause"
msgstr "En cours de mise en pause"

#. Used by: debug
#: musicbot/bot.py:1260
msgid "Running on_player_stop"
msgstr "Exécution sur_player_stop"

#. Used by: debug
#: musicbot/bot.py:1270
msgid "Running on_player_finished_playing"
msgstr "Lancement sur_player_finished_playing"

#. Used by: debug
#: musicbot/bot.py:1272 musicbot/bot.py:1318 musicbot/bot.py:1389
msgid "Event loop is closed, nothing else to do here."
msgstr "La boucle événement est fermée, rien d'autre à faire ici."

#. Used by: debug
#: musicbot/bot.py:1276 musicbot/bot.py:1322 musicbot/bot.py:1393
msgid "Logout under way, ignoring this event."
msgstr "Déconnexion en cours, ignorant cet événement."

#. Used by: debug
#: musicbot/bot.py:1293
msgid "VoiceClient says it is not connected, nothing else we can do here."
msgstr ""
"VoiceClient dit qu'il n'est pas connecté, rien d'autre que nous pouvons "
"faire ici."

#. Used by: info
#: musicbot/bot.py:1300
msgid "Player finished and queue is empty, leaving voice channel..."
msgstr ""
"Lecteur terminé et la file d'attente est vide, laissant le canal vocal..."

#. Used by: everything
#: musicbot/bot.py:1314
msgid "Looping over queue to expunge songs with missing author..."
msgstr ""
"Bouclage de la file d'attente pour éliminer les chansons avec l'auteur "
"manquant..."

#. Used by: noise
#: musicbot/bot.py:1353
#, python-format
msgid ""
"Author `%(user)s` absent, skipped (deleted) entry from queue:  %(song)s"
msgstr ""
"Auteur `%(user)s` absent, entrée ignorée (supprimée) de la file d'attente :"
"  %(song)s"

#. Used by: warning
#: musicbot/bot.py:1372
msgid "No playable songs in the Guild autoplaylist, disabling."
msgstr ""
"Aucune chanson jouable dans la liste de lecture automatique de la Guilde, "
"désactivée."

#. Used by: debug
#: musicbot/bot.py:1377
msgid "No content in current autoplaylist. Filling with new music..."
msgstr ""
"Aucun contenu dans la liste de lecture automatique actuelle. Remplissage "
"avec une nouvelle musique..."

#. Used by: everything
#: musicbot/bot.py:1385
msgid "Looping over player autoplaylist..."
msgstr "Bouclage de la liste de lecture automatique du joueur..."

#. Used by: error
#: musicbot/bot.py:1426
#, python-format
msgid "Error while processing song \"%(url)s\":  %(raw_error)s"
msgstr "Erreur lors du traitement de la chanson \"%(url)s\" :  %(raw_error)s"

#. Used by: error
#: musicbot/bot.py:1437
#, python-format
msgid "Error extracting song \"%(url)s\": %(raw_error)s"
msgstr "Erreur lors de l'extraction de la chanson \"%(url)s\" : %(raw_error)s"

#. Used by: exception
#: musicbot/bot.py:1452
msgid "MusicBot needs to stop the auto playlist extraction and bail."
msgstr ""
"MusicBot a besoin de mettre fin à l'extraction et au sauvetage de la liste "
"de lecture automatique."

#. Used by: exception
#: musicbot/bot.py:1457
msgid "MusicBot got an unhandled exception in player finished event."
msgstr ""
"MusicBot a obtenu une exception non gérée dans l'événement fini du lecteur."

#. Used by: info
#: musicbot/bot.py:1463
#, python-format
msgid "Expanding auto playlist with entries extracted from:  %s"
msgstr ""
"Étendre la liste de lecture automatique avec les entrées extraites de:  %s"

#. Used by: error
#: musicbot/bot.py:1487
#, python-format
msgid "Error adding song from autoplaylist: %s"
msgstr ""
"Erreur lors de l'ajout de la chanson de la liste de lecture automatique : %s"

#. Used by: debug
#: musicbot/bot.py:1490
msgid "Exception data for above error:"
msgstr "Données d'exception pour l'erreur ci-dessus :"

#. Used by: warning
#: musicbot/bot.py:1496
msgid "No playable songs in the autoplaylist, disabling."
msgstr ""
"Aucune musique jouable dans la liste de lecture automatique, désactivation."

#. Used by: debug
#: musicbot/bot.py:1516
msgid "Running on_player_entry_added"
msgstr "En cours d'exécution sur_player_entry_added"

#. Used by: debug
#: musicbot/bot.py:1526
msgid "Automatically skipping auto-playlist entry for queued entry."
msgstr ""
"Ignorer automatiquement l'entrée de la liste de lecture automatique pour "
"l'entrée en file d'attente."

#. Used by: exception
#: musicbot/bot.py:1546
#, python-format
msgid "MusicPlayer exception for entry: %r"
msgstr "Exception MusicPlayer pour l'entrée : %r"

#. Used by: exception
#: musicbot/bot.py:1552
msgid "MusicPlayer exception."
msgstr "Exception MusicPlayer."

#. Used by: info
#: musicbot/bot.py:1576
#, python-format
msgid "Auto playlist track could not be played:  %r"
msgstr "Impossible de lire la piste de la liste de lecture automatique : %r"

#. Used by: debug
#: musicbot/bot.py:1615
msgid "Logout under way, ignoring status update event."
msgstr "Déconnexion en cours, ignorant la mise à jour de l'événement."

#. Used by: noise
#: musicbot/bot.py:1716
#, python-format
msgid "Update bot status:  %(status)s -- %(activity)r"
msgstr "Mettre à jour le statut du bot :  %(status)s -- %(activity)r"

#. Used by: debug
#: musicbot/bot.py:1744
#, python-format
msgid "Serializing queue for %s"
msgstr "Sérialisation de la file d'attente pour %s"

#. Used by: debug
#: musicbot/bot.py:1770
#, python-format
msgid "Deserializing queue for %s"
msgstr "Désérialisation de la file d'attente pour %s"

#. Used by: debug
#: musicbot/bot.py:1788
#, python-format
msgid "Writing current song for %s"
msgstr "Écriture de la chanson actuelle pour %s"

#. Used by: error
#: musicbot/bot.py:1813
#, python-format
msgid "Cannot send non-response object:  %r"
msgstr "Impossible d'envoyer l'objet sans réponse :  %r"

#. Used by: MusicbotException
#: musicbot/bot.py:1818
msgid "[Dev Bug] Tried sending an invalid response object."
msgstr "[Dev Bug] Tentative d'envoi d'un objet de réponse invalide."

#. Used by: debug
#: musicbot/bot.py:1855
#, python-format
msgid "sending embed to: %s"
msgstr "envoi d'intégrations à: %s"

#. Used by: debug
#: musicbot/bot.py:1858
#, python-format
msgid "sending text to: %s"
msgstr "envoi de texte à: %s"

#. Used by: error
#: musicbot/bot.py:1863
#, python-format
msgid "Cannot send message to \"%s\", no permission"
msgstr "Impossible d'envoyer le message à \"%s\", aucune permission"

#. Used by: error
#: musicbot/bot.py:1870
#, python-format
msgid "Cannot send message to \"%s\", invalid or deleted channel"
msgstr "Impossible d'envoyer le message à \"%s\", canal invalide ou supprimé"

#. Used by: error
#: musicbot/bot.py:1878
#, python-format
msgid "Message is over the message size limit (%s)"
msgstr "Le message dépasse la limite de taille du message (%s)"

#. Used by: debug
#: musicbot/bot.py:1886
msgid "Could not send private message, sending in fallback channel instead."
msgstr ""
"Impossible d'envoyer un message privé, en envoyant un canal de secours à la "
"place."

#. Used by: warning
#: musicbot/bot.py:1904
#, python-format
msgid "Rate limited send message, retrying in %s seconds."
msgstr "Noter un message d'envoi limité, nouvel essai dans %s secondes."

#. Used by: warning
#: musicbot/bot.py:1910
#, python-format
msgid "Cancelled message retry for:  %s"
msgstr "Message annulé à nouveau pour :  %s"

#. Used by: error
#: musicbot/bot.py:1915
msgid "Rate limited send message, but cannot retry!"
msgstr "Noter un message d'envoi limité, mais ne peut pas recommencer!"

#. Used by: error
#: musicbot/bot.py:1921
msgid "Failed to send message in fallback channel."
msgstr "Impossible d'envoyer le message dans le canal de repli."

#. Used by: error
#: musicbot/bot.py:1926 musicbot/bot.py:1990 musicbot/bot.py:2060
msgid "Failed to send due to an HTTP error."
msgstr "Échec de l'envoi en raison d'une erreur HTTP."

#. Used by: warning
#: musicbot/bot.py:1952
#, python-format
msgid "Cannot delete message \"%s\", no permission"
msgstr "Impossible de supprimer le message \"%s\", aucune permission"

#. Used by: warning
#: musicbot/bot.py:1957
#, python-format
msgid "Cannot delete message \"%s\", message not found"
msgstr "Impossible de supprimer le message \"%s\", message introuvable"

#. Used by: warning
#: musicbot/bot.py:1975
#, python-format
msgid "Rate limited message delete, retrying in %s seconds."
msgstr ""
"Noter la suppression de messages limités, nouvel essai dans %s secondes."

#. Used by: error
#: musicbot/bot.py:1980
msgid "Rate limited message delete, but cannot retry!"
msgstr ""
"Noter la suppression de messages limités, mais ne peut pas recommencer !"

#. Used by: warning
#: musicbot/bot.py:1983
msgid "Failed to delete message"
msgstr "Échec de la suppression du message"

#. Used by: noise
#: musicbot/bot.py:1985
#, python-format
msgid "Got HTTPException trying to delete message: %s"
msgstr "Erreur HTTPException lors de la suppression du message : %s"

#. Used by: warning
#: musicbot/bot.py:2020
#, python-format
msgid "Cannot edit message \"%s\", message not found"
msgstr "Impossible de modifier le message \"%s\", message introuvable"

#. Used by: warning
#: musicbot/bot.py:2024
msgid "Sending message instead"
msgstr "Envoi du message à la place"

#. Used by: warning
#: musicbot/bot.py:2041
#, python-format
msgid "Rate limited edit message, retrying in %s seconds."
msgstr "Noter le message d'édition limité, nouvel essai dans %s secondes."

#. Used by: warning
#: musicbot/bot.py:2047
#, python-format
msgid "Cancelled message edit for:  %s"
msgstr "Modification du message annulée pour :  %s"

#. Used by: warning
#: musicbot/bot.py:2053
msgid "Failed to edit message"
msgstr "Impossible de modifier le message"

#. Used by: noise
#: musicbot/bot.py:2055
#, python-format
msgid "Got HTTPException trying to edit message %s to: %s"
msgstr "Exception HTTPException essayant d'éditer le message %s à: %s"

#. Used by: warning
#: musicbot/bot.py:2077
#, python-format
msgid "Cancelled delete for message (ID: %(id)s):  %(content)s"
msgstr "Suppression du message annulée (ID: %(id)s):  %(content)s"

#. Used by: warning
#: musicbot/bot.py:2139
#, python-format
msgid "Caught a signal from the OS: %s"
msgstr "Signal du système d'exploitation attrapé : %s"

#. Used by: info
#: musicbot/bot.py:2143
msgid "Disconnecting and closing down MusicBot..."
msgstr "Déconnexion et fermeture de MusicBot..."

#. Used by: exception
#: musicbot/bot.py:2146
msgid "Exception thrown while handling interrupt signal!"
msgstr "Exception lancée lors de la gestion du signal d'interruption !"

#. Used by: info
#: musicbot/bot.py:2161
msgid "MusicBot is now doing shutdown steps..."
msgstr "MusicBot fait maintenant des étapes d'arrêt..."

#. Used by: HelpfulError
#: musicbot/bot.py:2169
msgid ""
"Failed Discord API Login!\n"
"\n"
"Problem:\n"
"  MusicBot could not log into Discord API.\n"
"  Your Token may be incorrect or there may be an API outage.\n"
"\n"
"Solution:\n"
"  Make sure you have the correct Token set in your config.\n"
"  Check API status at the official site: discordstatus.com"
msgstr ""
"Échec de la connexion à l'API Discord !\n"
"\n"
"Problème :\n"
"  MusicBot n'a pas pu se connecter à l'API Discord.\n"
"  Votre jeton est peut-être incorrect ou il peut y avoir une panne d'API.\n"
"\n"
"Solution :\n"
"  Assurez-vous que le bon jeton est défini dans votre configuration.\n"
"  Vérifiez l'état de l'API sur le site officiel : discordstatus.com"

#. Used by: info
#: musicbot/bot.py:2183
msgid "Waiting for download threads to finish up..."
msgstr "En attente de la fin du téléchargement..."

#. Used by: debug
#: musicbot/bot.py:2209
#, python-format
msgid "Will wait for task:  %(name)s  (%(func)s)"
msgstr "Va attendre la tâche :  %(name)s  (%(func)s)"

#. Used by: debug
#: musicbot/bot.py:2216
#, python-format
msgid "Will try to cancel task:  %(name)s  (%(func)s)"
msgstr "Essaiera d'annuler la tâche :  %(name)s  (%(func)s)"

#. Used by: debug
#: musicbot/bot.py:2224
msgid "Awaiting pending tasks..."
msgstr "En attente de tâches..."

#. Used by: debug
#: musicbot/bot.py:2230
msgid "Closing HTTP Connector."
msgstr "Fermeture du connecteur HTTP."

#. Used by: debug
#: musicbot/bot.py:2236
msgid "Closing aiohttp session."
msgstr "Fermeture de la session aiohttp."

#. Used by: noise
#: musicbot/bot.py:2248
msgid "Logout has been called."
msgstr "La déconnexion a été appelée."

#. Used by: error
#: musicbot/bot.py:2260
#, python-format
msgid ""
"Exception in %(event)s:\n"
"%(error)s"
msgstr ""
"Exception dans %(event)s:\n"
"%(error)s"

#. Used by: error
#: musicbot/bot.py:2276
#, python-format
msgid "Exception in %s"
msgstr "Exception dans %s"

#. Used by: info
#: musicbot/bot.py:2283
msgid "MusicBot resumed a session with discord."
msgstr "MusicBot a repris une session avec discord."

#. Used by: debug
#: musicbot/bot.py:2300
msgid "Finish on_ready"
msgstr "Terminer le _prêt"

#. Used by: debug
#: musicbot/bot.py:2307
msgid "Logged in, now getting MusicBot ready..."
msgstr "Connecté, maintenant que MusicBot est prêt..."

#. Used by: critical
#: musicbot/bot.py:2310
msgid "ClientUser is somehow none, we gotta bail..."
msgstr "ClientUser est en quelque sorte aucun, nous devons sauvegarder..."

#. Used by: info
#: musicbot/bot.py:2319
#, python-format
msgid "MusicBot:  %(id)s/%(name)s#%(desc)s"
msgstr "MusicBot:  %(id)s/%(name)s#%(desc)s"

#. Used by: info
#: musicbot/bot.py:2330
#, python-format
msgid "Owner:     %(id)s/%(name)s#%(desc)s\n"
msgstr "Propriétaire :     %(id)s/%(name)s#%(desc)s\n"

#. Used by: info
#: musicbot/bot.py:2338 musicbot/bot.py:2365
msgid "Guild List:"
msgstr "Liste de guilde:"

#. Used by: info
#. Used by: debug
#: musicbot/bot.py:2342 musicbot/bot.py:2368 musicbot/bot.py:8862
#, python-format
msgid " - %s"
msgstr " - %s"

#. Used by: info
#: musicbot/bot.py:2351
#, python-format
msgid "Left %s due to bot owner not found"
msgstr "A quitté %s en raison du propriétaire du bot introuvable"

#. Used by: info
#: musicbot/bot.py:2356
#, python-format
msgid "Not proceeding with checks in %s servers due to unavailability"
msgstr ""
"Ne pas procéder aux vérifications sur les serveurs %s en raison d'une "
"indisponibilité"

#. Used by: warning
#: musicbot/bot.py:2362
#, python-format
msgid "Owner could not be found on any guild (id: %s)\n"
msgstr "Le propriétaire n'a pas pu être trouvé sur une guilde (id : %s)\n"

#. Used by: warning
#: musicbot/bot.py:2371
msgid "Owner unknown, bot is not on any guilds."
msgstr "Propriétaire inconnu, le bot n'est sur aucune guilde."

#. Used by: warning
#: musicbot/bot.py:2375
#, python-format
msgid ""
"To make the bot join a guild, paste this link in your browser. \n"
"Note: You should be logged into your main account and have \n"
"manage server permissions on the guild you want the bot to join.\n"
"  %s"
msgstr ""
"Pour que le bot rejoigne une guilde, collez ce lien dans votre navigateur. \n"
"Note : Vous devez être connecté à votre compte principal et avoir \n"
"gérer les permissions du serveur sur la guilde que vous voulez que le bot rejoigne.\n"
"  %s"

#. Used by: warning
#: musicbot/bot.py:2392
#, python-format
msgid "Got None for bound channel with ID:  %d"
msgstr "Aucun n'a été pour le canal lié avec l'ID :  %d"

#. Used by: warning
#: musicbot/bot.py:2398
#, python-format
msgid "Cannot bind to non Messageable channel with ID:  %d"
msgstr "Impossible de se lier à un canal non Messageable avec l'ID :  %d"

#. Used by: info
#: musicbot/bot.py:2412
msgid "Bound to text channels:"
msgstr "Lié aux salons textuels :"

#. Used by: info
#: musicbot/bot.py:2430 musicbot/bot.py:2480
#, python-format
msgid " - %(guild)s/%(channel)s"
msgstr " - %(guild)s/%(channel)s"

#. Used by: info
#: musicbot/bot.py:2434 musicbot/bot.py:2436
msgid "Not bound to any text channels"
msgstr "Non lié à aucun salon textuel"

#. Used by: warning
#: musicbot/bot.py:2447
#, python-format
msgid "Got None for auto join channel with ID:  %d"
msgstr ""
"Aucun n'a été trouvé pour le canal d'accès automatique avec l'ID :  %d"

#. Used by: warning
#: musicbot/bot.py:2453
#, python-format
msgid "Cannot auto join a Private/Non-Guild channel with ID:  %d"
msgstr ""
"Impossible de rejoindre automatiquement un canal Privé/Non-Guilde avec l'ID "
":  %d"

#. Used by: warning
#: musicbot/bot.py:2461
#, python-format
msgid "Cannot auto join to non-connectable channel with ID:  %d"
msgstr ""
"Impossible de joindre automatiquement au canal non connectable avec l'ID :  "
"%d"

#. Used by: info
#: musicbot/bot.py:2477
msgid "Auto joining voice channels:"
msgstr "Rejoindre automatiquement les salons vocaux:"

#. Used by: info
#: musicbot/bot.py:2485 musicbot/bot.py:2488
msgid "Not auto joining any voice channels"
msgstr "Ne pas rejoindre automatiquement les salons vocaux"

#. Used by: warning
#: musicbot/bot.py:2501
#, python-format
msgid ""
"Detected missing config options!\n"
"\n"
"Problem:\n"
"  You config options file is missing some options.\n"
"  Default settings will be used for these options.\n"
"  Here is a list of options we didn't find:\n"
"  %(missing)s\n"
"\n"
"Solution:\n"
"  Copy new options from the example options file.\n"
"  Or use the config command to set and save them.\n"
"\n"
msgstr ""
"Options de configuration manquantes détectées !\n"
"\n"
"Problème :\n"
"  Il manque certaines options à votre fichier d'options de configuration.\n"
"  Les paramètres par défaut seront utilisés pour ces options.\n"
"  Voici une liste d'options que nous n'avons pas trouvées :\n"
"  %(missing)s\n"
"\n"
"Solution :\n"
"  Copiez les nouvelles options à partir du fichier d'options d'exemple.\n"
"  Ou utilisez la commande config pour les définir et les enregistrer.\n"
"\n"

#. Used by: debug
#: musicbot/bot.py:2530
#, python-format
msgid "Event on_ready has fired %s times"
msgstr "L'événement on_ready a été déclenché %s fois"

#. Used by: debug
#: musicbot/bot.py:2546
msgid "Getting application info."
msgstr "Récupération des informations de l'application."

#. Used by: debug
#: musicbot/bot.py:2564
msgid "Ensuring data folders exist"
msgstr "S'assurer que les dossiers de données existent"

#. Used by: debug
#: musicbot/bot.py:2579
msgid "Validating config"
msgstr "Validation de la configuration"

#. Used by: debug
#: musicbot/bot.py:2582
msgid "Validating permissions config"
msgstr "Validation de la configuration des permissions"

#. Used by: _L
#: musicbot/bot.py:2592
msgid "Disabled"
msgstr "Désactivé"

#. Used by: _L
#: musicbot/bot.py:2592
msgid "Enabled"
msgstr "Activé"

#. Used by: info
#: musicbot/bot.py:2595
msgid "Options:"
msgstr "Options :"

#. Used by: info
#: musicbot/bot.py:2597
#, python-format
msgid "  Command prefix: %s"
msgstr "  Préfixe de commande : %s"

#. Used by: info
#: musicbot/bot.py:2602
#, python-format
msgid "  Default volume: %d%%"
msgstr "  Volume par défaut : %d%%"

#. Used by: info
#: musicbot/bot.py:2604
#, python-format
msgid "  Skip threshold: %(num)d votes or %(percent).0f%%"
msgstr "  Seuil de passage : %(num)d votes ou %(percent).0f%%"

#. Used by: info
#: musicbot/bot.py:2616
#, python-format
msgid "  Now Playing @mentions: %s"
msgstr "  Lecture en cours de @mentions: %s"

#. Used by: info
#: musicbot/bot.py:2623
#, python-format
msgid "  Auto-Playlist: %(status)s (order: %(order)s)"
msgstr "  Liste de lecture automatique : %(status)s (ordre : %(order)s)"

#. Used by: _L
#: musicbot/bot.py:2626
msgid "random"
msgstr "Aléatoire"

#. Used by: _L
#: musicbot/bot.py:2626
msgid "sequential"
msgstr "séquentielle"

#. Used by: info
#: musicbot/bot.py:2646
#, python-format
msgid "  Auto-Pause: %s"
msgstr "  Pause automatique : %s"

#. Used by: info
#: musicbot/bot.py:2648
#, python-format
msgid "  Delete Messages: %s"
msgstr "  Supprimer les messages : %s"

#. Used by: info
#: musicbot/bot.py:2653
#, python-format
msgid "    Delete Invoking: %s"
msgstr "    Suppression de l'appel: %s"

#. Used by: info
#: musicbot/bot.py:2657
#, python-format
msgid "    Delete Now Playing: %s"
msgstr "    Supprimer la lecture en cours : %s"

#. Used by: info
#: musicbot/bot.py:2660
#, python-format
msgid "  Debug Mode: %s"
msgstr "  Mode de débogage : %s"

#. Used by: info
#: musicbot/bot.py:2664
#, python-format
msgid "  Downloaded songs will be %s"
msgstr "  Les chansons téléchargées seront %s"

#. Used by: info
#: musicbot/bot.py:2668
#, python-format
msgid "    Delete if unused for %d days"
msgstr "    Supprimer si inutilisé pour %d jours"

#. Used by: info
#: musicbot/bot.py:2679
#, python-format
msgid "  Status message: %s"
msgstr "  Message de statut : %s"

#. Used by: info
#: musicbot/bot.py:2691
#, python-format
msgid "  Spotify integration: %s"
msgstr "  Intégration Spotify : %s"

#. Used by: info
#: musicbot/bot.py:2704
#, python-format
msgid "    Timeout: %s seconds"
msgstr "    Délai d'expiration : %s secondes"

#. Used by: info
#: musicbot/bot.py:2716
#, python-format
msgid "    Timeout: %d seconds"
msgstr "    Délai d'attente : %d secondes"

#. Used by: info
#: musicbot/bot.py:2717
#, python-format
msgid "  Self Deafen: %s"
msgstr "  Soi-même sourd : %s"

#. Used by: info
#: musicbot/bot.py:2719
#, python-format
msgid "  Per-server command prefix: %s"
msgstr "  Préfixe de commande par serveur : %s"

#. Used by: info
#: musicbot/bot.py:2725
#, python-format
msgid "  Round Robin Queue: %s"
msgstr "  Queue de Round Robin: %s"

#. Used by: CommandError
#: musicbot/bot.py:2780
#, python-format
msgid "The requested song `%(subject)s` is blocked by the song block list."
msgstr ""
"La chanson demandée `%(subject)s` est bloquée par la liste de blocage de "
"chansons."

#. Used by: warning
#: musicbot/bot.py:2791
msgid ""
"Attempted to handle Voice Channel inactivity, but Bot is not in voice..."
msgstr ""
"Tentative de gestion de l'inactivité du canal vocal, mais le bot n'est pas "
"dans la voix..."

#. Used by: debug
#: musicbot/bot.py:2798
#, python-format
msgid "Channel activity already waiting in guild: %s"
msgstr "L'activité du canal est déjà en attente dans la guilde : %s"

#. Used by: info
#: musicbot/bot.py:2808
#, python-format
msgid ""
"Channel activity waiting %(time)d seconds to leave channel: %(channel)s"
msgstr ""
"Activité du canal en attente %(time)d secondes pour quitter le canal : "
"%(channel)s"

#. Used by: info
#: musicbot/bot.py:2823
#, python-format
msgid "Channel activity timer for %s has expired. Disconnecting."
msgstr "La minuterie d'activité du canal %s a expiré. Déconnexion."

#. Used by: info
#: musicbot/bot.py:2829
#, python-format
msgid "Channel activity timer canceled for: %(channel)s in %(guild)s"
msgstr ""
"La minuterie d'activité du canal a été annulée pour: %(channel)s dans "
"%(guild)s"

#. Used by: debug
#: musicbot/bot.py:2857
#, python-format
msgid "Ignoring player inactivity in auto-joined channel:  %s"
msgstr "Inactivité du joueur ignorée dans le canal auto-rejoint :  %s"

#. Used by: debug
#: musicbot/bot.py:2864
#, python-format
msgid "Player activity timer already waiting in guild: %s"
msgstr ""
"La minuterie d'activité du joueur est déjà en attente dans la guilde : %s"

#. Used by: info
#: musicbot/bot.py:2872
#, python-format
msgid ""
"Player activity timer waiting %(time)d seconds to leave channel: %(channel)s"
msgstr ""
"Délai d'activité du joueur en attente %(time)d secondes pour quitter le "
"canal : %(channel)s"

#. Used by: info
#: musicbot/bot.py:2884
#, python-format
msgid "Player activity timer for %s has expired. Disconnecting."
msgstr "La minuterie d'activité du joueur pour %s a expiré. Déconnexion."

#. Used by: info
#: musicbot/bot.py:2890 musicbot/bot.py:2895
#, python-format
msgid "Player activity timer canceled for: %(channel)s in %(guild)s"
msgstr ""
"La minuterie d'activité du joueur a été annulée pour: %(channel)s dans "
"%(guild)s"

#. Used by: debug
#: musicbot/bot.py:2912
msgid "Player activity timer is being reset."
msgstr "Le minuteur d'activité du joueur est en cours de réinitialisation."

#. Used by: CommandError
#: musicbot/bot.py:3021
msgid "No such command"
msgstr "Aucune commande de ce type"

#. Used by: CommandError
#: musicbot/bot.py:3097
msgid "You must mention a user or provide their ID number."
msgstr ""
"Vous devez mentionner un utilisateur ou fournir son numéro d'identité."

#. Used by: CommandError
#: musicbot/bot.py:3102
msgid "Invalid sub-command given. Use `help blockuser` for usage examples."
msgstr ""
"Sous-commande invalide. Utilisez `help blockuser` pour des exemples "
"d'utilisation."

#. Used by: CommandError
#: musicbot/bot.py:3113
msgid "MusicBot could not find the user(s) you specified."
msgstr "MusicBot n'a pas pu trouver les utilisateurs que vous avez spécifiés."

#. Used by: CommandError
#: musicbot/bot.py:3120
msgid "The owner cannot be added to the block list."
msgstr "Le propriétaire ne peut pas être ajouté à la liste de blocs."

#. Used by: info
#: musicbot/bot.py:3124
#, python-format
msgid "Not adding user to block list, already blocked:  %(id)s/%(name)s"
msgstr ""
"Impossible d'ajouter un utilisateur à la liste de blocage, déjà bloqué :  "
"%(id)s/%(name)s"

#. Used by: info
#: musicbot/bot.py:3133
#, python-format
msgid "Not removing user from block list, not listed:  %(id)s/%(name)s"
msgstr ""
"Ne pas supprimer l'utilisateur de la liste bloquée, non listé :  "
"%(id)s/%(name)s"

#. Used by: CommandError
#: musicbot/bot.py:3150
msgid "Cannot add the users you listed, they are already added."
msgstr ""
"Impossible d'ajouter les utilisateurs que vous avez listés, ils sont déjà "
"ajoutés."

#. Used by: CommandError
#: musicbot/bot.py:3227
msgid "You must provide a song subject if no song is currently playing."
msgstr ""
"Vous devez indiquer un sujet si aucune chanson n'est en cours de lecture."

#. Used by: CommandError
#: musicbot/bot.py:3233
msgid "Invalid sub-command given. Use `help blocksong` for usage examples."
msgstr ""
"Sous-commande invalide. Utilisez `help blocksong` pour des exemples "
"d'utilisation."

#. Used by: CommandError
#: musicbot/bot.py:3245
#, python-format
msgid "Subject `%(subject)s` is already in the song block list."
msgstr "Sujet `%(subject)s` est déjà dans la liste de blocage de chansons."

#. Used by: CommandError
#: musicbot/bot.py:3277
msgid "The subject is not in the song block list and cannot be removed."
msgstr ""
"Le sujet n'est pas dans la liste des chansons bloquées et ne peut pas être "
"supprimé."

#. Used by: CommandError
#: musicbot/bot.py:3349
msgid "Invalid sub-command given. Use `help autoplaylist` for usage examples."
msgstr ""
"Sous-commande invalide. Utilisez `help autoplaylist` pour des exemples "
"d'utilisation."

#. Used by: CommandError
#: musicbot/bot.py:3356
msgid "The supplied song link is invalid"
msgstr "Le lien de la chanson fournie n'est pas valide"

#. Used by: CommandError
#: musicbot/bot.py:3362
msgid "The queue is empty. Add some songs with a play command!"
msgstr ""
"La file d'attente est vide. Ajoutez des morceaux avec une commande de "
"lecture!"

#. Used by: CommandError
#: musicbot/bot.py:3390
msgid "This song is already in the autoplaylist."
msgstr "Cette chanson est déjà dans la liste de lecture automatique."

#. Used by: CommandError
#: musicbot/bot.py:3407
msgid "This song is not yet in the autoplaylist."
msgstr "Cette chanson n'est pas encore dans la liste de lecture automatique."

#. Used by: CommandError
#: musicbot/bot.py:3441
msgid "You must provide a playlist filename."
msgstr "Vous devez fournir un nom de fichier de playlist."

#. Used by: PermissionsError
#: musicbot/bot.py:3551
msgid "You are not allowed to request playlists"
msgstr "Vous n'êtes pas autorisé à demander des playlists"

#. Used by: PermissionsError
#: musicbot/bot.py:3559
#, python-format
msgid "Playlist has too many entries (%(songs)s but max is %(max)s)"
msgstr "La playlist a trop d'entrées (%(songs)s mais max est %(max)s)"

#. Used by: PermissionsError
#: musicbot/bot.py:3570
#, python-format
msgid ""
"The playlist entries will exceed your queue limit.\n"
"There are %(songs)s in the list, and %(queued)s already in queue.\n"
"The limit is %(max)s for your group."
msgstr ""
"Les entrées de la liste de lecture dépasseront votre limite de file d'attente.\n"
"Il y a %(songs)s dans la liste, et %(queued)s déjà dans la file d'attente.\n"
"La limite est %(max)s pour votre groupe."

#. Used by: debug
#: musicbot/bot.py:3594
msgid "Ignoring auto-pause due to network outage."
msgstr "Ignorer la pause automatique en raison d'une panne de réseau."

#. Used by: voicedebug
#: musicbot/bot.py:3599
msgid ""
"MusicPlayer has no VoiceClient or has no channel data, cannot process auto-"
"pause."
msgstr ""
"MusicPlayer n'a pas de client vocal ou n'a pas de données de canal, ne peut "
"pas traiter la pause automatique."

#. Used by: debug
#: musicbot/bot.py:3610
msgid "Already processing auto-pause, ignoring this event."
msgstr "Traitement de la pause automatique, ignorant cet événement."

#. Used by: warning
#: musicbot/bot.py:3618
#, python-format
msgid ""
"%sVoiceClient not connected, waiting %s seconds to handle auto-pause in "
"guild:  %s"
msgstr ""
"%sClient vocal non connecté, en attente de %s secondes pour gérer la pause "
"automatique dans la guilde :  %s"

#. Used by: debug
#: musicbot/bot.py:3626
msgid "Auto-pause waiting was cancelled."
msgstr "L'attente de pause automatique a été annulée."

#. Used by: info
#: musicbot/bot.py:3633
msgid "A new MusicPlayer is being connected, ignoring old auto-pause event."
msgstr ""
"Un nouveau MusicPlayer est en cours de connexion, ignorant l'ancien "
"événement de pause automatique."

#. Used by: info
#: musicbot/bot.py:3649
#, python-format
msgid "Playing in an empty voice channel, running auto pause for guild: %s"
msgstr ""
"Lecture dans un salon vocal vide, pause automatique pour la guilde : %s"

#. Used by: info
#: musicbot/bot.py:3656
#, python-format
msgid "Previously auto paused player is unpausing for guild: %s"
msgstr "Le joueur en pause automatique est en pause pour la guilde : %s"

#. Used by: CommandError
#: musicbot/bot.py:3887
msgid "Cannot use seek if there is nothing playing."
msgstr "Impossible d'utiliser seek s'il n'y a rien à jouer."

#. Used by: CommandError
#: musicbot/bot.py:3892
msgid "Cannot use seek on current track, it has an unknown duration."
msgstr ""
"Impossible d'utiliser la recherche sur la piste en cours, elle a une durée "
"inconnue."

#. Used by: CommandError
#: musicbot/bot.py:3898
msgid "Seeking is not supported for streams."
msgstr "La recherche n'est pas prise en charge pour les flux."

#. Used by: CommandError
#: musicbot/bot.py:3908
msgid "Cannot use seek without a time to position playback."
msgstr ""
"Impossible d'utiliser la recherche sans un temps pour positionner la "
"lecture."

#. Used by: CommandError
#: musicbot/bot.py:3926
#, python-format
msgid "Could not convert `%(input)s` to a valid time in seconds."
msgstr "Impossible de convertir `%(input)s` en une heure valide en secondes."

#. Used by: CommandError
#: musicbot/bot.py:3939
#, python-format
msgid ""
"Cannot seek to `%(input)s` (`%(seconds)s` seconds) in the current track with"
" a length of `%(progress)s / %(total)s`"
msgstr ""
"Impossible de chercher à `%(input)s` (`%(seconds)s` secondes) dans la piste "
"actuelle avec une longueur de `%(progress)s / %(total)s`"

#. Used by: CommandError
#: musicbot/bot.py:4000
msgid "Invalid sub-command. Use the command `help repeat` for usage examples."
msgstr ""
"Sous-commande invalide. Utilisez la commande `help repeat` pour des exemples"
" d'utilisation."

#. Used by: CommandError
#: musicbot/bot.py:4038
msgid "The player is not currently looping."
msgstr "Le joueur n'est pas en boucle."

#. Used by: CommandError
#: musicbot/bot.py:4094
msgid "Song positions must be integers!"
msgstr "Les positions de la chanson doivent être des entiers !"

#. Used by: CommandError
#: musicbot/bot.py:4099
msgid "You gave a position outside the playlist size!"
msgstr "Vous avez donné une position en dehors de la taille de la playlist !"

#. Used by: warning
#: musicbot/bot.py:4147
msgid ""
"Could not prompt for playlist playback, no message to add reactions to."
msgstr ""
"N'a pas pu demander la lecture de la playlist, aucun message à ajouter des "
"réactions."

#. Used by: CommandError
#: musicbot/bot.py:4236
msgid "Local media playback is not enabled."
msgstr "La lecture des médias locaux n'est pas activée."

#. Used by: CommandError
#: musicbot/bot.py:4279
msgid "Spotify URL is invalid or not currently supported."
msgstr ""
"L'URL Spotify n'est pas valide ou n'est pas prise en charge actuellement."

#. Used by: CommandError
#: musicbot/bot.py:4283
msgid "Detected a Spotify URL, but Spotify is not enabled."
msgstr "Une URL Spotify a été détectée, mais Spotify n'est pas activé."

#. Used by: PermissionsError
#: musicbot/bot.py:4293 musicbot/bot.py:4498
#, python-format
msgid "You have reached your enqueued song limit (%(max)s)"
msgstr "Vous avez atteint votre limite de chansons en attente (%(max)s)"

#. Used by: PermissionsError
#: musicbot/bot.py:4299 musicbot/bot.py:4504 musicbot/bot.py:4601
msgid "Karaoke mode is enabled, please try again when its disabled!"
msgstr ""
"Le mode Karaoké est activé, veuillez réessayer quand il est désactivé!"

#. Used by: exception
#: musicbot/bot.py:4311
msgid "Issue with extract_info(): "
msgstr "Problème avec extract_info() : "

#. Used by: CommandError
#: musicbot/bot.py:4315 musicbot/bot.py:4520
#, python-format
msgid ""
"Failed to extract info due to error:\n"
"%(raw_error)s"
msgstr ""
"Échec de l'extraction des informations en raison d'une erreur :\n"
"%(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:4321
msgid "That video cannot be played. Try using the stream command."
msgstr ""
"Cette vidéo ne peut pas être lue. Essayez d'utiliser la commande stream."

#. Used by: CommandError
#: musicbot/bot.py:4332
#, python-format
msgid "YouTube search returned no results for:  %(url)s"
msgstr "La recherche YouTube n'a retourné aucun résultat pour :  %(url)s"

#. Used by: info
#: musicbot/bot.py:4362
#, python-format
msgid ""
"Processed %(number)d of %(total)d songs in %(time).3f seconds at "
"%(time_per).2f s/song"
msgstr ""
"Traité %(number)d de %(total)d chansons en %(time).3f secondes à "
"%(time_per).2f s/chanson"

#. Used by: CommandError
#: musicbot/bot.py:4373
#, python-format
msgid ""
"No songs were added, all songs were over max duration (%(max)s seconds)"
msgstr ""
"Aucune chanson n'a été ajoutée, toutes les chansons ont été supérieures à la"
" durée maximale (%(max)s secondes)"

#. Used by: noise
#: musicbot/bot.py:4389
msgid "Extracted an entry with 'youtube:playlist' as extractor key"
msgstr "Extrait une entrée avec 'youtube:playlist' comme clé d'extracteur"

#. Used by: PermissionsError
#: musicbot/bot.py:4401
#, python-format
msgid "Song duration exceeds limit (%(length)s > %(max)s)"
msgstr "La durée de la musique dépasse la limite (%(length)s > %(max)s)"

#. Used by: debug
#: musicbot/bot.py:4419
#, python-format
msgid "Added song(s) at position %s"
msgstr "Chanson(s) ajoutée à la position %s"

#. Used by: warning
#: musicbot/bot.py:4456
#, python-format
msgid "Cannot estimate time until playing for position: %d"
msgstr "Impossible d'estimer le temps avant de jouer pour la position : %d"

#. Used by: exception
#: musicbot/bot.py:4517
#, python-format
msgid "Failed to get info from the stream request: %s"
msgstr "Impossible d'obtenir les informations de la demande de flux: %s"

#. Used by: CommandError
#: musicbot/bot.py:4526
msgid "Streaming playlists is not yet supported."
msgstr "La diffusion de listes de lecture n'est pas encore prise en charge."

#. Used by: PermissionsError
#: musicbot/bot.py:4595
#, python-format
msgid "You have reached your playlist item limit (%(max)s)"
msgstr "Vous avez atteint la limite d'élément de votre playlist (%(max)s)"

#. Used by: CommandError
#: musicbot/bot.py:4607
msgid ""
"Please specify a search query.  Use `help search` for more information."
msgstr ""
"Veuillez spécifier une requête de recherche. Utilisez `help search` pour "
"plus d'informations."

#. Used by: CommandError
#: musicbot/bot.py:4643
#, python-format
msgid "You cannot search for more than %(max)s videos"
msgstr "Vous ne pouvez pas rechercher plus de vidéos %(max)s"

#. Used by: debug
#: musicbot/bot.py:4968
#, python-format
msgid "Waiting for summon lock: %s"
msgstr "En attente d'un verrou d'invocation : %s"

#. Used by: debug
#: musicbot/bot.py:4971
#, python-format
msgid "Summon lock acquired for: %s"
msgstr "Verrouillage de convocation acquis pour: %s"

#. Used by: CommandError
#: musicbot/bot.py:4975
msgid "You are not connected to voice. Try joining a voice channel!"
msgstr ""
"Vous n'êtes pas connecté à la voix. Essayez de rejoindre un salon vocal !"

#. Used by: info
#: musicbot/bot.py:5000
#, python-format
msgid "Joining %(guild)s/%(channel)s"
msgstr "Rejoindre %(guild)s/%(channel)s"

#. Used by: CommandError
#: musicbot/bot.py:5062
msgid "MusicBot cannot follow a user that is not a member of the server."
msgstr ""
"MusicBot ne peut pas suivre un utilisateur qui n'est pas membre du serveur."

#. Used by: CommandError
#: musicbot/bot.py:5090
msgid "Player is not playing."
msgstr "Le joueur ne joue pas."

#. Used by: CommandError
#: musicbot/bot.py:5215
msgid "Nothing in the queue to remove!"
msgstr "Rien dans la file d'attente à supprimer !"

#. Used by: CommandError
#: musicbot/bot.py:5236
#, python-format
msgid "Nothing found in the queue from user `%(user)s`"
msgstr ""
"Rien n'a été trouvé dans la file d'attente de l'utilisateur `%(user)s`"

#. Used by: PermissionsError
#: musicbot/bot.py:5241 musicbot/bot.py:5277
msgid ""
"You do not have the permission to remove that entry from the queue.\n"
"You must be the one who queued it or have instant skip permissions."
msgstr ""
"Vous n'avez pas le droit de supprimer cette entrée de la file d'attente.\n"
"Vous devez être celui qui l'a mis en file d'attente ou qui a des permissions de sauter instantanément."

#. Used by: CommandError
#: musicbot/bot.py:5252 musicbot/bot.py:5257
msgid "Invalid entry number. Use the queue command to find queue positions."
msgstr ""
"Numéro d'entrée invalide. Utilisez la commande file d'attente pour trouver "
"les positions de la file d'attente."

#. Used by: CommandError
#: musicbot/bot.py:5308
msgid "Can't skip! The player is not playing!"
msgstr "Impossible de sauter ! Le joueur ne joue pas !"

#. Used by: PermissionsError
#: musicbot/bot.py:5360
msgid "You do not have permission to force skip a looped song."
msgstr ""
"Vous n'avez pas la permission de forcer le saut d'une chanson en boucle."

#. Used by: PermissionsError
#: musicbot/bot.py:5380
msgid "You do not have permission to force skip."
msgstr "Vous n'avez pas la permission de forcer le saut."

#. Used by: PermissionsError
#: musicbot/bot.py:5417 musicbot/bot.py:5450
msgid "You do not have permission to skip a looped song."
msgstr "Vous n'avez pas la permission de sauter une chanson en boucle."

#. Used by: CommandError
#: musicbot/bot.py:5500
#, python-format
msgid "`%(new_volume)s` is not a valid number"
msgstr "`%(new_volume)s` n'est pas un nombre valide"

#. Used by: CommandError
#: musicbot/bot.py:5541
#, python-format
msgid ""
"Unreasonable volume change provided: %(old_volume)s%(adjustment)s is %(new_volume)s.\n"
"Volume can only be set from 1 to 100."
msgstr ""
"Changement de volume déraisonnable fourni: %(old_volume)s%(adjustment)s est %(new_volume)s.\n"
"Le volume ne peut être défini que de 1 à 100."

#. Used by: CommandError
#: musicbot/bot.py:5551
#, python-format
msgid ""
"Unreasonable volume provided: %(volume)s. Provide a value between 1 and 100."
msgstr ""
"Volume déraisonnable fourni: %(volume)s. Fournissez une valeur comprise "
"entre 1 et 100."

#. Used by: CommandError
#: musicbot/bot.py:5575
msgid ""
"No track is playing, cannot set speed.\n"
"Use the config command to set a default playback speed."
msgstr ""
"Aucune piste n'est lue, impossible de définir la vitesse.\n"
"Utilisez la commande de configuration pour définir une vitesse de lecture par défaut."

#. Used by: CommandError
#: musicbot/bot.py:5583
msgid "Speed cannot be applied to streamed media."
msgstr "La vitesse ne peut pas être appliquée aux médias streamés."

#. Used by: CommandError
#: musicbot/bot.py:5588
msgid "You must provide a speed to set."
msgstr "Vous devez fournir une vitesse à définir."

#. Used by: CommandError
#: musicbot/bot.py:5597
msgid "The speed you provided is invalid. Use a number between 0.5 and 100."
msgstr ""
"La vitesse que vous avez fournie n'est pas valide. Utilisez un nombre entre "
"0,5 et 100."

#. Used by: CommandError
#: musicbot/bot.py:5656 musicbot/bot.py:5772 musicbot/bot.py:6704
#, python-format
msgid "Invalid option for command: `%(option)s`"
msgstr "Option invalide pour la commande : `%(option)s`"

#. Used by: CommandError
#: musicbot/bot.py:5670
#, python-format
msgid ""
"Failed to save aliases due to error:\n"
"`%(raw_error)s`"
msgstr ""
"Échec de la sauvegarde des alias en raison d'une erreur :\n"
"`%(raw_error)s`"

#. Used by: CommandError
#: musicbot/bot.py:5677
msgid "You must supply an alias and a command to alias"
msgstr "Vous devez fournir un alias et une commande à alias"

#. Used by: CommandError
#: musicbot/bot.py:5692
msgid "You must supply an alias name to remove."
msgstr "Vous devez fournir un nom d'alias à supprimer."

#. Used by: CommandError
#: musicbot/bot.py:5697
#, python-format
msgid "The alias `%(alias)s` does not exist."
msgstr "L'alias `%(alias)s` n'existe pas."

#. Used by: CommandError
#: musicbot/bot.py:5755
msgid "Config cannot use channel and user mentions at the same time."
msgstr ""
"La configuration ne peut pas utiliser les mentions du canal et de "
"l'utilisateur en même temps."

#. Used by: CommandError
#: musicbot/bot.py:5853
#, python-format
msgid ""
"Unable to reload Config due to the following error:\n"
"%(raw_error)s"
msgstr ""
"Impossible de recharger la configuration en raison de l'erreur suivante :\n"
"%(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:5871
msgid ""
"Could not resolve section name from option name. Please provide a valid "
"section and option name."
msgstr ""
"Impossible de résoudre le nom de la section à partir du nom de l'option. "
"Veuillez fournir un nom de section et d'option valide."

#. Used by: CommandError
#: musicbot/bot.py:5875
msgid "The option given is ambiguous, please provide a section name."
msgstr "L'option donnée est ambiguë, veuillez fournir un nom de section."

#. Used by: CommandError
#: musicbot/bot.py:5881
msgid "You must provide a section name and option name for this command."
msgstr ""
"Vous devez fournir un nom de section et un nom d'option pour cette commande."

#. Used by: CommandError
#: musicbot/bot.py:5897
#, python-format
msgid ""
"The section `%(section)s` is not available.\n"
"The available sections are:  %(sections)s"
msgstr ""
"La section `%(section)s` n'est pas disponible.\n"
"Les sections disponibles sont :  %(sections)s"

#. Used by: CommandError
#: musicbot/bot.py:5905
#, python-format
msgid "The option `%(option)s` is not available."
msgstr "L'option `%(option)s` n'est pas disponible."

#. Used by: CommandError
#: musicbot/bot.py:5933
#, python-format
msgid "Option `%(option)s` is not editable. Cannot save to disk."
msgstr ""
"L'option `%(option)s` n'est pas modifiable. Impossible d'enregistrer sur le "
"disque."

#. Used by: CommandError
#: musicbot/bot.py:5942
#, python-format
msgid "Failed to save the option:  `%(option)s`"
msgstr "Impossible d'enregistrer l'option : `%(option)s`"

#. Used by: CommandError
#: musicbot/bot.py:5957
#, python-format
msgid "Option `%(option)s` is not editable, value cannot be displayed."
msgstr ""
"L'option `%(option)s` n'est pas modifiable, la valeur ne peut pas être "
"affichée."

#. Used by: CommandError
#: musicbot/bot.py:5987
#, python-format
msgid "Option `%(option)s` is not editable. Cannot update setting."
msgstr ""
"L'option `%(option)s` n'est pas modifiable. Impossible de mettre à jour le "
"paramètre."

#. Used by: CommandError
#: musicbot/bot.py:5993 musicbot/bot.py:6917
msgid "You must provide a section, option, and value for this sub command."
msgstr ""
"Vous devez fournir une section, une option et une valeur pour cette sous-"
"commande."

#. Used by: debug
#: musicbot/bot.py:5997
#, python-format
msgid "Doing set with on %(config)s == %(value)s"
msgstr "Faire avec %(config)s == %(value)s"

#. Used by: CommandError
#: musicbot/bot.py:6004
#, python-format
msgid "Option `%(option)s` was not updated!"
msgstr "L'option `%(option)s` n'a pas été mise à jour !"

#. Used by: CommandError
#: musicbot/bot.py:6020
#, python-format
msgid "Option `%(option)s` is not editable. Cannot reset to default."
msgstr ""
"L'option `%(option)s` n'est pas modifiable. Impossible de réinitialiser à la"
" valeur par défaut."

#. Used by: debug
#: musicbot/bot.py:6032
#, python-format
msgid "Resetting %(config)s to default %(value)s"
msgstr "Réinitialisation de %(config)s à %(value)s par défaut"

#. Used by: CommandError
#: musicbot/bot.py:6039
#, python-format
msgid "Option `%(option)s` was not reset to default!"
msgstr "L'option `%(option)s` n'a pas été réinitialisée par défaut!"

#. Used by: CommandError
#: musicbot/bot.py:6072
msgid "The option command is deprecated, use the config command instead."
msgstr ""
"La commande d'option est obsolète, utilisez la commande config à la place."

#. Used by: CommandError
#: musicbot/bot.py:6092
msgid "Invalid option specified, use: info, update, or clear"
msgstr ""
"Option non valide spécifiée, utilisez: info, mise à jour ou effacement"

#. Used by: CommandError
#: musicbot/bot.py:6149
msgid "**Failed** to delete cache, check logs for more info..."
msgstr ""
"**Échec** pour supprimer la cache, vérifiez les logs pour plus d'infos..."

#. Used by: CommandError
#: musicbot/bot.py:6184
msgid "Queue page argument must be a whole number."
msgstr "L'argument de la page de file d'attente doit être un nombre entier."

#. Used by: CommandError
#: musicbot/bot.py:6191
msgid "There are no songs queued! Queue something with a play command."
msgstr ""
"Il n'y a pas de chansons en attente ! Mettre en file d'attente quelque chose"
" avec une commande de lecture."

#. Used by: CommandError
#: musicbot/bot.py:6198
#, python-format
msgid ""
"Requested page number is out of bounds.\n"
"There are **%(total)s** pages."
msgstr ""
"Le numéro de page demandé est hors limites.\n"
"Il y a **%(total)s** pages."

#. Used by: debug
#: musicbot/bot.py:6241
msgid "Skipped the current playlist entry."
msgstr "L'entrée de la playlist actuelle a été ignorée."

#. Used by: debug
#: musicbot/bot.py:6284
msgid "Not enough entries to paginate the queue."
msgstr "Pas assez d'entrées pour paginer la file d'attente."

#. Used by: warning
#: musicbot/bot.py:6288
msgid "Could not post queue message, no message to add reactions to."
msgstr ""
"Impossible de poster le message de file d'attente, aucun message à ajouter "
"des réactions."

#. Used by: CommandError
#: musicbot/bot.py:6290
msgid ""
"Try that again. MusicBot couldn't make or get a reference to the queue message.\n"
"If the issue persists, file a bug report."
msgstr ""
"Essayez à nouveau. MusicBot n'a pas pu faire ou obtenir une référence au message de file d'attente.\n"
"Si le problème persiste, remplissez un rapport de bogue."

#. Used by: CommandError
#: musicbot/bot.py:6400
msgid "Cannot use purge on private DM channel."
msgstr "Impossible d'utiliser la purge sur un canal DM privé."

#. Used by: CommandError
#: musicbot/bot.py:6432
msgid "The given URL was not a valid URL."
msgstr "L'URL donnée n'est pas une URL valide."

#. Used by: CommandError
#: musicbot/bot.py:6442
#, python-format
msgid ""
"Could not extract info from input url\n"
"%(raw_error)s\n"
msgstr ""
"Impossible d'extraire les infos de l'url d'entrée\n"
"%(raw_error)s\n"

#. Used by: CommandError
#: musicbot/bot.py:6447
msgid "This does not seem to be a playlist."
msgstr "Cela ne semble pas être une playlist."

#. Used by: CommandError
#: musicbot/bot.py:6610
msgid ""
"Invalid user ID or server nickname, please double-check the ID and try "
"again."
msgstr ""
"Identifiant d'utilisateur ou surnom de serveur invalide, veuillez vérifier "
"l'ID et réessayer."

#. Used by: CommandError
#: musicbot/bot.py:6617
msgid "Could not determine the discord User.  Try again."
msgstr "Impossible de déterminer l'utilisateur de la discord. Réessayez."

#. Used by: CommandError
#: musicbot/bot.py:6688
msgid "Permissions cannot use channel and user mentions at the same time."
msgstr ""
"Les permissions ne peuvent pas utiliser les mentions de salon et "
"d'utilisateurs en même temps."

#. Used by: CommandError
#: musicbot/bot.py:6723
#, python-format
msgid ""
"Unable to reload Permissions due to an error:\n"
"%(raw_error)s"
msgstr ""
"Impossible de recharger les autorisations en raison d'une erreur :\n"
"%(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:6760
msgid "You must provide a group or option name for this command."
msgstr "Vous devez fournir un nom de groupe ou d'option pour cette commande."

#. Used by: CommandError
#: musicbot/bot.py:6764
msgid "You must provide a group, option, and value to set for this command."
msgstr ""
"Vous devez fournir un groupe, une option et une valeur à définir pour cette "
"commande."

#. Used by: CommandError
#: musicbot/bot.py:6778
#, python-format
msgid "The %(option)s sub-command requires a group and permission name."
msgstr ""
"La sous-commande %(option)s nécessite un nom de groupe et de permission."

#. Used by: CommandError
#: musicbot/bot.py:6790
#, python-format
msgid ""
"The group `%(group)s` is not available.\n"
"The available groups are:  %(sections)s"
msgstr ""
"Le groupe `%(group)s` n'est pas disponible.\n"
"Les groupes disponibles sont:  %(sections)s"

#. Used by: CommandError
#: musicbot/bot.py:6801
#, python-format
msgid "The permission `%(option)s` is not available."
msgstr "La permission `%(option)s` n'est pas disponible."

#. Used by: CommandError
#: musicbot/bot.py:6837
#, python-format
msgid "Cannot add group `%(group)s` it already exists."
msgstr "Impossible d'ajouter le groupe `%(group)s` il existe déjà."

#. Used by: CommandError
#: musicbot/bot.py:6855
msgid "Cannot remove built-in group."
msgstr "Impossible de supprimer le groupe intégré."

#. Used by: CommandError
#: musicbot/bot.py:6873 musicbot/bot.py:6912
msgid "The owner group is not editable."
msgstr "Le groupe propriétaire n'est pas modifiable."

#. Used by: CommandError
#: musicbot/bot.py:6881
#, python-format
msgid "Failed to save the group:  `%(group)s`"
msgstr "Impossible d'enregistrer le groupe: `%(group)s`"

#. Used by: debug
#: musicbot/bot.py:6921
#, python-format
msgid "Doing set on %(option)s with value: %(value)s"
msgstr "Faire sur %(option)s avec la valeur : %(value)s"

#. Used by: CommandError
#: musicbot/bot.py:6928
#, python-format
msgid "Permission `%(option)s` was not updated!"
msgstr "Permission `%(option)s` n'a pas été mise à jour !"

#. Used by: CommandError
#: musicbot/bot.py:6969
msgid ""
"Failed to change username. Did you change names too many times?\n"
"Remember name changes are limited to twice per hour.\n"
msgstr ""
"Impossible de changer le nom d'utilisateur. Avez-vous changé de nom trop de fois ?\n"
"Rappelez-vous que les changements de nom sont limités à deux fois par heure.\n"

#. Used by: CommandError
#: musicbot/bot.py:6975
#, python-format
msgid ""
"Failed to change username due to error:  \n"
"%(raw_error)s"
msgstr ""
"Impossible de modifier le nom d'utilisateur en raison d'une erreur :  \n"
"%(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:6997
msgid "Unable to change nickname: no permission."
msgstr "Impossible de changer le pseudo : pas de permission."

#. Used by: CommandError
#: musicbot/bot.py:7005
#, python-format
msgid ""
"Failed to set nickname due to error:  \n"
"%(raw_error)s"
msgstr ""
"Impossible de définir le pseudo en raison d'une erreur :  \n"
"%(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:7045
msgid "Custom emoji must be from this server to use as a prefix."
msgstr ""
"Les émojis personnalisés doivent provenir de ce serveur pour être utilisés "
"comme préfixes."

#. Used by: CommandError
#: musicbot/bot.py:7062
msgid ""
"Prefix per server is not enabled!\n"
"Use the config command to update the prefix instead."
msgstr ""
"Le préfixe par serveur n'est pas activé !\n"
"Utilisez la commande de configuration pour mettre à jour le préfixe à la place."

#. Used by: CommandError
#: musicbot/bot.py:7092
msgid "This command can only be used in guilds."
msgstr "Cette commande ne peut être utilisée que dans les guildes."

#. Used by: CommandError
#: musicbot/bot.py:7097
msgid "Invalid sub-command given. Use the help command for more information."
msgstr ""
"Sous-commande invalide. Utilisez la commande d'aide pour plus "
"d'informations."

#. Used by: CommandError
#: musicbot/bot.py:7118
#, python-format
msgid "Cannot set language to `%(locale)s` it is not available."
msgstr ""
"Impossible de définir la langue à `%(locale)s` il n'est pas disponible."

#. Used by: CommandError
#: musicbot/bot.py:7163
msgid "You must provide a URL or attach a file."
msgstr "Vous devez fournir une URL ou joindre un fichier."

#. Used by: CommandError
#: musicbot/bot.py:7173
#, python-format
msgid ""
"Unable to change avatar due to error:  \n"
"%(raw_error)s"
msgstr ""
"Impossible de changer d'avatar en raison d'une erreur :  \n"
"%(raw_error)s"

#. Used by: warning
#: musicbot/bot.py:7198
#, python-format
msgid "MusicBot found a %s with no guild!  This could be a problem."
msgstr "MusicBot a trouvé une %s sans guilde! Cela pourrait être un problème."

#. Used by: CommandError
#: musicbot/bot.py:7210
#, python-format
msgid "Not currently connected to server `%(guild)s`"
msgstr "Pas actuellement connecté au serveur `%(guild)s`"

#. Used by: CommandError
#: musicbot/bot.py:7251
msgid ""
"Invalid option given, use one of:  soft, full, upgrade, uppip, or upgit"
msgstr ""
"Option non valide, utilisez une de : soft, full, upgrade, uppip ou upgit"

#. Used by: CommandError
#: musicbot/bot.py:7360
msgid "You must provide an ID or name."
msgstr "Vous devez fournir un ID ou un nom."

#. Used by: CommandError
#: musicbot/bot.py:7371
#, python-format
msgid "No guild was found with the ID or name `%(input)s`"
msgstr "Aucune guilde n'a été trouvée avec l'ID ou le nom `%(input)s`"

#. Used by: critical
#: musicbot/bot.py:7428
#, python-format
msgid "Activating debug breakpoint ID: %(uuid)s"
msgstr "Activation de l'ID du point d'arrêt de débogage : %(uuid)s"

#. Used by: CommandError
#: musicbot/bot.py:7468
msgid "Could not import `objgraph`, is it installed?"
msgstr "Impossible d'importer `objgraph`, est-il installé ?"

#. Used by: debug
#: musicbot/bot.py:7544
msgid "Debug code ran with eval()."
msgstr "Le code de débogage a été exécuté avec eval()."

#. Used by: debug
#: musicbot/bot.py:7554
msgid "Debug code ran with exec()."
msgstr "Le code de débogage a été exécuté avec exec()."

#. Used by: exception
#: musicbot/bot.py:7557
msgid "Debug code failed to execute."
msgstr "L'exécution du code de débogage a échoué."

#. Used by: CommandError
#: musicbot/bot.py:7559
#, python-format
msgid ""
"Failed to execute debug code:\n"
"%(py_code)s\n"
"Exception: ```\n"
"%(ex_name)s:\n"
"%(ex_text)s```"
msgstr ""
"Impossible d'exécuter le code de débogage :\n"
"%(py_code)s\n"
"Exception : ```\n"
"%(ex_name)s:\n"
"%(ex_text)s```"

#. Used by: CommandError
#: musicbot/bot.py:7594 musicbot/bot.py:7655
#, python-format
msgid "Sub-command must be one of: %(options)s"
msgstr "La sous-commande doit être une des : %(options)s"

#. Used by: CommandError
#: musicbot/bot.py:7694
msgid "Could not locate git executable."
msgstr "Impossible de localiser l'exécutable git."

#. Used by: exception
#: musicbot/bot.py:7738
msgid "Failed while checking for updates via git command."
msgstr "Échec de la vérification des mises à jour via la commande git."

#. Used by: debug
#: musicbot/bot.py:7767
msgid "Package missing meta in pip report."
msgstr "Méta manquante dans le rapport pip."

#. Used by: exception
#: musicbot/bot.py:7781
msgid "Failed to get pip update status due to some error."
msgstr ""
"Impossible d'obtenir le statut de mise à jour de pip en raison d'une erreur."

#. Used by: debug
#: musicbot/bot.py:7842
msgid "Got a strange voice client entry."
msgstr "Vous avez reçu une étrange entrée du client vocal."

#. Used by: CommandError
#: musicbot/bot.py:7952
msgid "Cookies already enabled."
msgstr "Cookies déjà activés."

#. Used by: CommandError
#: musicbot/bot.py:7959
msgid "Cookies must be uploaded to be enabled. (Missing cookies file.)"
msgstr ""
"Les cookies doivent être téléchargés pour être activés. (Fichier de cookies)"

#. Used by: CommandError
#: musicbot/bot.py:7972
#, python-format
msgid "Could not enable cookies due to error:  %(raw_error)s"
msgstr ""
"Impossible d'activer les cookies en raison d'une erreur :  %(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:7986
#, python-format
msgid ""
"Could not rename cookies file due to error:  %(raw_error)s\n"
"Cookies temporarily disabled and will be re-enabled on next restart."
msgstr ""
"Impossible de renommer le fichier des cookies en raison d'une erreur :  %(raw_error)s\n"
"Cookies temporairement désactivés et seront réactivés au prochain redémarrage."

#. Used by: CommandError
#: musicbot/bot.py:7995
msgid ""
"No attached uploads were found, try again while uploading a cookie file."
msgstr ""
"Aucun téléchargement en pièce jointe n'a été trouvé, essayez à nouveau en "
"téléchargeant un fichier de cookies."

#. Used by: warning
#: musicbot/bot.py:8004
#, python-format
msgid "Could not remove old, disabled cookies file:  %(raw_error)s"
msgstr ""
"Impossible de supprimer le fichier ancien, les cookies désactivés :  "
"%(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:8013
#, python-format
msgid "Error downloading the cookies file from discord:  %(raw_error)s"
msgstr ""
"Erreur lors du téléchargement du fichier des cookies depuis le discord:  "
"%(raw_error)s"

#. Used by: CommandError
#: musicbot/bot.py:8018
#, python-format
msgid "Could not save cookies to disk:  %(raw_error)s"
msgstr "Impossible d'enregistrer les cookies sur le disque :  %(raw_error)s"

#. Used by: debug
#: musicbot/bot.py:8036
#, python-format
msgid "Got a message with no channel, somehow:  %s"
msgstr "A reçu un message sans canal, d'une manière ou d'une autre :  %s"

#. Used by: warning
#: musicbot/bot.py:8064
#, python-format
msgid "Ignoring command from myself (%s)"
msgstr "Commande ignorée de moi-même (%s)"

#. Used by: warning
#: musicbot/bot.py:8072
#, python-format
msgid "Ignoring command from other bot (%s)"
msgstr "Commande ignorée par un autre bot (%s)"

#. Used by: warning
#: musicbot/bot.py:8080
#, python-format
msgid "Ignoring command from channel of type:  %s"
msgstr "Commande ignorée du canal de type :  %s"

#. Used by: warning
#: musicbot/bot.py:8175
#, python-format
msgid "User in block list: %(id)s/%(name)s  tried command: %(command)s"
msgstr ""
"Utilisateur dans la liste de blocage : %(id)s/%(name)s  a essayé la commande"
" : %(command)s"

#. Used by: info
#: musicbot/bot.py:8182
#, python-format
msgid "Message from %(id)s/%(name)s: %(message)s"
msgstr "Message de %(id)s/%(name)s: %(message)s"

#. Used by: PermissionsError
#: musicbot/bot.py:8217
#, python-format
msgid "This command is not allowed for your permissions group:  %(group)s"
msgstr ""
"Cette commande n'est pas autorisée pour votre groupe de permissions :  "
"%(group)s"

#. Used by: CommandError
#: musicbot/bot.py:8252
msgid "This command requires you to be in a Voice channel."
msgstr "Cette commande nécessite d'être dans un canal vocal."

#. Used by: debug
#: musicbot/bot.py:8341
#, python-format
msgid "Invalid command usage, missing values for params: %(params)r"
msgstr ""
"Utilisation de la commande invalide, valeurs manquantes pour les paramètres "
": %(params)r"

#. Used by: error
#: musicbot/bot.py:8379
#, python-format
msgid "Error in %(command)s: %(err_name)s: %(err_text)s"
msgstr "Erreur dans %(command)s: %(err_name)s: %(err_text)s"

#. Used by: error
#: musicbot/bot.py:8402
#, python-format
msgid "Exception while handling command: %(command)s"
msgstr "Exception lors de la gestion de la commande : %(command)s"

#. Used by: debug
#: musicbot/bot.py:8433
#, python-format
msgid "Cannot generate help for missing command:  %s"
msgstr "Impossible de générer de l'aide pour la commande manquante :  %s"

#. Used by: critical
#: musicbot/bot.py:8437
#, python-format
msgid "Missing help data for command:  %s"
msgstr "Il manque des données d'aide pour la commande :  %s"

#. Used by: info
#: musicbot/bot.py:8554
#, python-format
msgid "Leaving voice channel %s in %s due to inactivity."
msgstr "Quitter le canal vocal %s en %s en raison de l'inactivité."

#. Used by: info
#: musicbot/bot.py:8563
msgid "MusicBot has become connected."
msgstr "MusicBot est devenu connecté."

#. Used by: info
#: musicbot/bot.py:8567
msgid "MusicBot has become disconnected."
msgstr "MusicBot est déconnecté."

#. Used by: everything
#: musicbot/bot.py:8572
#, python-format
msgid "Got a Socket Event:  %s"
msgstr "A eu un événement de socket:  %s"

#. Used by: warning
#: musicbot/bot.py:8588
msgid "VoiceState updated before on_ready finished"
msgstr "VoiceState mis à jour avant que le_ready ne soit terminé"

#. Used by: info
#: musicbot/bot.py:8601
#, python-format
msgid "Ignoring %s in %s as it is a bound voice channel."
msgstr "%s ignoré dans %s car il s'agit d'un salon vocal lié."

#. Used by: info
#: musicbot/bot.py:8610
#, python-format
msgid "%s has been detected as empty. Handling timeouts."
msgstr "%s a été détecté comme vide. Délai de manutention expiré."

#. Used by: info
#: musicbot/bot.py:8621
#, python-format
msgid "A user joined %s, cancelling timer."
msgstr "Un utilisateur a rejoint %s, annulation du délai."

#. Used by: info
#: musicbot/bot.py:8634
#, python-format
msgid ""
"The bot got moved and the voice channel %s is empty. Handling timeouts."
msgstr ""
"Le bot a été déplacé et le canal vocal %s est vide. Délai de manutention."

#. Used by: info
#: musicbot/bot.py:8643
#, python-format
msgid "The bot got moved and the voice channel %s is not empty."
msgstr "Le bot a été déplacé et le canal vocal %s n'est pas vide."

#. Used by: debug
#: musicbot/bot.py:8692
#, python-format
msgid "No longer following user %s"
msgstr "Plus utilisateur suivant %s"

#. Used by: debug
#: musicbot/bot.py:8714
#, python-format
msgid "Following user `%(user)s` to channel:  %(channel)s"
msgstr "Utilisateur suivant `%(user)s` pour le salon :  %(channel)s"

#. Used by: debug
#: musicbot/bot.py:8734
msgid "VoiceState disconnect before.channel is None."
msgstr "VoiceState déconnexion before.channel est Aucune."

#. Used by: info
#: musicbot/bot.py:8761
#, python-format
msgid ""
"Disconnected from voice by Discord API in: %(guild)s/%(channel)s (Code: "
"%(code)s) [S:%(state)s]"
msgstr ""
"Déconnecté de la voix par l'API Discord dans: %(guild)s/%(channel)s (Code : "
"%(code)s) [S:%(state)s]"

#. Used by: error
#: musicbot/bot.py:8783
#, python-format
msgid "Cannot use auto-join channel with type: %(type)s  in guild:  %(guild)s"
msgstr ""
"Impossible d'utiliser le canal de connexion automatique avec le type : "
"%(type)s  dans la guilde :  %(guild)s"

#. Used by: error
#: musicbot/bot.py:8790
#, python-format
msgid "Cannot find the auto-joined channel, was it deleted?  Guild:  %s"
msgstr ""
"Impossible de trouver le canal auto-joint, a-t-il été supprimé? Guilde:  %s"

#. Used by: info
#: musicbot/bot.py:8796
#, python-format
msgid "Reconnecting to auto-joined guild on channel:  %s"
msgstr "Reconnexion à la guilde automatiquement rejoint sur le canal :  %s"

#. Used by: warning
#: musicbot/bot.py:8809
#, python-format
msgid "Cannot auto join channel:  %s"
msgstr "Impossible de rejoindre automatiquement le canal :  %s"

#. Used by: info
#: musicbot/bot.py:8825
#, python-format
msgid "Bot has been added to guild: %s"
msgstr "Le bot a été ajouté à la guilde : %s"

#. Used by: info
#: musicbot/bot.py:8837
#, python-format
msgid "Left guild '%s' due to bot owner not found."
msgstr "A quitté la guilde '%s' en raison du propriétaire du bot introuvable."

#. Used by: debug
#: musicbot/bot.py:8851
#, python-format
msgid "Creating data folder for guild %s"
msgstr "Création du dossier de données pour la guilde %s"

#. Used by: info
#: musicbot/bot.py:8859
#, python-format
msgid "Bot has been removed from guild: %s"
msgstr "Le bot a été retiré de la guilde : %s"

#. Used by: debug
#: musicbot/bot.py:8860
msgid "Updated guild list:"
msgstr "Liste de guilde mise à jour :"

#. Used by: info
#: musicbot/bot.py:8875
#, python-format
msgid "Guild \"%s\" has become available."
msgstr "La guilde «%s» est devenue disponible."

#. Used by: debug
#: musicbot/bot.py:8881
#, python-format
msgid "Resuming player in \"%s\" due to availability."
msgstr "Reprise du joueur dans «%s» en raison de la disponibilité."

#. Used by: info
#: musicbot/bot.py:8898
#, python-format
msgid "Guild \"%s\" has become unavailable."
msgstr "La guilde «%s» est devenue indisponible."

#. Used by: debug
#: musicbot/bot.py:8904
#, python-format
msgid "Pausing player in \"%s\" due to unavailability."
msgstr "Pauser le joueur dans «%s» en raison de l'indisponibilité."

#. Used by: info
#: musicbot/bot.py:8920
#, python-format
msgid "Guild update for:  %s"
msgstr "Mise à jour de guilde pour :  %s"

#. Used by: everything
#: musicbot/bot.py:8926
#, python-format
msgid "Guild attribute %(attr)s is now: %(new)s  -- Was: %(old)s"
msgstr ""
"L'attribut de guilde %(attr)s est maintenant : %(new)s  -- Était: %(old)s"

#. Used by: info
#: musicbot/bot.py:8977
#, python-format
msgid "Channel update for:  %(channel)s  --  %(changes)s"
msgstr "Mise à jour du canal pour:  %(channel)s  --  %(changes)s"

#. Used by: warning
#: musicbot/config.py:86
#, python-format
msgid "Creating %s"
msgstr "Création de %s"

#. Used by: info
#: musicbot/config.py:107
#, python-format
msgid "Loading config from:  %s"
msgstr "Chargement de la configuration depuis :  %s"

#. Used by: HelpfulError
#: musicbot/config.py:1128
#, python-format
msgid ""
"Error while reading config.\n"
"\n"
"Problem:\n"
"  One or more required config option sections are missing.\n"
"  The missing sections are:\n"
"  %(sections)s\n"
"\n"
"Solution:\n"
"  Repair your config options file.\n"
"  Each [Section] must appear only once, with no other text on the same line.\n"
"  Each section must have at least one option.\n"
"  Use the example options as a template or copy it from the repository."
msgstr ""
"Erreur lors de la lecture de la configuration.\n"
"\n"
"Problème :\n"
"  Une ou plusieurs sections d'options de configuration requises sont manquantes.\n"
"  Les sections manquantes sont :\n"
"  %(sections)s\n"
"\n"
"Solution :\n"
"  Réparez votre fichier d'options de configuration.\n"
"  Chaque [Section] ne doit apparaître qu'une seule fois, sans autre texte sur la même ligne.\n"
"  Chaque section doit avoir au moins une option.\n"
"  Utilisez les options d'exemple comme modèle ou copiez-les à partir du référentiel."

#. Used by: warning
#: musicbot/config.py:1158
#, python-format
msgid ""
"Cannot store more than %s log files. Option LogsMaxKept will be limited "
"instead."
msgstr ""
"Impossible de stocker plus de fichiers journaux %s . L'option LogsMaxKept "
"sera limitée à la place."

#. Used by: warning
#: musicbot/config.py:1166
msgid ""
"Config option LogsDateFormat is empty and this will break log file rotation."
" Using default instead."
msgstr ""
"L'option de configuration LogsDateFormat est vide et cela cassera la "
"rotation des fichiers journaux. Utiliser par défaut à la place."

#. Used by: HelpfulError
#: musicbot/config.py:1177
msgid ""
"Error while validating config options.\n"
"\n"
"Problem:\n"
"  Config option AudioCachePath is not a directory.\n"
"\n"
"Solution:\n"
"  Make sure the path you configured is a path to a folder / directory."
msgstr ""
"Erreur lors de la validation des options de configuration.\n"
"\n"
"Problème :\n"
"  option de configuration AudioCachePath n'est pas un répertoire.\n"
"\n"
"Solution :\n"
"  Assurez-vous que le chemin que vous avez configuré est un chemin vers un dossier / répertoire."

#. Used by: exception
#: musicbot/config.py:1194
msgid "An exception was thrown while validating AudioCachePath."
msgstr "Une exception a été levée lors de la validation de AudioCachePath."

#. Used by: HelpfulError
#: musicbot/config.py:1198
#, python-format
msgid ""
"Error while validating config options.\n"
"\n"
"Problem:\n"
"  AudioCachePath config option could not be set due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Double check the setting is a valid, accessible directory path."
msgstr ""
"Erreur lors de la validation des options de configuration.\n"
"\n"
"Problčme :\n"
"  L'option de configuration AudioCachePath n'a pas pu ętre définie ŕ cause d'une erreur :\n"
"  %(raw_error)s\n"
"\n"
"Solution :\n"
"  Double vérifier que la configuration est valide, chemin d'accès au répertoire."

#. Used by: info
#: musicbot/config.py:1210
#, python-format
msgid "Audio Cache will be stored in:  %s"
msgstr "Le cache audio sera stocké dans :  %s"

#. Used by: HelpfulError
#: musicbot/config.py:1221
#, python-format
msgid ""
"Error while reading config options.\n"
"\n"
"Problem:\n"
"  No bot Token was specified in the config options or environment.\n"
"\n"
"Solution:\n"
"  Set the Token config option or set environment variable %(env_var)s with an App token."
msgstr ""
"Erreur lors de la lecture des options de configuration.\n"
"\n"
"Problème :\n"
"  Aucun jeton de bot n'a été spécifié dans les options ou l'environnement de configuration.\n"
"\n"
"Solution :\n"
"  Définissez l'option de configuration du jeton ou définissez la variable d'environnement %(env_var)s avec un jeton d'application."

#. Used by: warning
#: musicbot/config.py:1242
msgid ""
"StatusMessage config option is too long, it will be limited to 128 "
"characters."
msgstr ""
"L'option de configuration StatusMessage est trop longue, elle sera limitée à"
" 128 caractères."

#. Used by: warning
#: musicbot/config.py:1251
#, python-format
msgid ""
"The default playback speed must be between 0.5 and 100.0. The option value "
"of %.3f will be limited instead."
msgstr ""
"La vitesse de lecture par défaut doit être comprise entre 0.5 et 100.0. La "
"valeur d'option %.3f sera limitée à la place."

#. Used by: debug
#: musicbot/config.py:1268
msgid "Validating options with service data..."
msgstr "Validation des options avec les données du service..."

#. Used by: debug
#: musicbot/config.py:1274
msgid "Acquired owner ID via API"
msgstr "ID de propriétaire acquis via l'API"

#. Used by: HelpfulError
#: musicbot/config.py:1278
msgid ""
"Error while fetching 'OwnerID' automatically.\n"
"\n"
"Problem:\n"
"  Discord App info is not available.\n"
"  This could be a temporary API outage or a bug.\n"
"\n"
"Solution:\n"
"  Manually set the 'OwnerID' config option or try again later."
msgstr ""
"Erreur lors de la récupération automatique de « OwnerID ».\n"
"\n"
"Problème :\n"
"  Les informations de l'application Discord ne sont pas disponibles.\n"
"  Il peut s'agir d'une panne temporaire de l'API ou d'un bug.\n"
"\n"
"Solution :\n"
"  Définissez manuellement l'option de configuration « OwnerID » ou réessayez plus tard."

#. Used by: critical
#: musicbot/config.py:1290
msgid "MusicBot does not have a user instance, cannot proceed."
msgstr "MusicBot n'a pas d'instance d'utilisateur, impossible de continuer."

#. Used by: HelpfulError
#: musicbot/config.py:1296
msgid ""
"Error validating config options.\n"
"\n"
"Problem:\n"
"  The 'OwnerID' config is the same as your Bot / App ID.\n"
"\n"
"Solution:\n"
"  Do not use the Bot or App ID in the 'OwnerID' field."
msgstr ""
"Erreur lors de la validation des options de configuration.\n"
"\n"
"Problème:\n"
"  La configuration 'OwnerID' est la même que votre Bot / App ID.\n"
"\n"
"Solution :\n"
"  N'utilisez pas le Bot ou l'ID de l'application dans le champ 'OwnerID'."

#. Used by: warning
#: musicbot/config.py:1320
msgid "Config options file not found. Checking for alternatives..."
msgstr ""
"Fichier d'options de configuration introuvable. Vérification des "
"alternatives..."

#. Used by: warning
#: musicbot/config.py:1333
#, python-format
msgid ""
"Renaming %(ini_file)s to %(option_file)s, you should probably turn file "
"extensions on."
msgstr ""
"Renommer %(ini_file)s en %(option_file)s, vous devriez probablement activer "
"les extensions de fichiers."

#. Used by: warning
#: musicbot/config.py:1341
#, python-format
msgid "Copying existing example options file:  %(example_file)s"
msgstr "Copie du fichier d'options d'exemple existant :  %(example_file)s"

#. Used by: exception
#: musicbot/config.py:1355
msgid "Something went wrong while trying to find a config option file."
msgstr ""
"Une erreur s'est produite lors de la recherche d'un fichier d'options de "
"configuration."

#. Used by: HelpfulError
#: musicbot/config.py:1359
#, python-format
msgid ""
"Error locating config.\n"
"\n"
"Problem:\n"
"  Could not find or create a config file due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Verify the config folder and files exist and can be read by MusicBot."
msgstr ""
"Erreur lors de la localisation de la configuration.\n"
"\n"
"Problème :\n"
"  Impossible de trouver ou de créer un fichier de configuration en raison d'une erreur :\n"
"  %(raw_error)s\n"
"\n"
"Solution :\n"
"  Vérifiez que le dossier de configuration et les fichiers existent et peuvent être lus par MusicBot."

#. Used by: HelpfulError
#: musicbot/config.py:1377
#, python-format
msgid ""
"Error loading config.\n"
"\n"
"Problem:\n"
"  MusicBot could not read config file due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Make sure the file is accessible and error free.\n"
"  Copy the example file from the repo if all else fails."
msgstr ""
"Erreur lors du chargement de la configuration.\n"
"\n"
"Problčme :\n"
"  MusicBot n'a pas pu lire le fichier de configuration en raison d'une erreur :\n"
"  %(raw_error)s\n"
"\n"
"Solution :\n"
"  Assurez-vous que le fichier est accessible et sans erreur.\n"
"  Copiez le fichier d'exemple du dépôt si tout le reste échoue."

#. Used by: critical
#: musicbot/config.py:1401
msgid "Dev Bug! Config option has getter that is not available."
msgstr ""
"L'option Dev Bug ! L'option de configuration a getter qui n'est pas "
"disponible."

#. Used by: error
#: musicbot/config.py:1406
msgid ""
"Dev Bug! Config option has invalid type, getter and default must be the same"
" type."
msgstr ""
"Bug Dev ! L'option de configuration a un type non valide, getter et default "
"doit être le même type."

#. Used by: debug
#: musicbot/config.py:1426
msgid "Option was missing previously."
msgstr "L'option était manquante précédemment."

#. Used by: error
#: musicbot/config.py:1441
#, python-format
msgid "Config section not in parsed config! Missing: %s"
msgstr ""
"La section de configuration n'est pas dans la configuration analysée ! "
"Manquant : %s"

#. Used by: info
#: musicbot/config.py:1446
#, python-format
msgid "Saved config option: %(config)s  =  %(value)s"
msgstr "Option de configuration enregistrée : %(config)s  =  %(value)s"

#. Used by: exception
#: musicbot/config.py:1459
#, python-format
msgid "Failed to save config:  %s"
msgstr "Impossible d'enregistrer la configuration :  %s"

#. Used by: warning
#: musicbot/config.py:1973
msgid ""
"Option names are not unique between INI sections!  Resolver is disabled."
msgstr ""
"Les noms d'options ne sont pas uniques entre les sections INI ! Le résolveur"
" est désactivé."

#. Used by: exception
#: musicbot/config.py:2151 musicbot/permissions.py:909
#, python-format
msgid "Failed to save default INI file at:  %s"
msgstr "Impossible d'enregistrer le fichier INI par défaut à:  %s"

#. Used by: HelpfulError
#: musicbot/config.py:2241
#, python-format
msgid ""
"Error loading config value.\n"
"\n"
"Problem:\n"
"  The owner ID in [%(section)s] > %(option)s is not valid.\n"
"\n"
"Solution:\n"
"  Set %(option)s to a numerical ID or set it to `auto` or `0` for automatic owner binding."
msgstr ""
"Erreur lors du chargement de la valeur de la configuration.\n"
"\n"
"Problème :\n"
"  L'ID du propriétaire dans [%(section)s] > %(option)s n'est pas valide.\n"
"\n"
"Solution :\n"
"  Définissez %(option)s sur un ID numérique ou mettez-le à `auto` ou `0` pour relier automatiquement le propriétaire."

#. Used by: HelpfulError
#: musicbot/config.py:2277
#, python-format
msgid ""
"Error loading config value.\n"
"\n"
"Problem:\n"
"  The config option [%(section)s] > %(option)s is not a valid file location.\n"
"\n"
"Solution:\n"
"  Check the path setting and make sure the file exists and is accessible to MusicBot."
msgstr ""
"Erreur lors du chargement de la valeur de la configuration.\n"
"\n"
"Problème :\n"
"  L'option de configuration [%(section)s] > %(option)s n'est pas un emplacement de fichier valide.\n"
"\n"
"Solution :\n"
"  Vérifiez le paramétrage du chemin et assurez-vous que le fichier existe et est accessible à MusicBot."

#. Used by: HelpfulError
#: musicbot/config.py:2307
#, python-format
msgid ""
"Error loading config value.\n"
"\n"
"Problem:\n"
"  One of the IDs in option [%(section)s] > %(option)s is invalid.\n"
"\n"
"Solution:\n"
"  Ensure all IDs are numerical, and separated only by spaces or commas."
msgstr ""
"Erreur lors du chargement de la valeur de la configuration.\n"
"\n"
"Problème :\n"
"  Un des identifiants dans l'option [%(section)s] > %(option)s est invalide.\n"
"\n"
"Solution :\n"
"  S'assurer que tous les identifiants sont numériques, et séparés uniquement par des espaces ou des virgules."

#. Used by: warning
#: musicbot/config.py:2343
#, python-format
msgid ""
"Invalid DebugLevel option \"%(value)s\" given, falling back to level: "
"%(fallback)s"
msgstr ""
"L'option «%(value)s» du DebugLevel n'est pas valide, elle revient au niveau:"
" %(fallback)s"

#. Used by: warning
#: musicbot/config.py:2364
#, python-format
msgid ""
"Option [%(section)s] > %(option)s has invalid config value '%(value)s' using"
" default instead."
msgstr ""
"L'option [%(section)s] > %(option)s a une valeur de configuration invalide "
"'%(value)s' en utilisant la valeur par défaut."

#. Used by: warning
#: musicbot/config.py:2413
#, python-format
msgid ""
"Option [%(section)s] > %(option)s has a value greater than 100 %% "
"(%(value)s) and will be set to %(fallback)s instead."
msgstr ""
"L'option [%(section)s] > %(option)s a une valeur supérieure à 100 %% "
"(%(value)s) et sera définie à %(fallback)s à la place."

#. Used by: debug
#: musicbot/config.py:2538
#, python-format
msgid ""
"Renaming INI file entry [%(old_s)s] > %(old_o)s  to  [%(new_s)s] > %(new_o)s"
msgstr ""
"Renommer l'entrée du fichier INI [%(old_s)s] > %(old_o)s  en [%(new_s)s] > "
"%(new_o)s"

#. Used by: debug
#: musicbot/config.py:2609
msgid "Upgrading config file with renamed options..."
msgstr "Mise à jour du fichier de configuration avec les options renommées..."

#. Used by: exception
#: musicbot/config.py:2643
msgid "Failed to upgrade config.  You'll need to upgrade it manually."
msgstr ""
"Échec de la mise à jour de la configuration. Vous devrez la mettre à jour "
"manuellement."

#. Used by: warning
#: musicbot/config.py:2684
#, python-format
msgid "Block list file not found:  %s"
msgstr "Fichier de liste de blocage non trouvé :  %s"

#. Used by: error
#: musicbot/config.py:2705
#, python-format
msgid "Could not load block list from file:  %s"
msgstr "Impossible de charger la liste de blocage du fichier :  %s"

#. Used by: error
#: musicbot/config.py:2743 musicbot/config.py:2776
#, python-format
msgid "Could not update the block list file:  %s"
msgstr "Impossible de mettre à jour le fichier de la liste de blocage :  %s"

#. Used by: debug
#: musicbot/config.py:2803
#, python-format
msgid "Loaded User Block list with %s entries."
msgstr "Liste de blocage des utilisateurs chargée avec les entrées %s."

#. Used by: warning
#: musicbot/config.py:2814
#, python-format
msgid "We found a legacy blacklist file, it will be renamed to:  %s"
msgstr ""
"Nous avons trouvé un fichier de liste noire hérité, il sera renommé en :  %s"

#. Used by: debug
#: musicbot/config.py:2860
#, python-format
msgid "Loaded a Song Block list with %s entries."
msgstr "Une liste de blocs de chansons avec des entrées %s a été chargée."

#. Used by: error
#: musicbot/constructs.py:220
msgid ""
"Cannot load data for guild with ID 0. This is likely a bug in the code!"
msgstr ""
"Impossible de charger les données de la guilde avec l'ID 0. C'est "
"probablement un bug dans le code!"

#. Used by: debug
#: musicbot/constructs.py:229
#, python-format
msgid "No file for guild %(id)s/%(name)s"
msgstr "Aucun fichier pour la guilde %(id)s/%(name)s"

#. Used by: debug
#: musicbot/constructs.py:238
#, python-format
msgid "Loading guild data for guild with ID:  %(id)s/%(name)s"
msgstr ""
"Chargement des données de guilde pour la guilde avec ID:  %(id)s/%(name)s"

#. Used by: exception
#: musicbot/constructs.py:245
#, python-format
msgid "An OS error prevented reading guild data file:  %s"
msgstr ""
"Une erreur du système d'exploitation a empêché la lecture du fichier de "
"données de guilde :  %s"

#. Used by: info
#: musicbot/constructs.py:256
#, python-format
msgid "Guild %(id)s/%(name)s has custom command prefix: %(prefix)s"
msgstr ""
"La guilde %(id)s/%(name)s a un préfixe de commande personnalisé : %(prefix)s"

#. Used by: error
#: musicbot/constructs.py:276
msgid ""
"Cannot save data for guild with ID 0. This is likely a bug in the code!"
msgstr ""
"Impossible d'enregistrer des données pour la guilde avec l'ID 0. C'est "
"probablement un bug dans le code!"

#. Used by: exception
#: musicbot/constructs.py:300
msgid "Could not save guild specific data due to OS Error."
msgstr ""
"Impossible d'enregistrer les données spécifiques à la guilde en raison d'une"
" erreur d'exploitation."

#. Used by: exception
#: musicbot/constructs.py:303
msgid "Failed to serialize guild specific data due to invalid data."
msgstr ""
"Impossible de sérialiser les données spécifiques à la guilde en raison de "
"données non valides."

#. Used by: warning
#: musicbot/downloader.py:129
#, python-format
msgid "Forcing YTDLP to use User Agent:  %s"
msgstr "Forcer YTDLP à utiliser l'agent utilisateur :  %s"

#. Used by: info
#: musicbot/downloader.py:148
#, python-format
msgid "MusicBot will use cookies for yt-dlp from:  %s"
msgstr "MusicBot utilisera des cookies pour yt-dlp depuis:  %s"

#. Used by: info
#: musicbot/downloader.py:154
msgid "Yt-dlp will use your configured proxy server."
msgstr "Yt-dlp utilisera votre serveur proxy configuré."

#. Used by: ExtractionError
#: musicbot/downloader.py:244
msgid "HEAD seems to have no headers..."
msgstr "HEAD ne semble pas avoir d'en-têtes..."

#. Used by: warning
#: musicbot/downloader.py:255
msgid "Checking media headers failed due to timeout."
msgstr ""
"La vérification des en-têtes des médias a échoué en raison du délai "
"d'expiration."

#. Used by: warning
#: musicbot/downloader.py:258
#, python-format
msgid "Failed HEAD request for:  %s"
msgstr "Échec de la requête HEAD pour :  %s"

#. Used by: exception
#: musicbot/downloader.py:259
msgid "HEAD Request exception: "
msgstr "Exception de requête HEAD : "

#. Used by: noise
#: musicbot/downloader.py:327
#, python-format
msgid ""
"Sanitized YTDL Extraction Info (not JSON):\n"
"%s"
msgstr ""
"Infos d'extraction YTDL Sanitized (pas JSON) :\n"
"%s"

#. Used by: noise
#: musicbot/downloader.py:329
#, python-format
msgid "Sanitized YTDL Extraction Info (not JSON):  %s"
msgstr "Infos d'extraction YTDL Sanitized (pas JSON) :  %s"

#. Used by: ExtractionError
#: musicbot/downloader.py:393
msgid "Song info extraction returned no data."
msgstr ""
"L'extraction des informations de la chanson n'a renvoyé aucune donnée."

#. Used by: noise
#: musicbot/downloader.py:449
#, python-format
msgid "Called extract_info with:  '%(subject)s', %(args)s, %(kws)s"
msgstr "Extraction appelée avec : '%(subject)s', %(args)s, %(kws)s"

#. Used by: warning
#: musicbot/downloader.py:457
msgid "Cannot run extraction, loop is closed. (This is normal on shutdowns.)"
msgstr ""
"Impossible d'exécuter l'extraction, la boucle est fermée. (C'est normal lors"
" des arrêts.)"

#. Used by: MusicbotException
#: musicbot/downloader.py:459
msgid "Cannot continue extraction, event loop is closed."
msgstr ""
"Impossible de poursuivre l'extraction, la boucle d'événement est fermée."

#. Used by: ExtractionError
#: musicbot/downloader.py:468
msgid "Spotify URL is invalid or not supported."
msgstr "L'URL Spotify n'est pas valide ou n'est pas prise en charge."

#. Used by: exception
#: musicbot/downloader.py:506
msgid "Download Error with stream URL"
msgstr "Erreur de téléchargement avec l'URL du flux"

#. Used by: debug
#: musicbot/downloader.py:511
msgid "Assuming content is a direct stream"
msgstr "En supposant que le contenu est un flux direct"

#. Used by: ExtractionError
#: musicbot/downloader.py:519
msgid "Cannot stream an invalid URL."
msgstr "Impossible de diffuser une URL non valide."

#. Used by: noise
#: musicbot/downloader.py:530
msgid ""
"Caught NoSupportingHandlers, trying again after replacing colon with space."
msgstr ""
"NoSupportingHandlers attrapés, en essayant à nouveau après avoir remplacé "
"deux points par de l'espace."

#. Used by: noise
#: musicbot/downloader.py:574
#, python-format
msgid "Called safe_extract_info with:  %(args)s, %(kws)s"
msgstr "Appelé safe_extract_info avec :  %(args)s, %(kws)s"

#. Used by: MusicbotException
#: musicbot/downloader.py:594
msgid "The local media file could not be found."
msgstr "Le fichier média local est introuvable."

#. Used by: warning
#: musicbot/downloader.py:632
msgid "Missing __input_subject from YtdlpResponseDict"
msgstr "__input_subject manquant de YtdlpResponseDict"

#. Used by: warning
#: musicbot/downloader.py:637
msgid ""
"Entries is not a list in YtdlpResponseDict, set process=True to avoid this."
msgstr ""
"Les entrées ne sont pas une liste dans YtdlpResponseDict, set process=True "
"pour éviter cela."

#. Used by: noise
#: musicbot/downloader.py:866
#, python-format
msgid "Warning, duration error for: %(url)s"
msgstr "Attention, erreur de durée pour : %(url)s"

#. Used by: debug
#: musicbot/entry.py:46
msgid "module 'pymediainfo' not found, will fall back to ffprobe."
msgstr "module 'pymediainfo' non trouvé, va revenir à ffprobe."

#. Used by: debug
#: musicbot/entry.py:159
#, python-format
msgid "Created future for %r"
msgstr "Futur créé pour %r"

#. Used by: everything
#: musicbot/entry.py:171
#, python-format
msgid "Completed futures for %(entry)r with %(callback)r"
msgstr "Termes terminés pour %(entry)r avec %(callback)r"

#. Used by: exception
#: musicbot/entry.py:181
msgid "Unhandled exception in _for_each_future callback."
msgstr "Exception non gérée dans _for_each_future callback."

#. Used by: noise
#: musicbot/entry.py:223
#, python-format
msgid "Starting asyncio subprocess (%(process)s) with command: %(run)s"
msgstr ""
"Démarrage du sous-processus asyncio (%(process)s) avec la commande : %(run)s"

#. Used by: info
#: musicbot/entry.py:258
#, python-format
msgid ""
"Extraction did not provide a duration for this entry.\n"
"MusicBot cannot estimate queue times until it is downloaded.\n"
"Entry name:  %s"
msgstr ""
"L'extraction n'a pas fourni de durée pour cette entrée.\n"
"MusicBot ne peut pas estimer les temps d'attente tant qu'il n'est pas téléchargé.\n"
"Entrée :  %s"

#. Used by: error
#: musicbot/entry.py:364 musicbot/entry.py:874 musicbot/entry.py:1084
msgid "Entry data is missing version number, cannot deserialize."
msgstr ""
"Le numéro de version de l'entrée est manquant, impossible de désérialiser."

#. Used by: error
#: musicbot/entry.py:367 musicbot/entry.py:877 musicbot/entry.py:1087
msgid "Entry data has the wrong version number, cannot deserialize."
msgstr ""
"Les données de saisie ont le mauvais numéro de version, impossible de "
"désérialiser."

#. Used by: warning
#: musicbot/entry.py:383
#, python-format
msgid "Deserialized URLPlaylistEntry cannot find channel with ID:  %s"
msgstr ""
"L'URLPlaylistEntry désérialisé ne peut pas trouver de canal avec l'ID :  %s"

#. Used by: warning
#: musicbot/entry.py:399
#, python-format
msgid "Deserialized URLPlaylistEntry has the wrong channel type:  %s"
msgstr "L'URLPlaylistEntry désérialisé a le mauvais type de canal :  %s"

#. Used by: warning
#: musicbot/entry.py:421
#, python-format
msgid "Deserialized URLPlaylistEntry cannot find author with ID:  %s"
msgstr ""
"L'URLPlaylistEntry désérialisé ne peut pas trouver l'auteur avec l'ID :  %s"

#. Used by: warning
#: musicbot/entry.py:427
msgid ""
"Deserialized URLPlaylistEntry has an author ID but no channel for lookup!"
msgstr ""
"L'URLPlaylistEntry désérialisé a un ID d'auteur mais aucun canal de "
"recherche !"

#. Used by: error
#: musicbot/entry.py:437 musicbot/entry.py:943 musicbot/entry.py:1157
#, python-format
msgid "Could not load %s"
msgstr "Impossible de charger %s"

#. Used by: InvalidDataError
#: musicbot/entry.py:474
#, python-format
msgid "Cannot download Spotify links, processing error with type: %(type)s"
msgstr ""
"Impossible de télécharger les liens Spotify, erreur de traitement avec le "
"type : %(type)s"

#. Used by: debug
#: musicbot/entry.py:486 musicbot/entry.py:948 musicbot/entry.py:1190
#, python-format
msgid "Getting ready for entry:  %r"
msgstr "Préparation de l'entrée :  %r"

#. Used by: warning
#: musicbot/entry.py:503
msgid "Download cached with different extension..."
msgstr "Téléchargement mis en cache avec une extension différente..."

#. Used by: debug
#: musicbot/entry.py:512
msgid "Local size different from remote size. Re-downloading..."
msgstr ""
"La taille locale est différente de la taille de la télécommande. Re-"
"téléchargement..."

#. Used by: debug
#: musicbot/entry.py:516
#, python-format
msgid "Download already cached at:  %s"
msgstr "Téléchargement déjà mis en cache à:  %s"

#. Used by: error
#: musicbot/entry.py:536 musicbot/entry.py:1206
#, python-format
msgid ""
"MusicBot could not get duration data for this entry.\n"
"Queue time estimation may be unavailable until this track is cleared.\n"
"Entry file: %s"
msgstr ""
"MusicBot n'a pas pu obtenir les données de durée pour cette entrée.\n"
"L'estimation du temps d'attente peut être indisponible jusqu'à ce que cette piste soit effacée.\n"
"Fichier d'entrée: %s"

#. Used by: debug
#: musicbot/entry.py:543
#, python-format
msgid "Got duration of %(time)s seconds for file:  %(file)s"
msgstr "Durée de %(time)s secondes pour le fichier :  %(file)s"

#. Used by: error
#: musicbot/entry.py:554 musicbot/entry.py:1224
msgid ""
"There as a problem with working out EQ, likely caused by a strange "
"installation of FFmpeg. This has not impacted the ability for the bot to "
"work, but will mean your tracks will not be equalized."
msgstr ""
"Il y a un problème avec le fonctionnement de l'EQ, probablement causé par "
"une installation étrange de FFmpeg. Cela n'a pas affecté la capacité du bot "
"à travailler, mais cela signifie que vos pistes ne seront pas égalées."

#. Used by: error
#: musicbot/entry.py:566 musicbot/entry.py:1237
msgid "Exception while checking entry data."
msgstr "Exception lors de la vérification des données d'entrée."

#. Used by: debug
#: musicbot/entry.py:577 musicbot/entry.py:1248
#, python-format
msgid "Trying to get duration via pymediainfo for:  %s"
msgstr "Essai d'obtenir la durée via pymediainfo pour:  %s"

#. Used by: exception
#: musicbot/entry.py:583 musicbot/entry.py:1254
msgid "Failed to get duration via pymediainfo."
msgstr "Impossible d'obtenir la durée via pymediainfo."

#. Used by: debug
#: musicbot/entry.py:590 musicbot/entry.py:1261
#, python-format
msgid "Trying to get duration via ffprobe for:  %s"
msgstr "Essai d'obtenir la durée via ffprobe pour:  %s"

#. Used by: error
#: musicbot/entry.py:593 musicbot/entry.py:1264
msgid "Could not locate ffprobe in your path!"
msgstr "Impossible de localiser ffprobe dans votre chemin !"

#. Used by: error
#: musicbot/entry.py:614 musicbot/entry.py:1285
msgid "ffprobe returned something that could not be used."
msgstr "ffprobe a renvoyé quelque chose qui n'a pas pu être utilisé."

#. Used by: exception
#: musicbot/entry.py:617 musicbot/entry.py:1288
msgid "ffprobe could not be executed for some reason."
msgstr "ffprobe n'a pas pu être exécuté pour une raison quelconque."

#. Used by: debug
#: musicbot/entry.py:627 musicbot/entry.py:1298
#, python-format
msgid "Calculating mean volume of:  %s"
msgstr "Calcul du volume moyen de :  %s"

#. Used by: error
#: musicbot/entry.py:630 musicbot/entry.py:1301
msgid "Could not locate ffmpeg on your path!"
msgstr "Impossible de localiser ffmpeg sur votre chemin !"

#. Used by: debug
#: musicbot/entry.py:656 musicbot/entry.py:1327
msgid "Could not parse 'I' in normalize json."
msgstr "Impossible d'analyser 'I' dans normaliser json."

#. Used by: debug
#: musicbot/entry.py:664 musicbot/entry.py:1335
msgid "Could not parse 'LRA' in normalize json."
msgstr "Impossible d'analyser 'LRA' en normalise json."

#. Used by: debug
#: musicbot/entry.py:672 musicbot/entry.py:1343
msgid "Could not parse 'TP' in normalize json."
msgstr "Impossible d'analyser 'TP' dans normaliser json."

#. Used by: debug
#: musicbot/entry.py:680 musicbot/entry.py:1351
msgid "Could not parse 'thresh' in normalize json."
msgstr "Impossible d'analyser 'thresh' dans normalise json."

#. Used by: debug
#: musicbot/entry.py:688 musicbot/entry.py:1359
msgid "Could not parse 'offset' in normalize json."
msgstr "Impossible d'analyser 'offset' dans normalise json."

#. Used by: info
#: musicbot/entry.py:705
#, python-format
msgid "Download started:  %r"
msgstr "Téléchargement démarré:  %r"

#. Used by: everything
#: musicbot/entry.py:710
#, python-format
msgid "Download attempt %s of 3..."
msgstr "Tentative de téléchargement %s de 3..."

#. Used by: warning
#: musicbot/entry.py:722
#, python-format
msgid ""
"Download incomplete, retrying in %(time).1f seconds.  Reason: %(raw_error)s"
msgstr ""
"Téléchargement incomplet, nouvel essai dans %(time).1f secondes. Raison : "
"%(raw_error)s"

#. Used by: error
#: musicbot/entry.py:730
#, python-format
msgid "Download failed, not retrying! Reason:  %(raw_error)s"
msgstr ""
"Le téléchargement a échoué, ne pas réessayer ! Raison :  %(raw_error)s"

#. Used by: ExtractionError
#: musicbot/entry.py:735
#, python-format
msgid "Download did not complete due to an error: %(raw_error)s"
msgstr ""
"Le téléchargement n'a pas été terminé en raison d'une erreur : %(raw_error)s"

#. Used by: ExtractionError
#: musicbot/entry.py:741
#, python-format
msgid "Download failed due to a yt-dlp error: %(raw_error)s"
msgstr ""
"Le téléchargement a échoué à cause d'une erreur yt-dlp : %(raw_error)s"

#. Used by: error
#: musicbot/entry.py:747
msgid "Extraction encountered an unhandled exception."
msgstr "L'extraction a rencontré une exception non gérée."

#. Used by: MusicbotException
#: musicbot/entry.py:751
#, python-format
msgid "Download failed due to an unhandled exception: %(raw_error)s"
msgstr ""
"Le téléchargement a échoué en raison d'une exception non gérée : "
"%(raw_error)s"

#. Used by: error
#: musicbot/entry.py:756
#, python-format
msgid "Download failed:  %r"
msgstr "Échec du téléchargement :  %r"

#. Used by: ExtractionError
#: musicbot/entry.py:757
msgid "Failed to extract data for the requested media."
msgstr "Impossible d'extraire les données pour les médias demandés."

#. Used by: info
#: musicbot/entry.py:759
#, python-format
msgid "Download complete:  %r"
msgstr "Téléchargement terminé :  %r"

#. Used by: warning
#: musicbot/entry.py:890
#, python-format
msgid "Deserialized StreamPlaylistEntry cannot find channel with ID:  %s"
msgstr ""
"StreamPlaylistEntry désérialisé ne peut pas trouver de canal avec l'ID :  %s"

#. Used by: warning
#: musicbot/entry.py:906
#, python-format
msgid "Deserialized StreamPlaylistEntry has the wrong channel type:  %s"
msgstr "StreamPlaylistEntry désérialisé a le mauvais type de canal :  %s"

#. Used by: warning
#: musicbot/entry.py:928
#, python-format
msgid "Deserialized StreamPlaylistEntry cannot find author with ID:  %s"
msgstr ""
"StreamPlaylistEntry désérialisé ne peut pas trouver l'auteur avec l'ID :  %s"

#. Used by: warning
#: musicbot/entry.py:934
msgid ""
"Deserialized StreamPlaylistEntry has an author ID but no channel for lookup!"
msgstr ""
"StreamPlaylistEntry désérialisé a un ID d'auteur mais aucun canal à "
"rechercher !"

#. Used by: warning
#: musicbot/entry.py:1103
#, python-format
msgid "Deserialized LocalFilePlaylistEntry cannot find channel with ID:  %s"
msgstr ""
"Le canal LocalFilePlaylistEntry désérialisé ne peut pas être trouvé avec "
"l'ID :  %s"

#. Used by: warning
#: musicbot/entry.py:1119
#, python-format
msgid "Deserialized LocalFilePlaylistEntry has the wrong channel type:  %s"
msgstr "LocalFilePlaylistEntry désérialisé a le mauvais type de canal :  %s"

#. Used by: warning
#: musicbot/entry.py:1141
#, python-format
msgid "Deserialized LocalFilePlaylistEntry cannot find author with ID:  %s"
msgstr ""
"LocalFilePlaylistEntry désérialisé ne peut pas trouver l'auteur avec l'ID :"
"  %s"

#. Used by: warning
#: musicbot/entry.py:1147
msgid ""
"Deserialized LocalFilePlaylistEntry has an author ID but no channel for "
"lookup!"
msgstr ""
"LocalFilePlaylistEntry désérialisé a un ID de l'auteur mais aucun canal de "
"recherche !"

#. Used by: debug
#: musicbot/entry.py:1213
#, python-format
msgid "Got duration of %(seconds)s seconds for file:  %(file)s"
msgstr "Durée de %(seconds)s secondes pour le fichier :  %(file)s"

#. Used by: warning
#: musicbot/filecache.py:120
#, python-format
msgid "Failed to delete cache file:  %s"
msgstr "Impossible de supprimer le fichier de cache :  %s"

#. Used by: debug
#: musicbot/filecache.py:131
msgid "Audio cache directory has been removed."
msgstr "Le répertoire de cache audio a été supprimé."

#. Used by: debug
#: musicbot/filecache.py:138
msgid "Audio cache directory could not be removed or renamed."
msgstr "Le répertoire de cache audio n'a pas pu être supprimé ou renommé."

#. Used by: debug
#: musicbot/filecache.py:145
msgid "Audio cache directory could not be removed."
msgstr "Le répertoire de cache audio n'a pas pu être supprimé."

#. Used by: debug
#: musicbot/filecache.py:154
msgid "Audio cache has no limits set, nothing to delete."
msgstr "Le cache audio n'a pas de limites définies, rien à supprimer."

#. Used by: debug
#: musicbot/filecache.py:217
#, python-format
msgid "Audio cache deleted %(number)s file(s), total of %(size)s removed."
msgstr ""
"Le cache audio a supprimé le(s) fichier(s) %(number)s (s), total de %(size)s"
" supprimé(s)."

#. Used by: debug
#: musicbot/filecache.py:225
#, python-format
msgid ""
"Audio cached retained %(number)s file(s) from autoplaylist, total of "
"%(size)s retained."
msgstr ""
"L'audio mis en cache a retenu le(s) fichier(s) %(number)s de la liste de "
"lecture automatique, total de %(size)s retenu."

#. Used by: debug
#: musicbot/filecache.py:234
#, python-format
msgid "Audio cache is now %(size)s over %(number)s file(s)."
msgstr "Le cache audio est maintenant %(size)s sur %(number)s fichier(s)."

#. Used by: debug
#: musicbot/filecache.py:250
msgid "Audio cache directory is missing, nothing to delete."
msgstr "Le répertoire de cache audio est manquant, rien à supprimer."

#. Used by: noise
#: musicbot/filecache.py:269
msgid ""
"Audio cache file is from autoplaylist but marked as busted, ignoring it."
msgstr ""
"Le fichier de cache audio provient de la liste de lecture automatique, mais "
"marqué comme busé, l'ignorant."

#. Used by: debug
#: musicbot/filecache.py:280
#, python-format
msgid "Cache level requires cleanup. %s"
msgstr "Le niveau de cache nécessite un nettoyage. %s"

#. Used by: debug
#: musicbot/filecache.py:304
msgid "Auto playlist has no cache map, moving on."
msgstr "La liste de lecture automatique n'a pas de carte de cache."

#. Used by: info
#: musicbot/filecache.py:312
#, python-format
msgid "Loaded auto playlist cache map with %s entries."
msgstr ""
"Carte de cache de la liste de lecture automatique chargée avec les entrées "
"%s."

#. Used by: exception
#: musicbot/filecache.py:316
msgid "Failed to load auto playlist cache map."
msgstr "Impossible de charger le cache de la liste de lecture automatique."

#. Used by: debug
#: musicbot/filecache.py:341
#, python-format
msgid "Saved auto playlist cache map with %s entries."
msgstr ""
"La carte du cache de la liste de lecture automatique avec les entrées %s a "
"été enregistrée."

#. Used by: exception
#: musicbot/filecache.py:345
msgid "Failed to save auto playlist cache map."
msgstr ""
"Impossible d'enregistrer la carte du cache de la liste de lecture "
"automatique."

#. Used by: warning
#: musicbot/filecache.py:363
#, python-format
msgid ""
"Auto playlist cache map conflict on Key: %(file)s  Old: %(old)s  New: "
"%(new)s"
msgstr ""
"Conflit de la carte de la liste de lecture automatique sur Clef : %(file)s  "
"Ancien: %(old)s  Nouveau: %(new)s"

#. Used by: debug
#: musicbot/i18n.py:229
#, python-format
msgid "Lang Argument Error:  %s"
msgstr "Erreur Argument de Langue :  %s"

#. Used by: warning
#: musicbot/i18n.py:290
#, python-format
msgid "Failed to load log translations for any of:  [%s]  in:  %s"
msgstr ""
"Impossible de charger les traductions du journal pour n'importe quelle de:  "
"[%s]  dans:  %s"

#. Used by: warning
#: musicbot/i18n.py:338
#, python-format
msgid ""
"Failed to load discord translations for any of:  [%s]  guild:  %s  in:  %s"
msgstr ""
"Impossible de charger les traductions de discord pour n'importe quelle de:  "
"[%s]  guilde:  %s  dans:  %s"

#. Used by: debug
#: musicbot/json.py:14
#, python-format
msgid "Loading JSON file: %s"
msgstr "Chargement du fichier JSON : %s"

#. Used by: error
#: musicbot/json.py:27
#, python-format
msgid "Error parsing %s as JSON"
msgstr "Erreur lors de l'analyse de %s en JSON"

#. Used by: warning
#: musicbot/json.py:36
#, python-format
msgid "Could not grab data from JSON key: %s"
msgstr "Impossible de récupérer les données de la clé JSON : %s"

#. Used by: debug
#: musicbot/logs.py:131
msgid "Skipping logger setup, already set up"
msgstr "Ignorer la configuration du logger, déjà configuré"

#. Used by: debug
#: musicbot/logs.py:283
#, python-format
msgid "Log level was previously set via override to: %s"
msgstr "Le niveau du journal a été précédemment défini en remplaçant à: %s"

#. Used by: info
#: musicbot/logs.py:292
#, python-format
msgid "Changing log level to:  %s"
msgstr "Changement du niveau du journal à :  %s"

#. Used by: info
#: musicbot/logs.py:321
msgid "MusicBot loggers have been called to shut down."
msgstr "Les enregistreurs MusicBot ont été appelés à s'arrêter."

#. Used by: warning
#: musicbot/permissions.py:120
#, python-format
msgid "Permissions file not found, copying from:  %s"
msgstr "Fichier de permissions introuvable, copie de:  %s"

#. Used by: exception
#: musicbot/permissions.py:129
#, python-format
msgid "Error copying example permissions file:  %s"
msgstr "Erreur lors de la copie du fichier d'exemple des permissions :  %s"

#. Used by: debug
#: musicbot/permissions.py:195
msgid "Config 'OwnerID' is set auto, will set correctly later."
msgstr ""
"La configuration 'OwnerID' est réglée automatiquement, elle sera "
"correctement configurée plus tard."

#. Used by: debug
#: musicbot/permissions.py:212
msgid "Validating permissions..."
msgstr "Validation des permissions..."

#. Used by: debug
#: musicbot/permissions.py:214
msgid "Setting auto 'OwnerID' for owner permissions group."
msgstr "Réglage auto 'OwnerID' pour le groupe de permissions propriétaires."

#. Used by: debug
#: musicbot/permissions.py:274
#, python-format
msgid "Updating group in permissions file:  %s"
msgstr "Mise à jour du groupe dans le fichier des permissions :  %s"

#. Used by: debug
#: musicbot/permissions.py:280
#, python-format
msgid "Deleting group from permissions file:  %s"
msgstr "Suppression du groupe du fichier des permissions :  %s"

#. Used by: debug
#: musicbot/permissions.py:285
#, python-format
msgid "Adding new group to permissions file:  %s"
msgstr "Ajout d'un nouveau groupe au fichier des permissions :  %s"

#. Used by: debug
#: musicbot/permissions.py:300
msgid "Saving permissions file now."
msgstr "Enregistrement du fichier des permissions maintenant."

#. Used by: exception
#: musicbot/permissions.py:306
msgid "ConfigUpdater could not parse the permissions file!"
msgstr "ConfigUpdater n'a pas pu analyser le fichier des permissions !"

#. Used by: exception
#: musicbot/permissions.py:308
msgid "You have a duplicate section, fix your Permissions file!"
msgstr ""
"Vous avez une section en double, corrigez votre fichier de permissions!"

#. Used by: exception
#: musicbot/permissions.py:310
#, python-format
msgid "Failed to save permissions group:  %s"
msgstr "Impossible d'enregistrer le groupe de permissions :  %s"

#. Used by: critical
#: musicbot/permissions.py:325
msgid "Dev Bug! Permission has getter that is not available."
msgstr "Bug Dev ! Permission a un getter qui n'est pas disponible."

#. Used by: error
#: musicbot/permissions.py:330
msgid ""
"Dev Bug! Permission has invalid type, getter and default must be the same "
"type."
msgstr ""
"Bug Dev ! La permission a un type non valide, getter et default doit être le"
" même type."

#. Used by: warning
#: musicbot/permissions.py:574
msgid "Max search items can't be larger than 100. Setting to 100."
msgstr ""
"Le maximum d'éléments de recherche ne peut pas être supérieur à 100. Réglage"
" à 100."

#. Used by: PermissionsError
#: musicbot/permissions.py:657
#, python-format
msgid ""
"You do not have permission to play the requested media.\n"
"The yt-dlp extractor `%(extractor)s` is not permitted in your group."
msgstr ""
"Vous n'avez pas la permission de lire le média demandé.\n"
"L'extracteur yt-dlp `%(extractor)s` n'est pas autorisé dans votre groupe."

#. Used by: noise
#: musicbot/player.py:86
#, python-format
msgid "Cleanup got called on the audio source:  %r"
msgstr "Nettoyage appelé à la source audio :  %r"

#. Used by: noise
#: musicbot/player.py:191
#, python-format
msgid "MusicPlayer.skip() is called:  %s"
msgstr "MusicPlayer.skip() est appelée :  %s"

#. Used by: noise
#: musicbot/player.py:201
#, python-format
msgid "MusicPlayer.stop() is called:  %s"
msgstr "MusicPlayer.stop() est appelée :  %s"

#. Used by: warning
#: musicbot/player.py:216
msgid "Guild or network unavailable, cannot resume playback."
msgstr "Guilde ou réseau indisponible, impossible de reprendre la lecture."

#. Used by: noise
#: musicbot/player.py:220
#, python-format
msgid "MusicPlayer.resume() is called:  %s"
msgstr "MusicPlayer.resume() est appelée :  %s"

#. Used by: noise
#: musicbot/player.py:240
#, python-format
msgid "MusicPlayer.pause() is called:  %s"
msgstr "MusicPlayer.pause() est appelée :  %s"

#. Used by: noise
#: musicbot/player.py:262
#, python-format
msgid "MusicPlayer.kill() is called:  %s"
msgstr "MusicPlayer.kill() est appelé :  %s"

#. Used by: debug
#: musicbot/player.py:288
msgid "Playback finished, but _current_entry is None."
msgstr "Lecture terminée, mais _current_entry est Aucune."

#. Used by: noise
#: musicbot/player.py:343
msgid "Possible Warning from kill_current_player()"
msgstr "Avertissement possible de kill_current_player()"

#. Used by: noise
#: musicbot/player.py:362
#, python-format
msgid "MusicPlayer.play() is called:  %s"
msgstr "MusicPlayer.play() est appelée :  %s"

#. Used by: voicedebug
#: musicbot/player.py:372
msgid "MusicPlayer is dead, cannot play."
msgstr "MusicPlayer est mort, impossible de jouer."

#. Used by: warning
#: musicbot/player.py:377
msgid "Guild or network unavailable, cannot start playback."
msgstr "Guilde ou réseau indisponible, impossible de démarrer la lecture."

#. Used by: voicedebug
#: musicbot/player.py:382
msgid "MusicPlayer was previously paused, resuming current player."
msgstr ""
"MusicPlayer a été mis en pause précédemment, reprenant le lecteur actuel."

#. Used by: voicedebug
#: musicbot/player.py:388
msgid "MusicPlayer already locked for playback, this call is ignored."
msgstr ""
"MusicPlayer est déjà verrouillé pour la lecture, cet appel est ignoré."

#. Used by: warning
#: musicbot/player.py:399
msgid "Failed to get next entry."
msgstr "Impossible d'obtenir l'entrée suivante."

#. Used by: warning
#: musicbot/player.py:403
msgid "Failed to process entry for playback."
msgstr "Impossible de traiter l'entrée pour la lecture."

#. Used by: ffmpeg
#: musicbot/player.py:485
#, python-format
msgid "Creating player with options: ffmpeg %(before)s -i %(input)s %(after)s"
msgstr ""
"Création d'un joueur avec des options : ffmpeg %(before)s -i %(input)s "
"%(after)s"

#. Used by: voicedebug
#: musicbot/player.py:489
#, python-format
msgid "Playing %(source)r using %(client)r"
msgstr "Jouer à %(source)r en utilisant %(client)r"

#. Used by: debug
#: musicbot/player.py:520
#, python-format
msgid "Skipping deletion of '%s', found song in queue"
msgstr "Suppression de '%s', chanson trouvée dans la file d'attente"

#. Used by: debug
#: musicbot/player.py:524
#, python-format
msgid "Deleting file:  %s"
msgstr "Suppression du fichier :  %s"

#. Used by: debug
#: musicbot/player.py:529
#, python-format
msgid "File deleted:  %s"
msgstr "Fichier supprimé :  %s"

#. Used by: warning
#: musicbot/player.py:533
msgid "Cannot delete file, it is currently in use."
msgstr "Impossible de supprimer le fichier, il est actuellement utilisé."

#. Used by: warning
#: musicbot/player.py:536
msgid "Cannot delete file due to a permission error."
msgstr ""
"Impossible de supprimer le fichier en raison d'une erreur d'autorisation."

#. Used by: warning
#: musicbot/player.py:541
msgid "Cannot delete file, it was not found."
msgstr "Impossible de supprimer le fichier, il est introuvable."

#. Used by: warning
#: musicbot/player.py:547
msgid "Error while trying to delete file."
msgstr "Erreur lors de la tentative de suppression du fichier."

#. Used by: debug
#: musicbot/player.py:552
msgid "Could not delete file, giving up and moving on"
msgstr "Impossible de supprimer le fichier, d'abandonner et de déplacer le"

#. Used by: error
#: musicbot/player.py:618
#, python-format
msgid "Deserialize returned an object that is not a MusicPlayer:  %s"
msgstr "Désérialiser a renvoyé un objet qui n'est pas un MusicPlayer :  %s"

#. Used by: exception
#: musicbot/player.py:623
msgid "Failed to deserialize player"
msgstr "Impossible de désérialiser le joueur"

#. Used by: ffmpeg
#: musicbot/player.py:685
#, python-format
msgid "Data from ffmpeg: %s"
msgstr "Données de ffmpeg : %s"

#. Used by: ffmpeg
#: musicbot/player.py:695
#, python-format
msgid "Error from ffmpeg: %s"
msgstr "Erreur de ffmpeg : %s"

#. Used by: ffmpeg
#: musicbot/player.py:703
#, python-format
msgid "Warning from ffmpeg:  %s"
msgstr "Avertissement de ffmpeg :  %s"

#. Used by: ffmpeg
#: musicbot/player.py:732
msgid "Unknown error decoding message from ffmpeg"
msgstr "Erreur inconnue lors du décodage du message de ffmpeg"

#. Used by: ffmpeg
#: musicbot/player.py:736
#, python-format
msgid "Decoded data from ffmpeg: %s"
msgstr "Données décodées de ffmpeg : %s"

#. Used by: noise
#: musicbot/playlist.py:121
#, python-format
msgid "Adding stream entry for URL:  %(url)s"
msgstr "Ajout de l'entrée de flux pour l'URL :  %(url)s"

#. Used by: ExtractionError
#: musicbot/playlist.py:159
msgid "Could not extract information"
msgstr "Impossible d'extraire les informations"

#. Used by: WrongEntryTypeError
#: musicbot/playlist.py:163
msgid "This is a playlist."
msgstr "Ceci est une liste de lecture."

#. Used by: debug
#: musicbot/playlist.py:177
msgid "Entry info appears to be a stream, adding stream entry..."
msgstr ""
"Les informations d'entrée semblent être un flux, ajoutant une entrée de "
"flux..."

#. Used by: ExtractionError
#: musicbot/playlist.py:195
#, python-format
msgid "Invalid content type `%(type)s` for URL: %(url)s"
msgstr "Type de contenu invalide `%(type)s` pour l'URL : %(url)s"

#. Used by: warning
#: musicbot/playlist.py:203
msgid "Got text/html for content-type, this might be a stream."
msgstr "Texte reçu/html pour le type de contenu, il peut s'agir d'un flux."

#. Used by: warning
#: musicbot/playlist.py:210
#, python-format
msgid "Questionable content-type \"%(type)s\" for url:  %(url)s"
msgstr "Type de contenu questionnable «%(type)s» pour url:  %(url)s"

#. Used by: noise
#: musicbot/playlist.py:215
#, python-format
msgid "Adding URLPlaylistEntry for: %(subject)s"
msgstr "Ajout d'URLPlaylistEntry pour: %(subject)s"

#. Used by: noise
#: musicbot/playlist.py:235
#, python-format
msgid "Adding LocalFilePlaylistEntry for: %(subject)s"
msgstr "Ajout de LocalFilePlaylistEntry pour : %(subject)s"

#. Used by: debug
#: musicbot/playlist.py:280
#, python-format
msgid "Ignored video from compound playlist link with ID:  %s"
msgstr "Vidéo ignorée à partir du lien de la playlist composée avec ID:  %s"

#. Used by: info
#: musicbot/playlist.py:292
#, python-format
msgid ""
"Not allowing entry that is in song block list:  %(title)s  URL: %(url)s"
msgstr ""
"Ne permet pas l'entrée qui se trouve dans la liste de blocs de chansons : "
"URL  %(title)s  : %(url)s"

#. Used by: debug
#: musicbot/playlist.py:305
#, python-format
msgid ""
"Ignoring song in entries by '%s', duration longer than permitted maximum."
msgstr ""
"Ignorer la chanson dans les entrées par '%s', durée plus longue que la durée"
" maximale autorisée."

#. Used by: warning
#: musicbot/playlist.py:317
#, python-format
msgid "Not adding YouTube video because it is marked private or deleted:  %s"
msgstr ""
"Ne pas ajouter de vidéo YouTube car elle est marquée comme privée ou "
"supprimée :  %s"

#. Used by: warning
#: musicbot/playlist.py:342
msgid "Could not add item"
msgstr "Impossible d'ajouter l'élément"

#. Used by: debug
#: musicbot/playlist.py:343
#, python-format
msgid "Item: %s"
msgstr "Objet : %s"

#. Used by: info
#: musicbot/playlist.py:346
#, python-format
msgid "Skipped %s bad entries"
msgstr "A ignoré les entrées incorrectes %s"

#. Used by: everything
#: musicbot/playlist.py:387
msgid "Reorder looping over entries."
msgstr "Réorganiser la boucle sur les entrées."

#. Used by: everything
#: musicbot/playlist.py:469
#, python-format
msgid "Pre-downloading next track:  %r"
msgstr "Pré-téléchargement de la piste suivante :  %r"

#. Used by: InvalidDataError
#: musicbot/playlist.py:495
msgid "no duration data"
msgstr "aucune donnée de durée"

#. Used by: InvalidDataError
#: musicbot/playlist.py:504
msgid "no duration data in current entry"
msgstr "aucune donnée de durée dans l'entrée actuelle"

#. Used by: SpotifyError
#: musicbot/spotify.py:119
#, python-format
msgid "Invalid track_data, must be of type `track` got `%(type)s`"
msgstr ""
"Les track_data non valides, doivent être de type `track` obtenu `%(type)s`"

#. Used by: everything
#: musicbot/spotify.py:301
#, python-format
msgid "Ignored non-track entry in playlist with type:  %s"
msgstr "Entrée non-trackée ignorée dans la playlist avec le type :  %s"

#. Used by: debug
#: musicbot/spotify.py:487
#, python-format
msgid "Spotify Album total tacks:  %(total)s  Next URL: %(url)s"
msgstr "Total de l'album Spotify :  %(total)s  URL suivante : %(url)s"

#. Used by: debug
#: musicbot/spotify.py:492
#, python-format
msgid "Getting Spotify Album Next URL:  %s"
msgstr "Récupération de l'URL suivante de l'album Spotify :  %s"

#. Used by: warning
#: musicbot/spotify.py:503
#, python-format
msgid ""
"Spotify Album Object may not be complete, expected %(total)s tracks but got "
"%(number)s"
msgstr ""
"L'objet Album Spotify peut ne pas être complet, les pistes %(total)s "
"attendues mais %(number)s obtenu"

#. Used by: warning
#: musicbot/spotify.py:507
msgid "Spotify Album has more tracks than initial total."
msgstr "Spotify Album a plus de pistes que le total initial."

#. Used by: debug
#: musicbot/spotify.py:530
#, python-format
msgid "Spotify Playlist total tacks: %(total)s  Next URL: %(url)s"
msgstr "Total de la playlist Spotify : %(total)s  URL suivante : %(url)s"

#. Used by: debug
#: musicbot/spotify.py:535
#, python-format
msgid "Getting Spotify Playlist Next URL:  %s"
msgstr "Récupération de la liste de lecture Spotify URL suivante :  %s"

#. Used by: warning
#: musicbot/spotify.py:546
#, python-format
msgid ""
"Spotify Playlist Object may not be complete, expected %(total)s tracks but "
"got %(number)s"
msgstr ""
"L'objet Spotify Playlist peut ne pas être complet, les pistes %(total)s "
"attendues mais %(number)s"

#. Used by: warning
#: musicbot/spotify.py:550
msgid "Spotify Playlist has more tracks than initial total."
msgstr "Spotify Playlist a plus de pistes que le total initial."

#. Used by: debug
#: musicbot/spotify.py:555
#, python-format
msgid "Spotify Playlist contained %s usable tracks."
msgstr "Spotify Playlist contenait %s pistes utilisables."

#. Used by: SpotifyError
#: musicbot/spotify.py:581 musicbot/spotify.py:617
#, python-format
msgid "Response status is not OK: [%(status)s] %(reason)s"
msgstr "Le statut de la réponse n'est pas correct : [%(status)s] %(reason)s"

#. Used by: SpotifyError
#: musicbot/spotify.py:587 musicbot/spotify.py:623 musicbot/spotify.py:733
msgid "Response JSON did not decode to a dict!"
msgstr "La réponse JSON n'a pas décodé un dictionnaire !"

#. Used by: exception
#: musicbot/spotify.py:596
#, python-format
msgid "Failed making GET request to url:  %s"
msgstr "Impossible de faire la requête GET à l'url:  %s"

#. Used by: SpotifyError
#: musicbot/spotify.py:602
#, python-format
msgid "Could not make GET to URL:  %(url)s  Reason:  %(raw_error)s"
msgstr "Impossible de rendre GET à l'URL :  %(url)s  Raison :  %(raw_error)s"

#. Used by: exception
#: musicbot/spotify.py:632
#, python-format
msgid "Failed making POST request to url:  %s"
msgstr "Impossible de faire la requête POST à l'url:  %s"

#. Used by: SpotifyError
#: musicbot/spotify.py:638
#, python-format
msgid "Could not make POST to URL:  %(url)s  Reason:  %(raw_error)s"
msgstr "Impossible de faire POST à l'URL :  %(url)s  Raison :  %(raw_error)s"

#. Used by: SpotifyError
#: musicbot/spotify.py:672
msgid ""
"Failed to get a guest token from Spotify, please try specifying client ID "
"and client secret"
msgstr ""
"Impossible d'obtenir un jeton d'invité de Spotify, veuillez essayer de "
"spécifier l'ID client et le secret du client"

#. Used by: debug
#: musicbot/spotify.py:679
msgid "Created a new Guest Mode access token."
msgstr "Créé un nouveau jeton d'accès en mode invité."

#. Used by: SpotifyError
#: musicbot/spotify.py:683
#, python-format
msgid ""
"API response did not contain the expected data. Missing key: %(raw_error)s"
msgstr ""
"La réponse de l'API ne contient pas les données attendues. Clé manquante: "
"%(raw_error)s"

#. Used by: SpotifyError
#: musicbot/spotify.py:689
#, python-format
msgid ""
"API response contained unexpected data.\n"
"%(raw_error)s"
msgstr ""
"La réponse de l'API contenait des données inattendues.\n"
"%(raw_error)s"

#. Used by: SpotifyError
#: musicbot/spotify.py:696
msgid "Requested a token from Spotify, did not end up getting one"
msgstr "Demandé un jeton de Spotify, n'a pas fini par en obtenir un"

#. Used by: debug
#: musicbot/spotify.py:700
msgid "Created a new Client Mode access token."
msgstr "Créé un nouveau jeton d'accès au mode client."

#. Used by: SpotifyError
#: musicbot/spotify.py:727
#, python-format
msgid "API response status is not OK: [%(status)s]  %(reason)s"
msgstr ""
"Le statut de réponse de l'API n'est pas correct : [%(status)s]  %(reason)s"

#. Used by: exception
#: musicbot/spotify.py:743
msgid "Failed to get Spotify Guest Token."
msgstr "Impossible d'obtenir le jeton d'invité Spotify."

#. Used by: error
#: musicbot/spotify.py:750
#, python-format
msgid "Failed to get Guest Token due to: %(raw_error)s"
msgstr "Impossible d'obtenir le jeton d'invité en raison de: %(raw_error)s"

#. Used by: PermissionsError
#: musicbot/utils.py:174
msgid "Only the owner can use this command."
msgstr "Seul le propriétaire peut utiliser cette commande."

#. Used by: PermissionsError
#: musicbot/utils.py:194
msgid "Only dev users can use this command."
msgstr "Seuls les utilisateurs de dev peuvent utiliser cette commande."

#. Used by: debug
#: musicbot/utils.py:280 musicbot/utils.py:322
msgid "Cannot count members when voice_channel is None."
msgstr "Impossible de compter les membres quand voice_channel est None."

#. Used by: warning
#: run.py:107
msgid "Could not find git executable."
msgstr "Impossible de trouver l'exécutable git."

#. Used by: info
#: run.py:156
msgid "Attempting to upgrade with `git pull` on current path."
msgstr "Tentative de mise à jour avec `git pull` sur le chemin courant."

#. Used by: info
#: run.py:163
#, python-format
msgid "Result of git pull:  %s"
msgstr "Résultat du tirage git :  %s"

#. Used by: exception
#: run.py:171
msgid "Upgrade failed, you need to run `git pull` manually."
msgstr "La mise à jour a échoué, vous devez exécuter `git pull` manuellement."

#. Used by: _L
#: run.py:181
msgid "Cannot execute pip."
msgstr "Impossible d'exécuter le pip."

#. Used by: exception
#: run.py:188
msgid "Error using -m method"
msgstr "Erreur en utilisant la méthode -m"

#. Used by: exception
#: run.py:234
msgid "PIP failed while calling sub-process."
msgstr "Le PIP a échoué lors de l'appel du sous-processus."

#. Used by: exception
#: run.py:237
msgid "PIP failed due to Permission Error."
msgstr "Le PIP a échoué en raison d'une erreur de permission."

#. Used by: exception
#: run.py:241
#, python-format
msgid "PIP failed due to missing Python executable?  (%s)"
msgstr "Le PIP a échoué en raison de l'exécutable Python manquant ? (%s)"

#. Used by: exception
#: run.py:246
msgid "PIP failed due to OSError."
msgstr "Le PIP a échoué en raison d'une erreur d'OS."

#. Used by: warning
#: run.py:267
msgid "Could not decode pip update report JSON."
msgstr "Impossible de décoder le rapport de mise à jour de pip JSON."

#. Used by: _L
#: run.py:289
msgid "Cannot locate or execute python -m pip"
msgstr "Impossible de localiser ou d'exécuter python -m pip"

#. Used by: info
#: run.py:292
#, python-format
msgid "Attempting to upgrade with `%s` on current path..."
msgstr "Tentative de mise à jour avec `%s` sur le chemin courant..."

#. Used by: info
#: run.py:310
#, python-format
msgid ""
"Result of pip upgrade:\n"
"%s"
msgstr ""
"Résultat de l'amélioration de pip :\n"
"%s"

#. Used by: info
#: run.py:315
#, python-format
msgid "Result exit code from pip upgrade: %s"
msgstr "Résultat du code de sortie de la mise à jour de pip : %s"

#. Used by: exception
#: run.py:330
msgid "Upgrade failed to execute or we could not understand the output"
msgstr ""
"La mise à jour n'a pas réussi à s'exécuter ou nous n'avons pas pu comprendre"
" la sortie"

#. Used by: warning
#: run.py:333
#, python-format
msgid "You may need to run `%s` manually."
msgstr "Vous devrez peut-être exécuter `%smanuellement."

#. Used by: _L
#: run.py:342
msgid "Press enter to continue . . ."
msgstr "Appuyez sur Entrée pour continuer . . . ."

#. Used by: info
#: run.py:355
msgid "Starting sanity checks"
msgstr "Démarrage des contrôles de santé"

#. Used by: info
#: run.py:366
msgid "Required checks passed."
msgstr "Les contrôles requis ont été effectués."

#. Used by: info
#: run.py:379
msgid "Skipped checking for updates."
msgstr "Vérification des mises à jour ignorée."

#. Used by: info
#: run.py:381
msgid "Optional checks passed."
msgstr "Vérifications optionnelles réussies."

#. Used by: warning
#: run.py:403
msgid "Could not locate py.exe"
msgstr "Impossible de localiser py.exe"

#. Used by: info
#: run.py:418
msgid "Python 3 found.  Launching bot..."
msgstr "Python 3 trouvé. Lancement du bot..."

#. Used by: info
#: run.py:478
msgid "Ensuring we're in the right environment"
msgstr "Veiller à ce que nous soyons dans le bon environnement"

#. Used by: critical
#: run.py:501
#, python-format
msgid "Failed environment check, %s"
msgstr "Échec de la vérification de l'environnement, %s"

#. Used by: info
#: run.py:542
#, python-format
msgid "Detected FFmpeg is installed at:  %s"
msgstr "FFmpeg détecté est installé à:  %s"

#. Used by: info
#: run.py:544
msgid "Adding local bins/ folder environment PATH for bundled ffmpeg..."
msgstr ""
"Ajout du PATH d'environnement de bins/dossier local pour ffmpeg groupé..."

#. Used by: critical
#: run.py:553
msgid ""
"MusicBot could not locate FFmpeg binary in your environment.\n"
"Please install FFmpeg so it is available in your environment PATH variable."
msgstr ""
"MusicBot n'a pas pu localiser le binaire FFmpeg dans votre environnement.\n"
"Veuillez installer FFmpeg pour qu'il soit disponible dans votre variable PATH d'environnement."

#. Used by: info
#: run.py:558
msgid ""
"On Windows, you can add a pre-compiled EXE to the MusicBot `bin` folder,\n"
"or you can install FFmpeg system-wide using WinGet or by running the install.bat file."
msgstr ""
"Sous Windows, vous pouvez ajouter une EXE pré-compilée au dossier `bin` de MusicBot,\n"
"ou vous pouvez installer FFmpeg sur tout le système en utilisant WinGet ou en exécutant l'installation. dans le fichier."

#. Used by: info
#: run.py:563
msgid ""
"On MacOS, you may be able to install FFmpeg via homebrew.\n"
"Otherwise, check the official FFmpeg site for build or install steps."
msgstr ""
"Sur MacOS, vous pourriez être en mesure d'installer FFmpeg via homebrew.\n"
"Sinon, vérifiez le site officiel FFmpeg pour les étapes de compilation ou d'installation."

#. Used by: info
#: run.py:568
msgid ""
"On Linux, many distros make FFmpeg available via system package managers.\n"
"Check for ffmpeg with your system package manager or build from sources."
msgstr ""
"Sous Linux, de nombreuses distributions rendent FFmpeg disponible via les gestionnaires de paquets du système.\n"
"Vérifiez la présence de ffmpeg avec votre gestionnaire de paquets système ou construisez à partir des sources."

#. Used by: warning
#: run.py:581
#, python-format
msgid "Less than %sMB of free space remains on this device"
msgstr "Il reste moins de %sMB d'espace libre sur cet appareil"

#. Used by: info
#: run.py:590
msgid ""
"\n"
"Checking for updates to MusicBot or dependencies..."
msgstr ""
"\n"
"Vérification des mises à jour de MusicBot ou des dépendances..."

#. Used by: info
#: run.py:607
msgid "No MusicBot updates available via `git` command."
msgstr "Aucune mise à jour de MusicBot disponible via la commande `git`."

#. Used by: warning
#: run.py:610
msgid ""
"Could not check for updates using `git` commands.  You should check "
"manually."
msgstr ""
"Impossible de vérifier les mises à jour en utilisant les commandes `git`. "
"Vous devriez vérifier manuellement."

#. Used by: _L
#: run.py:617
msgid "The following packages can be updated:\n"
msgstr "Les paquets suivants peuvent être mis à jour :\n"

#. Used by: _L
#: run.py:623
#, python-format
msgid "  %s  to version:  %s\n"
msgstr "  %s  à la version :  %s\n"

#. Used by: info
#: run.py:634
msgid "No dependency updates available via `pip` command."
msgstr "Aucune mise à jour des dépendances disponible via la commande `pip`."

#. Used by: warning
#: run.py:637
msgid ""
"Could not check for updates using `pip` commands.  You should check "
"manually."
msgstr ""
"Impossible de vérifier les mises à jour en utilisant les commandes `pip`. "
"Vous devriez vérifier manuellement."

#. Used by: info
#: run.py:641
#, python-format
msgid ""
"You can run a guided update by using the command:\n"
"    %s ./update.py"
msgstr ""
"Vous pouvez lancer une mise à jour guidée en utilisant la commande :\n"
"    %s ./update.py"

#. Used by: _L
#: run.py:659
msgid "Value is above the maximum limit."
msgstr "La valeur est supérieure à la limite maximale."

#. Used by: _L
#: run.py:661
msgid "Value must not be negative."
msgstr "La valeur ne doit pas être négative."

#. Used by: _L
#: run.py:665
#, python-format
msgid "Value for Max Logs Kept must be a number from 0 to %s"
msgstr "La valeur pour Max Logs Kept doit être un nombre de 0 à %s"

#. Used by: _L
#: run.py:675
#, python-format
msgid "Log level '%s' is not available."
msgstr "Le niveau de log '%s' n'est pas disponible."

#. Used by: _L
#: run.py:679
#, python-format
msgid "Log Level must be one of:  %s"
msgstr "Le niveau de log doit être le :  %s"

#. Used by: _L
#: run.py:689
msgid ""
"Launch a music playing discord bot built using discord.py, youtubeDL, and "
"ffmpeg."
msgstr ""
"Lancez un bot discord construit en utilisant discord.py, youtubeDL, et "
"ffmpeg."

#. Used by: _L
#: run.py:692
msgid "Available via Github:"
msgstr "Disponible via Github:"

#. Used by: _L
#: run.py:696
msgid "For more help and support with this bot, join our discord:"
msgstr "Pour plus d'aide et de support avec ce bot, rejoignez notre discord:"

#. Used by: _L
#: run.py:698
msgid "This software is provided under the MIT License."
msgstr "Ce logiciel est fourni sous la licence MIT."

#. Used by: _L
#: run.py:700
msgid "See the `LICENSE` text file for complete details."
msgstr "Voir le fichier texte `LICENSE` pour plus de détails."

#. Used by: _L
#: run.py:713
msgid ""
"Override the default / system detected language for all text in MusicBot."
msgstr ""
"Remplacer la langue par défaut / système détectée pour tous les textes de "
"MusicBot."

#. Used by: _L
#: run.py:723
msgid "Use this language for all server-side log messages from MusicBot."
msgstr ""
"Utilisez cette langue pour tous les messages de log côté serveur de "
"MusicBot."

#. Used by: _L
#: run.py:733
msgid ""
"Use this language for all messages sent to discord from MusicBot.\n"
"This does not prevent per-guild language selection."
msgstr ""
"Utilisez cette langue pour tous les messages envoyés à la discorde de MusicBot.\n"
"Cela n'empêche pas la sélection de langue par guilde."

#. Used by: _L
#: run.py:744
msgid "Print the MusicBot version information and exit."
msgstr "Imprimez les informations de version de MusicBot et quittez."

#. Used by: _L
#: run.py:752
msgid "Skip all optional startup checks, including the update check."
msgstr ""
"Ignorer toutes les vérifications optionnelles de démarrage, y compris la "
"vérification de mise à jour."

#. Used by: _L
#: run.py:760
msgid "Skip only the disk space check at startup."
msgstr "Ignorer seulement l'espace disque au démarrage."

#. Used by: _L
#: run.py:768
msgid "Skip only the update check at startup."
msgstr "Ignorer uniquement la vérification des mises à jour au démarrage."

#. Used by: _L
#: run.py:777
msgid ""
"Disable MusicBot from trying to install dependencies when it cannot import "
"them."
msgstr ""
"Désactivez MusicBot d'essayer d'installer des dépendances quand il ne peut "
"pas les importer."

#. Used by: _L
#: run.py:789
#, python-format
msgid ""
"Specify how many log files to keep, between 0 and %s inclusive. (Default: "
"%s)"
msgstr ""
"Spécifiez le nombre de fichiers journaux à conserver, compris entre 0 et %s "
"inclusivement. (par défaut : %s)"

#. Used by: _L
#: run.py:800
#, python-format
msgid "Override the log level settings set in config. Must be one of: %s"
msgstr ""
"Remplacer les paramètres de niveau de journal définis dans la configuration."
" Doit être l'un des : %s"

#. Used by: _L
#: run.py:812
#, python-format
msgid ""
"Override the default date format used when rotating log files. This should "
"contain values compatible with strftime().  (Default:  '%s')"
msgstr ""
"Remplacer le format de date par défaut utilisé lors de la rotation des "
"fichiers journaux. Cela doit contenir des valeurs compatibles avec "
"strftime(). (par défaut: '%s')"

#. Used by: _L
#: run.py:843
#, python-format
msgid "Version:  %s"
msgstr "Version :  %s"

#. Used by: _L
#: run.py:918
msgid "Opened a new MusicBot instance. This terminal can be safely closed!"
msgstr ""
"Ouvert une nouvelle instance de MusicBot. Ce terminal peut être fermé en "
"toute sécurité!"

#. Used by: info
#: run.py:989
#, python-format
msgid "Loading MusicBot version:  %s"
msgstr "Chargement de la version de MusicBot :  %s"

#. Used by: info
#: run.py:990
#, python-format
msgid "Log opened:  %s"
msgstr "Journal ouvert :  %s"

#. Used by: info
#: run.py:991
#, python-format
msgid "Python version:  %s"
msgstr "Python version:  %s"

#. Used by: warning
#: run.py:1000
#, python-format
msgid "Changing working directory to:  %s"
msgstr "Changement du répertoire de travail en :  %s"

#. Used by: critical
#: run.py:1004
msgid ""
"Cannot start the bot!  You started `run.py` in the wrong directory and we "
"could not locate `musicbot` and `.git` folders to verify a new directory "
"location."
msgstr ""
"Impossible de démarrer le bot ! Vous avez démarré `run.py` dans le mauvais "
"répertoire et nous n'avons pas pu localiser `musicbot` et `. it` dossiers "
"pour vérifier un nouvel emplacement de répertoire."

#. Used by: error
#: run.py:1009
msgid ""
"For best results, start `run.py` from the same folder you cloned MusicBot into.\n"
"If you did not use git to clone the repository, you are strongly urged to."
msgstr ""
"Pour de meilleurs résultats, lancez `run.py` depuis le même dossier dans lequel vous avez cloné MusicBot.\n"
"Si vous n'avez pas utilisé git pour cloner le dépôt, il vous est fortement recommandé de le faire."

#. Used by: critical
#: run.py:1074
msgid ""
"Certificate error is not a verification error, not trying certifi and "
"exiting."
msgstr ""
"L'erreur de certificat n'est pas une erreur de vérification, n'essayant pas "
"de certifi et quittant."

#. Used by: exception
#: run.py:1076
msgid "Here is the exact error, it could be a bug."
msgstr "Voici l'erreur exacte, elle pourrait être un bug."

#. Used by: warning
#: run.py:1092
msgid ""
"To easily add a certificate to Windows trust store, \n"
"you can open the failing site in Microsoft Edge or IE...\n"
msgstr ""
"Pour ajouter facilement un certificat au magasin de confiance Windows, \n"
"vous pouvez ouvrir le site défaillant dans Microsoft Edge ou IE...\n"

#. Used by: warning
#: run.py:1098
msgid ""
"Could not get Issuer Certificate from default trust store, trying certifi "
"instead."
msgstr ""
"Impossible d'obtenir le certificat d'émetteur à partir du magasin de "
"confiance par défaut, en essayant de certifi à la place."

#. Used by: exception
#: run.py:1107
msgid "Syntax error (modification detected, did you edit the code?)"
msgstr "Erreur de syntaxe (modification détectée, avez-vous modifié le code?)"

#. Used by: exception
#: run.py:1110
msgid "Syntax error (this is a bug, not your fault)"
msgstr "Erreur de syntaxe (c'est un bug, pas votre faute)"

#. Used by: error
#: run.py:1122
msgid ""
"Cannot start MusicBot due to an error!\n"
"\n"
"Problem:\n"
"  There was an error importing MusicBot or a dependency package.\n"
"\n"
"Solution:\n"
"  You need to manually install pip packages for MusicBot\n"
"  or launch without `--no-install-deps` and MusicBot will try to install them for you."
msgstr ""
"Impossible de démarrer MusicBot à cause d'une erreur !\n"
"\n"
"Problème:\n"
"  Une erreur s'est produite lors de l'importation de MusicBot ou d'un paquet de dépendances.\n"
"\n"
"Solution :\n"
"  Vous devez installer manuellement des paquets pip pour MusicBot\n"
"  ou lancer sans `--no-install-deps` et MusicBot essayera de les installer pour vous."

#. Used by: info
#: run.py:1155
msgid "Attempting to install MusicBot dependency packages automatically...\n"
msgstr ""
"Tentative d'installation automatique des paquets de dépendances "
"MusicBot...\n"

#. Used by: critical
#: run.py:1164
#, python-format
msgid ""
"MusicBot dependencies may not be installed!\n"
"\n"
"Problem:\n"
"  The pip install process ended with a possible error.\n"
"  Some or all of the the dependencies may be missing.\n"
"\n"
"Solution:\n"
"  You must manually install dependency packages.\n"
"  Open a CMD prompt / terminal to the MusicBot directory.\n"
"  You can try using the update scripts install packages.\n"
"  Or try this manual command:\n"
"    %(py_bin)s -m pip install -U -r ./requirements.txt\n"
"\n"
"You can also ask for help in MusicBot's support discord:\n"
"  https://discord.gg/bots"
msgstr ""
"Les dépendances MusicBot peuvent ne pas être installées !\n"
"\n"
"Problème:\n"
"  Le processus d'installation de pip s'est terminé par une erreur possible.\n"
"  Une partie ou la totalité des dépendances peuvent être manquantes.\n"
"\n"
"Solution :\n"
"  Vous devez installer manuellement des paquets de dépendances.\n"
"  Ouvrez une invite CMD / terminal dans le répertoire MusicBot.\n"
"  Vous pouvez essayer d'utiliser les paquets d'installation de scripts de mise à jour.\n"
"  Ou essayez la commande manuelle\n"
"    %(py_bin)s -m pip install -U -r . requirements.txt\n"
"\n"
"Vous pouvez également demander de l'aide dans le discord-support de MusicBot:\n"
"  https://discord.gg/bots."

#. Used by: info
#: run.py:1185
msgid "OK, lets hope installing dependencies worked!"
msgstr ""
"OK, laissons espérer que l'installation des dépendances a fonctionné !"

#. Used by: error
#: run.py:1197
msgid ""
"MusicBot got an ImportError after trying to install packages. MusicBot must "
"exit..."
msgstr ""
"MusicBot a obtenu une erreur d'importation après avoir essayé d'installer "
"des paquets. MusicBot doit quitter..."

#. Used by: exception
#: run.py:1199
msgid "The exception which caused the above error: "
msgstr "L'exception qui a causé l'erreur ci-dessus : "

#. Used by: info
#: run.py:1218
msgid "MusicBot is doing a soft restart..."
msgstr "MusicBot fait un redémarrage doux..."

#. Used by: info
#: run.py:1222
msgid "MusicBot is doing a full process restart..."
msgstr "MusicBot effectue un redémarrage complet du processus..."

#. Used by: exception
#: run.py:1228
msgid "Error starting bot"
msgstr "Erreur lors du démarrage du bot"

#. Used by: debug
#: run.py:1233
msgid "Closing event loop."
msgstr "Fermeture de la boucle d'événements."

#. Used by: info
#: run.py:1238
#, python-format
msgid "Restarting in %s seconds..."
msgstr "Redémarrage dans %s secondes..."

#. Used by: info
#: run.py:1242
msgid "All done."
msgstr "Terminé."

#. Used by: _L
#: run.py:1271
msgid "OK, we're closing!"
msgstr "OK, nous sommes en train de fermer!"

#. Used by: info
#: musicbot/bot.py:2159
msgid "MusicBot is now doing start up steps..."
msgstr ""

#. Used by: warning
#: musicbot/bot.py:2166
msgid "Start up failed at login."
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:3481
#, python-format
msgid "No playlist file exists with the name: `%(playlist)s`"
msgstr ""

#. Used by: CommandError
#: musicbot/bot.py:5165
msgid ""
"There is nothing currently playing. Play something with a play command."
msgstr ""

#. Used by: error
#: musicbot/bot.py:5179
#, python-format
msgid ""
"Missing permissions to delete queue file for %(guild)s(%(id)s) at: %(path)s"
msgstr ""

#. Used by: exception
#: musicbot/bot.py:5184
#, python-format
msgid "OS level error while trying to delete queue file: %(path)s"
msgstr ""

#. Used by: info
#: musicbot/config.py:1084
msgid "Generating new config options files..."
msgstr ""

#. Used by: HelpfulError
#: musicbot/config.py:1094
#, python-format
msgid ""
"Error creating default config options file.\n"
"\n"
"Problem:\n"
"  MusicBot attempted to generate the config files but failed due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Make sure MusicBot can read and write to your config files.\n"
msgstr ""

#. Used by: error
#: musicbot/config.py:1348
#, python-format
msgid ""
"Could not locate config options or example options files.\n"
"MusicBot will generate the config files at the location:\n"
"  %(cfg_file)s"
msgstr ""

#. Used by: everything
#: musicbot/filecache.py:332
msgid "Cachemap defer flag is set, not yet saving to disk..."
msgstr ""

#. Used by: error
#: musicbot/permissions.py:136
#, python-format
msgid ""
"Could not locate config permissions or example permissions files.\n"
"MusicBot will generate the config files at the location:\n"
"  %(perms_file)s"
msgstr ""

#. Used by: info
#: musicbot/permissions.py:163
msgid "Generating new config permissions files..."
msgstr ""

#. Used by: HelpfulError
#: musicbot/permissions.py:172
#, python-format
msgid ""
"Error creating default config permissions file.\n"
"\n"
"Problem:\n"
"  MusicBot attempted to generate the config files but failed due to an error:\n"
"  %(raw_error)s\n"
"\n"
"Solution:\n"
"  Make sure MusicBot can read and write to your config files.\n"
msgstr ""

#. Used by: critical
#: run.py:525
#, python-format
msgid ""
"MusicBot could not write files in the following directory:\n"
"%(dir)s"
msgstr ""

#. Used by: critical
#: run.py:529
msgid "Please make sure MusicBot can read and write in the above directory."
msgstr ""

#. Used by: exception
#: run.py:536
msgid "Failed to clean up write-test path."
msgstr ""

#. Used by: _L
#: run.py:826
msgid ""
"Supply a directory where MusicBot can store all mutable files.\n"
"Essentially treats the install directory as read-only.\n"
"MusicBot must have permission to create this directory.\n"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2414
msgid "Private Channel"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2416
msgid "Unknown User DM"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2418
#, python-format
msgid "User DM: %(name)s"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2422
msgid "Unknown Channel (Partial)"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2424
#, python-format
msgid "Unnamed Channel: %(id)s"
msgstr ""

#. Used by: _L
#: musicbot/bot.py:2803
msgid "Unknown Channel"
msgstr ""

#. TRANSLATORS: Placeholder for empty track title.
#. Used by: _X
#: musicbot/entry.py:299 musicbot/entry.py:821 musicbot/entry.py:1020
msgid "Unknown"
msgstr ""

#. Used by: info
#: musicbot/bot.py:709
#, python-format
msgid "MusicBot may use up to %(rate).2f %(suffix)s of bandwidth."
msgstr ""

#. Used by: everything
#: musicbot/player.py:446
#, python-format
msgid "Probed codec and bitrate: %(name)s at %(rate)s kbps"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2599
#, python-format
msgid "  Command by @mention: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2601
#, python-format
msgid "  Command aliases: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2610
#, python-format
msgid "    Legacy skip: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2612
#, python-format
msgid "    Author insta-skip: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2620
#, python-format
msgid "  Auto-join Owner's voice channel: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2632
#, python-format
msgid "    Save per-server queue history: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2636
#, python-format
msgid "    Save global queue history: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2640
#, python-format
msgid "    Remove URLs on extraction error: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2643
#, python-format
msgid "    Skip playlist for user requests: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2661
#, python-format
msgid "  Songs blocklist: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2662
#, python-format
msgid "  Users blocklist: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2671
#, python-format
msgid "    Delete if cache exceeds %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2674
#, python-format
msgid "  Pre-download next track: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2681
#, python-format
msgid "  Write current song title to file: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2684
#, python-format
msgid "  Respond with Embeds: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2687
msgid "    Footer Text Disabled"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2689
#, python-format
msgid "    Footer Text:  %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2695
#, python-format
msgid "  Leave servers where Owner is not a member: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2699
#, python-format
msgid "  Disconnect from inactive channel: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2708
#, python-format
msgid "  Disconnect at end of queue: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2712
#, python-format
msgid "  Disconnect when player idles: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2722
#, python-format
msgid "  Search using reactions: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2723
#, python-format
msgid "    Results per search: %d"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2728
#, python-format
msgid "  Local media files: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2731
#, python-format
msgid "  Network checking ping tests: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2741
#, python-format
msgid "  Audio processed with: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2744
#, python-format
msgid "  Equalize audio level per-track: %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2749
#, python-format
msgid "  HTTP Proxy set to:  %s"
msgstr ""

#. Used by: info
#: musicbot/bot.py:2751
#, python-format
msgid "  User Agent set to:  %s"
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8149
msgid ""
"MusicBot has bound channel config and caller channel is not in bound "
"channels."
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8156
msgid "Caller server has a bound channel, caller channel ignored."
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8159
msgid "Caller server has no bound channel, caller allowed."
msgstr ""

#. Used by: debug
#: musicbot/bot.py:8162
#, python-format
msgid "Unbound channel (%s) in server:  %s"
msgstr ""

#. Used by: info
#: musicbot/testrig.py:462
msgid "Starting Command Tests..."
msgstr ""

#. Used by: info
#: musicbot/testrig.py:510
#, python-format
msgid "Buffered command: %(cmd)s"
msgstr ""

#. Used by: info
#: musicbot/testrig.py:527
#, python-format
msgid "- Processing CMD %(n)s of %(t)s: %(cmd)s"
msgstr ""

#. Used by: info
#: run.py:389
msgid "Checking for Python 3.9+"
msgstr ""

#. Used by: warning
#: run.py:393
#, python-format
msgid "Python 3.9+ is required. This version is %s"
msgstr ""

#. Used by: warning
#: run.py:395
msgid "Attempting to locate Python 3.9..."
msgstr ""

#. Used by: warning
#: run.py:414
msgid "Could not execute `py.exe -3.9` "
msgstr ""

#. Used by: info
#: run.py:423
msgid "Trying \"python3.9\""
msgstr ""

#. Used by: warning
#: run.py:426
msgid "Could not locate python3.9 on path."
msgstr ""

#. Used by: info
#: run.py:440
#, python-format
msgid ""
"\n"
"Python 3.9 found.  Re-launching bot using: %s run.py\n"
msgstr ""

#. Used by: critical
#: run.py:445
msgid ""
"Could not find Python 3.9 or higher.  Please run the bot using Python "
"version 3.9 to 3.13"
msgstr ""

#. Used by: ExtractionError
#: musicbot/downloader.py:502
#, python-format
msgid "Error in yt-dlp while downloading media data: %(raw_error)s"
msgstr ""

#. Used by: ExtractionError
#: musicbot/downloader.py:523
#, python-format
msgid "Error in yt-dlp while downloading stream data: %(raw_error)s"
msgstr ""

#. Used by: noise
#: musicbot/downloader.py:557
#, python-format
msgid ""
"Extractor %(extractor)s returned single-entry result, replacing base info "
"with entry info."
msgstr ""

#. Used by: info
#: run.py:1053
msgid "Updating example config files..."
msgstr ""

#~ msgid ""
#~ "Experimental Yt-dlp OAuth2 plugin is enabled. This might break at any point!"
#~ msgstr ""
#~ "Le plugin OAuth2 Yt-dlp expérimental est activé. Cela pourrait se briser à "
#~ "n'importe quel point !"

#~ msgid ""
#~ "Cookies TXT file detected. MusicBot will pass them to yt-dlp.\n"
#~ "Cookies are not recommended, may not be supported, and may totally break.\n"
#~ "Copying cookies from your web-browser risks exposing personal data and \n"
#~ "in the best case can result in your accounts being banned!\n"
#~ "\n"
#~ "You have been warned!  Good Luck!  \\U0001F596\n"
#~ msgstr ""
#~ "Fichier TXT de cookies détecté. MusicBot les transmettra à yt-dlp.\n"
#~ "Les cookies ne sont pas recommandés, peuvent ne pas être pris en charge et peuvent complètement échouer.\n"
#~ "La copie de cookies à partir de votre navigateur Web risque d'exposer des données personnelles et\n"
#~ "dans le meilleur des cas, cela peut entraîner le bannissement de vos comptes !\n"
#~ "\n"
#~ "Vous êtes prévenu ! Bonne chance ! \\U0001F596\n"

#~ msgid ""
#~ "Original OAuth2 plugin is installed and will be used instead.\n"
#~ "This may cause MusicBot to not close completely, or hang pending authorization!\n"
#~ "To close MusicBot, you must manually Kill the MusicBot process!\n"
#~ "Yt-dlp is being set to show warnings and other log messages, to show the Auth code.\n"
#~ "Uninstall the yt-dlp-youtube-oauth2 package to use integrated OAuth2 features instead."
#~ msgstr ""
#~ "Le plug-in OAuth2 d'origine est installé et sera utilisé à la place.\n"
#~ "Cela peut empêcher MusicBot de se fermer complètement ou de se bloquer en attendant l'autorisation !\n"
#~ "Pour fermer MusicBot, vous devez tuer manuellement le processus MusicBot !\n"
#~ "Yt-dlp est configuré pour afficher des avertissements et d'autres messages de journal, pour afficher le code d'authentification.\n"
#~ "Désinstallez le package yt-dlp-youtube-oauth2 pour utiliser les fonctionnalités OAuth2 intégrées à la place."

#, python-format
#~ msgid "Error in yt-dlp while downloading data: %(raw_error)s"
#~ msgstr "Erreur dans yt-dlp lors du téléchargement des données : %(raw_error)s"

#~ msgid ""
#~ "Extractor youtube:search returned single-entry result, replacing base info "
#~ "with entry info."
#~ msgstr ""
#~ "L'extracteur youtube:search a retourné le résultat d'une seule entrée, "
#~ "remplaçant les informations de base par les informations d'entrée."

#, python-format
#~ msgid "Failed to save ytdlp oauth2 token data due to:  %s"
#~ msgstr "Échec de la sauvegarde des données du jeton oauth2 en raison de:  %s"

#~ msgid "Loading YouTube TV OAuth2 token data."
#~ msgstr "Chargement des données du jeton OAuth2 de YouTube TV."

#, python-format
#~ msgid "Failed to load ytdlp oauth2 token data due to:  %s"
#~ msgstr ""
#~ "Impossible de charger les données du jeton ytdlp oauth2 en raison de:  %s"

#~ msgid "Storing YouTube TV OAuth2 token data"
#~ msgstr "Stockage des données de jeton OAuth2 de YouTube TV"

#~ msgid "Invalid cached OAuth2 token data."
#~ msgstr "Données de jeton OAuth2 non valides."

#~ msgid "Access token expired, refreshing"
#~ msgstr "Jeton d'accès expiré, actualisation"

#~ msgid ""
#~ "YouTube cookies have been provided, but OAuth2 is being used. If you "
#~ "encounter problems, stop providing YouTube cookies to yt-dlp."
#~ msgstr ""
#~ "Des cookies YouTube ont été fournis, mais OAuth2 est utilisé. Si vous "
#~ "rencontrez des problèmes, arrêtez de fournir des cookies YouTube à yt-dlp."

#~ msgid "Refreshing YouTube TV oauth2 token..."
#~ msgstr "Rafraîchissement du jeton oauth2 YouTube TV..."

#, python-format
#~ msgid ""
#~ "Failed to refresh OAuth2 access token due to:  %s\n"
#~ "Restarting authorization flow..."
#~ msgstr ""
#~ "Échec de l'actualisation du jeton d'accès OAuth2 à cause de :  %s\n"
#~ "Redémarrage du flux d'autorisation..."

#~ msgid "Starting oauth2 flow..."
#~ msgstr "Démarrage du flux oauth2..."

#, python-format
#~ msgid ""
#~ "\n"
#~ "NOTICE:\n"
#~ "To give yt-dlp access to your account, visit:\n"
#~ "  %s\n"
#~ "Then enter this authorization code:  %s\n"
#~ "You have %s seconds to complete authorization.\n"
#~ msgstr ""
#~ "\n"
#~ "AVIS :\n"
#~ "Pour donner l'accès à yt-dlp à votre compte, visite :\n"
#~ "  %s\n"
#~ "Entrez ensuite ce code d'autorisation :  %s\n"
#~ "Vous avez %s secondes pour terminer l'autorisation.\n"

#~ msgid ""
#~ "The application may hang until authorization time out if closed at this "
#~ "point. This is normal."
#~ msgstr ""
#~ "L'application peut être suspendue jusqu'à la fin du délai d'autorisation si "
#~ "elle est fermée à ce stade. C'est normal."

#~ msgid "Timed out while waiting for OAuth2 token."
#~ msgstr "Expiration du délai d'attente du jeton OAuth2."

#~ msgid "The device code has expired, restarting authorization flow for yt-dlp."
#~ msgstr ""
#~ "Le code de l'appareil a expiré, redémarrage du flux d'autorisation pour yt-"
#~ "dlp."

#~ msgid "Yt-dlp OAuth2 authorization successful."
#~ msgstr "L'autorisation OAuth2 de Yt-dlp a réussi."

#, python-format
#~ msgid "Adding OAuth2 Plugin to Yt-dlp IE:  %s"
#~ msgstr "Ajout du plugin OAuth2 à Yt-dlp IE:  %s"

#, python-format
#~ msgid "Default Yt-dlp Clients:  %s"
#~ msgstr "Client Yt-dlp par défaut :  %s"

#, python-format
#~ msgid "  Auto-Summon: %s"
#~ msgstr "  Invocation automatique : %s"

#, python-format
#~ msgid "    Delete if size exceeds %s"
#~ msgstr "    Supprimer si la taille dépasse %s"

#, python-format
#~ msgid "  Write current songs to file: %s"
#~ msgstr "  Écrire les chansons actuelles dans le fichier : %s"

#, python-format
#~ msgid "  Author insta-skip: %s"
#~ msgstr "  Auteur saut instantané : %s"

#, python-format
#~ msgid "  Embeds: %s"
#~ msgstr "  Embeds: %s"

#, python-format
#~ msgid "  Legacy skip: %s"
#~ msgstr "  Passage hérité : %s"

#, python-format
#~ msgid "  Leave non owners: %s"
#~ msgstr "  Laisser les non-propriétaires: %s"

#, python-format
#~ msgid "  Leave inactive VC: %s"
#~ msgstr "  Laisser le VC inactif : %s"

#, python-format
#~ msgid "  Leave at song end/empty queue: %s"
#~ msgstr "  Laisser à la fin de la chanson / file d'attente vide : %s"

#, python-format
#~ msgid "  Leave when player idles: %s"
#~ msgstr "  Quitter quand le joueur est inactif : %s"

#, python-format
#~ msgid "  Search List: %s"
#~ msgstr "  Liste de recherche : %s"

#~ msgid "Checking for Python 3.8+"
#~ msgstr "Vérification de Python 3.8+"

#, python-format
#~ msgid "Python 3.8+ is required. This version is %s"
#~ msgstr "Python 3.8+ est requis. Cette version est %s"

#~ msgid "Attempting to locate Python 3.8..."
#~ msgstr "Tentative de localisation de Python 3.8..."

#~ msgid "Could not execute `py.exe -3.8` "
#~ msgstr "Impossible d'exécuter `py.exe -3.8` "

#~ msgid "Trying \"python3.8\""
#~ msgstr "Essai de \"python3.8\""

#~ msgid "Could not locate python3.8 on path."
#~ msgstr "Impossible de localiser python3.8 sur le chemin."

#, python-format
#~ msgid ""
#~ "\n"
#~ "Python 3.8 found.  Re-launching bot using: %s run.py\n"
#~ msgstr ""
#~ "\n"
#~ "Python 3.8 trouvé. Relancement du bot en utilisant : %s run.py\n"

#~ msgid ""
#~ "Could not find Python 3.8 or higher.  Please run the bot using Python 3.8"
#~ msgstr ""
#~ "Impossible de trouver Python 3.8 ou supérieur. Veuillez exécuter le bot en "
#~ "utilisant Python 3.8"

#, python-format
#~ msgid "  Audio Codec: %s"
#~ msgstr ""

#, python-format
#~ msgid "Generated a new %(example_file)s and copied it to %(option_file)s"
#~ msgstr "Générer un nouveau %(example_file)s et le copier vers %(option_file)s"

#~ msgid "Current working directory does not seem to be writable"
#~ msgstr ""
#~ "Le répertoire de travail actuel ne semble pas être accessible en écriture"

#~ msgid "Please move the bot to a folder that is writable"
#~ msgstr "Veuillez déplacer le bot dans un dossier accessible en écriture"
